const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const nodes=new Map(),groups={plan:[],billingCycle:[],onboarding:[]};
const classes={add(){},toggle(){}};
function node(id){if(!nodes.has(id))nodes.set(id,{value:'',checked:false,textContent:'',hidden:false,classList:classes,dataset:{},required:false,disabled:false,setCustomValidity(){},reportValidity(){this.reported=true;return !this.required||this.checked;},setAttribute(){},removeAttribute(){},events:{},addEventListener(name,fn){this.events[name]=fn;}});return nodes.get(id);}
function radio(group,value,checked=false){const n=node(group+':'+value);n.value=value;let on=checked;Object.defineProperty(n,'checked',{get:()=>on,set:v=>{if(v)for(const x of groups[group])if(x!==n)x.checked=false;on=v;}});n.closest=()=>({querySelector:s=>node(value+s)});groups[group].push(n);return n;}
for(const v of ['starter','growth','pro'])radio('plan',v,v==='growth');for(const v of ['monthly','annual'])radio('billingCycle',v,v==='monthly');radio('onboarding','self',true);
const sections=[1,2,3].map(n=>({...node('step'+n),dataset:{step:String(n)}}));const progress=[1,2,3].map(n=>({...node('go'+n),dataset:{go:String(n)}}));
const doc={documentElement:{classList:classes},querySelector(s){if(s.startsWith('#'))return node(s.slice(1));const checked=s.match(/^\[name="([^\"]+)"\]:checked$/);if(checked)return groups[checked[1]].find(x=>x.checked);const value=s.match(/\[value="([^\"]+)"\]/);if(value)return groups.plan.find(x=>x.value===value[1]);throw Error('Unexpected selector '+s);},querySelectorAll(s){if(s==='.signup-step')return sections;if(s==='.signup-progress button')return progress;if(s==='[data-next]'||s==='[data-back]')return [];if(s==='[name="plan"],[name="billingCycle"]')return [...groups.plan,...groups.billingCycle];throw Error('Unexpected selectors '+s);}};
const amounts={starter:{first:891,renewal:990},growth:{first:1791,renewal:1990},pro:{first:3591,renewal:3990}};
const context=vm.createContext({document:doc,window:{scrollTo(){}},location:{search:'?plan=starter',replace(){throw Error('No signup or checkout navigation in UI test');}},URLSearchParams,Intl,localStorage:{setItem(){}},fetch:async url=>{assert.ok(['/api/founder-offer','/api/annual-upfront-offer'].includes(url),'only read-only offers');return {json:async()=>url.includes('annual-upfront')?{enabled:true,amounts}:{enabled:true,setupAvailable:true,prices:{starter:{monthly:79,annual:790},growth:{monthly:159,annual:1590},pro:{monthly:319,annual:3190}}}};}});
vm.runInContext(fs.readFileSync(require.resolve('./signup.js'),'utf8'),context);
(async()=>{for(let i=0;i<8;i++)await Promise.resolve();
assert.match(node('signup-offer-heading').textContent,/14-day trial/);groups.billingCycle[1].checked=true;groups.billingCycle[1].events.change();assert.equal(node('annual-upfront-choice').hidden,false);
node('annual-upfront').checked=true;node('annual-upfront').events.change();assert.match(node('annual-upfront-summary').textContent,/891.*990/);assert.match(node('plan-offer-help').textContent,/Pay.*today.*No free trial/);assert.doesNotMatch(node('signup-offer-heading').textContent,/no credit card/);
node('trade').value='Concrete';assert.equal(vm.runInContext('validateTrade()',context),false);assert.equal(vm.runInContext('currentStep',context),2);assert.equal(node('annual-upfront-terms').reported,true);node('annual-upfront-terms').checked=true;assert.equal(vm.runInContext('validateTrade()',context),true);
node('employees').value='50';node('projects').value='30';node('employees').oninput();assert.equal(groups.plan[2].checked,true);assert.match(node('annual-upfront-summary').textContent,/3,591.*3,990/);assert.match(node('plan-offer-help').textContent,/3,591.*3,990/);
node('founder-code').value='synthetic-unvalidated';node('founder-code').events.input();assert.equal(node('annual-upfront').checked,false);assert.equal(node('annual-upfront-choice').hidden,true);assert.match(node('signup-offer-heading').textContent,/Founder membership/);
node('founder-code').value='';node('founder-code').events.input();assert.match(node('signup-offer-heading').textContent,/14-day trial/);assert.match(node('plan-offer-help').textContent,/Nothing is charged today/);assert.equal(node('annual-upfront-terms').required,false);
console.log('PASS actual signup script with synthetic DOM: consent blocks wizard navigation, recommended plan refreshes actual charge/renewal, paid/no-trial copy replaces trial promise, founder cannot stack, deselection restores normal trial. No signup/provider calls.');
})().catch(e=>{console.error(e);process.exitCode=1;});
