'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'pdl-assignment-daily-')),companyId='11221122-1122-4122-8122-112211221122',token='synthetic-assignment-owner',fieldToken='synthetic-assignment-field',date='2026-10-08';
const db={company:{id:companyId,name:'Synthetic handoff',demo:true,timezone:'UTC'},projects:[{id:101,name:'Synthetic Job',estimateItems:[]}],team:[{id:7,name:'Synthetic worker',crew:'A'},{id:8,name:'Other worker',crew:'C'}],assignments:[{id:1,projectId:101,date,crew:'A',memberIds:[7]},{id:2,projectId:101,date,crew:'B',memberIds:[7]},{id:3,projectId:101,date,crew:'C',memberIds:[8]}],reports:[],photos:[],workdays:[],timeCards:[],users:[{id:1,name:'Synthetic owner',role:'owner',status:'Active',companyId},{id:2,name:'Synthetic worker',memberId:7,role:'field',status:'Active',companyId}],sessions:[{companyId,userId:1,tokenHash:crypto.createHash('sha256').update(token).digest('hex'),expiresAt:'2099-01-01'},{companyId,userId:2,tokenHash:crypto.createHash('sha256').update(fieldToken).digest('hex'),expiresAt:'2099-01-01'}],customers:[],changes:[],catalog:[]};
const file=path.join(root,'db.json');fs.writeFileSync(file,JSON.stringify(db));fs.writeFileSync(path.join(root,'platform.json'),JSON.stringify({users:[],sessions:[]}));
Object.assign(process.env,{PDL_DB_FILE:file,PDL_PLATFORM_FILE:path.join(root,'platform.json'),PDL_REQUIRE_AUTH:'1',PDL_SUPABASE_ENABLED:'0',PDL_TRANSACTIONAL_DB:'off',PDL_EMAIL_DEV_MODE:'1'});for(const name of ['OPENAI_API_KEY','SENTRY_DSN','RESEND_API_KEY','STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET'])delete process.env[name];require('./database/supabase').loadLocalEnv=()=>{};
const {server}=require('./server'),nativeFetch=global.fetch;let base;
global.fetch=(url,options)=>{assert.ok(String(url).startsWith(base+'/'),'only synthetic localhost requests permitted');return nativeFetch(url,options);};
async function call(method,route,body,auth=token){const response=await fetch(base+route,{method,signal:AbortSignal.timeout(10000),headers:{'Content-Type':'application/json','x-pdl-company':companyId,Authorization:'Bearer '+auth},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,data:await response.json()};}
(async()=>{try{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port;
 const input={projectId:101,dateIso:date,status:'Draft',notes:'Synthetic edited notes',productionEntries:[],laborEntries:[],sourceAssignmentId:2,crew:'User edited crew'};
 const created=await call('POST','/api/reports',input,fieldToken);assert.equal(created.status,201);assert.equal(created.data.sourceAssignmentId,2);assert.equal(created.data.crew,'User edited crew');
 const other=await call('POST','/api/reports',{...input,sourceAssignmentId:1},fieldToken);assert.equal(other.status,201);assert.notEqual(other.data.id,created.data.id,'same notes on different shifts must remain separate drafts');
 const state=await call('GET','/api/state',null,fieldToken),saved=state.data.reports.find(row=>row.id===created.data.id);assert.equal(saved.sourceAssignmentId,2);assert.equal(saved.notes,input.notes);assert.equal(saved.crew,input.crew);
 const edited=await call('PATCH','/api/reports/'+created.data.id,{...input,notes:'Further user edits'},fieldToken);assert.equal(edited.status,200);assert.equal(edited.data.sourceAssignmentId,2);
 for(const wrong of [{sourceAssignmentId:3},{sourceAssignmentId:99},{sourceAssignmentId:2,dateIso:'2026-10-09'}]){const result=await call('POST','/api/reports',{...input,...wrong},fieldToken);assert.ok([403,409].includes(result.status));}
 const stored=JSON.parse(fs.readFileSync(file));stored.assignments=stored.assignments.filter(row=>row.id!==2);fs.writeFileSync(file,JSON.stringify(stored));
 const deleted=await call('PATCH','/api/reports/'+created.data.id,{...input,notes:'Edits after schedule deletion'},fieldToken);assert.equal(deleted.status,200);assert.equal(deleted.data.sourceAssignmentId,2);assert.equal(deleted.data.notes,'Edits after schedule deletion');
 const cleared=await call('PATCH','/api/reports/'+created.data.id,{...input,sourceAssignmentId:null},fieldToken);assert.equal(cleared.status,200);assert.equal(cleared.data.sourceAssignmentId,null);
 console.log('Assignment daily API passed: authenticated draft save/reload/edit, distinct-shift deduplication, scope rejection and retained edits after schedule deletion.');
}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));global.fetch=nativeFetch;fs.rmSync(root,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;server.close();});
