'use strict';
const assert = require('node:assert/strict'), crypto = require('node:crypto');
const registry = require('./capability-registry'), operations = require('./capability-operations'), projections = require('./account-projections');
const { fixture, token, companyA, companyB } = require('./fixtures/project-assistant');
const old = require('./fixtures/atomic-route-baseline'), routes = require('./database/tenant-atomic-routes');
const policy = module => ({ version: 1, revision: 1, roles: Object.fromEntries(module.roles.map(role => [role, module.ceiling(role)])) });
async function main() {
  const db = fixture(); db.company.features.timeCards = true;
  Object.assign(db.users[1].permissions, { manageTime: true, viewTime: true, viewDailies: true, approveDailies: true });
  const before = structuredClone(db), user = db.users[1], initial = registry.effective(db, user);
  assert.deepEqual(registry.baseline(db, user), initial); assert.equal(registry.families.reduce((sum, row) => sum + row[4].actions.length, 0), 32);
  for (const [id, , prefix, property, module] of registry.families) {
    assert.deepEqual(initial[id], module.access(db, user));
    for (const malformed of [false, 0, '', null]) { db.company[prefix + 'RolePolicy'] = malformed; assert.ok(module.required(db)); assert.ok(Object.values(registry.effective(db, user)[id]).every(value => value === false)); assert.deepEqual(module.access(db, db.users[0]), module.access({ ...db, company: { ...db.company, [prefix + 'RolePolicy']: undefined } }, db.users[0])); delete db.company[prefix + 'RolePolicy']; }
    const raw = policy(module); db.company[prefix + 'RolePolicy'] = raw;
    for (const action of module.actions) {
      const reduced = structuredClone(raw); reduced.roles.project_manager = Object.fromEntries(module.actions.map(key => [key, false])); db.company[prefix + 'RolePolicy'] = reduced;
      assert.equal(registry.effective(db, user)[id][action], false); assert.deepEqual(registry.baseline(db, user), initial);
    }
    delete db.company[prefix + 'RolePolicy'];
    assert.deepEqual(registry.actor(db, user, true)[property], module.access(db, user));
  }
  assert.deepEqual(db, before); assert.equal(registry.actor(db, user, false), user);
  const set = Object.fromEntries(registry.families.map(([id, , , , module]) => [id, policy(module)])); registry.validatePolicySet(set); assert.throws(() => registry.validatePolicySet({ ...set, security: {} })); assert.throws(() => registry.validatePolicySet({ ...set, notes: { ...set.notes, roles: { ...set.notes.roles, owner: {} } } }));
  const known = new Set(registry.families.flatMap(([id, , , , module]) => module.actions.map(action => id + '.' + action))), covered = new Set();
  for (const row of operations.describe()) for (const control of row.controls) { assert.ok(known.has(control), control); covered.add(control); }
  assert.deepEqual([...covered].sort(), [...known].sort());
  for (const preview of registry.describe(db).previews) { assert.ok(preview.control ? known.has(preview.control) : preview.immutable === 'owner'); const row = operations.classify(preview.method, preview.target.replace('{id}', preview.endpoint.includes('pay-period') ? 'a'.repeat(36) : '11')); assert.ok(row); assert.ok(preview.control ? row.controls.includes(preview.control) : row.immutable === 'owner'); }
  const samples = ['/api/auth/me', '/api/users', '/api/auth/login', '/api/auth/logout', '/api/account-access', '/api/users/2', '/api/assignments', '/api/assignments/11', '/api/assignments/11/acknowledge', '/api/schedule-availability', '/api/time-off-requests', '/api/time-off-requests/x/review-preview', '/api/time-off-requests/x/approve', '/api/time-cards', '/api/time-cards/11', '/api/time-cards/company-clock', '/api/time-cards/11/clock-out', '/api/time-cards/11/submit', '/api/time-cards/approve', '/api/time-cards/11/approve', '/api/time-cards/11/unapprove', '/api/time-cards/review-preview', '/api/time-cards/action-preview', '/api/time-cards.csv', '/api/report-labor-suggestions', '/api/company-activities', '/api/reports', '/api/reports/11', '/api/reports/11/approve', '/api/workdays', '/api/workdays/11', '/api/workdays/start', '/api/workdays/11/end', '/api/daily-actions/preview', '/api/pay-periods', '/api/pay-periods/action-preview', '/api/reporting-exports', '/api/photos', '/api/photos/upload-preview', '/api/photos/11', '/api/photos/11/file', '/api/photos/11/export', '/api/photos/recovery-manifest', '/api/projects/101/notes-todos', '/api/projects/101/notes-todos/x', '/api/projects/101/assistant/context', '/api/projects/101/assistant/preview', '/api/projects/101/assistant/confirm'];
  for (const suffix of ['', '/summary', '/exports', '/exports/' + 'b'.repeat(36), '/exports/' + 'b'.repeat(36) + '.csv']) samples.push('/api/pay-periods/' + 'a'.repeat(36) + suffix);
  samples.push('/api/reporting-exports/' + 'a'.repeat(36), '/api/reporting-exports/' + 'a'.repeat(36) + '.csv', '/api/files/project-photos/' + 'a'.repeat(36) + '/atomic-photos/' + 'b'.repeat(36) + '/photo.png');
  for (const path of samples.flatMap(path => [path, path + '/extra', path + '/', path.replace('/api/', '/api/other/')])) for (const method of ['GET', 'POST', 'PATCH', 'DELETE', 'PUT']) assert.equal(routes.supportedRoute(method, path), old.supportedRoute(method, path), method + ' ' + path);
  const projected = projections.dto(db, { ...user, passwordHash: 'Private sentinel', resetTokenHash: 'Private sentinel', permissions: { ...user.permissions, aiAssistant: true }, preferences: { private: { tokenHash: 'Private sentinel' } } }, { current: true }); assert.ok(!JSON.stringify(projected).includes('Private sentinel')); assert.equal(projected.permissions.aiAssistant, undefined); assert.deepEqual(projected.effectiveCapabilities, initial);
  db.company.schedulingRolePolicy = policy(registry.families[0][4]); db.company.schedulingRolePolicy.roles.project_manager.create = false;
  const restricted = projections.dto(db, user, { directory: true }); assert.equal(restricted.permissions.scheduleCrews, true); assert.equal(restricted.storedPermissions.scheduleCrews, true); assert.equal(restricted.effectiveCapabilities.scheduling.create, false); assert.equal(restricted.baselineCapabilities.scheduling.create, true); delete db.company.schedulingRolePolicy;
  const foreman = projections.dto(db, db.users[4], { current: true }); assert.equal(foreman.role, 'field'); assert.equal(foreman.accessRole, 'foreman'); assert.equal(projections.dto(db, db.users[4], { directory: true }).role, 'foreman');
  const inactive = projections.dto(db, { ...user, status: 'Deactivated' }, { directory: true }); assert.ok(Object.values(inactive.effectiveCapabilities).every(family => Object.values(family).every(value => !value)));
  db.company.features.timeCards = false; const noCards = registry.effective(db, user); assert.equal(noCards.timeReview.reviewLeave, true); assert.equal(noCards.timeReview.viewCards, false); assert.ok(Object.values(noCards.timeWrite).every(value => !value)); assert.equal(noCards.daily.runWorkdays, true); db.company.features.timeCards = true;
  assert.equal(registry.immutable(db, db.users[3]).assistantEligible, false); assert.equal(registry.immutable({ ...db, company: { ...db.company, id: companyB } }, user).assistantEligible, false);
  for (const mutate of [row => { row.name = { secret: 'Private sentinel' }; }, row => { row.projectIds = [{ secret: 'Private sentinel' }]; }, row => { row.preferences = { theme: { secret: 'Private sentinel' } }; }]) { const row = structuredClone(user); mutate(row); assert.throws(() => projections.dto(db, row), { statusCode: 409 }); }
  db.users.unshift({ ...user, id: '02' }); assert.throws(() => projections.directory(db), { statusCode: 409 }); db.users.shift();
  const missingScope = projections.dto(db, { ...user, projectIds: [101, 999999] }, { directory: true }); assert.equal(missingScope.scopeState, 'unresolved'); assert.deepEqual(missingScope.effectiveCapabilities, registry.effective(db, user)); assert.equal(missingScope.immutableAccess.assistantEligible, true);
  const sessionHash = db.sessions.find(row => row.userId === 2).tokenHash;
  for (const [collection, id] of [['team', '013'], ['projects', '0101']]) { db[collection].unshift({ ...db[collection][0], id }); assert.throws(() => projections.sessionUser(db, sessionHash), { statusCode: 409 }); db[collection].shift(); }
  for (const mutate of [row => { row.projectIds = [[101]]; }, row => { row.assignedCrews = [['A']]; }, row => { row.memberId = [11]; }, row => { row.name = { private: 'sentinel' }; }, row => { row.permissions.viewTime = 'true'; }]) { const source = structuredClone(db); mutate(source.users[1]); assert.throws(() => projections.sessionUser(source, sessionHash), { statusCode: 409 }); assert.throws(() => projections.dto(source, source.users[1]), { statusCode: 409 }); }
  for (const value of [['A'], { private: 'sentinel' }]) { const source = structuredClone(db); source.team.find(row => row.id === 13).crew = value; assert.throws(() => projections.sessionUser(source, sessionHash), { statusCode: 409 }); }
  const privatePreferences = structuredClone(db); privatePreferences.users[1].preferences = { theme: { private: 'sentinel' } }; assert.ok(projections.sessionUser(privatePreferences, sessionHash).user); assert.throws(() => projections.dto(privatePreferences, privatePreferences.users[1]), { statusCode: 409 });
  const req = { method: 'GET', token: token(companyA, 2) }, assemble = (req, db) => { const session = db.sessions.find(row => row.userId === 2); req.auth = { session, user: registry.actor(db, db.users[1], true) }; return { auth: req.auth, status: 200 }; };
  assert.ok(projections.authenticate(req, db, assemble, req => req.token).auth); db.sessions.push({ ...db.sessions[1], companyId: companyB }); assert.throws(() => projections.authenticate(req, db, assemble, req => req.token), { statusCode: 409 }); assert.equal(req.auth, null); db.sessions.pop();
  let response, writes = 0, denied = false;
  const handle = projections.createHandler({ readDb: () => db, writeDb: () => writes++, authenticate: assemble, token: req => req.token, flags: () => ({ timeCards: true, templates: false }), json: (_res, status, data) => { response = { status, data }; }, jsonHeaders: (_res, status, data) => { response = { status, data }; }, assertCurrent: async () => { if (denied) throw Object.assign(Error('Synthetic stale projection'), { statusCode: 409 }); }, accountAccess: () => ({ locked: true }) });
  await handle(req, {}, new URL('http://localhost/api/auth/me')); assert.equal(response.status, 200); assert.equal(response.data.accountLocked, true); assert.equal(writes, 1); denied = true; await handle(req, {}, new URL('http://localhost/api/auth/me')); assert.equal(response.status, 409); assert.equal(writes, 1);
  let naturallyLocked = false;
  const recovery = projections.createHandler({ readDb: () => db, writeDb: () => writes++, authenticate: assemble, token: req => req.token, flags: () => ({}), json: (_res, status, data) => { response = { status, data }; }, jsonHeaders: (_res, status, data) => { response = { status, data }; }, assertCurrent: async () => { naturallyLocked = true; }, accountAccess: () => ({ locked: naturallyLocked }) });
  for (const route of ['/api/account-access', '/api/auth/me']) { naturallyLocked = false; await recovery(req, {}, new URL('http://localhost' + route)); assert.equal(response.status, 200); assert.equal(route.includes('/auth/') ? response.data.accountLocked : response.data.locked, true); }
  console.log('Capability registry/account pure tests passed: 32 real actions/dependencies/default parity, present-malformed denial, immutable eligibility, route admission parity/closed preview coverage, finite current/directory projections, stored/effective separation, inactive/foreman/foreign/ambiguous sessions and stale zero-write bootstrap.');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
