'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {A,B,initial,snapshot,memory,credential}=require('./compat-account-fixture');
const {workspaceSnapshot}=require('./compat-workspace-fixture'),{services}=require('./compat-lifecycle-fixture');
const registry=require('./capability-registry'),workflows=require('./schedule-workflow-access');
async function main(){
  const directory=fs.mkdtempSync(path.join(os.tmpdir(),'pdl-compat-schedule-workflows-')),file=path.join(directory,'legacy.json'),legacy=snapshot();legacy.company.id=B;legacy.users[0].companyId=B;fs.writeFileSync(file,JSON.stringify(legacy));const original=fs.readFileSync(file),key=crypto.randomBytes(32);
  Object.assign(process.env,{NODE_ENV:'test',PDL_COMPAT_ACCOUNT_SYNTHETIC:'1',PDL_REQUIRE_AUTH:'1',PDL_DB_FILE:file,PDL_PLATFORM_FILE:path.join(directory,'platform.json'),PDL_SUPABASE_ENABLED:'0',PDL_TRANSACTIONAL_DB:'off'});
  for(const name of ['OPENAI_API_KEY','RESEND_API_KEY','STRIPE_SECRET_KEY','SENTRY_DSN','SUPABASE_SECRET_KEY','PDL_PLATFORM_KEY'])process.env[name]='';
  const mod=require('./server');await new Promise(resolve=>mod.server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+mod.server.address().port;
  const native=process.env.TEST_COMPAT_DATABASE_URL?await require('./compat-lifecycle-native-fixture').nativeFixture():null;let uninstall,effects=0;
  function seed(){
    const db=workspaceSnapshot();db.company.timezone='UTC';db.team[0].crew='Office';db.assignments[0].date='2026-10-05';
    for(const [id,role]of[[3,'project_manager'],[4,'admin']])db.users.push({id,companyId:A,name:'Synthetic '+role,email:role+'@example.invalid',role,status:'Active',emailVerifiedAt:'2026-10-01T00:00:00Z',...credential(initial),projectIds:role==='project_manager'?[101]:[],assignedCrews:role==='project_manager'?['Synthetic Crew']:[],permissions:{scheduleCrews:true,viewTime:false,manageTime:false,viewDailies:false,approveDailies:false}});
    db.workdays=[{id:1,projectId:101,memberIds:[12],status:'complete',startedAt:'2026-10-05T07:13:00.000Z',endedAt:'2026-10-05T15:43:00.000Z',reportId:null}];return db;
  }
  async function scenario(db=seed()){
    uninstall?.();let cached,store;
    if(native){await native.reset(db);cached=await native.repository.load(A);store={loseAck:false,async load(id){cached=await native.repository.load(id);return structuredClone(cached);},async commit(...args){const result=await native.repository.commit(...args);cached=await native.repository.load(A);if(store.loseAck){store.loseAck=false;throw Object.assign(Error('Synthetic scheduling COMMIT acknowledgement lost'),{statusCode:503,code:'PDL_COMMIT_OUTCOME_UNKNOWN'});}return result;},current:()=>structuredClone(cached.snapshot),revision:()=>cached.revision};}
    else{store=memory(db);store.loseAck=false;const commit=store.commit.bind(store);store.commit=async(...args)=>{const result=await commit(...args);if(store.loseAck){store.loseAck=false;throw Object.assign(Error('Synthetic scheduling acknowledgement lost'),{statusCode:503,code:'PDL_COMMIT_OUTCOME_UNKNOWN'});}return result;};}
    const install=()=>{const fixture=services(store,origin,{key});uninstall=mod.installCompatibilityAccountTests({synthetic:true,companyId:A,origin,globalOrigin:'http://localhost:4999',repository:store,...fixture,workspace:true,workspaceKey:key,assignmentSend:async()=>{effects++;return {status:'accepted'};}});};install();
    const tokens=new Map();
    const request=async(route,method='GET',data,email='project_manager@example.invalid',company=A)=>{const response=await fetch(origin+route,{method,signal:AbortSignal.timeout(10000),headers:{'X-PDL-Company':company,...(tokens.has(email)?{Authorization:'Bearer '+tokens.get(email)}:{}),...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});return {status:response.status,data:await response.json()};};
    const login=async(email='project_manager@example.invalid')=>{const response=await request('/api/auth/login','POST',{email,password:initial},email);assert.equal(response.status,200,JSON.stringify(response));tokens.set(email,response.data.token);};await login();
    const preview=async(operation,email)=>{const identity=await request('/api/workspace-identity','GET',null,email);assert.equal(identity.status,200);return request('/api/schedule/workflow-preview','POST',{operation,expectedRevision:identity.data.revision},email);};
    const confirm=(operation,p,envelope,email)=>request(operation.path,'POST',envelope||{token:p.data.token,version:p.data.version,confirmed:true,requestId:crypto.randomUUID()},email);
    const alter=async(fn)=>{const loaded=await store.load(A),next=loaded.snapshot;fn(next);await store.commit(next,loaded.revision);};
    return {store,request,login,preview,confirm,alter,restart(){uninstall();install();}};
  }
  const mark={action:'markOff',path:'/api/schedule/mark-off',details:{memberId:12,date:'2026-10-15',reason:'sick',note:'Synthetic leave',paid:true}};
  const repeat={action:'repeatWeek',path:'/api/schedule/repeat-week',details:{targetStart:'2026-10-12',assignmentIds:[1]}};
  const adopt={action:'adoptActual',path:'/api/assignments/1/adopt-actual-times',details:{}};
  const policy=(db,family,action)=>{const entry=registry.families.find(row=>row[0]===family),controller=entry[4],roles=Object.fromEntries(registry.roles.map(role=>[role,controller.ceiling(role)]));roles.project_manager[action]=false;if(action==='viewCards')roles.project_manager.approveCards=roles.project_manager.unapproveCards=false;if(action==='viewWorkdays')roles.project_manager.runWorkdays=false;if(action==='view')for(const key of controller.actions)roles.project_manager[key]=false;db.company[entry[2]+'RolePolicy']={version:1,revision:1,roles};db.company[entry[2]+'PolicyRequired']=true;};
  try{
    let s=await scenario(),actor=s.store.current().users.find(row=>row.id===3);
    assert.equal(registry.effective(s.store.current(),actor).timeReview.reviewLeave,false);assert.equal(registry.effective(s.store.current(),actor).daily.viewWorkdays,false);assert.deepEqual(workflows.eligible(s.store.current(),actor),{liveToday:true,markOff:true,repeatWeek:true,adoptActual:true});
    for(const operation of[mark,repeat,adopt]){
      s=await scenario();const business=s.store.current(),before=JSON.stringify(operation.action==='markOff'?business.timeOffRequests:business.assignments),beforeEffects=effects,p=await s.preview(operation);assert.equal(p.status,200,JSON.stringify(p));assert.equal(JSON.stringify(operation.action==='markOff'?s.store.current().timeOffRequests:s.store.current().assignments),before);assert.equal(effects,beforeEffects);
      const envelope={token:p.data.token,version:p.data.version,confirmed:true,requestId:crypto.randomUUID()};assert.equal((await s.confirm(operation,p,{...envelope,confirmed:false})).status,400);
      const first=await s.confirm(operation,p,envelope);assert.ok([200,201].includes(first.status),JSON.stringify(first));const saved=JSON.stringify(s.store.current()),revision=s.store.revision(),afterEffects=effects;
      const replay=await s.confirm(operation,p,envelope);assert.equal(replay.status,first.status,JSON.stringify(replay));assert.equal(replay.data.originalSaveResult,true);assert.equal(JSON.stringify(s.store.current()),saved);assert.equal(s.store.revision(),revision);assert.equal(effects,afterEffects);
      assert.equal((await s.confirm(operation,p,{...envelope,requestId:crypto.randomUUID()})).status,409);
      if(operation.action==='markOff'){assert.equal(first.data.row.status,'approved');assert.equal(first.data.row.type,'sick');assert.equal(first.data.overlapping,0);assert.equal(registry.effective(s.store.current(),s.store.current().users.find(row=>row.id===3)).timeReview.reviewLeave,false);}
      if(operation.action==='adoptActual'){assert.equal(first.data.assignment.start,'07:15');assert.equal(first.data.assignment.end,'15:45');assert.deepEqual(s.store.current().workdays,business.workdays);}
      if(operation.action==='repeatWeek'){assert.equal(first.data.created,1);assert.equal(first.data.createdRows[0].date,'2026-10-12');assert.equal(effects,beforeEffects+1);assert.equal(s.store.current().workspaceAssignmentJobs[0].status,'sent');}
    }
    for(const[operation,family,action]of[[mark,'timeReview','reviewLeave'],[mark,'timeOff','viewRequests'],[adopt,'daily','viewWorkdays'],[repeat,'scheduling','create']]){
      const db=seed();policy(db,family,action);s=await scenario(db);assert.equal((await s.preview(operation)).status,403);
    }
    s=await scenario();let p=await s.preview(mark);assert.equal(p.status,200);const originalEffective=registry.effective(s.store.current(),s.store.current().users.find(row=>row.id===3));await s.alter(db=>policy(db,'timeReview','reviewLeave'));assert.deepEqual(registry.effective(s.store.current(),s.store.current().users.find(row=>row.id===3)),originalEffective);assert.equal((await s.confirm(mark,p)).status,409);assert.equal((s.store.current().timeOffRequests||[]).length,0);
    s=await scenario();p=await s.preview(mark);s.store.loseAck=true;const envelope={token:p.data.token,version:p.data.version,confirmed:true,requestId:crypto.randomUUID()};assert.equal((await s.confirm(mark,p,envelope)).status,503);const committed=JSON.stringify(s.store.current()),rev=s.store.revision();s.restart();assert.equal((await s.confirm(mark,p,envelope)).data.originalSaveResult,true);assert.equal(JSON.stringify(s.store.current()),committed);assert.equal(s.store.revision(),rev);
    await s.login();assert.equal((await s.confirm(mark,p,envelope)).status,409);
    s=await scenario();await s.login('field@example.invalid');for(const operation of[mark,repeat,adopt])assert.equal((await s.preview(operation,'field@example.invalid')).status,403);assert.equal((await s.request('/api/schedule/today','GET',null,'field@example.invalid')).status,403);
    s=await scenario();assert.equal((await s.request('/api/schedule/today')).status,200);await s.alter(db=>policy(db,'timeReview','viewCards'));assert.equal((await s.request('/api/schedule/today')).status,403);
    s=await scenario();assert.equal((await s.preview({...repeat,details:{...repeat.details,assignmentIds:[999]}})).status,404);assert.equal((await s.preview({...mark,details:{...mark.details,memberId:999}})).status,404);assert.equal((await s.request('/api/schedule/today','GET',null,undefined,B)).status,404);
    for(const operation of[{...mark,details:{...mark.details,permissions:{manageTime:true}}},{...repeat,details:{...repeat.details,assignmentIds:'1'}},{...adopt,details:{start:'00:00'}},{action:'owner',path:'/api/users',details:{}}])assert.equal((await s.preview(operation)).status,400);
    s=await scenario();p=await s.preview(adopt);await s.alter(db=>{db.users.find(row=>row.id===3).role='field';});assert.equal((await s.confirm(adopt,p)).status,409);
    s=await scenario();p=await s.preview(mark);await s.alter(db=>{db.sessions=[];});assert.equal((await s.confirm(mark,p)).status,401);
    s=await scenario();p=await s.preview(mark);await s.alter(db=>{db.scheduleWorkflowPreviews[0].operation.details.paid=false;});assert.equal((await s.request('/api/workspace-identity')).status,409);
    const stringScope=seed(),stringActor=stringScope.users.find(row=>row.id===3);stringActor.projectIds=['101'];assert.equal(workflows.assignmentScope(stringScope,stringActor,stringScope.assignments[0]),true);assert.equal(workflows.sourceView(stringScope,stringActor,stringScope.workdays[0]),true);assert.throws(()=>require('./account-evidence').validateAccounts(stringScope),error=>error.code==='PDL_COMPAT_ACCOUNT_EVIDENCE','the preserved selected runtime still requires imported canonical numeric scopes');
    // Manual no-op uses the upstream helper without timestamp, acknowledgement or legacy-audit churn.
    const same=seed();same.assignments[0].start='07:15';same.assignments[0].end='15:45';s=await scenario(same);p=await s.preview(adopt);assert.equal(p.status,200);const sameRows=structuredClone(s.store.current().assignments),sameAudit=s.store.current().auditLog.length;assert.equal((await s.confirm(adopt,p)).status,200);assert.deepEqual(s.store.current().assignments,sameRows);assert.equal(s.store.current().auditLog.length,sameAudit+1);
    // The role editor must disclose a workflow revocation even where its older grant was already false.
    s=await scenario();await s.login('owner@example.invalid');const policyState=await s.request('/api/company/role-policy','GET',null,'owner@example.invalid'),roleRows=structuredClone(policyState.data.defaults);roleRows.timeReview.project_manager.reviewLeave=false;
    const impact=await s.request('/api/company/role-policy/preview','POST',{requestId:crypto.randomUUID(),expectedRevision:policyState.data.tenantRevision,reason:'Synthetic mark-off restriction',policies:roleRows},'owner@example.invalid');assert.equal(impact.status,200,JSON.stringify(impact));const affected=impact.data.impact.accounts.find(row=>row.accountId===3);assert.equal(affected.before.timeReview.reviewLeave,false);assert.equal(affected.after.timeReview.reviewLeave,false);assert.deepEqual(affected.changes,[{capability:'scheduleWorkflows.markOff',before:true,after:false}]);assert.equal(impact.data.impact.changedAccounts,1);assert.equal(affected.scheduleWorkflowsBefore.markOff,true);assert.equal(affected.scheduleWorkflowsAfter.markOff,false);
    function daySeed(mode){
      const db=seed(),at=Date.now();db.company.features.timeCards=false;db.company.autoAdoptActualTimes=mode!=='disabled';db.company.timezone=new Date(at).getUTCHours()<4?'Etc/GMT+8':'UTC';const startedAt=new Date(at-3600000).toISOString(),parts=new Intl.DateTimeFormat('en-US',{timeZone:db.company.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(startedAt)),part=type=>parts.find(row=>row.type===type).value;
      db.assignments[0].date=part('year')+'-'+part('month')+'-'+part('day');db.assignments[0].start='00:00';db.assignments[0].end='00:15';db.workdays=[{id:1,projectId:101,memberIds:[12],status:'active',startedAt,endedAt:null,reportId:null}];
      if(['mixed','foreignEvidence'].includes(mode)){db.team.push({id:13,name:'Synthetic other crew',crew:'Other'});if(mode==='mixed')db.assignments[0].memberIds.push(13);else{db.team.at(-1).crew='Synthetic Crew';db.assignments[0].memberIds.push(13);db.workdays.push({id:2,projectId:101,memberIds:[13],status:'complete',startedAt,endedAt:new Date(at-1800000).toISOString(),reportId:null});}}
      if(mode==='coworkerLeave'){db.team.push({id:13,name:'Synthetic private leave person',crew:'Synthetic Crew'});db.assignments[0].memberIds.push(13);db.timeOffRequests=[{id:crypto.randomUUID(),memberId:13,startDate:db.assignments[0].date,endDate:db.assignments[0].date,allDay:true,type:'vacation',note:'Synthetic private reason',status:'approved',history:[]}];}
      if(mode==='hidden'){const controller=registry.families.find(row=>row[0]==='scheduling')[4],roles=Object.fromEntries(registry.roles.map(role=>[role,controller.ceiling(role)]));for(const action of controller.actions)roles.field[action]=false;db.company.schedulingRolePolicy={version:1,revision:1,roles};db.company.schedulingPolicyRequired=true;}
      if(mode==='conflict'){db.projects.push({id:202,name:'Synthetic conflicting project'});db.assignments.push({...structuredClone(db.assignments[0]),id:2,projectId:202,start:'00:15',end:'23:45'});}
      return db;
    }
    for(const mode of ['enabled','disabled','mixed','foreignEvidence','conflict','hidden','coworkerLeave']){
      s=await scenario(daySeed(mode));await s.login('field@example.invalid');const actor=s.store.current().users.find(row=>row.id===2);assert.equal(registry.effective(s.store.current(),actor).scheduling.edit,false);assert.equal(workflows.eligible(s.store.current(),actor).adoptActual,false);const beforeRows=structuredClone(s.store.current().assignments),businessDay=structuredClone(s.store.current().workdays[0]);
      const dailyPreview=await s.request('/api/daily-actions/preview','POST',{action:'endWorkday',id:1,details:{notes:'Synthetic completed tile',foreman:'Untrusted supplied foreman'}},'field@example.invalid');assert.equal(dailyPreview.status,200,JSON.stringify(dailyPreview));assert.deepEqual(s.store.current().assignments,beforeRows);assert.deepEqual(s.store.current().workdays[0],businessDay);
      const proof={token:dailyPreview.data.token,version:dailyPreview.data.version,confirmed:true,requestId:crypto.randomUUID()},end=await s.request('/api/workdays/1/end','POST',proof,'field@example.invalid');assert.equal(end.status,200,JSON.stringify(end));assert.equal(end.data.workday.status,'complete');assert.equal(s.store.current().workdays[0].status,'complete');
      if(mode==='enabled'||mode==='hidden'){if(mode==='enabled'){assert.equal(end.data.adopted.length,1);assert.equal(end.data.adopted[0].changed,true);}else assert.deepEqual(end.data.adopted,[]);assert.notDeepEqual(s.store.current().assignments,beforeRows);const autoAudit=s.store.current().auditLog.find(row=>row.auto===true);assert.equal(autoAudit.actorId,2);assert.equal(autoAudit.actor,actor.name);}
      else{assert.deepEqual(s.store.current().assignments,beforeRows);if(mode==='conflict'||mode==='coworkerLeave'){assert.ok(end.data.adopted.length);assert.ok(end.data.adopted.every(row=>row.changed===false&&row.error));}else assert.deepEqual(end.data.adopted,[]);}
      if(mode==='coworkerLeave'){assert.ok(!JSON.stringify(dailyPreview.data).includes('Synthetic private leave person'));assert.ok(!JSON.stringify(end.data).includes('Synthetic private leave person'));assert.ok(!JSON.stringify(end.data).includes('Synthetic private reason'));assert.equal(end.data.adopted[0].error,'Automatic update skipped. Review the schedule and workday times.');}
      const after=JSON.stringify(s.store.current()),rev=s.store.revision();const replay=await s.request('/api/workdays/1/end','POST',proof,'field@example.invalid');assert.equal(replay.status,200,JSON.stringify(replay));assert.deepEqual(replay.data,end.data);assert.equal(JSON.stringify(s.store.current()),after);assert.equal(s.store.revision(),rev);assert.equal(registry.effective(s.store.current(),s.store.current().users.find(row=>row.id===2)).scheduling.edit,false);
    }
    s=await scenario(daySeed('enabled'));await s.login('field@example.invalid');p=await s.request('/api/daily-actions/preview','POST',{action:'endWorkday',id:1,details:{notes:'Synthetic completed tile'}},'field@example.invalid');assert.equal(p.status,200);await s.alter(db=>{db.company.autoAdoptActualTimes=false;});assert.equal((await s.request('/api/workdays/1/end','POST',{token:p.data.token,version:p.data.version,confirmed:true,requestId:crypto.randomUUID()},'field@example.invalid')).status,409);assert.equal(s.store.current().workdays[0].status,'active');
    assert.deepEqual(fs.readFileSync(file),original);console.log('Finite scheduling workflows: default baselines, restrictions, scopes, preview/confirm, replay, lost ACK/restart, revocation, delivery and malicious custody passed ('+(native?'native PostgreSQL':'memory')+').');
  }finally{uninstall?.();await new Promise(resolve=>mod.server.close(resolve));await native?.close();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
