'use strict';
const assert = require('node:assert/strict'), crypto = require('node:crypto'), fs = require('node:fs'), os = require('node:os'), path = require('node:path'), { fork } = require('node:child_process'), { once } = require('node:events');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { A, B, initial, snapshot, memory } = require('./compat-account-fixture'), { services } = require('./compat-lifecycle-fixture'), { nativeFixture } = require('./compat-lifecycle-native-fixture');
async function main() {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'pdl-compat-lifecycle-')), evidence = process.env.PDL_COMPAT_BROWSER_EVIDENCE || path.join(directory, 'evidence'); fs.mkdirSync(evidence, { recursive: true });
  Object.assign(process.env, { NODE_ENV: 'test', PDL_COMPAT_ACCOUNT_SYNTHETIC: '1', PDL_REQUIRE_AUTH: '1', PDL_SUPABASE_ENABLED: '0', PDL_TRANSACTIONAL_DB: 'off', PDL_COMPAT_GLOBAL_FENCE_FILE: '' });
  for (const name of ['OPENAI_API_KEY', 'RESEND_API_KEY', 'STRIPE_SECRET_KEY', 'SENTRY_DSN', 'SUPABASE_SECRET_KEY', 'PDL_PLATFORM_KEY']) { if (process.env[name]) throw Error('Provider-free synthetic browser required'); process.env[name] = ''; }
  const legacy = snapshot(); legacy.company.id = B; legacy.users[0].companyId = B; legacy.users[0].email = 'global-owner@example.invalid'; const globalDirectory = path.join(directory, 'global'); fs.mkdirSync(globalDirectory); const globalFile = path.join(globalDirectory, 'db.json'); fs.writeFileSync(globalFile, JSON.stringify(legacy));
  const env = { ...process.env, PDL_DB_FILE: globalFile, PDL_PLATFORM_FILE: path.join(globalDirectory, 'platform.json') }, globalWorker = fork(path.join(__dirname, 'compat-account-browser-worker.cjs'), [], { env, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe', 'ipc'] });
  const ready = await once(globalWorker, 'message'); assert.equal(ready[0].event, 'ready'); const globalOrigin = 'http://localhost:' + ready[0].port;
  let browser, module, uninstall, native; const checks = [], errors = [], blocked = new Set(), external = new Set();
  try {
    const file = path.join(directory, 'db.json'); fs.writeFileSync(file, JSON.stringify(legacy)); process.env.PDL_DB_FILE = file; process.env.PDL_PLATFORM_FILE = path.join(directory, 'platform.json'); module = require('./server'); await new Promise(resolve => module.server.listen(0, '127.0.0.1', resolve)); const origin = 'http://127.0.0.1:' + module.server.address().port;
    if (process.env.TEST_COMPAT_DATABASE_URL) native = await nativeFixture(); const store = native?.repository || memory(snapshot());
    const fixture = services(store, origin); uninstall = module.installCompatibilityAccountTests({ synthetic: true, companyId: A, origin, globalOrigin, repository: store, ...fixture, dispatchAfterCommit: true });
    const fenceFile = path.join(directory, 'fence.json'); fs.writeFileSync(fenceFile, JSON.stringify({ version: 1, companyId: A, origin, globalOrigin })); const fenced = once(globalWorker, 'message'); globalWorker.send({ event: 'fence', file: fenceFile }); assert.equal((await fenced)[0].event, 'fenced');
    async function reset() { const db = snapshot(); db.projectTickets.push({ id: 900, projectId: 101, vendor: 'Synthetic retained source', lines: [], deletedAt: '2025-01-01T00:00:00.000Z', retainedUntil: '2025-04-01T00:00:00.000Z', url: '/uploads/project-tickets/never-delete-synthetic-g1.pdf', history: [] }); if (native) await native.reset(db); else { const loaded = await store.load(A); await store.commit(db, loaded.revision); } fixture.messages.length = 0; }
    browser = await chromium.launch({ ...(process.env.PDL_CHROMIUM_EXECUTABLE ? { executablePath: process.env.PDL_CHROMIUM_EXECUTABLE } : {}), headless: true, args: ['--disable-background-networking'] });
    async function context(viewport = { width: 1440, height: 1000 }) { const value = await browser.newContext({ viewport }); await value.route('**/*', route => { const url = new URL(route.request().url()); if ([origin, globalOrigin].includes(url.origin)) return route.continue(); external.add(url.origin + url.pathname); return route.abort(); }); return value; }
    async function login(page, email = 'owner@example.invalid', password = initial) { await page.goto(origin + '/login.html?tenant=' + A); await page.fill('#email', email); await page.fill('#password', password); await page.click('#login button[type=submit]'); await page.waitForURL(url => url.pathname === '/app'); await page.waitForFunction(() => document.documentElement.classList.contains('workspace-ready')); }
    async function review(page) { await page.locator('#account-review-dialog').waitFor(); await page.fill('#account-review-reason', 'Synthetic owner reviewed actual existing account form'); await page.click('#account-review-preview'); await page.locator('#account-review-save').waitFor({ state: 'visible' }); assert.equal(await page.isChecked('#account-review-confirmed'), false); await page.check('#account-review-confirmed'); await page.click('#account-review-save'); }
    for (const [name, viewport] of [['desktop', { width: 1440, height: 1000 }], ['mobile', { width: 390, height: 844 }]]) {
      await reset(); const ctx = await context(viewport), page = await ctx.newPage(); page.on('pageerror', error => errors.push(error.message)); page.on('response', response => { if (response.status() === 503) blocked.add(new URL(response.url()).pathname); });
      await login(page); await page.waitForFunction(() => Boolean(document.querySelector('#email-verification-banner'))); await page.waitForTimeout(250);
      for (let attempt = 0; attempt < 80 && !fixture.messages.some(row => row.purpose === 'email-verification'); attempt++) await page.waitForTimeout(50);
      const verification = fixture.messages.find(row => row.purpose === 'email-verification'); assert.ok(verification); await page.goto(verification.verifyUrl.replace(origin, globalOrigin)); await page.waitForURL(url => url.origin === origin && url.pathname === '/verify-email.html'); await page.locator('#verification-next:not([hidden])').waitFor(); await page.click('#verification-next'); await page.waitForFunction(() => document.documentElement.classList.contains('workspace-ready')); checks.push(name + ': existing resend and legacy-host verification link preserves sessions');
      assert.equal((await store.load(A)).snapshot.projectTickets[0].purgedAt, undefined); checks.push(name + ': account page loads with expired retained source without deleting it');
      if (name === 'mobile') await page.click('#menu-button'); if (!(await page.isVisible('.nav-item[data-page="team"]'))) await page.click('.nav-more > summary'); await page.click('.nav-item[data-page="team"]'); await page.click('[data-team-tab="accounts"]'); await page.click('#team-add-button'); await page.fill('#user-name', 'Browser PM ' + name); await page.fill('#user-email', 'browser-' + name + '@example.invalid'); await page.selectOption('#user-role', 'project_manager'); await page.click('#save-user'); await review(page); await page.locator('#setup-code-result input').waitFor();
      let loaded = await store.load(A); const target = loaded.snapshot.users.find(row => row.email === 'browser-' + name + '@example.invalid'); assert.ok(target); const secretInput = page.locator('#setup-code-result input'); const temporaryPassword = await secretInput.inputValue(); assert.match(temporaryPassword, /^[A-Za-z0-9_-]{8}$/); assert.equal(JSON.stringify(loaded.snapshot).includes(temporaryPassword), false); checks.push(name + ': existing add-account form uses preview/reason/unchecked confirmation and committed secret');
      await page.locator('#user-modal .close-button').click(); await page.screenshot({ path: path.join(evidence, 'g1-' + name + '-accounts.png'), fullPage: true });
      if (name === 'mobile') await page.click('#menu-button'); await page.click('#profile-button'); await page.fill('#profile-display-name', 'Browser Owner ' + name); await page.selectOption('#profile-language', 'es'); await page.click('#save-profile'); await page.locator('#profile-modal').waitFor({ state: 'hidden' }); if (name === 'mobile') await page.mouse.click(viewport.width - 10, 100); assert.equal((await store.load(A)).snapshot.users[0].preferences.displayName, 'Browser Owner ' + name); checks.push(name + ': existing owner profile preferences save and read back');
      await page.click('[data-user-edit="' + target.id + '"]'); await page.check('#user-schedule-crews'); await page.click('#save-user'); await review(page); await page.locator('#user-modal').waitFor({ state: 'hidden' }); assert.equal((await store.load(A)).snapshot.users.find(row => row.id === target.id).permissions.scheduleCrews, true); checks.push(name + ': existing account access edit reviewed with actual stored grants');
      await page.click('[data-user-reset="' + target.id + '"]'); await page.click('#confirm-password-reset'); await review(page); await page.locator('#password-reset-result input').waitFor(); const replacement = await page.locator('#password-reset-result input').inputValue(); assert.notEqual(replacement, temporaryPassword); await page.locator('#password-reset-modal .close-button').click(); checks.push(name + ': existing reset-password dialog commits replacement once');
      await page.click('[data-team-tab="employees"]'); await page.click('#team-add-button'); await page.fill('#member-name', 'Browser linked employee ' + name); await page.selectOption('#member-role', 'Laborer'); await page.selectOption('#member-crew', '__new__'); await page.fill('#member-new-crew', 'New browser synthetic crew ' + name); await page.fill('#member-email', 'linked-' + name + '@example.invalid'); await page.selectOption('#member-account-role', 'field'); await page.click('#save-team-member'); await review(page); await page.locator('#password-reset-modal[open]').waitFor(); const compound = (await store.load(A)).snapshot, linkedUser = compound.users.find(row => row.email === 'linked-' + name + '@example.invalid'); assert.ok(compound.team.some(row => row.id === linkedUser.memberId)); await page.locator('#password-reset-modal .close-button').click(); checks.push(name + ': existing employee-with-login form commits member and account together');
      const memberCtx = await context(viewport), memberPage = await memberCtx.newPage(); await memberPage.goto(origin + '/login.html?tenant=' + A); await memberPage.fill('#email', target.email); await memberPage.fill('#password', replacement); await memberPage.click('#login button[type=submit]'); await memberPage.locator('#setup-modal[open]').waitFor(); const permanent = 'Synthetic browser permanent ' + name; await memberPage.fill('#new-password', permanent); await memberPage.fill('#confirm-password', permanent); await memberPage.click('#claim button[type=submit]'); await memberPage.waitForURL(url => url.pathname === '/app'); await memberPage.waitForFunction(() => document.documentElement.classList.contains('workspace-ready')); assert.equal((await store.load(A)).snapshot.users.find(row => row.id === target.id).mustSetPassword, false); checks.push(name + ': actual first-login setup claims code and signs in'); await memberCtx.close(); await ctx.close();
    }
    // A buffered private result must not appear after the actual browser cookie
    // changes to another current actor, even if the old request committed.
    await reset(); {
      const loaded = await store.load(A); loaded.snapshot.users[0].emailVerifiedAt = new Date().toISOString(); loaded.snapshot.users.push({ ...loaded.snapshot.users[0], id: 2, role: 'admin', email: 'browser-admin@example.invalid', name: 'Synthetic Browser Admin' }); await store.commit(loaded.snapshot, loaded.revision);
      const ctx = await context(); await ctx.addInitScript(() => { const original = fetch; window.fetch = async (...args) => { const response = await original(...args); if (args[0] === '/api/account-actions/confirm') { const json = response.json.bind(response); response.json = async () => { const data = await json(); window.g1Buffered = true; await new Promise(resolve => { window.g1Release = resolve; }); return data; }; } return response; }; });
      const page = await ctx.newPage(); await login(page); await page.click('.nav-more > summary'); await page.click('.nav-item[data-page="team"]'); await page.click('[data-team-tab="accounts"]'); await page.click('#team-add-button'); await page.fill('#user-name', 'Buffered Synthetic Account'); await page.fill('#user-email', 'buffered@example.invalid'); await page.click('#save-user'); await review(page); await page.waitForFunction(() => window.g1Buffered === true);
      assert.equal((await ctx.request.post(origin + '/api/auth/login', { headers: { 'X-PDL-Company': A }, data: { email: 'browser-admin@example.invalid', password: initial } })).status(), 200); await page.evaluate(() => window.g1Release()); await page.locator('#account-review-dialog').waitFor({ state: 'detached' }); await page.waitForTimeout(100); assert.equal(await page.locator('#setup-code-result input').count(), 0); assert.equal(await page.locator('#password-reset-result input').count(), 0); assert.ok((await store.load(A)).snapshot.users.some(row => row.email === 'buffered@example.invalid')); checks.push('buffered committed confirmation cannot reveal former-owner secret after real actor/cookie change'); await ctx.close();
    }
    // A response lost after COMMIT is checked by its original operation. After
    // setup consumes the code, the owner reviews current accounts and explicitly
    // closes browser recovery while retaining the server receipt and audit.
    await reset(); {
      const loaded = await store.load(A); loaded.snapshot.users[0].emailVerifiedAt = new Date().toISOString(); await store.commit(loaded.snapshot, loaded.revision);
      const ctx = await context(), page = await ctx.newPage(); await login(page); await page.click('.nav-more > summary'); await page.click('.nav-item[data-page="team"]'); await page.click('[data-team-tab="accounts"]'); await page.click('#team-add-button'); await page.fill('#user-name', 'Lost Synthetic Account'); await page.fill('#user-email', 'lost@example.invalid');
      await ctx.route(origin + '/api/account-actions/confirm', async route => { await route.fetch(); await route.abort(); }); await page.click('#save-user'); await review(page); await page.locator('#account-original-result').waitFor(); await ctx.unroute(origin + '/api/account-actions/confirm');
      const pending = await page.evaluate(() => JSON.parse(sessionStorage.getItem('pdl-original-account-operation-v1'))); const stored = (await store.load(A)).snapshot, target = stored.users.find(row => row.email === 'lost@example.invalid'), cookies = await ctx.cookies(origin), sessionCookie = cookies.find(row => row.name === 'pdl_session').value, sessionHash = crypto.createHash('sha256').update(sessionCookie).digest('hex'), session = stored.sessions.find(row => row.tokenHash === sessionHash), owner = stored.users.find(row => row.id === session.userId);
      const original = fixture.secretRecovery.recover(stored, { companyId: A, user: owner, session }, pending.operationId); assert.equal((await ctx.request.post(origin + '/api/auth/claim', { headers: { 'X-PDL-Company': A }, data: { email: target.email, temporaryPassword: original.temporaryPassword, password: 'Synthetic consumed lost-result password' } })).status(), 200);
      await page.locator('#user-modal .close-button').click(); await page.click('#account-original-result'); await page.locator('#account-reconcile-result').waitFor(); await page.click('#account-reconcile-result'); await page.locator('#account-original-result-dialog').waitFor(); assert.equal(await page.isChecked('#account-original-result-dialog input[type=checkbox]'), false); await page.fill('#account-original-result-dialog textarea', 'Reviewed committed account and consumed setup password'); await page.check('#account-original-result-dialog input[type=checkbox]'); await page.getByRole('button', { name: 'Retain original history and close browser recovery' }).click(); await page.locator('#account-original-result-dialog').waitFor({ state: 'detached' });
      assert.equal(await page.evaluate(() => sessionStorage.getItem('pdl-original-account-operation-v1')), null); const final = (await store.load(A)).snapshot; assert.ok(final.accountActionReceipts.some(row => row.operationId === pending.operationId)); assert.ok(final.auditLog.some(row => row.type === 'account_original_result_reconciled' && row.observedOutcome === 'committed')); checks.push('lost-response then consumed-code recovery has explicit current-account reconciliation and retained original history'); await ctx.close();
    }
    // Original generic global login discovers the selected current account and
    // redirects before transmitting the credential to any global tenant route.
    await reset(); const ctx = await context(), page = await ctx.newPage(); let globalCredentialCalls = 0;
    page.on('request', request => { if (request.url() === globalOrigin + '/api/auth/login') globalCredentialCalls++; }); await page.goto(globalOrigin + '/login.html'); await page.fill('#email', 'owner@example.invalid'); await page.fill('#password', initial); await page.click('#login button[type=submit]'); await page.waitForURL(url => url.origin === origin && url.pathname === '/login.html'); assert.equal(globalCredentialCalls, 0); assert.equal(new URL(page.url()).searchParams.get('tenant'), A); checks.push('no-hint existing global login discovers current selected tenant and redirects before credential send');
    assert.equal((await ctx.request.get(globalOrigin + '/api/founder-offer')).status(), 200); const signup = await ctx.request.post(globalOrigin + '/api/signup', { data: { companyName: 'Synthetic unchanged global enrollment', ownerName: 'Synthetic global owner', email: 'new-global@example.invalid', password: initial, employeeCount: 2, projectCount: 1, plan: 'starter', onboardingPreference: 'self', legalAccepted: true, legalVersion: '2026-09-17' } }); assert.equal(signup.status(), 201); assert.equal((await ctx.request.get(globalOrigin + '/api/auth/me')).status(), 200); checks.push('ordinary founder/signup and newly enrolled other tenant remain legacy'); await ctx.close();
    assert.deepEqual(errors, []); const report = { checks, backend: native ? 'native-postgresql' : 'synthetic-memory', blockedOtherGatePaths: [...blocked].sort(), externalAttemptsAborted: [...external], allowedExternalRequests: 0, pageErrors: errors, productionReady: false }; fs.writeFileSync(path.join(evidence, 'g1-account-lifecycle-browser-results.json'), JSON.stringify(report, null, 2)); console.log(JSON.stringify({ passed: checks.length, backend: report.backend, pageErrors: 0, allowedExternalRequests: 0 }));
  } finally { uninstall?.(); await browser?.close(); if (module) await new Promise(resolve => module.server.close(resolve)); await native?.close(); if (globalWorker.connected) globalWorker.send({ event: 'close' }); await new Promise(resolve => { if (globalWorker.exitCode !== null) return resolve(); globalWorker.once('exit', resolve); setTimeout(() => { if (globalWorker.exitCode === null) globalWorker.kill(); }, 3000); }); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
