'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const A='b0576860-a3d9-4bb6-aae2-b5e7186cbb71',B='ba19a156-1cac-4c8a-b921-6bc356df97ef',hash='a'.repeat(64),other='b'.repeat(64);
const identity=(companyId=A,role='owner')=>({companyId,actorId:1,role,revision:10,authority:companyId===A?hash:other,sessionBinding:companyId===A?hash:other,expiresAt:new Date(Date.now()+60000).toISOString(),locked:false,effectiveCapabilities:{},features:{}});
async function main(){
 let company=A,next=identity(),retired=0,hold,started;const events={};
 const box={window:{addEventListener:(name,fn)=>events[name]=fn},document:{querySelectorAll:()=>[],getElementById:()=>null,querySelector:()=>null},localStorage:{getItem:()=>company},Date,Error,URL,fetch:async()=>({ok:true,json:async()=>{if(hold){started?.();await hold;}return next;}})};
 vm.createContext(box);vm.runInContext(fs.readFileSync('workspace-actions-ui.js','utf8'),box);const actions=box.window.pdlWorkspaceActions;
 await assert.rejects(actions.verifyResponse({ok:true,headers:{get:key=>key.includes('Revision')?'10':hash}},'/api/state'),/configuration is required/);assert.equal(actions.enabled(),false);
 const configure=(role='owner')=>actions.configure({compatibilityAccount:{workspace:true,companyId:company}},{id:1,role:role==='foreman'?'field':role,accessRole:role,accountSessionBinding:company===A?hash:other},()=>retired++);
 configure();await actions.identity();
 let release;hold=new Promise(resolve=>release=resolve);let begun;const ready=new Promise(resolve=>begun=resolve);started=begun;
 const old=actions.identity();await ready;company=B;configure();release();await assert.rejects(old,/changed while checking/);hold=null;next=identity(B);await actions.identity();assert.equal(retired,1);
 await assert.rejects(actions.verifyResponse({ok:true,headers:{get:key=>key.includes('Revision')?'10':hash}},'/api/production'),/changed while loading/);assert.equal(retired,2);
 company=A;configure('foreman');next=identity(A,'foreman');assert.equal((await actions.identity()).role,'foreman');
 next={...next,locked:true};await assert.rejects(actions.identity(),/access changed/);assert.ok(retired>=3);
 await assert.rejects(actions.verifyResponse({ok:false,status:402,headers:{get:()=>null}},'/api/time-cards.csv'),error=>error.status===402);
 const responseHeaders=(authority=other,reconciled=hash)=>({get:name=>({'X-PDL-Workspace-Revision':'10','X-PDL-Workspace-Authority':authority,'X-PDL-Workspace-Reconciled-From':reconciled}[name]??null)});
 company=A;next=identity();configure();await actions.identity();next={...next,authority:other};await actions.verifyResponse({ok:true,headers:responseHeaders()},'/api/state');assert.equal((await actions.identity()).authority,other);
 next=identity();configure();await actions.identity();next={...next,authority:other};await assert.rejects(actions.verifyResponse({ok:true,headers:responseHeaders()},'/api/production'),/access changed/);
 next=identity();configure();await actions.identity();next={...next,authority:other};await assert.rejects(actions.verifyResponse({ok:true,headers:responseHeaders(other,other)},'/api/state'),/access changed/);
 next=identity();configure();await actions.identity();next={...next,role:'admin',authority:other};await assert.rejects(actions.verifyResponse({ok:true,headers:responseHeaders()},'/api/state'),/Sign in again/);
 company=A;next=identity();configure();const root={style:{visibility:''}};box.document.getElementById=()=>root;
 const beforePrepare=retired;let ran=0;box.workspaceApi=async()=>{throw Object.assign(Error('Synthetic prepare unavailable'),{status:503});};
 await assert.rejects(actions.load(async()=>ran++),error=>error.status===503);assert.equal(ran,0);assert.equal(retired,beforePrepare+1);assert.equal(actions.displayedRevision(),null);assert.equal(root.style.visibility,'');
 box.workspaceApi=async()=>({ready:true});assert.equal(await actions.load(async()=>++ran),1);assert.equal(actions.displayedRevision(),10);assert.equal(root.style.visibility,'');
 let releasePrepare,prepareStarted;const preparing=new Promise(resolve=>prepareStarted=resolve),prepareHold=new Promise(resolve=>releasePrepare=resolve);let preparationCount=0,visible='current',olderRuns=0;
 box.workspaceApi=async()=>{if(++preparationCount===1){prepareStarted();await prepareHold;}return {ready:true};};
 const older=actions.load(async()=>{olderRuns++;visible='older';}).catch(error=>error);await preparing;
 const newer=actions.load(async()=>{visible='newer';});releasePrepare();assert.match((await older).message,/changed while preparing/);await newer;
 assert.equal(olderRuns,0);assert.equal(visible,'newer');assert.equal(actions.displayedRevision(),10);assert.equal(root.style.visibility,'');
 let releaseRun,runStarted,binding;const running=new Promise(resolve=>runStarted=resolve),runHold=new Promise(resolve=>releaseRun=resolve);box.workspaceApi=async()=>({ready:true});
 const runningOlder=actions.load(async()=>{binding=actions.capture();runStarted();await runHold;visible='older';}).catch(error=>error);await running;
 const queuedNewer=actions.load(async()=>{visible='newer';});
 await assert.rejects(actions.verifyResponse({ok:true,headers:{get:key=>key.includes('Revision')?'10':hash}},'/api/state',binding),/earlier load/);
 releaseRun();assert.match((await runningOlder).message,/changed during loading/);await queuedNewer;assert.equal(visible,'newer');assert.equal(root.style.visibility,'');
 let releaseDelivery,deliveryStarted,deliveryApplied=false;const deliveryReady=new Promise(resolve=>deliveryStarted=resolve),deliveryHold=new Promise(resolve=>releaseDelivery=resolve);
 const deliveryOlder=actions.load(async()=>{hold=deliveryHold;started=deliveryStarted;try{await actions.verifyResponse({ok:true,headers:{get:key=>key.includes('Revision')?'10':hash}},'/api/state',actions.capture());deliveryApplied=true;}finally{hold=null;started=null;}}).catch(error=>error);
 await deliveryReady;const deliveryNewer=actions.load(async()=>{visible='newer';});releaseDelivery();assert.match((await deliveryOlder).message,/earlier load/);await deliveryNewer;assert.equal(deliveryApplied,false);assert.equal(visible,'newer');
 const reviewBox={window:{},location:{origin:'http://127.0.0.1'},URL,crypto:require('node:crypto').webcrypto};vm.createContext(reviewBox);vm.runInContext(fs.readFileSync('workspace-action-review.js','utf8'),reviewBox);
 const operation=reviewBox.window.pdlWorkspaceReview.operation;
 const clock=operation('/api/time-cards/1/clock-out',{method:'POST',body:'{}'});assert.equal(clock.preview.action,'clockOut');assert.equal(clock.action,'clockCards');assert.equal(operation('/api/time-cards/approve',{method:'POST',body:'{"ids":[1]}'}).action,'approveCards');
 const source=fs.readFileSync('app.js','utf8'),begin=source.indexOf('async function api(path,options={})'),end=source.indexOf('\nconst workspaceApi=api;',begin);assert.ok(begin>0&&end>begin);
 let ack=0,posts=0,clears=0,refreshStatus=503;const notices=[];
 const apiBox={window:{pdlWorkspaceActions:{enabled:()=>true,clear:()=>clears++,verifyResponse:async()=>{}}},signedInCompanyId:()=>A,wakeService:async()=>{},fetch:async(path,request)=>{if(request.method==='PATCH')posts++;const status=path==='/api/state'?refreshStatus:200;return {ok:status===200,status,headers:{get:()=> 'application/json'},json:async()=>status===200?{id:501,status:'Approved'}:{error:'Synthetic refresh failure'}};},notify:value=>notices.push(value),location:{},Error};
 vm.createContext(apiBox);vm.runInContext(source.slice(begin,end),apiBox);
 assert.equal((await apiBox.api('/api/reports/501/approve',{method:'PATCH',onAcknowledged:()=>ack++})).id,501);assert.equal(ack,1);assert.equal(posts,1);assert.ok(notices.some(value=>value.startsWith('Saved.')));
 refreshStatus=403;await assert.rejects(apiBox.api('/api/reports/501/approve',{method:'PATCH',onAcknowledged:()=>ack++}),error=>error.saved===true&&error.message.startsWith('Saved.'));assert.equal(ack,2);assert.equal(clears,1);
 apiBox.fetch=async()=>{throw Error('Synthetic acknowledgement lost');};
 await assert.rejects(apiBox.api('/api/time-cards',{method:'POST',onAcknowledged:()=>ack++}),error=>error.code==='PDL_WORKSPACE_SAVE_UNKNOWN'&&/unknown.*original save result/.test(error.message));assert.equal(ack,2);
 apiBox.window.pdlWorkspaceActions.enabled=()=>false;
 await assert.rejects(apiBox.api('/api/time-cards',{method:'POST',onAcknowledged:()=>ack++}),/Nothing was saved/);
 const bootBegin=source.indexOf('async function boot(){'),bootEnd=source.indexOf('\nfunction showEmailVerificationNotice',bootBegin);assert.ok(bootBegin>0&&bootEnd>bootBegin);
 let privateLoads=0,configuredLoads=0,configFetches=0,bootRetired=0;
 const me={id:1,role:'owner',companyId:A},bootBox={window:{pdlWorkspaceConfig:{authRequired:true,compatibilityAccount:{workspace:true,companyId:A}},pdlAuthenticatedUser:me,pdlWorkspaceActions:{configure:(config,user,onRetire)=>{assert.equal(config.authRequired,true);assert.equal(user.companyId,A);assert.equal(typeof onRetire,'function');configuredLoads++;}}},fetch:async()=>{configFetches++;throw Error('Second config unavailable');},api:async path=>path==='/api/auth/me'?me:{locked:false},workspaceApi:async()=>{},retireWorkspaceData:()=>bootRetired++,loadRole:async()=>{privateLoads++;},handleBillingReturn:async()=>{},identifyAnalyticsUser(){},localStorage:{getItem:()=>A,setItem(){}},$:()=>({hidden:true}),location:{search:''},URLSearchParams,notify(){},currentUser:null};
 vm.createContext(bootBox);vm.runInContext(source.slice(bootBegin,bootEnd),bootBox);await bootBox.boot();assert.equal(configFetches,0);assert.equal(configuredLoads,1);assert.equal(privateLoads,1);
 delete bootBox.window.pdlWorkspaceConfig;await bootBox.boot();assert.equal(privateLoads,1);assert.equal(bootRetired,1);assert.equal(bootBox.window.pdlAuthenticatedUser,null);
 bootBox.fetch=async()=>({ok:true,json:async()=>({})});await bootBox.boot();assert.equal(privateLoads,1);assert.equal(bootRetired,2);
 bootBox.fetch=async()=>({ok:true,json:async()=>({authRequired:false})});await bootBox.boot();assert.equal(privateLoads,2);assert.equal(configuredLoads,1);
 const declaration=name=>{const line=source.split('\n').find(line=>line.startsWith('function '+name+'(')||line.startsWith('async function '+name+'('));assert.ok(line,name);return line;};
 const reads=[],refreshBox={window:{pdlWorkspaceActions:{enabled:()=>true}},currentRole:'office',currentUser:{role:'project_manager',permissions:{viewTime:true,manageTime:true},effectiveCapabilities:{timeReview:{viewCards:false},timeWrite:{viewActivities:false},timeOff:{viewRequests:false}}},company:{features:{timeCards:true}},document:{body:{classList:{toggle(){}}}},timeCards:[{id:9}],timeOffRequests:[{id:'private'}],companyActivityCodes:[{id:'private'}],api:async path=>{reads.push(path);return[];},$:()=>({classList:{contains:()=>false},value:'',innerHTML:''}),renderTimeCards(){},renderTimeCardWarnings(){},renderTimeOverview(){},renderProjectCards(){},renderCompanyClockStatus(){},renderTimeOff(){},notify(){},escapeHtml:value=>value};
 vm.createContext(refreshBox);vm.runInContext(['timeCardsOn','canViewTime','refreshTimeCards','refreshCompanyActivities','refreshTimeOff'].map(declaration).join('\n'),refreshBox);
 assert.equal(refreshBox.canViewTime(),false);await refreshBox.refreshTimeCards();await refreshBox.refreshCompanyActivities();await refreshBox.refreshTimeOff();assert.equal(reads.length,0);assert.equal(refreshBox.timeCards.length,0);assert.equal(refreshBox.timeOffRequests.length,0);assert.equal(refreshBox.companyActivityCodes.length,0);
 console.log('workspace client: tenant/configure epoch, Foreman, natural lock, denied CSV, clock/bulk routing and known-save refresh failures passed');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
