'use strict';
const assert = require('node:assert/strict'), crypto = require('node:crypto'), fs = require('node:fs'), os = require('node:os'), path = require('node:path'), { fork } = require('node:child_process');
const { A, B, initial, snapshot, credential } = require('./compat-account-fixture');
const { nativeFixture } = require('./compat-lifecycle-native-fixture');
process.env.NODE_ENV = 'test'; process.env.PDL_COMPAT_ACCOUNT_SYNTHETIC = '1'; process.env.PDL_REQUIRE_AUTH = '1';
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
function event(child, type) { return new Promise((resolve, reject) => { const timer = setTimeout(() => { child.off('message', on); reject(Error('Synthetic worker timeout: ' + type)); }, 15000); function on(message) { if (message.event === type) { clearTimeout(timer); child.off('message', on); resolve(message); } } child.on('message', on); child.once('error', reject); }); }
async function main() {
  const fixture = await nativeFixture(), directory = fs.mkdtempSync(path.join(os.tmpdir(), 'pdl-compat-lifecycle-')), workers = [];
  const keyFile = path.join(directory, 'synthetic-key'); fs.writeFileSync(keyFile, crypto.randomBytes(32), { mode: 0o600 }); const legacy = snapshot(); legacy.company.id = B; legacy.users[0].companyId = B; const file = path.join(directory, 'db.json'); fs.writeFileSync(file, JSON.stringify(legacy));
  const checks = []; let sharedOrigin, token;
  async function start() { const env = { ...process.env, PDL_DB_FILE: file, PDL_PLATFORM_FILE: path.join(directory, 'platform.json'), PDL_COMPAT_GLOBAL_FENCE_FILE: '', PDL_SUPABASE_ENABLED: '0', PDL_TRANSACTIONAL_DB: 'off', TEST_COMPAT_LIFECYCLE_KEY_FILE: keyFile, TEST_COMPAT_LIFECYCLE_ORIGIN: sharedOrigin || '' }; for (const name of ['OPENAI_API_KEY', 'RESEND_API_KEY', 'STRIPE_SECRET_KEY', 'SENTRY_DSN', 'SUPABASE_SECRET_KEY', 'PDL_PLATFORM_KEY']) env[name] = ''; const child = fork(path.join(__dirname, 'compat-lifecycle-http-worker.cjs'), [], { env, stdio: ['ignore', 'pipe', 'pipe', 'ipc'], windowsHide: true }); const ready = await event(child, 'ready'); child.origin = ready.origin; workers.push(child); sharedOrigin ||= ready.origin; return child; }
  async function close(child) { if (!child.connected) return; const exited = new Promise(resolve => child.once('exit', resolve)); child.send({ event: 'close' }); await exited; }
  async function request(child, route, method = 'GET', input, bearer = token) { const response = await fetch(child.origin + route, { method, headers: { 'X-PDL-Company': A, ...(bearer ? { Authorization: 'Bearer ' + bearer } : {}), ...(input === undefined ? {} : { 'Content-Type': 'application/json' }) }, ...(input === undefined ? {} : { body: JSON.stringify(input) }) }); return { status: response.status, data: await response.json() }; }
  async function login(child, email = 'owner@example.invalid') { const result = await request(child, '/api/auth/login', 'POST', { email, password: initial }, ''); assert.equal(result.status, 200); return result.data.token; }
  async function preview(child, route, method, input) { const result = await request(child, '/api/account-actions/preview', 'POST', { method, path: route, input, reason: 'Synthetic native owner review', operationId: crypto.randomUUID() }); assert.equal(result.status, 200, JSON.stringify(result)); return { previewId: result.data.previewId, operationId: result.data.operationId, expectedRevision: result.data.expectedRevision, confirmed: true }; }
  async function alter(change) { const loaded = await fixture.repository.load(A); change(loaded.snapshot); await fixture.repository.commit(loaded.snapshot, loaded.revision); }
  try {
    await fixture.reset(snapshot()); let first = await start(), second = await start(); token = await login(first);
    const body = await preview(first, '/api/users', 'POST', { name: 'Native PM', email: 'native-pm@example.invalid', role: 'project_manager', projectIds: [101], assignedCrews: ['Synthetic Crew'], permissions: { scheduleCrews: true } });
    const attempts = await Promise.all([request(first, '/api/account-actions/confirm', 'POST', body), request(second, '/api/account-actions/confirm', 'POST', body)]); assert.ok(attempts.some(row => row.status === 201)); assert.ok(attempts.every(row => [201, 409].includes(row.status)));
    const account = attempts.find(row => row.status === 201).data, password = account.temporaryPassword, target = account.id; let current = await fixture.repository.load(A); assert.equal(current.snapshot.users.length, 2); assert.equal(current.snapshot.auditLog.filter(row => row.type === 'account_change_confirmed').length, 1);
    assert.equal((await request(second, '/api/account-actions/confirm', 'POST', body)).data.temporaryPassword, password); checks.push('two HTTP workers first-confirm/replay single account and audit');
    await close(first); first = await start(); assert.equal((await request(first, '/api/account-actions/recover', 'POST', { operationId: body.operationId })).data.temporaryPassword, password); checks.push('restart with same synthetic purpose keys recovers original secret');
    const reset = await preview(second, '/api/users/' + target + '/reset-code', 'POST', {}); const armed = event(second, 'armed'); second.send({ event: 'lose-ack' }); await armed; assert.equal((await request(second, '/api/account-actions/confirm', 'POST', reset)).status, 503); assert.match((await request(first, '/api/account-actions/recover', 'POST', { operationId: reset.operationId })).data.temporaryPassword, /^[A-Za-z0-9_-]{8}$/); checks.push('native commit succeeds then lost HTTP acknowledgement recovers only original receipt');
    const stale = await preview(first, '/api/users/' + target + '/time-access', 'PATCH', { manageTime: true }); const arm = event(first, 'armed'); first.send({ event: 'hold-commit' }); await arm; const held = event(first, 'commit-held'), pending = request(first, '/api/account-actions/confirm', 'POST', stale); await held; await alter(db => { db.users[0].role = 'admin'; }); first.send({ event: 'release-commit' }); assert.equal((await pending).status, 409); assert.equal((await fixture.repository.load(A)).snapshot.users[1].permissions.manageTime, false); await alter(db => { db.users[0].role = 'owner'; }); checks.push('role revoked on another native worker before staged confirmation commit');
    const hold = event(second, 'armed'); second.send({ event: 'hold-final' }); await hold; const finalHeld = event(second, 'final-held'), returning = request(second, '/api/account-actions/recover', 'POST', { operationId: reset.operationId }); await finalHeld; await alter(db => { db.users[1].status = 'Deactivated'; }); second.send({ event: 'release-final' }); const result = await returning; assert.equal(result.status, 409); assert.equal(Object.hasOwn(result.data, 'temporaryPassword'), false); checks.push('held secret return suppressed by current target revocation');
    await alter(db => { db.users[1].status = 'Active'; db.company.billingExempt = false; db.company.subscriptionStatus = 'Trial'; db.company.trialEndsAt = new Date(Date.now() + 1000).toISOString(); });
    const before = await fixture.repository.load(A), locker = await fixture.admin.connect(); await locker.query('BEGIN'); await locker.query('SELECT revision FROM public.tenant_revisions WHERE company_id=$1 FOR UPDATE', [A]);
    try { const waiting = request(first, '/api/users/1/preferences', 'PATCH', { displayName: 'Must not commit after trial expiry' }); await delay(1400); await locker.query('COMMIT'); assert.equal((await waiting).status, 409); const after = await fixture.repository.load(A); assert.equal(after.revision, before.revision); assert.equal(after.contentHash, before.contentHash); } finally { await locker.query('ROLLBACK').catch(() => {}); locker.release(); }
    checks.push('trial natural expiry under held SQL row lock rolls back all preference changes');
    await fixture.reset(snapshot()); const policy = require('./scheduling-access'); await alter(db => { db.users.push({ ...db.users[0], id: 2, role: 'project_manager', name: 'Restricted PM', email: 'restricted@example.invalid', ...credential(initial), projectIds: [101], assignedCrews: ['Synthetic Crew'], permissions: { scheduleCrews: true } }); db.company.schedulingRolePolicy = { version: 1, revision: 1, roles: Object.fromEntries(policy.roles.map(role => [role, { ...policy.ceiling(role), ...(role === 'project_manager' ? { create: false, edit: false, remove: false } : {}) }])) }; });
    const pmToken = await login(second, 'restricted@example.invalid'), pm = await request(second, '/api/auth/me', 'GET', undefined, pmToken); assert.equal(pm.status, 200); assert.equal(pm.data.schedulingAccess.edit, false); assert.equal(pm.data.permissions.scheduleCrews, true); assert.equal((await request(second, '/api/users', 'GET', undefined, pmToken)).status, 403); checks.push('current restrictive typed policy resolves in actual login/me and cannot grant owner management');
    const profiles = require('./role-profiles'), profileId = crypto.randomUUID();
    await alter(db => { delete db.company.schedulingRolePolicy; db.company.roleProfilesRequired = true; db.company.roleProfiles = { version: 1, revision: 1, profiles: [{ id: profiles.OFFICE_ID, name: 'Office', kind: 'office', baseRole: 'admin', scopeInheritance: profiles.SCOPE, revision: 1, capabilities: profiles.defaults('admin', true) }, { id: profileId, name: 'Read existing assigned work', kind: 'custom', baseRole: 'project_manager', scopeInheritance: profiles.SCOPE, revision: 1, capabilities: profiles.defaults('project_manager', true) }], assignments: [{ accountId: 2, profileId }], retiredIds: [] }; });
    const assigned = await request(second, '/api/auth/me', 'GET', undefined, pmToken); assert.equal(assigned.status, 200); assert.equal(assigned.data.schedulingAccess.create, false); assert.equal(assigned.data.notesPermissions.edit, false); token = await login(first);
    const roleChange = await request(first, '/api/account-actions/preview', 'POST', { method: 'PATCH', path: '/api/users/2', input: { role: 'field', memberId: 11 }, reason: 'Synthetic attempted assigned base role change', operationId: crypto.randomUUID() }); assert.equal(roleChange.status, 409); checks.push('assigned restrictive profile freshly resolves and its base-role binding cannot be bypassed by account edit');
    await fixture.reset(snapshot()); token = await login(first);
    const { services } = require('./compat-lifecycle-fixture'), delivery = services(fixture.repository, sharedOrigin, { key: fs.readFileSync(keyFile) });
    let loaded = await fixture.repository.load(A); const verification = delivery.credentials.requestVerification(loaded.snapshot, 1); await fixture.repository.commit(loaded.snapshot, loaded.revision); await delivery.credentials.dispatch(A, verification.jobId);
    const verificationToken = new URL(delivery.messages[0].verifyUrl).searchParams.get('token'), existingSessions = (await fixture.repository.load(A)).snapshot.sessions;
    const verifyRace = await Promise.all([request(first, '/api/auth/email-verification/confirm', 'POST', { token: verificationToken }, ''), request(second, '/api/auth/email-verification/confirm', 'POST', { token: verificationToken }, '')]); assert.equal(verifyRace.filter(row => row.status === 200).length, 1); assert.ok(verifyRace.every(row => [200, 401, 409].includes(row.status))); assert.deepEqual((await fixture.repository.load(A)).snapshot.sessions, existingSessions); checks.push('two HTTP workers consume verification once and preserve current sessions');
    loaded = await fixture.repository.load(A); const resetJob = delivery.credentials.requestReset(loaded.snapshot, 'owner@example.invalid'); await fixture.repository.commit(loaded.snapshot, loaded.revision); await delivery.credentials.dispatch(A, resetJob.jobId);
    const resetToken = new URL(delivery.messages.at(-1).resetUrl).searchParams.get('token');
    const resetRace = await Promise.all([request(first, '/api/auth/reset', 'POST', { email: 'owner@example.invalid', token: resetToken, password: 'Synthetic permanent native reset' }, ''), request(second, '/api/auth/reset', 'POST', { email: 'owner@example.invalid', token: resetToken, password: 'Synthetic permanent native reset' }, '')]); assert.equal(resetRace.filter(row => row.status === 200).length, 1); assert.ok(resetRace.every(row => [200, 401, 409].includes(row.status))); assert.equal((await request(first, '/api/users')).status, 401); assert.equal((await fixture.repository.load(A)).snapshot.sessions.length, 0); checks.push('two HTTP workers consume reset once and revoke the former owner session');
    await fixture.reset(snapshot()); await alter(db => { const salt = crypto.randomBytes(16).toString('hex'); Object.assign(db.users[0], { mustSetPassword: true, setupSalt: salt, setupHash: crypto.scryptSync('Setup123', salt, 64).toString('hex'), setupExpiresAt: new Date(Date.now() + 72 * 3600000).toISOString() }); });
    const claimRace = await Promise.all([request(first, '/api/auth/claim', 'POST', { email: 'owner@example.invalid', temporaryPassword: 'Setup123', password: 'Synthetic claimed native password' }, ''), request(second, '/api/auth/claim', 'POST', { email: 'owner@example.invalid', temporaryPassword: 'Setup123', password: 'Synthetic claimed native password' }, '')]); assert.equal(claimRace.filter(row => row.status === 200).length, 1); assert.ok(claimRace.every(row => [200, 401, 409].includes(row.status))); assert.equal((await fixture.repository.load(A)).snapshot.users[0].setupHash, undefined); checks.push('legacy setup without a new ledger is consumed once across HTTP workers');
    console.log(JSON.stringify({ nativeAccountLifecycle: checks, passed: checks.length, workers: 2, productionReady: false }));
  } finally { for (const child of workers) await close(child); await fixture.close(); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
