'use strict';
const assert = require('node:assert/strict'), crypto = require('node:crypto'), fs = require('node:fs'), os = require('node:os'), path = require('node:path'), { fork } = require('node:child_process'), { once } = require('node:events');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { A, B, initial, snapshot, memory } = require('./compat-account-fixture'), { services } = require('./compat-lifecycle-fixture'), { nativeFixture } = require('./compat-lifecycle-native-fixture');
async function main() {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'pdl-compat-lifecycle-')), evidence = process.env.PDL_COMPAT_BROWSER_EVIDENCE || path.join(directory, 'evidence'); fs.mkdirSync(evidence, { recursive: true });
  Object.assign(process.env, { NODE_ENV: 'test', PDL_COMPAT_ACCOUNT_SYNTHETIC: '1', PDL_REQUIRE_AUTH: '1', PDL_SUPABASE_ENABLED: '0', PDL_TRANSACTIONAL_DB: 'off', PDL_COMPAT_GLOBAL_FENCE_FILE: '' });
  for (const name of ['OPENAI_API_KEY', 'RESEND_API_KEY', 'STRIPE_SECRET_KEY', 'SENTRY_DSN', 'SUPABASE_SECRET_KEY', 'PDL_PLATFORM_KEY']) { if (process.env[name]) throw Error('Provider-free synthetic browser required'); process.env[name] = ''; }
  const legacy = snapshot(); legacy.company.id = B; legacy.users[0].companyId = B; legacy.users[0].email = 'global-owner@example.invalid'; const globalDirectory = path.join(directory, 'global'); fs.mkdirSync(globalDirectory); const globalFile = path.join(globalDirectory, 'db.json'); fs.writeFileSync(globalFile, JSON.stringify(legacy));
  const env = { ...process.env, PDL_DB_FILE: globalFile, PDL_PLATFORM_FILE: path.join(globalDirectory, 'platform.json') }, globalWorker = fork(path.join(__dirname, 'compat-account-browser-worker.cjs'), [], { env, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe', 'ipc'] });
  const ready = await once(globalWorker, 'message'); assert.equal(ready[0].event, 'ready'); const globalOrigin = 'http://localhost:' + ready[0].port;
  let browser, module, uninstall, native; const checks = [], errors = [], blocked = new Set(), external = new Set();
  try {
    const file = path.join(directory, 'db.json'); fs.writeFileSync(file, JSON.stringify(legacy)); process.env.PDL_DB_FILE = file; process.env.PDL_PLATFORM_FILE = path.join(directory, 'platform.json'); module = require('./server'); await new Promise(resolve => module.server.listen(0, '127.0.0.1', resolve)); const origin = 'http://127.0.0.1:' + module.server.address().port;
    if (process.env.TEST_COMPAT_DATABASE_URL) native = await nativeFixture(); const store = native?.repository || memory(snapshot());
    const fixture = services(store, origin); uninstall = module.installCompatibilityAccountTests({ synthetic: true, companyId: A, origin, globalOrigin, repository: store, ...fixture, dispatchAfterCommit: true });
    const fenceFile = path.join(directory, 'fence.json'); fs.writeFileSync(fenceFile, JSON.stringify({ version: 1, companyId: A, origin, globalOrigin })); const fenced = once(globalWorker, 'message'); globalWorker.send({ event: 'fence', file: fenceFile }); assert.equal((await fenced)[0].event, 'fenced');
    async function reset() { const db = snapshot(); db.projectTickets.push({ id: 900, projectId: 101, vendor: 'Synthetic retained source', lines: [], deletedAt: '2025-01-01T00:00:00.000Z', retainedUntil: '2025-04-01T00:00:00.000Z', url: '/uploads/project-tickets/never-delete-synthetic-g1.pdf', history: [] }); if (native) await native.reset(db); else { const loaded = await store.load(A); await store.commit(db, loaded.revision); } fixture.messages.length = 0; }
    browser = await chromium.launch({ ...(process.env.PDL_CHROMIUM_EXECUTABLE ? { executablePath: process.env.PDL_CHROMIUM_EXECUTABLE } : {}), headless: true, args: ['--disable-background-networking'] });
    async function context(viewport = { width: 1440, height: 1000 }) { const value = await browser.newContext({ viewport }); value.on('page', page => page.on('pageerror', error => errors.push(error.message))); await value.route('**/*', route => { const url = new URL(route.request().url()); if ([origin, globalOrigin].includes(url.origin)) return route.continue(); external.add(url.origin + url.pathname); return route.abort(); }); return value; }
    async function login(page, email = 'owner@example.invalid', password = initial) { await page.goto(origin + '/login.html?tenant=' + A); await page.fill('#email', email); await page.fill('#password', password); await page.click('#login button[type=submit]'); await page.waitForURL(url => url.pathname === '/app'); await page.waitForFunction(() => document.documentElement.classList.contains('workspace-ready')); }
    async function review(page) { await page.locator('#account-review-dialog').waitFor(); await page.fill('#account-review-reason', 'Synthetic owner reviewed actual existing account form'); await page.click('#account-review-preview'); await page.locator('#account-review-save').waitFor({ state: 'visible' }); assert.equal(await page.isChecked('#account-review-confirmed'), false); await page.check('#account-review-confirmed'); await page.click('#account-review-save'); }
    for (const [name, viewport] of [['desktop', { width: 1440, height: 1000 }], ['mobile', { width: 390, height: 844 }]]) {
      await reset(); const ctx = await context(viewport), page = await ctx.newPage(); page.on('response', response => { if (response.status() === 503) blocked.add(new URL(response.url()).pathname); });
      await login(page); await page.waitForFunction(() => Boolean(document.querySelector('#email-verification-banner'))); await page.waitForTimeout(250);
      for (let attempt = 0; attempt < 80 && !fixture.messages.some(row => row.purpose === 'email-verification'); attempt++) await page.waitForTimeout(50);
      const verification = fixture.messages.find(row => row.purpose === 'email-verification'); assert.ok(verification); await page.goto(verification.verifyUrl.replace(origin, globalOrigin)); await page.waitForURL(url => url.origin === origin && url.pathname === '/verify-email.html'); await page.locator('#verification-next:not([hidden])').waitFor(); await page.click('#verification-next'); await page.waitForFunction(() => document.documentElement.classList.contains('workspace-ready')); checks.push(name + ': existing resend and legacy-host verification link preserves sessions');
      assert.equal((await store.load(A)).snapshot.projectTickets[0].purgedAt, undefined); checks.push(name + ': account page loads with expired retained source without deleting it');
      if (name === 'mobile') await page.click('#menu-button'); if (!(await page.isVisible('.nav-item[data-page="team"]'))) await page.click('.nav-more > summary'); await page.click('.nav-item[data-page="team"]'); await page.click('[data-team-tab="accounts"]'); await page.click('#team-add-button'); await page.fill('#user-name', 'Browser PM ' + name); await page.fill('#user-email', 'browser-' + name + '@example.invalid'); await page.selectOption('#user-role', 'project_manager'); await page.click('#save-user'); await review(page); await page.locator('#setup-code-result input').waitFor();
      let loaded = await store.load(A); const target = loaded.snapshot.users.find(row => row.email === 'browser-' + name + '@example.invalid'); assert.ok(target); const secretInput = page.locator('#setup-code-result input'); const temporaryPassword = await secretInput.inputValue(); assert.match(temporaryPassword, /^[A-Za-z0-9_-]{8}$/); assert.equal(JSON.stringify(loaded.snapshot).includes(temporaryPassword), false); checks.push(name + ': existing add-account form uses preview/reason/unchecked confirmation and committed secret');
      await page.locator('#user-modal .close-button').click(); await page.screenshot({ path: path.join(evidence, 'g1-' + name + '-accounts.png'), fullPage: true });
      if (name === 'mobile') await page.click('#menu-button'); await page.click('#profile-button'); await page.fill('#profile-display-name', 'Browser Owner ' + name); await page.selectOption('#profile-language', 'es'); await page.click('#save-profile'); await page.locator('#profile-modal').waitFor({ state: 'hidden' }); if (name === 'mobile') await page.mouse.click(viewport.width - 10, 100); assert.equal((await store.load(A)).snapshot.users[0].preferences.displayName, 'Browser Owner ' + name); checks.push(name + ': existing owner profile preferences save and read back');
      await page.click('[data-user-edit="' + target.id + '"]'); await page.check('#user-schedule-crews'); await page.click('#save-user'); await review(page); await page.locator('#user-modal').waitFor({ state: 'hidden' }); assert.equal((await store.load(A)).snapshot.users.find(row => row.id === target.id).permissions.scheduleCrews, true); checks.push(name + ': existing account access edit reviewed with actual stored grants');
      await page.click('[data-user-reset="' + target.id + '"]'); await page.click('#confirm-password-reset'); await review(page); await page.locator('#password-reset-result input').waitFor(); const replacement = await page.locator('#password-reset-result input').inputValue(); assert.notEqual(replacement, temporaryPassword); await page.locator('#password-reset-modal .close-button').click(); checks.push(name + ': existing reset-password dialog commits replacement once');
      await page.click('[data-team-tab="employees"]'); await page.click('#team-add-button'); await page.fill('#member-name', 'Browser linked employee ' + name); await page.selectOption('#member-role', 'Laborer'); await page.selectOption('#member-crew', '__new__'); await page.fill('#member-new-crew', 'New browser synthetic crew ' + name); await page.fill('#member-email', 'linked-' + name + '@example.invalid'); await page.selectOption('#member-account-role', 'field'); await page.click('#save-team-member'); await review(page); await page.locator('#password-reset-modal[open]').waitFor(); const compound = (await store.load(A)).snapshot, linkedUser = compound.users.find(row => row.email === 'linked-' + name + '@example.invalid'); assert.ok(compound.team.some(row => row.id === linkedUser.memberId)); await page.locator('#password-reset-modal .close-button').click(); checks.push(name + ': existing employee-with-login form commits member and account together');
      const memberCtx = await context(viewport), memberPage = await memberCtx.newPage(); await memberPage.goto(origin + '/login.html?tenant=' + A); await memberPage.fill('#email', target.email); await memberPage.fill('#password', replacement); await memberPage.click('#login button[type=submit]'); await memberPage.locator('#setup-modal[open]').waitFor(); const permanent = 'Synthetic browser permanent ' + name; await memberPage.fill('#new-password', permanent); await memberPage.fill('#confirm-password', permanent); await memberPage.click('#claim button[type=submit]'); await memberPage.waitForURL(url => url.pathname === '/app'); await memberPage.waitForFunction(() => document.documentElement.classList.contains('workspace-ready')); assert.equal((await store.load(A)).snapshot.users.find(row => row.id === target.id).mustSetPassword, false); if (name === 'mobile') await memberPage.click('#menu-button'); await memberPage.click('#profile-button'); assert.equal(await memberPage.inputValue('#profile-display-name'), target.name); assert.equal(await memberPage.locator('#profile-modal[open]').count(), 1); await memberPage.locator('#profile-modal .close-button').click(); checks.push(name + ': actual first-login setup claims code, signs in and preserves fresh nonowner profile display'); await memberCtx.close(); await ctx.close();
    }
    // A buffered private result must not appear after the actual browser cookie
    // changes to another current actor, even if the old request committed.
    await reset(); {
      const loaded = await store.load(A); loaded.snapshot.users[0].emailVerifiedAt = new Date().toISOString(); loaded.snapshot.users.push({ ...loaded.snapshot.users[0], id: 2, role: 'admin', email: 'browser-admin@example.invalid', name: 'Synthetic Browser Admin' }); await store.commit(loaded.snapshot, loaded.revision);
      const ctx = await context(); await ctx.addInitScript(() => { const original = fetch; window.fetch = async (...args) => { const response = await original(...args); if (args[0] === '/api/account-actions/confirm') { const json = response.json.bind(response); response.json = async () => { const data = await json(); window.g1Buffered = true; await new Promise(resolve => { window.g1Release = resolve; }); return data; }; } return response; }; });
      const page = await ctx.newPage(); await login(page); await page.click('.nav-more > summary'); await page.click('.nav-item[data-page="team"]'); await page.click('[data-team-tab="accounts"]'); await page.click('#team-add-button'); await page.fill('#user-name', 'Buffered Synthetic Account'); await page.fill('#user-email', 'buffered@example.invalid'); await page.click('#save-user'); await review(page); await page.waitForFunction(() => window.g1Buffered === true);
      assert.equal((await ctx.request.post(origin + '/api/auth/login', { headers: { 'X-PDL-Company': A }, data: { email: 'browser-admin@example.invalid', password: initial } })).status(), 200); await page.evaluate(() => window.g1Release()); await page.locator('#account-review-dialog').waitFor({ state: 'detached' }); await page.waitForTimeout(100); assert.equal(await page.locator('#setup-code-result input').count(), 0); assert.equal(await page.locator('#password-reset-result input').count(), 0); assert.ok((await store.load(A)).snapshot.users.some(row => row.email === 'buffered@example.invalid')); await page.click('[data-team-tab="accounts"]'); assert.equal(await page.locator('#account-list .account-row').count(), 0); checks.push('buffered committed confirmation cannot reveal former-owner secret or refill cached accounts after real actor/cookie change'); await ctx.close();
    }
    // Acknowledged create delivers its private result before optional directory
    // readback; a transient read failure cannot become a false unsaved outcome.
    for (const scenario of ['503', 'network']) {
      await reset(); const loaded = await store.load(A); loaded.snapshot.users[0].emailVerifiedAt = new Date().toISOString(); await store.commit(loaded.snapshot, loaded.revision); const ctx = await context(), page = await ctx.newPage(); await login(page); await page.click('.nav-more > summary'); await page.click('.nav-item[data-page="team"]'); await page.click('[data-team-tab="accounts"]'); await page.click('#team-add-button'); await page.fill('#user-name', 'Known saved ' + scenario); await page.fill('#user-email', 'known-' + scenario + '@example.invalid');
      await ctx.route(origin + '/api/users', route => route.request().method() === 'GET' ? scenario === '503' ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Synthetic transient directory failure' }) }) : route.abort() : route.continue()); await page.click('#save-user'); await review(page); await page.locator('#setup-code-result input').waitFor(); await page.waitForFunction(() => document.querySelector('#toast')?.textContent.includes('Account was created.')); assert.match(await page.locator('#setup-code-result input').inputValue(), /^[A-Za-z0-9_-]{8}$/); assert.equal((await page.locator('#toast').textContent()).includes('Nothing was saved'), false); const final = (await store.load(A)).snapshot; assert.ok(final.users.some(row => row.email === 'known-' + scenario + '@example.invalid')); assert.equal(final.auditLog.filter(row => row.type === 'account_change_confirmed').length, 1); assert.equal(await page.evaluate(() => sessionStorage.getItem('pdl-original-account-operation-v1')), null); checks.push('confirmed native account201 with dependent directory ' + scenario + ' retains delivered password and truthful known-saved outcome'); await ctx.close();
    }
    // The legacy add-account consumer awaits a directory read after successful
    // confirmation. Its buffered private body receives the same identity fence.
    await reset(); {
      const loaded = await store.load(A); loaded.snapshot.users[0].emailVerifiedAt = new Date().toISOString(); loaded.snapshot.users.push({ ...loaded.snapshot.users[0], id: 2, role: 'admin', email: 'browser-admin@example.invalid', name: 'Synthetic Browser Admin' }); await store.commit(loaded.snapshot, loaded.revision);
      const ctx = await context(); await ctx.addInitScript(() => { const original = fetch; window.fetch = async (...args) => { const response = await original(...args); if (args[0] === '/api/users' && window.g1ArmDirectory) { const json = response.json.bind(response); response.json = async () => { const data = await json(); window.g1BufferedDirectory = true; await new Promise(resolve => { window.g1ReleaseDirectory = resolve; }); return data; }; } return response; }; });
      const page = await ctx.newPage(); await login(page); await page.click('.nav-more > summary'); await page.click('.nav-item[data-page="team"]'); await page.click('[data-team-tab="accounts"]'); await page.click('#team-add-button'); await page.fill('#user-name', 'Dependent Synthetic Account'); await page.fill('#user-email', 'dependent@example.invalid'); await page.evaluate(() => { window.g1ArmDirectory = true; }); await page.click('#save-user'); await review(page); await page.waitForFunction(() => window.g1BufferedDirectory === true);
      assert.equal((await ctx.request.post(origin + '/api/auth/login', { headers: { 'X-PDL-Company': A }, data: { email: 'browser-admin@example.invalid', password: initial } })).status(), 200); await page.evaluate(() => window.g1ReleaseDirectory()); await page.locator('#user-modal').waitFor({ state: 'hidden' }); assert.equal(await page.locator('#setup-code-result input').count(), 0); assert.equal(await page.locator('#account-list .account-row').count(), 0); await page.click('[data-team-tab="accounts"]'); assert.equal(await page.locator('#account-list .account-row').count(), 0); await page.click('#profile-button'); assert.equal(await page.locator('#profile-modal[open]').count(), 0); checks.push('buffered dependent directory read cannot render old private accounts/confirmation secret or reopen retired accounts/profile after actual cookie change'); await ctx.close();
    }
    // A definitive denial retires already displayed private recovery and its
    // cached authority while preserving original operation provenance.
    for (const [scenario, expected] of [['session', 401], ['account', 402], ['owner', 403]]) {
      await reset(); const loaded = await store.load(A); loaded.snapshot.users[0].emailVerifiedAt = new Date().toISOString(); loaded.snapshot.users[0].preferences = { displayName: 'Private cached display ' + scenario, profilePhoto: '' }; await store.commit(loaded.snapshot, loaded.revision);
      const ctx = await context(), page = await ctx.newPage(); await login(page); await page.evaluate(companyId => localStorage.setItem('pdl-profile-photo-' + companyId + '-1', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jv2kAAAAASUVORK5CYII='), A); await page.click('#profile-button'); assert.equal(await page.inputValue('#profile-display-name'), 'Private cached display ' + scenario); assert.match(await page.locator('#profile-preview').evaluate(node => node.style.backgroundImage), /data:image/); await page.locator('#profile-modal .close-button').click(); await page.click('.nav-more > summary'); await page.click('.nav-item[data-page="team"]'); await page.click('[data-team-tab="accounts"]'); await page.click('#team-add-button'); await page.fill('#user-name', 'Denied recovery ' + scenario); await page.fill('#user-email', 'denied-' + scenario + '@example.invalid');
      await ctx.route(origin + '/api/account-actions/confirm', async route => { await route.fetch(); await route.abort(); }); await page.click('#save-user'); await review(page); await page.locator('#account-original-result').waitFor(); await ctx.unroute(origin + '/api/account-actions/confirm'); await page.locator('#user-modal .close-button').click(); await page.click('#account-original-result'); await page.locator('#account-original-result-dialog').waitFor(); assert.match(await page.locator('#account-original-result-dialog pre').textContent(), /temporaryPassword/);
      const changed = await store.load(A); if (scenario === 'session') changed.snapshot.sessions = []; else if (scenario === 'account') { changed.snapshot.company.billingExempt = false; changed.snapshot.company.subscriptionStatus = 'Trial'; changed.snapshot.company.trialEndsAt = '2000-01-01T00:00:00.000Z'; } else changed.snapshot.users[0].role = 'admin'; await store.commit(changed.snapshot, changed.revision);
      const denied = page.waitForResponse(response => response.url() === origin + '/api/account-actions/recover' && response.status() === expected); await page.evaluate(() => document.getElementById('account-original-result').onclick()); await denied; await page.locator('#account-original-result-dialog').waitFor({ state: 'detached' }); assert.equal(await page.locator('#account-original-result').count(), 0); assert.equal(await page.locator('#account-list .account-row').count(), 0); assert.ok(await page.evaluate(() => sessionStorage.getItem('pdl-original-account-operation-v1'))); const retired = await page.evaluate(async () => { let calls = 0; try { await pdlAccountActions.request('/api/users', { method: 'POST', body: '{}' }, async () => { calls++; }); } catch {} return calls; }); assert.equal(retired, 0); await page.click('[data-team-tab="accounts"]'); assert.equal(await page.locator('#account-list .account-row').count(), 0); await page.click('#profile-button'); assert.equal(await page.locator('#profile-modal[open]').count(), 0); assert.equal(await page.inputValue('#profile-display-name'), ''); assert.equal(await page.locator('#profile-preview').evaluate(node => node.style.backgroundImage), ''); await page.click('#team-add-button'); assert.equal(await page.locator('#user-modal[open]').count(), 0); checks.push('actual ' + expected + ' ' + scenario + ' denial clears private recovery/accounts/preferences and prevents local private reopening with provenance retained'); await ctx.close();
    }
    // A successful known confirmation stays usable if storage cleanup fails.
    await reset(); {
      const loaded = await store.load(A); loaded.snapshot.users[0].emailVerifiedAt = new Date().toISOString(); await store.commit(loaded.snapshot, loaded.revision); const ctx = await context(); await ctx.addInitScript(() => { const remove = Storage.prototype.removeItem; Storage.prototype.removeItem = function (key) { if (key === 'pdl-original-account-operation-v1') throw Error('Synthetic cleanup failure'); return remove.call(this, key); }; }); const page = await ctx.newPage(); await login(page); await page.click('.nav-more > summary'); await page.click('.nav-item[data-page="team"]'); await page.click('[data-team-tab="accounts"]'); await page.click('#team-add-button'); await page.fill('#user-name', 'Cleanup Synthetic Account'); await page.fill('#user-email', 'cleanup@example.invalid'); await page.click('#save-user'); await review(page); await page.locator('#setup-code-result input').waitFor(); assert.ok(await page.evaluate(() => sessionStorage.getItem('pdl-original-account-operation-v1'))); assert.equal(await page.locator('#account-original-result').count(), 0); await page.locator('#user-modal .close-button').click(); await page.click('#team-add-button'); await page.fill('#user-name', 'Next cleanup account'); await page.fill('#user-email', 'next-cleanup@example.invalid'); await page.click('#save-user'); await page.locator('#account-review-dialog').waitFor(); await page.click('#account-review-cancel'); checks.push('known confirmation survives journal cleanup failure and allows next deliberate review without automatic replay'); await ctx.close();
    }
    // A response lost after COMMIT is checked by its original operation. After
    // setup consumes the code, the owner reviews current accounts and explicitly
    // closes browser recovery while retaining the server receipt and audit.
    await reset(); {
      const loaded = await store.load(A); loaded.snapshot.users[0].emailVerifiedAt = new Date().toISOString(); await store.commit(loaded.snapshot, loaded.revision);
      const ctx = await context(), page = await ctx.newPage(); await login(page); await page.click('.nav-more > summary'); await page.click('.nav-item[data-page="team"]'); await page.click('[data-team-tab="accounts"]'); await page.click('#team-add-button'); await page.fill('#user-name', 'Lost Synthetic Account'); await page.fill('#user-email', 'lost@example.invalid');
      await ctx.route(origin + '/api/account-actions/confirm', async route => { await route.fetch(); await route.abort(); }); await page.click('#save-user'); await review(page); await page.locator('#account-original-result').waitFor(); await ctx.unroute(origin + '/api/account-actions/confirm');
      const pending = await page.evaluate(() => JSON.parse(sessionStorage.getItem('pdl-original-account-operation-v1'))); const stored = (await store.load(A)).snapshot, target = stored.users.find(row => row.email === 'lost@example.invalid'), cookies = await ctx.cookies(origin), sessionCookie = cookies.find(row => row.name === 'pdl_session').value, sessionHash = crypto.createHash('sha256').update(sessionCookie).digest('hex'), session = stored.sessions.find(row => row.tokenHash === sessionHash), owner = stored.users.find(row => row.id === session.userId);
      const original = fixture.secretRecovery.recover(stored, { companyId: A, user: owner, session }, pending.operationId); assert.equal((await ctx.request.post(origin + '/api/auth/claim', { headers: { 'X-PDL-Company': A }, data: { email: target.email, temporaryPassword: original.temporaryPassword, password: 'Synthetic consumed lost-result password' } })).status(), 200);
      await page.locator('#user-modal .close-button').click(); await page.click('#account-original-result'); await page.locator('#account-reconcile-result').waitFor(); await page.click('#account-reconcile-result'); await page.locator('#account-original-result-dialog').waitFor(); assert.equal(await page.isChecked('#account-original-result-dialog input[type=checkbox]'), false); await page.fill('#account-original-result-dialog textarea', 'Reviewed committed account and consumed setup password'); await page.check('#account-original-result-dialog input[type=checkbox]'); await page.evaluate(() => { const remove = Storage.prototype.removeItem; Storage.prototype.removeItem = function (key) { if (key === 'pdl-original-account-operation-v1') throw Error('Synthetic reconciliation cleanup failure'); return remove.call(this, key); }; }); await page.getByRole('button', { name: 'Retain original history and close browser recovery' }).click(); await page.locator('#account-original-result-dialog').waitFor({ state: 'detached' });
      assert.ok(await page.evaluate(() => sessionStorage.getItem('pdl-original-account-operation-v1'))); assert.equal(await page.locator('#account-original-result').count(), 0); await page.click('#team-add-button'); await page.fill('#user-name', 'After reconciled cleanup'); await page.fill('#user-email', 'reconciled-cleanup@example.invalid'); await page.click('#save-user'); await page.locator('#account-review-dialog').waitFor(); await page.click('#account-review-cancel'); const final = (await store.load(A)).snapshot; assert.ok(final.accountActionReceipts.some(row => row.operationId === pending.operationId)); assert.ok(final.auditLog.some(row => row.type === 'account_original_result_reconciled' && row.observedOutcome === 'committed')); checks.push('lost-response then consumed-code recovery has explicit current-account reconciliation, retained original history and nonblocking cleanup failure'); await ctx.close();
    }
    // With the synthetic lifecycle absent, existing legacy account creation and
    // focus/pagehide preserve its displayed password and use no review/journal.
    {
      const ctx = await context(), page = await ctx.newPage(); await page.goto(globalOrigin + '/login.html?tenant=' + B); await page.fill('#email', 'global-owner@example.invalid'); await page.fill('#password', initial); await page.click('#login button[type=submit]'); await page.waitForURL(url => url.pathname === '/app'); await page.waitForFunction(() => document.documentElement.classList.contains('workspace-ready')); assert.equal(await page.evaluate(() => pdlAccountActions.canUseAccountData()), true); await page.click('.nav-more > summary'); await page.click('.nav-item[data-page="team"]'); await page.click('[data-team-tab="accounts"]'); await page.click('#team-add-button'); await page.fill('#user-name', 'Unchanged legacy synthetic account'); await page.fill('#user-email', 'legacy-focus@example.invalid'); await page.click('#save-user'); await page.locator('#setup-code-result input').waitFor(); const password = await page.locator('#setup-code-result input').inputValue(); assert.match(password, /^[A-Za-z0-9_-]{8}$/); assert.equal(await page.locator('#account-review-dialog').count(), 0); await page.evaluate(() => { dispatchEvent(new Event('focus')); dispatchEvent(new Event('pagehide')); }); assert.equal(await page.locator('#setup-code-result input').inputValue(), password); assert.equal(await page.evaluate(() => sessionStorage.getItem('pdl-original-account-operation-v1')), null); checks.push('default-disabled actual legacy add-account result survives focus/pagehide with no review or recovery journal'); await ctx.close();
    }
    // Per-company email uniqueness does not imply global uniqueness. A shared
    // email needs an explicit tenant before any login/reset credential request.
    await reset(); {
      const loaded = await store.load(A); loaded.snapshot.users[0].email = 'global-owner@example.invalid'; loaded.snapshot.users[0].emailVerifiedAt = new Date().toISOString(); await store.commit(loaded.snapshot, loaded.revision); const ctx = await context(), page = await ctx.newPage(); let credentialCalls = 0; page.on('request', request => { if (['/api/auth/login', '/api/auth/forgot'].includes(new URL(request.url()).pathname)) credentialCalls++; });
      await page.goto(globalOrigin + '/login.html'); await page.fill('#email', 'global-owner@example.invalid'); await page.fill('#password', initial); await page.click('#login button[type=submit]'); await page.waitForFunction(() => document.querySelector('#message')?.textContent.includes('company sign-in link')); assert.equal(credentialCalls, 0); assert.equal(new URL(page.url()).origin, globalOrigin); await page.evaluate(companyId => localStorage.setItem('pdl-company-id', companyId), B); await page.goto(globalOrigin + '/forgot-password.html'); await page.fill('#email', 'global-owner@example.invalid'); await page.click('#forgot-form button[type=submit]'); await page.waitForFunction(() => document.querySelector('#message')?.textContent.includes('company sign-in link')); assert.equal(credentialCalls, 0); const direct = await ctx.request.post(globalOrigin + '/api/auth/login', { data: { email: 'global-owner@example.invalid', password: initial } }); assert.equal(direct.status(), 409); checks.push('shared selected/legacy email without explicit tenant fails closed before login/reset submission and backend rejects no-hint login'); await ctx.close();
      for (const failure of ['503', 'network']) {
        const unavailableCtx = await context(); await unavailableCtx.addInitScript(companyId => { if (location.protocol === 'http:') localStorage.setItem('pdl-company-id', companyId); }, B); await unavailableCtx.route(globalOrigin + '/api/config', route => failure === '503' ? route.fulfill({ status: 503, contentType: 'application/json', body: '{}' }) : route.abort()); const unavailablePage = await unavailableCtx.newPage(); let sent = 0; unavailablePage.on('request', request => { if (new URL(request.url()).pathname === '/api/auth/forgot') sent++; }); await unavailablePage.goto(globalOrigin + '/forgot-password.html'); await unavailablePage.fill('#email', 'global-owner@example.invalid'); await unavailablePage.click('#forgot-form button[type=submit]'); await unavailablePage.waitForFunction(() => document.querySelector('#message')?.textContent.includes('company sign-in link')); assert.equal(sent, 0); checks.push('remembered shared-email reset with config ' + failure + ' safely rediscoveries current ambiguity and submits no credential mutation'); await unavailableCtx.close();
      }
      const selectedCtx = await context(), selectedPage = await selectedCtx.newPage(); await selectedPage.goto(globalOrigin + '/login.html?tenant=' + A); await selectedPage.waitForURL(url => url.origin === origin); await selectedPage.fill('#email', 'global-owner@example.invalid'); await selectedPage.fill('#password', initial); await selectedPage.click('#login button[type=submit]'); await selectedPage.waitForURL(url => url.origin === origin && url.pathname === '/app'); await selectedPage.waitForFunction(() => document.documentElement.classList.contains('workspace-ready')); checks.push('shared-email explicit selected company link redirects and signs into current selected authority'); await selectedCtx.close();
      const wrongCtx = await context(), wrongPage = await wrongCtx.newPage(); let selectedCredentials = 0; wrongPage.on('request', request => { if (new URL(request.url()).origin === origin && ['/api/auth/login', '/api/auth/forgot'].includes(new URL(request.url()).pathname)) selectedCredentials++; }); await wrongPage.goto(origin + '/login.html?tenant=' + B); await wrongPage.waitForURL(url => url.origin === globalOrigin && url.pathname === '/login.html'); assert.equal(new URL(wrongPage.url()).searchParams.get('tenant'), B); await wrongPage.goto(origin + '/forgot-password.html?tenant=' + B); await wrongPage.waitForURL(url => url.origin === globalOrigin && url.pathname === '/forgot-password.html'); assert.equal(new URL(wrongPage.url()).searchParams.get('tenant'), B); assert.equal(selectedCredentials, 0); checks.push('foreign login/reset link on selected origin preserves requested company and routes to legacy origin before any selected credential send'); await wrongCtx.close();
      const foreignCtx = await context(), foreignPage = await foreignCtx.newPage(); await foreignPage.goto(globalOrigin + '/login.html?tenant=' + B); await foreignPage.fill('#email', 'global-owner@example.invalid'); await foreignPage.fill('#password', initial); await foreignPage.click('#login button[type=submit]'); await foreignPage.waitForURL(url => url.origin === globalOrigin && url.pathname === '/app'); await foreignPage.waitForFunction(() => document.documentElement.classList.contains('workspace-ready')); checks.push('shared-email explicit foreign company link keeps the selected foreign legacy authority'); await foreignCtx.close();
    }
    // Original generic global login discovers the selected current account and
    // redirects before transmitting the credential to any global tenant route.
    await reset(); const ctx = await context(), page = await ctx.newPage(); let globalCredentialCalls = 0;
    page.on('request', request => { if (request.url() === globalOrigin + '/api/auth/login') globalCredentialCalls++; }); await page.goto(globalOrigin + '/login.html'); await page.fill('#email', 'owner@example.invalid'); await page.fill('#password', initial); await page.click('#login button[type=submit]'); await page.waitForURL(url => url.origin === origin && url.pathname === '/login.html'); assert.equal(globalCredentialCalls, 0); assert.equal(new URL(page.url()).searchParams.get('tenant'), A); checks.push('no-hint existing global login discovers current selected tenant and redirects before credential send');
    assert.equal((await ctx.request.get(globalOrigin + '/api/founder-offer')).status(), 200); const signup = await ctx.request.post(globalOrigin + '/api/signup', { data: { companyName: 'Synthetic unchanged global enrollment', ownerName: 'Synthetic global owner', email: 'new-global@example.invalid', password: initial, employeeCount: 2, projectCount: 1, plan: 'starter', onboardingPreference: 'self', legalAccepted: true, legalVersion: '2026-09-17' } }); assert.equal(signup.status(), 201); assert.equal((await ctx.request.get(globalOrigin + '/api/auth/me')).status(), 200); checks.push('ordinary founder/signup and newly enrolled other tenant remain legacy'); await ctx.close();
    assert.deepEqual(errors, []); const report = { checks, backend: native ? 'native-postgresql' : 'synthetic-memory', blockedOtherGatePaths: [...blocked].sort(), externalAttemptsAborted: [...external], allowedExternalRequests: 0, pageErrors: errors, productionReady: false }; fs.writeFileSync(path.join(evidence, 'g1-account-lifecycle-browser-results.json'), JSON.stringify(report, null, 2)); console.log(JSON.stringify({ passed: checks.length, backend: report.backend, pageErrors: 0, allowedExternalRequests: 0 }));
  } finally { uninstall?.(); await browser?.close(); if (module) await new Promise(resolve => module.server.close(resolve)); await native?.close(); if (globalWorker.connected) globalWorker.send({ event: 'close' }); await new Promise(resolve => { if (globalWorker.exitCode !== null) return resolve(); globalWorker.once('exit', resolve); setTimeout(() => { if (globalWorker.exitCode === null) globalWorker.kill(); }, 3000); }); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
