'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {A,B,initial,snapshot,memory,credential}=require('./compat-account-fixture'),{workspaceSnapshot}=require('./compat-workspace-fixture'),{services}=require('./compat-lifecycle-fixture');
const registry=require('./capability-registry'),profiles=require('./role-profiles');
async function main(){
  const directory=fs.mkdtempSync(path.join(os.tmpdir(),'pdl-compat-role-policy-')),file=path.join(directory,'legacy.json'),legacy=snapshot();legacy.company.id=B;legacy.users[0].companyId=B;fs.writeFileSync(file,JSON.stringify(legacy));const original=fs.readFileSync(file),key=crypto.randomBytes(32);
  Object.assign(process.env,{NODE_ENV:'test',PDL_COMPAT_ACCOUNT_SYNTHETIC:'1',PDL_REQUIRE_AUTH:'1',PDL_DB_FILE:file,PDL_PLATFORM_FILE:path.join(directory,'platform.json'),PDL_SUPABASE_ENABLED:'0',PDL_TRANSACTIONAL_DB:'off'});
  for(const name of ['OPENAI_API_KEY','RESEND_API_KEY','STRIPE_SECRET_KEY','SENTRY_DSN','SUPABASE_SECRET_KEY','PDL_PLATFORM_KEY'])process.env[name]='';
  const mod=require('./server');await new Promise(resolve=>mod.server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+mod.server.address().port;let uninstall;const native=process.env.TEST_COMPAT_DATABASE_URL?await require('./compat-lifecycle-native-fixture').nativeFixture():null;
  const seed=()=>{const db=workspaceSnapshot();db.team[0].crew='Office';for(const [id,role] of [[3,'project_manager'],[4,'admin']])db.users.push({id,companyId:A,name:'Synthetic '+role,email:role+'@example.invalid',role,status:'Active',emailVerifiedAt:'2026-10-01T00:00:00Z',...credential(initial),projectIds:role==='project_manager'?[101]:[],assignedCrews:role==='project_manager'?['Synthetic Crew']:[],permissions:{scheduleCrews:true,viewTime:true,manageTime:true,viewDailies:true,approveDailies:true}});return db;};
  async function scenario(db=seed()){
    uninstall?.();let store;if(native){await native.reset(db);let cached=await native.repository.load(A);store={loseCommitAck:false,async load(id){cached=await native.repository.load(id);return structuredClone(cached);},async commit(...args){const result=await native.repository.commit(...args);cached=await native.repository.load(A);if(store.loseCommitAck){store.loseCommitAck=false;throw Object.assign(Error('Synthetic permission COMMIT acknowledgement lost'),{statusCode:503,code:'PDL_COMMIT_OUTCOME_UNKNOWN'});}return result;},current:()=>structuredClone(cached.snapshot),revision:()=>cached.revision};}else store=memory(db);const fixture=services(store,origin,{key});uninstall=mod.installCompatibilityAccountTests({synthetic:true,companyId:A,origin,globalOrigin:'http://localhost:4999',repository:store,...fixture,workspace:true,workspaceKey:key});
    const tokens=new Map(),request=async(route,method='GET',data,email='owner@example.invalid',company=A)=>{const res=await fetch(origin+route,{method,signal:AbortSignal.timeout(10000),headers:{'X-PDL-Company':company,...(tokens.has(email)?{Authorization:'Bearer '+tokens.get(email)}:{}),...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});return {status:res.status,data:await res.json(),headers:Object.fromEntries(res.headers)};};
    const login=async(email='owner@example.invalid')=>{const res=await request('/api/auth/login','POST',{email,password:initial},email);assert.equal(res.status,200,JSON.stringify(res));tokens.set(email,res.data.token);};await login();
    const state=()=>request('/api/company/role-policy'),preview=async(policies,reason='Synthetic role restriction')=>{const current=await state();assert.equal(current.status,200);return request('/api/company/role-policy/preview','POST',{requestId:crypto.randomUUID(),expectedRevision:current.data.tenantRevision,reason,policies});},confirm=p=>request('/api/company/role-policy/confirm','POST',{previewId:p.data.previewId,version:p.data.version,requestId:crypto.randomUUID(),confirmed:true});
    return {store,request,login,state,preview,confirm};
  }
  const policyRoot='/api/company/role-policy';
  try{
    let s=await scenario(),state=await s.state();assert.equal(state.status,200,JSON.stringify(state));assert.equal(state.data.policyRevision,0);assert.ok(Object.values(state.data.states).every(row=>row.state==='default'));const baseline=registry.effective(s.store.current(),s.store.current().users[2]),rows=structuredClone(state.data.defaults);rows.scheduling.project_manager.create=false;
    const before=s.store.current(),p=await s.preview(rows);assert.equal(p.status,200,JSON.stringify(p));assert.equal(p.data.impact.changedAccounts,1);assert.deepEqual(p.data.impact.accounts.find(row=>row.accountId===3).changes,[{capability:'scheduling.create',before:true,after:false},{capability:'scheduleWorkflows.repeatWeek',before:true,after:false}]);assert.deepEqual(registry.effective(s.store.current(),s.store.current().users[2]),baseline,'preview grants/restrictions do not apply');assert.deepEqual(s.store.current().company,before.company);assert.ok(s.store.current().rolePolicyPreviews[0].custodyProof);
    const envelope={previewId:p.data.previewId,version:p.data.version,requestId:crypto.randomUUID(),confirmed:true};assert.equal((await s.request(policyRoot+'/confirm','POST',{...envelope,confirmed:false})).status,400);const saved=await s.request(policyRoot+'/confirm','POST',envelope);assert.equal(saved.status,200,JSON.stringify(saved));assert.equal(saved.data.committed,true);assert.match(saved.headers['x-pdl-workspace-policy-from'],/^[a-f0-9]{64}$/);assert.equal(registry.effective(s.store.current(),s.store.current().users[2]).scheduling.create,false);assert.equal(s.store.current().users[2].permissions.scheduleCrews,true);assert.equal(registry.effective(s.store.current(),s.store.current().users[0]).scheduling.create,true);const revision=s.store.revision();assert.equal((await s.request(policyRoot+'/confirm','POST',envelope)).status,200);assert.equal(s.store.revision(),revision);assert.equal((await s.request(policyRoot+'/confirm','POST',{...envelope,requestId:crypto.randomUUID()})).status,409);
    const audit=await s.request(policyRoot+'/audit');assert.equal(audit.status,200);assert.deepEqual(audit.data.entries.map(row=>row.kind),['previewed','confirmed']);for(const text of ['custodyProof','sessionHash','passwordHash','rolePolicyPreviews','rolePolicyReceipts'])assert.ok(!JSON.stringify(audit).includes(text));
    for(const email of ['admin@example.invalid','project_manager@example.invalid','field@example.invalid']){await s.login(email);for(const route of [policyRoot,policyRoot+'/audit',policyRoot+'/profiles','/api/company/role-capabilities'])assert.equal((await s.request(route,'GET',undefined,email)).status,403);assert.equal((await s.request(policyRoot+'/confirm','POST',envelope,email)).status,403);}
    assert.equal((await s.request(policyRoot,'GET',undefined,'owner@example.invalid',B)).status,404);
    s=await scenario();await s.login('project_manager@example.invalid');state=await s.state();let bad=structuredClone(state.data.defaults);bad.scheduling.owner={view:false};assert.equal((await s.preview(bad)).status,400);bad=structuredClone(state.data.defaults);bad.notes.field.assistant=true;assert.equal((await s.preview(bad)).status,400);bad=structuredClone(state.data.defaults);bad.daily.field.approveReports=true;assert.equal((await s.preview(bad)).status,400);
    rows.scheduling.project_manager.edit=false;let pending=await s.preview(rows);assert.equal(pending.status,200);const loaded=await s.store.load(A);loaded.snapshot.users[0].role='admin';await s.store.commit(loaded.snapshot,loaded.revision);assert.equal((await s.confirm(pending)).status,403);assert.equal(s.store.current().company.schedulingRolePolicy,undefined);
    s=await scenario();state=await s.state();pending=await s.preview(rows);assert.equal(pending.status,200);let changed=await s.store.load(A);changed.snapshot.company.name='Synthetic changed after preview';await s.store.commit(changed.snapshot,changed.revision);assert.equal((await s.confirm(pending)).status,409);assert.equal(s.store.current().company.schedulingRolePolicy,undefined);
    // Original Owner session binding survives restart; a newly authenticated
    // session, including the same Owner account, cannot adopt its proof.
    s=await scenario();pending=await s.preview(rows);assert.equal(pending.status,200);await s.login();assert.equal((await s.confirm(pending)).status,409);assert.equal(s.store.current().company.schedulingRolePolicy,undefined);
    s=await scenario();pending=await s.preview(rows);assert.equal(pending.status,200);changed=await s.store.load(A);changed.snapshot.sessions=[];await s.store.commit(changed.snapshot,changed.revision);assert.equal((await s.confirm(pending)).status,401);assert.equal(s.store.current().company.schedulingRolePolicy,undefined);
    s=await scenario();pending=await s.preview(rows);assert.equal(pending.status,200);const originalConfirm={previewId:pending.data.previewId,version:pending.data.version,requestId:crypto.randomUUID(),confirmed:true};s.store.loseCommitAck=true;assert.equal((await s.request(policyRoot+'/confirm','POST',originalConfirm)).status,503);const committedRevision=s.store.revision();uninstall();uninstall=mod.installCompatibilityAccountTests({synthetic:true,companyId:A,origin,globalOrigin:'http://localhost:4999',repository:s.store,...services(s.store,origin,{key}),workspace:true,workspaceKey:key});const replay=await s.request(policyRoot+'/confirm','POST',originalConfirm);assert.equal(replay.status,200,JSON.stringify(replay));assert.equal(s.store.revision(),committedRevision);const nextRows=structuredClone(rows);nextRows.scheduling.project_manager.edit=true;pending=await s.preview(nextRows);assert.equal(pending.status,200);assert.equal((await s.confirm(pending)).status,200);const revised=s.store.revision();assert.equal((await s.request(policyRoot+'/confirm','POST',originalConfirm)).status,409);assert.equal(s.store.revision(),revised,'Old receipt cannot overwrite a later policy');
    const twoOwners=seed();twoOwners.users.push({id:5,companyId:A,name:'Synthetic second Owner',email:'second-owner@example.invalid',role:'owner',status:'Active',emailVerifiedAt:new Date().toISOString(),...credential(initial),projectIds:[],assignedCrews:[],permissions:{}});s=await scenario(twoOwners);await s.login('second-owner@example.invalid');state=await s.state();pending=await s.preview(rows);assert.equal(pending.status,200);const secondState=await s.request(policyRoot,'GET',undefined,'second-owner@example.invalid'),secondPreview=await s.request(policyRoot+'/preview','POST',{requestId:crypto.randomUUID(),expectedRevision:secondState.data.tenantRevision,reason:'Synthetic competing Owner',policies:nextRows},'second-owner@example.invalid');assert.equal(secondPreview.status,200);assert.equal((await s.confirm(pending)).status,409);assert.equal((await s.request(policyRoot+'/confirm','POST',{previewId:secondPreview.data.previewId,version:secondPreview.data.version,requestId:crypto.randomUUID(),confirmed:true},'second-owner@example.invalid')).status,200);assert.deepEqual(s.store.current().company.schedulingRolePolicy.roles,nextRows.scheduling);
    s=await scenario();const office=await s.request(policyRoot+'/profiles');assert.equal(office.status,200);pending=await s.request(policyRoot+'/profiles/preview','POST',{requestId:crypto.randomUUID(),expectedRevision:office.data.tenantRevision,reason:'Synthetic Office profile',profileChange:{operation:'createOffice'}});assert.equal(pending.status,200,JSON.stringify(pending));assert.equal(pending.data.impact.changedAccounts,0);assert.equal(profiles.read(s.store.current()),null);assert.equal((await s.confirm(pending)).status,200);assert.equal(profiles.read(s.store.current()).profiles[0].id,profiles.OFFICE_ID);assert.equal(profiles.read(s.store.current()).assignments.length,0);
    const current=await s.request(policyRoot+'/profiles');pending=await s.request(policyRoot+'/profiles/preview','POST',{requestId:crypto.randomUUID(),expectedRevision:current.data.tenantRevision,reason:'Synthetic Office assignment',profileChange:{operation:'assign',accountId:4,profileId:profiles.OFFICE_ID}});assert.equal(pending.status,200,JSON.stringify(pending));assert.equal(pending.data.impact.changedAccounts,1);assert.equal((await s.confirm(pending)).status,200);assert.equal(registry.effective(s.store.current(),s.store.current().users[3]).scheduling.create,false);assert.equal(registry.effective(s.store.current(),s.store.current().users[3]).scheduling.view,true);assert.equal(registry.immutable(s.store.current(),s.store.current().users[3]).financialPolicy,'existing-pricing-policy');
    for(const id of [1,2,3]){const current=await s.request(policyRoot+'/profiles');assert.equal((await s.request(policyRoot+'/profiles/preview','POST',{requestId:crypto.randomUUID(),expectedRevision:current.data.tenantRevision,reason:'Invalid escalation',profileChange:{operation:'assign',accountId:id,profileId:profiles.OFFICE_ID}})).status,400);}
    for(const mutate of [db=>{db.rolePolicyPreviews=null;},db=>{db.rolePolicyPreviews[0].reason='forged';},db=>{db.rolePolicyReceipts[0].policyRevision=99;},db=>{db.rolePolicyAudit[0].custodyProof='0'.repeat(64);},db=>{db.rolePolicyPreviews[0].custodyProof=db.rolePolicyReceipts[0].custodyProof;},db=>{db.rolePolicyAudit[0].requestId=db.rolePolicyReceipts[0].id;}]){s=await scenario();pending=await s.preview(rows);assert.equal(pending.status,200);assert.equal((await s.confirm(pending)).status,200);const loaded=await s.store.load(A);mutate(loaded.snapshot);await s.store.commit(loaded.snapshot,loaded.revision);assert.equal((await s.request('/api/state')).status,409);}
    assert.deepEqual(fs.readFileSync(file),original);assert.equal(fs.existsSync(path.join(directory,'platform.json')),false);console.log('Synthetic Company Roles: unchanged defaults, real typed restrictions, owner-only preview/confirm/audit, exact replay, scope/role revocation, Office profiles and poisoned custody passed.');
  }finally{uninstall?.();await native?.close();mod.server.closeAllConnections();await new Promise(resolve=>mod.server.close(resolve));}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
