'use strict';
// Ordinary Company Settings controls, actual credential login, synthetic data.
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {spawnSync,execFileSync}=require('node:child_process');
const argument=name=>process.argv.find(value=>value.startsWith('--'+name+'='))?.slice(name.length+3);
const group=argument('group')||'all',viewportName=argument('viewport')||'desktop',groups=['roles','profiles','recovery','stale','session','boundaries','workflows'];
const viewports={desktop:{width:1440,height:1000},mobile:{width:390,height:844}};
const evidence=process.env.PDL_COMPAT_BROWSER_EVIDENCE||path.join(os.tmpdir(),'pdl-company-roles-'+Date.now());fs.mkdirSync(evidence,{recursive:true});
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
async function main(){
  if(group==='all'){const results=[];for(const next of groups)for(const viewport of Object.keys(viewports)){const result=spawnSync(process.execPath,[__filename,'--group='+next,'--viewport='+viewport],{cwd:__dirname,stdio:'inherit',env:{...process.env,PDL_COMPAT_BROWSER_EVIDENCE:evidence}});assert.equal(result.status,0,next+'/'+viewport);results.push(JSON.parse(fs.readFileSync(path.join(evidence,'company-roles-'+next+'-'+viewport+'.json'))));}fs.writeFileSync(path.join(evidence,'company-roles-browser-results.json'),JSON.stringify({sourceHead:results[0].sourceHead,backend:results[0].backend,journeys:results,passed:results.reduce((n,row)=>n+row.checks.length,0),productionReady:false},null,2));return;}
  assert.ok(groups.includes(group));assert.ok(viewports[viewportName]);
  const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),{A,B,initial,snapshot,memory,credential}=require('./compat-account-fixture'),{workspaceSnapshot}=require('./compat-workspace-fixture'),{services}=require('./compat-lifecycle-fixture'),registry=require('./capability-registry');
  for(const name of ['OPENAI_API_KEY','RESEND_API_KEY','STRIPE_SECRET_KEY','SENTRY_DSN','SUPABASE_SECRET_KEY','PDL_PLATFORM_KEY']){assert.ok(!process.env[name],name);process.env[name]='';}
  const directory=fs.mkdtempSync(path.join(os.tmpdir(),'pdl-company-roles-fixture-')),file=path.join(directory,'legacy.json'),legacy=snapshot();legacy.company.id=B;legacy.users[0].companyId=B;fs.writeFileSync(file,JSON.stringify(legacy));const original=fs.readFileSync(file);
  Object.assign(process.env,{NODE_ENV:'test',PDL_COMPAT_ACCOUNT_SYNTHETIC:'1',PDL_REQUIRE_AUTH:'1',PDL_DB_FILE:file,PDL_PLATFORM_FILE:path.join(directory,'platform.json'),PDL_SUPABASE_ENABLED:'0',PDL_TRANSACTIONAL_DB:'off'});
  const mod=require('./server');await new Promise(resolve=>mod.server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+mod.server.address().port;
  let native,store,browser,context,page,uninstall;const checks=[],requests=[],pageErrors=[],external=new Set();const prefix='company-roles-'+group+'-'+viewportName;
  try{
    const db=workspaceSnapshot();db.team[0].crew='Office';for(const [id,role]of [[3,'project_manager'],[4,'admin']])db.users.push({id,companyId:A,name:'Synthetic '+role,email:role+'@example.invalid',role,status:'Active',emailVerifiedAt:new Date().toISOString(),...credential(initial),projectIds:role==='project_manager'?[101]:[],assignedCrews:role==='project_manager'?['Synthetic Crew']:[],permissions:{scheduleCrews:true,viewTime:true,manageTime:true,viewDailies:true,approveDailies:true}});
    if(group==='workflows'){db.company.timezone='UTC';db.company.weekStart='sunday';const now=new Date(),today=now.toISOString().slice(0,10),sunday=new Date(today+'T12:00:00Z');sunday.setUTCDate(sunday.getUTCDate()-sunday.getUTCDay());const source=new Date(sunday);source.setUTCDate(source.getUTCDate()-7+(now.getUTCDay()===4?5:4));db.assignments[0].date=source.toISOString().slice(0,10);db.assignments.push({...structuredClone(db.assignments[0]),id:2,date:today});db.workdays=[{id:1,projectId:101,memberIds:[12],status:'complete',startedAt:today+'T07:13:00.000Z',endedAt:today+'T15:43:00.000Z',reportId:null}];const pm=db.users.find(row=>row.id===3);pm.permissions={scheduleCrews:true,viewTime:false,manageTime:false,viewDailies:false,approveDailies:false};}
    if(process.env.TEST_COMPAT_DATABASE_URL){native=await require('./compat-lifecycle-native-fixture').nativeFixture();await native.reset(db);}store=native?.repository||memory(db);const key=crypto.randomBytes(32);
    const install=()=>{uninstall?.();uninstall=mod.installCompatibilityAccountTests({synthetic:true,companyId:A,origin,globalOrigin:'http://localhost:4999',repository:store,...services(store,origin,{key}),workspace:true,workspaceKey:key});};install();
    browser=await chromium.launch({headless:true,args:['--disable-background-networking']});context=await browser.newContext({viewport:viewports[viewportName],timezoneId:'UTC'});
    await context.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin===origin)return route.continue();external.add(url.origin+url.pathname);return route.abort();});
    page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',error=>pageErrors.push(error.message));page.on('response',response=>{const url=new URL(response.url());if(url.origin===origin&&url.pathname.startsWith('/api/'))requests.push({path:url.pathname,method:response.request().method(),status:response.status()});});
    const read=async()=>(await store.load(A)).snapshot,alter=async change=>{const state=await store.load(A);change(state.snapshot);await store.commit(state.snapshot,state.revision);};
    async function login(email='owner@example.invalid'){await page.goto(origin+'/login.html?tenant='+A);await page.fill('#email',email);await page.fill('#password',initial);await page.click('#login button[type=submit]');await page.waitForURL(url=>url.pathname==='/app');await page.waitForFunction(()=>document.documentElement.classList.contains('workspace-ready'));}
    async function openRoles(){if(viewportName==='mobile'&&await page.locator('#menu-button').getAttribute('aria-expanded')!=='true')await page.click('#menu-button');if(!await page.locator('.nav-item[data-page="settings"]').isVisible())await page.locator('#nav-more > summary').click();await page.locator('.nav-item[data-page="settings"]').click();await page.click('#settings-tab-roles');await page.locator('#company-role-editor h2').filter({hasText:'What each role can do'}).waitFor();}
    async function screen(label){await page.screenshot({path:path.join(evidence,prefix+'-'+label+'.png'),fullPage:true});}
    async function preview(reason){await page.fill('#role-change-reason',reason);const response=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/preview')&&r.request().method()==='POST');await page.click('[data-role-command="preview"]');assert.equal((await response).status(),200);await page.locator('#role-explicit-confirm').waitFor();assert.equal(await page.isChecked('#role-explicit-confirm'),false);assert.equal(await page.locator('[data-role-command="confirm"]').isDisabled(),true);}
    async function save(){await page.check('#role-explicit-confirm');const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/company/role-policy/confirm'&&r.request().method()==='POST');await page.click('[data-role-command="confirm"]');assert.equal((await response).status(),200);await page.locator('#role-editor-message').filter({hasText:'Saved policy revision'}).waitFor();}
    await login(group==='workflows'?'project_manager@example.invalid':'owner@example.invalid');if(group!=='workflows')await openRoles();assert.equal((await read()).company.rolePolicyRevision,undefined);
    if(group==='workflows'){
      if(viewportName==='mobile')await page.click('#menu-button');await page.click('.nav-item[data-page="schedule"]');await page.locator(viewportName==='mobile'?'.schedule-mobile-agenda':'.schedule-cell[data-schedule-member="12"]').first().waitFor();
      const today=new Date().toISOString().slice(0,10),dbBefore=await read();assert.equal(registry.effective(dbBefore,dbBefore.users.find(row=>row.id===3)).timeReview.reviewLeave,false);assert.equal(registry.effective(dbBefore,dbBefore.users.find(row=>row.id===3)).daily.viewWorkdays,false);await page.waitForFunction(()=>scheduleLive.today!==null);assert.equal(await page.evaluate(()=>workdays.length),0);checks.push('current PM retains named schedule workflows while ordinary leave review and workday data stay restricted');
      if(viewportName==='desktop'){
      const cell=page.locator('.schedule-cell[data-schedule-member="12"]:not([data-schedule-date="'+today+'"])').first();await cell.click({position:{x:4,y:4}});await page.click('#day-action-markoff');await page.fill('#mark-off-note','Synthetic reviewed mark-off');await page.check('input[name="mark-off-paid"][value="unpaid"]');await page.click('#mark-off-save');await page.locator('[data-workspace-dialog] input[type="checkbox"]').waitFor();assert.equal(await page.isChecked('[data-workspace-dialog] input[type="checkbox"]'),false);assert.match(await page.locator('[data-workspace-dialog] pre').innerText(),/approved unpaid leave/);assert.equal((await read()).timeOffRequests.length,0);await screen('mark-off-preview');
      await page.click('#workspace-action-save');assert.equal((await read()).timeOffRequests.length,0);assert.match(await page.locator('[data-workspace-dialog] [role="status"]').innerText(),/confirmation box/);
      let originalBody,ack;const drop=async route=>{originalBody=route.request().postDataJSON();const response=await route.fetch();assert.equal(response.status(),201);ack=await response.json();await route.abort();};await context.route(origin+'/api/schedule/mark-off',drop);await page.check('[data-workspace-dialog] input[type="checkbox"]');await page.click('#workspace-action-save');await page.locator('#workspace-original-save').waitFor();await page.locator('#mark-off-message').filter({hasText:/unknown/i}).waitFor();await context.unroute(origin+'/api/schedule/mark-off',drop);await page.keyboard.press('Escape');const saved=await store.load(A);assert.equal(saved.snapshot.timeOffRequests.length,1);await screen('unknown-mark-off');const replayResponse=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/schedule/mark-off');await page.click('#workspace-original-save button');const replay=await replayResponse;assert.equal(replay.status(),201);assert.deepEqual(replay.request().postDataJSON(),originalBody);assert.equal((await replay.json()).originalSaveResult,true);await page.locator('#workspace-original-save').waitFor({state:'detached'});const afterRecovery=await store.load(A);assert.deepEqual(afterRecovery.snapshot.timeOffRequests,saved.snapshot.timeOffRequests);assert.equal(afterRecovery.revision,saved.revision);assert.equal(ack.row.type,'unpaid');checks.push('mark-off requires unchecked explicit review; lost acknowledgement recovers the original envelope without duplicate leave or revision');
      await page.click('#repeat-week');await page.locator('#repeat-week-list input').first().waitFor();await page.click('#repeat-week-confirm');await page.locator('[data-workspace-dialog] input[type="checkbox"]').waitFor();assert.match(await page.locator('[data-workspace-dialog] pre').innerText(),/Assignments to create: 1/);assert.equal((await read()).assignments.length,2);await screen('repeat-preview');await page.check('[data-workspace-dialog] input[type="checkbox"]');const repeated=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/schedule/repeat-week');await page.click('#workspace-action-save');assert.equal((await repeated).status(),200);await page.locator('#repeat-week-result[open]').waitFor();assert.equal((await read()).assignments.length,3);await page.keyboard.press('Escape');checks.push('repeat-week normal control shows its server-computed scoped batch and creates it only after explicit confirmation');
      }else{assert.equal(await page.locator('#repeat-week').isVisible(),false);assert.equal(await page.locator('.schedule-cell[data-schedule-member="12"]').first().isVisible(),false);checks.push('inherited mobile layout hides repeat-week and has no mark-off entry point; scheduling feature gap is recorded without forcing hidden controls');}
      await page.locator(viewportName==='mobile'?'.schedule-agenda-assignment[data-assignment="2"]':'[data-assignment="2"]').first().click();await page.locator('#adopt-actual-times').waitFor({state:'visible'});await page.click('#adopt-actual-times');await page.locator('[data-workspace-dialog] input[type="checkbox"]').waitFor();assert.match(await page.locator('[data-workspace-dialog] pre').innerText(),/07:15 to 15:45/);assert.equal((await read()).assignments.find(row=>row.id===2).start,'08:00');await screen('adopt-preview');await page.check('[data-workspace-dialog] input[type="checkbox"]');const adopted=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/assignments/2/adopt-actual-times');await page.click('#workspace-action-save');assert.equal((await adopted).status(),200);await page.locator('#assignment-detail-modal').waitFor({state:'hidden'});assert.equal((await read()).assignments.find(row=>row.id===2).start,'07:15');assert.equal(await page.evaluate(()=>workdays.length),0);checks.push('manual adoption uses authorized server preview while PM raw workday access remains restricted');
      await alter(db=>{const module=registry.families.find(row=>row[0]==='timeReview')[4],roles=Object.fromEntries(registry.roles.map(role=>[role,module.ceiling(role)]));roles.project_manager.reviewLeave=false;db.company.timeReviewRolePolicy={version:1,revision:1,roles};db.company.timeReviewPolicyRequired=true;});await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.locator('#workspace-refresh-access').waitFor();assert.equal(await page.evaluate(()=>scheduleLive.today),null);assert.equal(await page.locator('[data-workspace-dialog]').count(),0);checks.push('revoked named-workflow restriction retires schedule evidence and pending private controls');await screen('workflow-revoked');
    }else if(group==='roles'){
      await page.uncheck('[data-role-family="scheduling"][data-role="project_manager"][data-role-action="create"]');await preview('Synthetic PM scheduling limit');assert.equal((await read()).company.schedulingRolePolicy,undefined);assert.match(await page.locator('.role-review').innerText(),/1 people affected/);await screen('server-preview');await save();const saved=await read();assert.equal(registry.effective(saved,saved.users[2]).scheduling.create,false);assert.equal(saved.users[2].permissions.scheduleCrews,true);assert.equal(registry.effective(saved,saved.users[0]).scheduling.create,true);assert.deepEqual(saved.company.roleProfiles,undefined);checks.push('real server preview has no permission effect; explicit save restricts PM scheduling and preserves Owner and stored grants');
      await screen('saved-current');await page.reload();await page.waitForFunction(()=>document.documentElement.classList.contains('workspace-ready'));await openRoles();assert.equal(await page.isChecked('[data-role-family="scheduling"][data-role="project_manager"][data-role-action="create"]'),false);assert.match(await page.locator('#company-role-editor').innerText(),/Synthetic Owner saved scheduling/);checks.push('ordinary Company Settings reload displays committed policy and audit');
      await context.clearCookies();await login('admin@example.invalid');if(viewportName==='mobile')await page.click('#menu-button');if(!await page.locator('.nav-item[data-page="settings"]').isVisible())await page.locator('#nav-more > summary').click();await page.locator('.nav-item[data-page="settings"]').click();assert.equal(await page.locator('#settings-tab-roles').isVisible(),false);checks.push('Admin has ordinary settings but cannot open Owner-only Roles');
    }else if(group==='profiles'){
      await page.click('[data-role-mode="profiles"]');await page.click('[data-role-command="office"]');await preview('Synthetic optional Office profile');assert.match(await page.locator('.role-review').innerText(),/0 people affected/);await save();assert.equal((await read()).company.roleProfiles.assignments.length,0);
      await page.selectOption('#role-account-4','office-profile-v1');await page.click('[data-profile-assign="4"]');await preview('Synthetic Admin Office limits');await screen('office-assignment-preview');await save();let current=await read();assert.equal(registry.effective(current,current.users[3]).scheduling.create,false);assert.equal(registry.effective(current,current.users[3]).scheduling.view,true);checks.push('Office creation assigns nobody; explicit compatible Admin assignment applies real restrictions');
      await page.click('[data-role-command="new-profile"]');await page.fill('#role-profile-name','Synthetic PM Reader');await page.selectOption('#role-profile-base','project_manager');await page.uncheck('[data-profile-family="scheduling"][data-role-action="create"]');await preview('Synthetic named PM profile');await save();current=await read();const profile=current.company.roleProfiles.profiles.find(row=>row.kind==='custom');assert.equal(profile.name,'Synthetic PM Reader');assert.equal(current.company.roleProfiles.assignments.some(row=>row.profileId===profile.id),false);await page.selectOption('#role-account-3',profile.id);await page.click('[data-profile-assign="3"]');await preview('Synthetic PM profile assignment');await save();current=await read();assert.equal(registry.effective(current,current.users[2]).scheduling.create,false);assert.deepEqual(current.users[2].projectIds,[101]);assert.deepEqual(current.users[2].assignedCrews,['Synthetic Crew']);await screen('profiles-saved');checks.push('custom profile creation and compatible assignment retain existing PM project and crew scope');
    }else if(group==='recovery'){
      await page.uncheck('[data-role-family="scheduling"][data-role="project_manager"][data-role-action="create"]');await preview('Synthetic lost permission acknowledgement');let body,ack;const intercept=async route=>{body=route.request().postDataJSON();const response=await route.fetch();assert.equal(response.status(),200);ack=await response.json();await route.abort();};await context.route(origin+'/api/company/role-policy/confirm',intercept);await page.check('#role-explicit-confirm');await page.click('[data-role-command="confirm"]');await page.locator('[data-role-command="recover"]:enabled').waitFor();assert.equal(ack.committed,true);const saved=await store.load(A);await context.unroute(origin+'/api/company/role-policy/confirm',intercept);install();const start=requests.length;await page.reload();await page.waitForFunction(()=>document.documentElement.classList.contains('workspace-ready'));await openRoles();await page.locator('[data-role-command="recover"]:enabled').waitFor();assert.equal(requests.slice(start).filter(row=>row.path.endsWith('/confirm')).length,0);const reloaded=await store.load(A);assert.deepEqual(reloaded.snapshot.company,saved.snapshot.company);for(const collection of ['rolePolicyPreviews','rolePolicyReceipts','rolePolicyAudit'])assert.deepEqual(reloaded.snapshot[collection],saved.snapshot[collection]);await screen('unknown-after-reload');const response=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/confirm'));await page.click('[data-role-command="recover"]');const replay=await response;assert.equal(replay.status(),200);assert.deepEqual(replay.request().postDataJSON(),body);assert.deepEqual(await replay.json(),ack);assert.equal((await store.load(A)).revision,reloaded.revision);await page.locator('#role-editor-message').filter({hasText:'Saved policy revision'}).waitFor();assert.deepEqual(JSON.parse(await page.evaluate(()=>sessionStorage.getItem('pdl-role-save-recovery-v1'))),[]);checks.push('lost acknowledgement survives tab reload and handler restart; no auto resend; explicit exact-envelope replay preserves revision and original receipt');await screen('original-recovered');
    }else if(group==='session'){
      await page.uncheck('[data-role-family="scheduling"][data-role="project_manager"][data-role-action="create"]');await preview('Synthetic detached save identity');let body;const intercept=async route=>{body=route.request().postDataJSON();const response=await route.fetch();assert.equal(response.status(),200);await route.abort();};await context.route(origin+'/api/company/role-policy/confirm',intercept);await page.check('#role-explicit-confirm');await page.click('[data-role-command="confirm"]');await page.locator('[data-role-command="recover"]:enabled').waitFor();await context.unroute(origin+'/api/company/role-policy/confirm',intercept);const prior=await read(),start=requests.length;await context.clearCookies();await login();await openRoles();assert.equal(await page.locator('[data-role-command="recover"]').count(),0);assert.match(await page.locator('.role-review').innerText(),/earlier signed-in session/);assert.equal(await page.locator('[data-role-command="retire-unknown"]').isDisabled(),true);assert.equal(requests.slice(start).filter(row=>row.path.endsWith('/confirm')).length,0);await screen('detached-original-session');await page.check('#role-reconciled');await page.click('[data-role-command="retire-unknown"]');await page.locator('[data-role-command="preview"]').waitFor();const entries=JSON.parse(await page.evaluate(()=>sessionStorage.getItem('pdl-role-save-recovery-v1')));assert.equal(entries.length,1);assert.equal(entries[0].requestId,body.requestId);assert.equal(entries[0].state,'retired-unknown');const current=await read();assert.deepEqual(current.company,prior.company);assert.deepEqual(current.rolePolicyReceipts,prior.rolePolicyReceipts);checks.push('a new Owner session cannot replay an earlier envelope; explicit current-state/activity review retains the unknown result history and makes no permission write');
    }else if(group==='boundaries'){
      await page.uncheck('[data-role-family="scheduling"][data-role="project_manager"][data-role-action="create"]');await preview('Synthetic storage and navigation boundaries');await page.evaluate(()=>{window.syntheticRoleStorageWrite=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='pdl-role-save-recovery-v1')throw Error('Synthetic tab quota');return window.syntheticRoleStorageWrite.call(this,key,value);};});const start=requests.length;await page.check('#role-explicit-confirm');await page.click('[data-role-command="confirm"]');await page.locator('#role-editor-message').filter({hasText:'cannot read or preserve the original save identity'}).waitFor();assert.equal(requests.slice(start).filter(row=>row.path.endsWith('/confirm')).length,0);assert.equal((await read()).company.schedulingRolePolicy,undefined);await page.evaluate(()=>{Storage.prototype.setItem=window.syntheticRoleStorageWrite;delete window.syntheticRoleStorageWrite;});checks.push('failed technical-marker storage prevents the first confirmation POST and all permission changes');
      let held,release;const ready=new Promise(resolve=>held=resolve),gate=new Promise(resolve=>release=resolve);const intercept=async route=>{const response=await route.fetch();assert.equal(response.status(),200);held();await gate;await route.abort();};await context.route(origin+'/api/company/role-policy/confirm',intercept);await page.check('#role-explicit-confirm');await page.click('[data-role-command="confirm"]');await ready;await page.click('#settings-tab-company');assert.equal(await page.locator('#company-role-editor').innerText(),'');release();await context.unroute(origin+'/api/company/role-policy/confirm',intercept);await page.waitForFunction(()=>JSON.parse(sessionStorage.getItem('pdl-role-save-recovery-v1'))?.length===1);await page.reload();await page.waitForFunction(()=>document.documentElement.classList.contains('workspace-ready'));await openRoles();await page.locator('[data-role-command="recover"]:enabled').waitFor();assert.equal((await read()).rolePolicyReceipts.length,1);checks.push('navigation during a held acknowledgement retires private editor DOM while preserving original unknown-save metadata for explicit recovery');await screen('navigated-original-recovery');
    }else{
      await page.uncheck('[data-role-family="scheduling"][data-role="project_manager"][data-role-action="create"]');await preview('Synthetic stale review');await page.check('#role-explicit-confirm');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal(await page.isChecked('#role-explicit-confirm'),false);assert.equal(await page.locator('[data-role-command="confirm"]').isDisabled(),true);await alter(db=>{db.company.name='Synthetic concurrent company change';});await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.locator('#role-editor-message').filter({hasText:'company changed'}).waitFor();assert.equal((await read()).company.schedulingRolePolicy,undefined);assert.equal(await page.locator('#role-explicit-confirm').count(),0);checks.push('blur removes confirmation; fresh focus retires a review after competing company revision');await screen('stale-retired');await alter(db=>{db.sessions=[];});await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForFunction(()=>!document.getElementById('company-role-editor')||document.getElementById('company-role-editor').textContent==='');checks.push('revoked session retires private role/profiles/audit DOM');
    }
    assert.deepEqual(pageErrors,[]);assert.deepEqual(fs.readFileSync(file),original);assert.equal(fs.existsSync(path.join(directory,'platform.json')),false);const artifacts=fs.readdirSync(evidence).filter(name=>name.startsWith(prefix)&&name.endsWith('.png')).map(name=>{const bytes=fs.readFileSync(path.join(evidence,name));return {name,bytes:bytes.length,sha256:hash(bytes)};});const sourceHead=execFileSync('git',['rev-parse','HEAD'],{cwd:__dirname,encoding:'utf8'}).trim();if(process.env.PDL_COMPAT_SOURCE_SHA)assert.equal(sourceHead,process.env.PDL_COMPAT_SOURCE_SHA);fs.writeFileSync(path.join(evidence,prefix+'.json'),JSON.stringify({sourceHead,testSourceHash:hash(fs.readFileSync(__filename)),backend:native?'native-postgresql':'synthetic-memory',group,viewport:viewportName,checks,requests,pageErrors,artifacts,blockedExternalRequests:[...external],allowedExternalRequests:0,productionReady:false},null,2));console.log(JSON.stringify({group,viewport:viewportName,passed:checks.length,apiOutcomes:requests.length,backend:native?'native-postgresql':'synthetic-memory'}));
  }catch(error){fs.writeFileSync(path.join(evidence,prefix+'-failure.json'),JSON.stringify({message:error.message,pageErrors,requests,body:await page?.locator('body').innerText().catch(()=>''),state:await page?.evaluate(()=>({role:currentUser?.role,mode:currentRole,enabled:window.pdlWorkspaceActions?.enabled(),rolePolicies:window.pdlWorkspaceActions?.rolePolicies(),config:window.pdlWorkspaceConfig})).catch(()=>null)},null,2));await page?.screenshot({path:path.join(evidence,prefix+'-failure.png'),fullPage:true}).catch(()=>{});throw error;}finally{await browser?.close();uninstall?.();await native?.close();mod.server.closeAllConnections();await new Promise(resolve=>mod.server.close(resolve));}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
