'use strict';
const assert = require('node:assert/strict'), crypto = require('node:crypto'), fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { A, B, initial, snapshot, memory } = require('./compat-account-fixture'), { services } = require('./compat-lifecycle-fixture'), { nativeFixture } = require('./compat-lifecycle-native-fixture'), { workspaceSnapshot } = require('./compat-workspace-fixture');
async function main() {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'pdl-compat-workspace-browser-')), evidence = process.env.PDL_COMPAT_BROWSER_EVIDENCE || path.join(directory, 'evidence'); fs.mkdirSync(evidence, { recursive: true });
  for (const name of ['OPENAI_API_KEY', 'RESEND_API_KEY', 'STRIPE_SECRET_KEY', 'SENTRY_DSN', 'SUPABASE_SECRET_KEY', 'PDL_PLATFORM_KEY']) { if (process.env[name]) throw Error('Provider-free browser required'); process.env[name] = ''; }
  const legacy = snapshot(); legacy.company.id = B; legacy.users[0].companyId = B; const file = path.join(directory, 'legacy.json'); fs.writeFileSync(file, JSON.stringify(legacy));
  Object.assign(process.env, { NODE_ENV: 'test', PDL_COMPAT_ACCOUNT_SYNTHETIC: '1', PDL_REQUIRE_AUTH: '1', PDL_DB_FILE: file, PDL_PLATFORM_FILE: path.join(directory, 'platform.json'), PDL_SUPABASE_ENABLED: '0', PDL_TRANSACTIONAL_DB: 'off' });
  const mod = require('./server'); await new Promise(resolve => mod.server.listen(0, '127.0.0.1', resolve)); const origin = 'http://127.0.0.1:' + mod.server.address().port;
  let browser, native, uninstall; const checks = [], errors = [], requests = [], external = new Set();
  try {
    if (process.env.TEST_COMPAT_DATABASE_URL) native = await nativeFixture(); const store = native?.repository || memory(workspaceSnapshot()), key = crypto.randomBytes(32), fixture = services(store, origin, { key });
    const deliveries=[];
    uninstall = mod.installCompatibilityAccountTests({ synthetic: true, companyId: A, origin, globalOrigin: 'http://localhost:4999', repository: store, ...fixture, workspace: true, workspaceKey: key,complianceSend:async(source)=>{deliveries.push(source);return {status:'accepted'};} });
    async function reset() { const db = workspaceSnapshot(); if (native) await native.reset(db); else { const loaded = await store.load(A); await store.commit(db, loaded.revision); } }
    browser = await chromium.launch({ headless: true, args: ['--disable-background-networking'] });
    async function context(viewport) { const ctx = await browser.newContext({ viewport }); ctx.on('page', page => { page.on('pageerror', error => errors.push(error.message)); page.on('response', response => { if (new URL(response.url()).pathname.startsWith('/api/')) requests.push({ path: new URL(response.url()).pathname, status: response.status() }); }); }); await ctx.route('**/*', route => { const url = new URL(route.request().url()); if (url.origin === origin) return route.continue(); external.add(url.origin + url.pathname); return route.abort(); }); return ctx; }
    async function login(page, email = 'owner@example.invalid') { await page.goto(origin + '/login.html?tenant=' + A); await page.fill('#email', email); await page.fill('#password', initial); await page.click('#login button[type=submit]'); await page.waitForURL(url => url.pathname === '/app'); await page.waitForFunction(() => document.documentElement.classList.contains('workspace-ready')); await page.waitForFunction(() => document.querySelector('#dashboard-page.active') || document.querySelector('#myday-page.active')); await page.waitForTimeout(500); }
    async function confirm(page) { await page.locator('#workspace-action-review').waitFor(); assert.equal(await page.isChecked('#workspace-action-confirmed'), false); await page.check('#workspace-action-confirmed'); await page.click('#workspace-action-save'); await page.locator('#workspace-action-review').waitFor({ state: 'detached' }); }
    for (const [name, viewport] of [['desktop', { width: 1440, height: 1000 }], ['mobile', { width: 390, height: 844 }]]) {
      await reset(); const ctx = await context(viewport), page = await ctx.newPage(); await login(page); await page.screenshot({ path: path.join(evidence, 'g2-' + name + '-dashboard.png'), fullPage: true }); checks.push(name + ': actual signed-out sign-in opens normal finite dashboard');
      if (name === 'mobile') await page.click('#menu-button'); await page.click('.nav-item[data-page=schedule]'); await page.locator('#schedule-page.active').waitFor(); checks.push(name + ': ordinary schedule navigation');
      await page.goto(origin + '/app#timecards'); await page.waitForFunction(() => document.querySelector('#timecards-page.active')); await page.locator('#timecard-add').waitFor({ state: 'visible' });
      await page.click('#timecard-add'); await page.selectOption('#timecard-add-member', '12'); await page.selectOption('#timecard-add-project', '101'); await page.fill('#timecard-add-in', '2026-10-09T08:00'); await page.fill('#timecard-add-out', '2026-10-09T10:00'); await page.fill('#timecard-add-reason', 'Synthetic existing form time'); await page.click('#timecard-add-save'); await confirm(page); await page.locator('#timecard-add-modal').waitFor({ state: 'hidden' });
      const loaded = await store.load(A); assert.equal(loaded.snapshot.timeCards.length, 1); assert.equal(loaded.snapshot.timeCards[0].status, 'draft'); checks.push(name + ': normal add-time form uses server preview and explicit confirmation');
      await page.screenshot({ path: path.join(evidence, 'g2-' + name + '-time.png'), fullPage: true }); await page.reload(); await page.waitForFunction(() => document.querySelector('#timecards-page.active')); await page.waitForTimeout(400); assert.equal((await store.load(A)).snapshot.timeCards.length, 1); checks.push(name + ': deep link and reload retain admitted saved time'); await ctx.close();
    }
    await reset(); const recoveryCtx=await context({width:1440,height:1000}),recoveryPage=await recoveryCtx.newPage();await login(recoveryPage);await recoveryPage.goto(origin+'/app#timecards');await recoveryPage.waitForFunction(()=>document.querySelector('#timecards-page.active'));await recoveryPage.click('#timecard-add');await recoveryPage.selectOption('#timecard-add-member','12');await recoveryPage.selectOption('#timecard-add-project','101');await recoveryPage.fill('#timecard-add-in','2026-10-09T08:00');await recoveryPage.fill('#timecard-add-out','2026-10-09T10:00');await recoveryPage.fill('#timecard-add-reason','Synthetic lost response');
    await recoveryCtx.route(origin+'/api/time-cards',async route=>{if(route.request().method()!=='POST')return route.continue();const response=await route.fetch();assert.equal(response.status(),201);await route.abort();});
    await recoveryPage.click('#timecard-add-save');await confirm(recoveryPage);await recoveryPage.locator('#workspace-original-save').waitFor();await recoveryPage.waitForFunction(()=>/save result is unknown.*original save result/i.test(document.querySelector('#toast').textContent));assert.equal((await store.load(A)).snapshot.timeCards.length,1);await recoveryCtx.unroute(origin+'/api/time-cards');await recoveryPage.reload();await recoveryPage.waitForFunction(()=>document.documentElement.classList.contains('workspace-ready'));await recoveryPage.locator('#workspace-original-save button').waitFor();await recoveryPage.click('#workspace-original-save button');await recoveryPage.locator('#workspace-original-save').waitFor({state:'detached'});assert.equal((await store.load(A)).snapshot.timeCards.length,1);checks.push('same-session lost confirmation response and reload recover the exact original save without duplicate time');await recoveryCtx.close();
    await reset();let loaded=await store.load(A);loaded.snapshot.users[1].role='foreman';await store.commit(loaded.snapshot,loaded.revision);const foremanCtx=await context({width:390,height:844}),foremanPage=await foremanCtx.newPage();await login(foremanPage,'field@example.invalid');assert.equal(await foremanPage.evaluate(async()=> (await window.pdlWorkspaceActions.identity()).role),'foreman');assert.equal(await foremanPage.evaluate(()=>currentRole),'field');await foremanPage.screenshot({path:path.join(evidence,'g2-mobile-foreman.png'),fullPage:true});checks.push('genuine Foreman enters the existing field presentation with linked-member scope');await foremanCtx.close();
    await reset();loaded=await store.load(A);loaded.snapshot.subcontractors=[{id:51,companyId:A,name:'Synthetic Subcontractor',contact:'Synthetic Contact',email:'synthetic@example.invalid',autoComplianceReminders:true}];await store.commit(loaded.snapshot,loaded.revision);const complianceCtx=await context({width:1440,height:1000}),compliancePage=await complianceCtx.newPage();await login(compliancePage);assert.equal((await store.load(A)).snapshot.workspaceComplianceJobs[0].status,'sent');assert.equal(deliveries.length,1);assert.equal(await compliancePage.evaluate(()=>projects.length),1);await compliancePage.screenshot({path:path.join(evidence,'g2-desktop-compliance-dashboard.png'),fullPage:true});checks.push('named CAS-first compliance preparation completes before the normal coherent dashboard read');await complianceCtx.close();
    await reset();const expiryCtx=await context({width:1440,height:1000}),expiryPage=await expiryCtx.newPage();await login(expiryPage);loaded=await store.load(A);loaded.snapshot.company.billingExempt=false;loaded.snapshot.company.subscriptionStatus='Trial';loaded.snapshot.company.trialEndsAt=new Date(Date.now()+1800).toISOString();await store.commit(loaded.snapshot,loaded.revision);await expiryPage.evaluate(()=>window.pdlWorkspaceActions.identity());const fixed=(await store.load(A)).revision;await expiryPage.waitForTimeout(2000);await expiryPage.evaluate(()=>window.dispatchEvent(new Event('focus')));await expiryPage.locator('#workspace-refresh-access').waitFor();assert.equal(await expiryPage.evaluate(()=>projects.length),0);assert.equal(await expiryPage.locator('main').innerText().then(value=>value.includes('Synthetic Project')),false);assert.equal((await store.load(A)).revision,fixed);checks.push('unchanged-revision natural trial lock retires the actual cached dashboard on focus and presents the refresh/billing recovery shell');await expiryCtx.close();
    assert.deepEqual(errors, []); const stops = requests.filter(row => row.status >= 500); assert.deepEqual(stops, []);
    const result = { checks, backend: native ? 'native-postgresql' : 'synthetic-memory', pageErrors: errors, requests, externalAttemptsAborted: [...external], allowedExternalRequests: 0, productionReady: false, sourceHead:process.env.PDL_COMPAT_SOURCE_SHA||null,runId:process.env.GITHUB_RUN_ID||null }; fs.writeFileSync(path.join(evidence, 'g2-workspace-browser-results.json'), JSON.stringify(result, null, 2)); console.log(JSON.stringify({ passed: checks.length, backend: result.backend, pageErrors: errors, stops }));
  } finally { fs.writeFileSync(path.join(evidence, 'g2-workspace-browser-diagnostics.json'), JSON.stringify({ checks, errors, requests, externalAttemptsAborted: [...external] }, null, 2)); if(browser)for(const ctx of browser.contexts())for(const page of ctx.pages()){await page.screenshot({path:path.join(evidence,'g2-last-page.png'),fullPage:true}).catch(()=>{});console.log(JSON.stringify({pathname:new URL(page.url()).pathname,classes:await page.locator('html').getAttribute('class'),active:await page.locator('.page.active').getAttribute('id').catch(()=>null),messages:await page.locator('[role=status]').allTextContents(),errors,failedRequests:requests.filter(row=>row.status>=400).slice(0,12)}));} uninstall?.(); await browser?.close(); await new Promise(resolve => mod.server.close(resolve)); await native?.close(); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
