'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {A,B,initial,snapshot,memory}=require('./compat-account-fixture');
const {workspaceSnapshot}=require('./compat-workspace-fixture');
const {services}=require('./compat-lifecycle-fixture');
const platform=require('./compat-workspace-platform-sink'),facts=require('./compat-workspace-billing-journal');
async function main(){
  const directory=fs.mkdtempSync(path.join(os.tmpdir(),'pdl-g2-dependencies-')),file=path.join(directory,'legacy.json'),legacy=snapshot();legacy.company.id=B;legacy.users[0].companyId=B;fs.writeFileSync(file,JSON.stringify(legacy));const bytes=fs.readFileSync(file);
  for(const name of ['OPENAI_API_KEY','RESEND_API_KEY','STRIPE_SECRET_KEY','SENTRY_DSN','SUPABASE_SECRET_KEY','PDL_PLATFORM_KEY'])process.env[name]='';
  Object.assign(process.env,{NODE_ENV:'test',PDL_COMPAT_ACCOUNT_SYNTHETIC:'1',PDL_REQUIRE_AUTH:'1',PDL_DB_FILE:file,PDL_PLATFORM_FILE:path.join(directory,'platform.json'),PDL_SUPABASE_ENABLED:'0',PDL_TRANSACTIONAL_DB:'off'});
  const mod=require('./server');await new Promise(r=>mod.server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+mod.server.address().port,key=crypto.randomBytes(32);
  let uninstall;const checks=[];
  async function scenario(seed,provider,send){uninstall?.();const store=memory(seed),sinkStore=platform.memoryStorage(),journalStore=facts.memoryStorage(),fixture=services(store,origin,{key});uninstall=mod.installCompatibilityAccountTests({synthetic:true,companyId:A,origin,globalOrigin:'http://localhost:4999',repository:store,...fixture,workspace:true,workspaceKey:key,billingProvider:provider,billingPlatformSink:platform.createSink(sinkStore),billingJournal:facts.createJournal(journalStore,key),assignmentSend:send});
    const request=async(route,method='GET',data,bearer)=>{const response=await fetch(origin+route,{method,headers:{'X-PDL-Company':A,...(bearer?{Authorization:'Bearer '+bearer}:{}),...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});return {status:response.status,data:await response.json(),revision:Number(response.headers.get('X-PDL-Workspace-Revision'))};};
    const login=await request('/api/auth/login','POST',{email:'owner@example.invalid',password:initial});assert.equal(login.status,200,JSON.stringify(login));return {store,sinkStore,journalStore,request:(route,method,data)=>request(route,method,data,login.data.token),token:login.data.token};
  }
  function billingSeed(isFounder=false){const seed=workspaceSnapshot();Object.assign(seed.company,{stripeSubscriptionId:'sub_synthetic_one',stripeCustomerId:'cus_synthetic_one',billingExempt:false,subscriptionStatus:'Past due'});if(isFounder)seed.company.founder={requested:true,plan:'growth',billingCycle:'monthly',assistedSetup:true,termsVersion:'founder-2026-09-28'};return seed;}
  function provider(isFounder=false){const calls=[],start=1791504000,price='price_synthetic_'+(isFounder?'founder_':'')+'growth_monthly';let configured=false,scheduled=false,status='active';
    const invoke=async(d,proof)=>{calls.push({d,proof});assert.equal(d.companyId,A);assert.equal(d.subscriptionId,'sub_synthetic_one');assert.equal(d.customerId,'cus_synthetic_one');
      if(d.kind==='subscription')return {status:'accepted',value:{id:d.subscriptionId,livemode:false,customer:d.customerId,metadata:{company_id:A,...(isFounder?{offer:'founder'}:{})},status,items:{data:[{price:{id:price},quantity:1}]},current_period_start:start,current_period_end:start+2592000,latest_invoice:isFounder?'in_synthetic_one':null,schedule:scheduled?'sub_sched_synthetic_one':null}};
      if(d.kind==='invoice')return {status:'accepted',value:{id:d.invoiceId,livemode:false,customer:d.customerId,subscription:d.subscriptionId,status:'paid'}};
      if(d.kind==='scheduleCreate')scheduled=true;if(d.kind==='configurePhases')configured=true;
      return {status:'accepted',value:{id:'sub_sched_synthetic_one',livemode:false,subscription:d.subscriptionId,customer:d.customerId,metadata:configured?{company_id:A,pdl_founder_configured:'1'}:{},phases:[{start_date:start,...(configured?{end_date:require('./founder-billing').addMonths(start,24),proration_behavior:'none'}:{}),items:[{price,quantity:1}]}],...(configured?{end_behavior:'cancel',proration_behavior:'none'}:{})}};
    };return {calls,invoke,setStatus:value=>{status=value;}};
  }
  try {
    let p=provider(),s=await scenario(billingSeed(),p.invoke);let response=await s.request('/api/billing');assert.equal(response.status,200,JSON.stringify(response));assert.equal(response.data.status,'Active');assert.equal(response.data.refresh.status,'accepted');assert.equal(s.store.current().company.stripeCustomerId,'cus_synthetic_one');assert.equal(p.calls.length,1);assert.equal(s.journalStore.rows.size,1);assert.equal(s.sinkStore.rows.size,0);p.setStatus('canceled');response=await s.request('/api/billing');assert.equal(response.data.status,'Cancelled');assert.equal(p.calls.length,2);checks.push('each Owner billing opening freshly observes provider status changes while preserving immutable subscription ownership');
    p=provider(true);s=await scenario(billingSeed(true),p.invoke);response=await s.request('/api/billing');assert.equal(response.status,200,JSON.stringify(response));assert.equal(response.data.refresh.status,'accepted');assert.deepEqual(p.calls.map(c=>c.d.kind),['subscription','invoice','scheduleCreate','configurePhases']);assert.equal(s.store.current().company.founder.renewalReviewRequired,true);assert.equal(s.sinkStore.rows.size,1);assert.equal(s.journalStore.rows.size,4);await s.request('/api/billing');assert.equal(p.calls.length,7);assert.equal(s.sinkStore.rows.size,1);checks.push('founder GET/create/phases run from staged claims and independently unique platform receipt');
    p=provider(true);s=await scenario(billingSeed(true),p.invoke);const originalEnsure=s.sinkStore.ensure;let setupAttempts=0;s.sinkStore.ensure=async(...args)=>{setupAttempts++;assert.equal(s.store.current().workspaceBillingJobs[0].platformStep.status,'sending');await originalEnsure(...args);throw Object.assign(Error('Synthetic lost independent setup COMMIT acknowledgement'),{statusCode:503});};response=await s.request('/api/billing');assert.equal(response.status,503);assert.equal(s.store.current().company.subscriptionStatus,'Past due');assert.equal(s.sinkStore.rows.size,1);response=await s.request('/api/billing');assert.equal(response.status,200,JSON.stringify(response));assert.equal(response.data.refresh.status,'unknown');assert.equal(response.data.refresh.observed,'accepted');assert.equal(setupAttempts,1);assert.equal(p.calls.length,4);response=await s.request('/api/billing/recover','POST',{jobId:response.data.refresh.jobId,confirmed:true});assert.equal(response.status,200,JSON.stringify(response));assert.equal(response.data.status,'Active');assert.equal(setupAttempts,1);assert.equal(p.calls.length,4);assert.equal(s.store.current().workspaceBillingJobs[0].platformStep.status,'accepted');checks.push('lost independent setup acknowledgement remains a durable pending claim; explicit recovery uses its unique observed receipt without another insert or provider attempt');
    let calls=0;s=await scenario(billingSeed(),async()=>{calls++;return {status:'unknown'};});response=await s.request('/api/billing');assert.equal(response.status,200);assert.equal(response.data.refresh.status,'unknown');assert.equal(s.store.current().company.subscriptionStatus,'Past due');await s.request('/api/billing');assert.equal(calls,1);checks.push('uncertain provider outcome retains last saved billing and never automatically resends');
    p=provider();s=await scenario(billingSeed(),async(d,k)=>{const receipt=await p.invoke(d,k);receipt.value.metadata.company_id=B;return receipt;});response=await s.request('/api/billing');assert.equal(response.status,200);assert.equal(response.data.refresh.status,'unknown');assert.equal(s.store.current().company.subscriptionStatus,'Past due');checks.push('foreign provider company binding cannot activate tenant access');
    p=provider();s=await scenario(billingSeed(),async(d,k)=>{const receipt=await p.invoke(d,k);s.store.rejectCommit=true;return receipt;});response=await s.request('/api/billing');assert.equal(response.status,409);s.store.rejectCommit=false;response=await s.request('/api/billing');assert.equal(response.status,200);assert.equal(response.data.refresh.status,'unknown');assert.equal(response.data.refresh.observed,'accepted');assert.equal(p.calls.length,1);response=await s.request('/api/billing/recover','POST',{jobId:response.data.refresh.jobId,confirmed:true});assert.equal(response.status,200,JSON.stringify(response));assert.equal(response.data.status,'Active');assert.equal(p.calls.length,1);checks.push('explicit originating-owner recovery consumes a recorded accepted result without repeating its provider operation');
    p=provider();s=await scenario(billingSeed(),async(d,k)=>{const receipt=await p.invoke(d,k),loaded=await s.store.load(A);loaded.snapshot.users[0].status='Inactive';await s.store.commit(loaded.snapshot,loaded.revision);return receipt;});response=await s.request('/api/billing');assert.equal(response.status,409);assert.equal(s.store.current().company.subscriptionStatus,'Past due');assert.equal([...s.journalStore.rows.values()][0].status,'accepted');checks.push('known provider acceptance survives authority/CAS loss independently and cannot activate revoked owner');
    const deliveries=[];s=await scenario(workspaceSnapshot(),null,async(source)=>{deliveries.push(source);assert.equal(s.store.current().workspaceAssignmentJobs[0].status,'sending');return {status:'accepted'};});
    const details={projectId:101,memberIds:[12],crew:'Synthetic Crew',date:'2026-10-20',start:'08:00',end:'16:00',activity:'Synthetic assignment',requestId:crypto.randomUUID()},preview=await s.request('/api/workspace-direct-preview','POST',{family:'scheduling',method:'POST',path:'/api/assignments',details});assert.equal(preview.status,200,JSON.stringify(preview));const proof={token:preview.data.token,version:preview.data.version,confirmed:true,requestId:crypto.randomUUID()};response=await s.request('/api/assignments','POST',proof);assert.equal(response.status,201,JSON.stringify(response));assert.equal(deliveries.length,1);assert.equal(s.store.current().workspaceAssignmentJobs[0].status,'sent');assert.equal(s.store.current().assignments.at(-1).notifications[12].emailStatus,'sent');assert.equal((await s.request('/api/assignments','POST',proof)).status,201);assert.equal(deliveries.length,1);checks.push('assignment email is CAS-first and original action replay cannot resend');
    assert.deepEqual(fs.readFileSync(file),bytes);assert.equal(fs.existsSync(path.join(directory,'platform.json')),false);console.log(JSON.stringify({passed:checks.length,checks,allowedExternalCalls:0}));
  }finally{uninstall?.();await new Promise(r=>mod.server.close(r));}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
