'use strict';
const assert = require('node:assert/strict'), crypto = require('node:crypto'), fs = require('node:fs'), os = require('node:os'), path = require('node:path'), { fork } = require('node:child_process');
const { A, B, initial, snapshot, credential } = require('./compat-account-fixture'), { workspaceSnapshot } = require('./compat-workspace-fixture'), { nativeFixture } = require('./compat-lifecycle-native-fixture');
Object.assign(process.env, { NODE_ENV: 'test', PDL_COMPAT_ACCOUNT_SYNTHETIC: '1', PDL_REQUIRE_AUTH: '1' });
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
function event(child, type) { return new Promise((resolve, reject) => { const cleanup=()=>{clearTimeout(timer);child.off('message',on);child.off('error',failed);},timer=setTimeout(()=>{cleanup();reject(Error('Synthetic workspace worker timeout: '+type));},15000);function failed(error){cleanup();reject(error);}function on(message){if(message.event===type){cleanup();resolve(message);}}child.on('message',on);child.once('error',failed); }); }
async function main() {
  const fixture = await nativeFixture(), directory = fs.mkdtempSync(path.join(os.tmpdir(), 'pdl-compat-workspace-native-')), workers = [], checks = [];
  const keyFile = path.join(directory, 'synthetic-key'); fs.writeFileSync(keyFile, crypto.randomBytes(32), { mode: 0o600 }); const legacy = snapshot(); legacy.company.id = B; legacy.users[0].companyId = B; const file = path.join(directory, 'legacy.json'); fs.writeFileSync(file, JSON.stringify(legacy)); const original = fs.readFileSync(file);
  let sharedOrigin, token;
  async function start() { const env = { ...process.env, PDL_DB_FILE: file, PDL_PLATFORM_FILE: path.join(directory, 'platform.json'), PDL_COMPAT_GLOBAL_FENCE_FILE: '', PDL_SUPABASE_ENABLED: '0', PDL_TRANSACTIONAL_DB: 'off', TEST_COMPAT_LIFECYCLE_KEY_FILE: keyFile, TEST_COMPAT_LIFECYCLE_ORIGIN: sharedOrigin || '' }; for (const name of ['OPENAI_API_KEY','RESEND_API_KEY','STRIPE_SECRET_KEY','SENTRY_DSN','SUPABASE_SECRET_KEY','PDL_PLATFORM_KEY']) env[name] = ''; const child = fork(path.join(__dirname, 'compat-workspace-http-worker.cjs'), [], { env, stdio: ['ignore','pipe','pipe','ipc'], windowsHide: true }); const ready = await event(child, 'ready'); child.origin = ready.origin; workers.push(child); sharedOrigin ||= child.origin; return child; }
  async function close(child) { if (!child.connected) return; const exited = new Promise(resolve => child.once('exit', resolve)); child.send({ event: 'close' }); await exited; }
  async function request(child, route, method = 'GET', input, bearer = token, tenant = A) { const response = await fetch(child.origin + route, { method, headers: { 'X-PDL-Company': tenant, ...(bearer ? { Authorization: 'Bearer ' + bearer } : {}), ...(input === undefined ? {} : { 'Content-Type':'application/json' }) }, ...(input === undefined ? {} : { body: JSON.stringify(input) }) }); const value = await response.json(); return { status: response.status, data: value, revision: response.headers.get('X-PDL-Workspace-Revision'), authority: response.headers.get('X-PDL-Workspace-Authority') }; }
  async function login(child, email = 'owner@example.invalid') { const value = await request(child, '/api/auth/login', 'POST', { email, password: initial }, ''); assert.equal(value.status, 200, JSON.stringify(value)); return value.data.token; }
  async function alter(change) { const loaded = await fixture.repository.load(A); change(loaded.snapshot); await fixture.repository.commit(loaded.snapshot, loaded.revision); }
  async function preview(child) { const value = await request(child, '/api/time-cards/action-preview', 'POST', { action:'create', details:{memberId:12,projectId:101,inAt:'2026-10-09T08:00:00Z',outAt:'2026-10-09T10:00:00Z',reason:'Synthetic native finite time'} }); assert.equal(value.status, 200, JSON.stringify(value)); return { token:value.data.token,version:value.data.version,confirmed:true,requestId:crypto.randomUUID() }; }
  async function arm(child, name) { const ready = event(child, 'armed'); child.send({ event:name }); await ready; }
  async function directProof(child,method,route,details,bearer=token){const selected=require('./workspace-direct-admission').route(method,route),result=await request(child,'/api/workspace-direct-preview','POST',{family:selected.family,method,path:route,details},bearer);assert.equal(result.status,200,JSON.stringify(result));return {token:result.data.token,version:result.data.version,confirmed:true,requestId:crypto.randomUUID()};}
  async function effectCount(child){const result=event(child,'effect-count');child.send({event:'effect-count'});return (await result).count;}
  try {
    await fixture.reset(workspaceSnapshot()); let first = await start(), second = await start(); token = await login(first);
    const proof = await preview(first), race = await Promise.all([request(first,'/api/time-cards','POST',proof),request(second,'/api/time-cards','POST',proof)]); assert.equal(race.filter(row=>row.status===201).length,1); assert.ok(race.every(row=>[201,200,409].includes(row.status))); assert.equal((await fixture.repository.load(A)).snapshot.timeCards.length,1); assert.equal((await request(second,'/api/time-cards','POST',proof)).status,200); checks.push('two HTTP workers consume and replay one finite time proof exactly once');
    await close(first);first=await start();assert.equal((await request(first,'/api/time-cards','POST',proof)).status,200);checks.push('restarted worker retains native original time result with same purpose key');
    const cards=await request(first,'/api/time-cards');const cardId=cards.data[0].id;const submit=await request(first,'/api/time-cards/action-preview','POST',{action:'submit',id:cardId,details:{}});assert.equal(submit.status,200);assert.equal((await request(second,'/api/time-cards/'+cardId+'/submit','POST',{token:submit.data.token,version:submit.data.version,confirmed:true,requestId:crypto.randomUUID()})).status,200);
    const review=await request(first,'/api/time-cards/review-preview','POST',{decision:'approve',ids:[cardId]});assert.equal(review.status,200);assert.equal((await request(second,'/api/time-cards/'+cardId+'/approve','POST',{token:review.data.token,version:review.data.version,confirmed:true,requestId:crypto.randomUUID()})).status,200);checks.push('stable purpose key supports actual time review preview and confirmation across workers');
    await fixture.reset(workspaceSnapshot());token=await login(first);const lost=await preview(first);await arm(second,'lose-ack');assert.equal((await request(second,'/api/time-cards','POST',lost)).status,503);assert.equal((await request(first,'/api/time-cards','POST',lost)).status,200);assert.equal((await fixture.repository.load(A)).snapshot.timeCards.length,1);checks.push('lost native COMMIT acknowledgement replays only the original saved time');
    await fixture.reset(workspaceSnapshot());token=await login(first);await arm(first,'hold-final');const held=event(first,'final-held'), pending=request(first,'/api/state');await held;await alter(db=>{db.users[0].status='Inactive';});first.send({event:'release-final'});const stale=await pending;assert.ok([401,409].includes(stale.status));assert.equal(JSON.stringify(stale.data).includes('Synthetic wall tile'),false);checks.push('buffered private bootstrap is withheld after current account revocation');
    await fixture.reset(workspaceSnapshot());token=await login(first);await alter(db=>{const hash=crypto.createHash('sha256').update(token).digest('hex');db.sessions.find(row=>row.tokenHash===hash).expiresAt=new Date(Date.now()+800).toISOString();});await arm(first,'hold-final');const heldExpiry=event(first,'final-held'), expiry=request(first,'/api/state');await heldExpiry;const unchanged=(await fixture.repository.load(A)).revision;await delay(900);first.send({event:'release-final'});assert.equal((await expiry).status,401);assert.equal((await fixture.repository.load(A)).revision,unchanged);checks.push('natural session expiry with unchanged native revision blocks buffered private data');
    await fixture.reset(workspaceSnapshot());token=await login(first);const expiring=await preview(first);await alter(db=>{const hash=crypto.createHash('sha256').update(token).digest('hex');db.sessions.find(row=>row.tokenHash===hash).expiresAt=new Date(Date.now()+1100).toISOString();const p=db.timeWriterPreviews.find(row=>row.tokenHash===require('./database/transactional-repository').canonicalHash(expiring.token));p.expectedRevision+=1;p.version=require('./database/transactional-repository').canonicalHash({operation:p.operation,actorHash:p.actorHash,expectedRevision:p.expectedRevision,tokenHash:p.tokenHash});expiring.version=p.version;});
    const lock=await fixture.admin.connect();await lock.query('BEGIN');await lock.query('SELECT revision FROM public.tenant_revisions WHERE company_id=$1 FOR UPDATE',[A]);const confirming=request(first,'/api/time-cards','POST',expiring);await delay(1200);await lock.query('ROLLBACK');lock.release();assert.equal((await confirming).status,409);assert.equal((await fixture.repository.load(A)).snapshot.timeCards.length,0);checks.push('native post-lock deadline rejects confirmation after session expiry without writing time');
    await fixture.reset(workspaceSnapshot());await alter(db=>{db.company.features.timeCards=true;db.team.push({id:13,name:'Hidden Native Crew',crew:'Hidden Crew'});db.projects.push({id:102,name:'Hidden Native Project',estimateItems:[]});db.reports.push({id:2,project:1,foreman:'Hidden Native Crew',dateIso:'2026-10-09',status:'Approved',notes:'Hidden native work',laborEntries:[{memberId:13,hours:99}],productionEntries:[{description:'Hidden scope',quantity:999,unit:'EA',laborHours:99}],flags:[],history:[]});db.users.push({id:3,companyId:A,name:'Native PM',email:'pm@example.invalid',status:'Active',role:'project_manager',...credential(initial),projectIds:[101],assignedCrews:['Synthetic Crew'],permissions:{scheduleCrews:true,viewTime:true,manageTime:true,viewDailies:true,approveDailies:true}});});token=await login(first,'pm@example.invalid');const scoped=await request(second,'/api/state');assert.equal(scoped.status,200);assert.equal(scoped.data.projects.length,1);assert.equal(scoped.data.reports.length,1);assert.equal(scoped.data.reports[0].project,0);assert.equal(JSON.stringify(scoped.data).includes('Hidden Native'),false);assert.equal((await request(second,'/api/reports/2')).status,404);assert.equal((await request(second,'/api/state','GET',undefined,token,B)).status,404);checks.push('finite bootstrap and detail reads hide foreign project/crew IDs with native project-index remapping');
    await alter(db=>{const module=require('./daily-access');db.company.dailyPolicyRequired=true;db.company.dailyRolePolicy={version:1,revision:1,roles:Object.fromEntries(module.roles.map(role=>[role,module.ceiling(role)]))};for(const name of module.actions)db.company.dailyRolePolicy.roles.project_manager[name]=false;});const denied=await request(first,'/api/state');assert.equal(denied.status,200);assert.equal(denied.data.reports.length,0);assert.equal(denied.data.projects[0].production,undefined);const insights=await request(first,'/api/insights');assert.equal(insights.status,200);assert.equal(insights.data.records.length,0);checks.push('current restrictive daily policy suppresses raw rows and derived aggregates while stored grants stay true');
    await alter(db=>{db.projects[0].companyId=B;});const foreign=await request(second,'/api/state');assert.equal(foreign.status,409);assert.equal(JSON.stringify(foreign.data).includes('Synthetic Project'),false);checks.push('foreign company binding is rejected before field projection');
    await fixture.reset(workspaceSnapshot());token=await login(first);
    const assignmentDetails={projectId:101,memberIds:[12],crew:'Synthetic Crew',date:'2026-10-20',start:'08:00',end:'16:00',activity:'Synthetic native assignment',requestId:crypto.randomUUID()};
    const assignmentProof=await directProof(first,'POST','/api/assignments',assignmentDetails),beforeEffects=await effectCount(first)+await effectCount(second),scheduleRace=await Promise.all([request(first,'/api/assignments','POST',assignmentProof),request(second,'/api/assignments','POST',assignmentProof)]);
    assert.ok(scheduleRace.some(r=>r.status===201),JSON.stringify(scheduleRace));assert.ok(scheduleRace.every(r=>[201,409].includes(r.status)));assert.equal((await fixture.repository.load(A)).snapshot.assignments.length,2);assert.equal(await effectCount(first)+await effectCount(second)-beforeEffects,1);assert.equal((await request(second,'/api/assignments','POST',assignmentProof)).status,201);checks.push('two workers save one reviewed schedule and claim one assignment delivery; original replay never resends');
    await fixture.reset(workspaceSnapshot());token=await login(first);const lostSchedule=await directProof(first,'POST','/api/assignments',{...assignmentDetails,requestId:crypto.randomUUID()});await arm(second,'lose-ack');assert.equal((await request(second,'/api/assignments','POST',lostSchedule)).status,503);const beforeResume=await effectCount(first);assert.equal((await request(first,'/api/assignments','POST',lostSchedule)).status,201);assert.equal(await effectCount(first)-beforeResume,1);assert.equal((await fixture.repository.load(A)).snapshot.assignments.length,2);checks.push('lost initial schedule COMMIT ACK retains original receipt and queued delivery for guarded exact replay');
    await fixture.reset(workspaceSnapshot());token=await login(first);const noteProof=await directProof(first,'POST','/api/projects/101/notes-todos',{kind:'todo',text:'Synthetic native original note',requestId:crypto.randomUUID()});const createdNote=await request(second,'/api/projects/101/notes-todos','POST',noteProof);assert.equal(createdNote.status,201,JSON.stringify(createdNote));const noteId=createdNote.data.id,editProof=await directProof(first,'PATCH','/api/projects/101/notes-todos/'+noteId,{revision:1,text:'Synthetic native changed note'});await arm(second,'lose-ack');assert.equal((await request(second,'/api/projects/101/notes-todos/'+noteId,'PATCH',editProof)).status,503);await close(first);first=await start();assert.equal((await request(first,'/api/projects/101/notes-todos/'+noteId,'PATCH',editProof)).data.currentItem.revision,2);const completeProof=await directProof(first,'PATCH','/api/projects/101/notes-todos/'+noteId,{revision:2,completed:true});assert.equal((await request(second,'/api/projects/101/notes-todos/'+noteId,'PATCH',completeProof)).status,200);const originalNote=await request(first,'/api/projects/101/notes-todos/'+noteId,'PATCH',editProof);assert.equal(originalNote.data.revision,2);assert.equal(originalNote.data.currentItem.revision,3);assert.equal(originalNote.data.originalSaveResult,true);checks.push('note create/edit/complete receipts survive workers, restart and COMMIT ACK loss with explicit original versus current projection');
    await fixture.reset(workspaceSnapshot());token=await login(first,'field@example.invalid');const leaveInput={startDate:'2026-10-20',endDate:'2026-10-20',allDay:true,type:'vacation',note:'Synthetic native private note',requestId:crypto.randomUUID()},leaveProof=await directProof(first,'POST','/api/time-off-requests',leaveInput);await arm(second,'lose-ack');assert.equal((await request(second,'/api/time-off-requests','POST',leaveProof)).status,503);const recoveredLeave=await request(first,'/api/time-off-requests','POST',leaveProof);assert.equal(recoveredLeave.status,201);assert.equal((await fixture.repository.load(A)).snapshot.timeOffRequests.length,1);const ack=await directProof(first,'POST','/api/assignments/1/acknowledge',{memberId:12});assert.equal((await request(second,'/api/assignments/1/acknowledge','POST',ack)).status,200);assert.equal((await request(first,'/api/assignments/1/acknowledge','POST',ack)).data.originalSaveResult,true);checks.push('linked field leave and acknowledgement have native original-session exact-result recovery');
    await fixture.reset(workspaceSnapshot());token=await login(first,'field@example.invalid');await alter(db=>{db.timeOffRequests=[{id:crypto.randomUUID(),memberId:12,requestId:leaveInput.requestId,startDate:'2026-10-20',endDate:'2026-10-20',allDay:true,type:'vacation',note:'Legacy synthetic request',status:'pending',history:[]}];});assert.equal((await request(first,'/api/workspace-direct-preview','POST',{family:'timeOff',method:'POST',path:'/api/time-off-requests',details:leaveInput})).status,409);checks.push('legacy leave request identity without originating receipt fails closed instead of duplicating');
    await fixture.reset(workspaceSnapshot());token=await login(first);const revokeProof=await directProof(first,'POST','/api/projects/101/notes-todos',{kind:'note',text:'Synthetic restricted note',requestId:crypto.randomUUID()});await alter(db=>{db.users[0].role='project_manager';db.users[0].projectIds=[];db.users[0].assignedCrews=[];});assert.equal((await request(second,'/api/projects/101/notes-todos','POST',revokeProof)).status,409);assert.equal((await fixture.repository.load(A)).snapshot.projectNotesTodos.length,0);checks.push('current role/project change between preview and confirmation cannot reuse direct authority');
    await fixture.reset(workspaceSnapshot());token=await login(first);await alter(db=>{db.workspaceDirectReceipts=null;});assert.equal((await request(first,'/api/workspace-direct-preview','POST',{family:'notes',method:'POST',path:'/api/projects/101/notes-todos',details:{kind:'note',text:'Synthetic malformed custody',requestId:crypto.randomUUID()}})).status,409);checks.push('present falsy native custody cannot be overwritten as an absent ledger');
    await fixture.reset(workspaceSnapshot());token=await login(first);await alter(db=>{Object.assign(db.company,{stripeSubscriptionId:'sub_synthetic_one',stripeCustomerId:'cus_synthetic_one',billingExempt:false,subscriptionStatus:'Past due',founder:{requested:true,plan:'growth',billingCycle:'monthly',assistedSetup:true,termsVersion:'founder-2026-09-28'}});});const billing=await request(second,'/api/billing');assert.equal(billing.status,200,JSON.stringify(billing));assert.equal(billing.data.status,'Active');const billingDb=(await fixture.repository.load(A)).snapshot;assert.deepEqual(billingDb.workspaceBillingJobs[0].steps.map(s=>s.kind),['subscription','invoice','scheduleCreate','configurePhases']);assert.equal((await fixture.admin.query('SELECT count(*)::int AS n FROM public.compat_assisted_setup_receipts WHERE company_id=$1',[A])).rows[0].n,1);assert.equal((await fixture.admin.query('SELECT count(*)::int AS n FROM public.compat_billing_provider_facts WHERE company_id=$1',[A])).rows[0].n,4);checks.push('native immutable billing phase claims, observed facts and independent unique platform setup receipt');
    await fixture.admin.query('DELETE FROM public.compat_billing_provider_facts WHERE company_id=$1',[A]);await fixture.reset(workspaceSnapshot());token=await login(first);await alter(db=>{Object.assign(db.company,{stripeSubscriptionId:'sub_synthetic_two',stripeCustomerId:'cus_synthetic_two',billingExempt:false,subscriptionStatus:'Past due'});});await arm(second,'hold-effect');const providerHeld=event(second,'effect-held'),billingPending=request(second,'/api/billing');await providerHeld;await alter(db=>{db.users[0].status='Inactive';});second.send({event:'release-effect'});assert.equal((await billingPending).status,409);assert.equal((await fixture.repository.load(A)).snapshot.company.subscriptionStatus,'Past due');assert.equal((await fixture.admin.query('SELECT data->>\'status\' AS status FROM public.compat_billing_provider_facts WHERE company_id=$1',[A])).rows[0].status,'accepted');checks.push('native observed provider acceptance remains separate from revoked tenant-CAS ownership');
    await fixture.reset(workspaceSnapshot());token=await login(first);await alter(db=>{Object.assign(db.company,{stripeSubscriptionId:'sub_synthetic_recovery',stripeCustomerId:'cus_synthetic_recovery',billingExempt:false,subscriptionStatus:'Past due'});});await arm(second,'hold-effect');const observedHeld=event(second,'effect-held'),observedPending=request(second,'/api/billing');await observedHeld;await arm(second,'hold-commit');const observedCommitHeld=event(second,'commit-held');second.send({event:'release-effect'});await observedCommitHeld;await alter(db=>{db.company.trade='Synthetic unrelated revision retained';});second.send({event:'release-commit'});assert.equal((await observedPending).status,409);const beforeRecoveryEffects=await effectCount(second);const observedRead=await request(second,'/api/billing');assert.equal(observedRead.status,200,JSON.stringify(observedRead));assert.equal(observedRead.data.refresh.status,'unknown');assert.equal(observedRead.data.refresh.observed,'accepted');const originalRecovery={jobId:observedRead.data.refresh.jobId,confirmed:true};const recoveredBilling=await request(first,'/api/billing/recover','POST',originalRecovery);assert.equal(recoveredBilling.status,200,JSON.stringify(recoveredBilling));assert.equal(recoveredBilling.data.status,'Active');assert.equal(await effectCount(second),beforeRecoveryEffects);assert.equal((await fixture.repository.load(A)).snapshot.company.trade,'Synthetic unrelated revision retained');assert.equal((await fixture.repository.load(A)).snapshot.workspaceBillingJobs[0].steps[0].status,'accepted');checks.push('native provider acceptance survives receipt-CAS rollback and explicit original-owner recovery preserves the concurrent revision without resending');
    await fixture.reset(workspaceSnapshot());token=await login(first);await alter(db=>{db.subcontractors=[{id:51,companyId:A,name:'Synthetic Subcontractor',contact:'Synthetic Recipient',email:'synthetic@example.invalid',autoComplianceReminders:true}];});await arm(first,'hold-effect');const complianceHeld=event(first,'effect-held'),compliancePending=request(first,'/api/workspace-prepare');await complianceHeld;await alter(db=>{db.subcontractors[0].email='changed@example.invalid';});first.send({event:'release-effect'});assert.equal((await compliancePending).status,409);assert.equal((await fixture.repository.load(A)).snapshot.workspaceComplianceJobs[0].status,'sending');assert.equal((await fixture.repository.load(A)).snapshot.subcontractors[0].complianceReminderStages,undefined);const sends=await effectCount(first);assert.equal((await request(first,'/api/workspace-prepare')).status,200);assert.equal(await effectCount(first),sends);checks.push('native changed compliance recipient leaves uncertain claimed outcome and never automatically re-sends');
    assert.deepEqual(fs.readFileSync(file),original);console.log(JSON.stringify({nativeWorkspace:checks,passed:checks.length,workers:2,productionReady:false}));
  } finally { for(const child of workers)await close(child);await fixture.close(); }
}
main().catch(error=>{console.error(error);process.exitCode=1;});
