'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('app.js','utf8');function code(name){const lines=source.split('\n'),start=lines.findIndex(line=>(line.startsWith(`function ${name}(`)||line.startsWith(`async function ${name}(`)));assert.ok(start>=0,name);if(lines[start].trimEnd().endsWith('}'))return lines[start];const end=lines.findIndex((l,i)=>i>start&&l.trimEnd()==='}');return lines.slice(start,end+1).join('\n')}
const nodes=new Map();function node(key){if(!nodes.has(key))nodes.set(key,{dataset:{},hidden:false,checked:false,disabled:false,textContent:'',innerHTML:'',classList:{toggle(){},add(){},contains(){return false}},setAttribute(){},querySelector:part=>node(key+' '+part)});return nodes.get(key)}
let boxes=[];const context={$:node,$$:selector=>selector==='.time-manager-only'?[node('#time-nav'),node('#mutation-only')]:selector==='[data-timecard-pick]:not(:disabled)'?boxes.filter(b=>!b.disabled):selector==='[data-timecard-pick]:checked'?boxes.filter(b=>b.checked):selector==='[data-timecard-pick]'?boxes:[],currentRole:'office',currentUser:{id:1,role:'project_manager',permissions:{viewTime:true}},company:{features:{timeCards:true}},document:{body:{classList:{toggle(){}}}},team:[{id:1,name:'<img src=x>',crew:'Allowed',role:'Worker'},{id:2,name:'Hidden Person',crew:'Other'}],projects:[{id:1,name:'Project <script>',code:'QA'}],timeCards:[],timeOffRequests:[],scheduleAvailability:[],scheduleAvailabilityStatus:'ready',scheduleView:'week',interfaceLocale:()=> 'en-US',window:{PDLScheduleAvailability:require('./schedule-availability')},assignments:[{id:10,projectId:1,date:'2026-10-05',start:'07:00',end:'15:00',memberIds:[1],crew:'Allowed',activity:'Work <script>'},{id:11,projectId:1,date:'2026-10-05',start:'07:00',end:'15:00',memberIds:[2],crew:'Other',activity:'Hidden assignment'}],fillTimeCardFilters(){},filteredTimeCards:()=>context.timeCards,timeCardFilters:()=>({}),timeCardClock:()=> '7:00 AM',formatDate:value=>value,localDateIso:()=> '2026-10-05',displayTime:value=>value,renderTimeOverview(){}};
vm.createContext(context);for(const name of ['escapeHtml','canManageTime','canViewTime','canManageSchedule','applyTimeAccess','renderTimeOff','openAssignment','editScheduledWork','moveScheduledWork','addAssignmentDay','removeScheduledWork','timeCardsOn','timeCardOffice','timeCardApproved','timeCardRowMarkup','updateTimeCardSelection','renderTimeCards','scheduleUnavailable','timeOffHoursLabel','scheduleLeaveRanges','scheduleLeaveConflict','scheduleLeaveMarkup','scheduleDayLeaveMarkup','scheduleUnavailableSummary','scheduleMobileMarkup'])vm.runInContext(code(name),context);
const closed={id:1,memberId:1,projectId:1,date:'2026-10-05',inAt:'2026-10-05T07:00:00Z',outAt:'2026-10-05T15:00:00Z',hours:8,status:'submitted',historyLines:['<script>old</script>']};context.timeCards=[closed];context.renderTimeCards();assert.equal(node('#timecard-add').hidden,true,'view-only manager cannot add');assert.equal(node('#timecard-office-actions').hidden,true);assert.equal(node('#timecard-export').hidden,false,'authorized scoped export stays available');assert.ok(!node('#timecard-rows').innerHTML.includes('data-timecard-approve'));assert.match(node('#timecard-rows').innerHTML,/View only/);assert.ok(!node('#timecard-rows').innerHTML.includes('<script>'));
context.currentUser.permissions.manageTime=true;context.renderTimeCards();assert.equal(node('#timecard-add').hidden,false);assert.match(node('#timecard-rows').innerHTML,/data-timecard-approve/);
const approved=context.timeCardRowMarkup({...closed,status:'approved'},true,true);assert.match(approved,/Return to Draft/);assert.ok(!approved.includes('data-timecard-edit'));assert.ok(!approved.includes('data-timecard-delete'));assert.ok(!context.timeCardRowMarkup({...closed,status:'draft',outAt:null},true,true).includes('data-timecard-submit'),'running clock cannot submit');assert.match(context.timeCardRowMarkup({...closed,status:'draft'},false,false),/data-timecard-submit/);assert.ok(!context.timeCardRowMarkup(closed,false,false).includes('data-timecard-approve'));
boxes=[{checked:false,disabled:false},{checked:false,disabled:false},{checked:false,disabled:true}];context.updateTimeCardSelection();assert.equal(node('#timecard-bulk-approve').disabled,true);vm.runInContext(source.match(/^\$\('#timecard-check-all'\)\.onclick=[^\r\n]+/m)[0],context);vm.runInContext(source.match(/^\$\('#timecard-toggle-selection'\)\.onclick=[^\r\n]+/m)[0],context);node('#timecard-toggle-selection').onclick();assert.equal(boxes[2].checked,false);assert.equal(node('#timecard-bulk-approve').disabled,false,'select-all enables approval');assert.equal(node('#timecard-bulk-approve').textContent,'Approve selected (2)');assert.equal(node('#timecard-toggle-selection').textContent,'Clear selection');node('#timecard-toggle-selection').onclick();assert.equal(node('#timecard-bulk-approve').disabled,true);boxes[0].checked=true;context.updateTimeCardSelection();assert.equal(node('#timecard-check-all').indeterminate,true);
context.currentUser.permissions.scheduleCrews=true;const agenda=context.scheduleMobileMarkup([{date:'2026-10-05'}],[context.team[0]]);assert.match(agenda,/data-assignment="10"/);assert.ok(!agenda.includes('data-assignment="11"'));assert.ok(!agenda.includes('Hidden Person'));assert.ok(!agenda.includes('<script>'));assert.match(agenda,/data-agenda-date="2026-10-05"/);
node('#time-nav').dataset.page='timeoverview';context.currentUser.permissions.manageTime=false;context.applyTimeAccess();assert.equal(node('#time-nav').hidden,false,'viewTime manager has visible Time navigation');assert.equal(node('#mutation-only').hidden,true,'viewTime does not expose mutation-only controls');
context.timeOffRequests=[{id:1,memberId:1,status:'pending',startDate:'2026-10-05',endDate:'2026-10-05',type:'vacation'}];context.renderTimeOff();assert.ok(!node('#time-office-timeoff-list').innerHTML.includes('data-time-off-approve'),'viewTime does not offer leave approval');context.currentUser.permissions.manageTime=true;context.renderTimeOff();assert.match(node('#time-office-timeoff-list').innerHTML,/data-time-off-approve/);
context.currentUser.permissions.scheduleCrews=false;const readonlyAgenda=context.scheduleMobileMarkup([{date:'2026-10-05'}],[context.team[0]]);assert.match(readonlyAgenda,/View assignment/);assert.ok(!readonlyAgenda.includes('data-agenda-date'),'read-only schedule has no add-work controls');
context.openAssignment();context.editScheduledWork();void context.moveScheduledWork(1,'2026-10-05');void context.addAssignmentDay();void context.removeScheduledWork(false);
context.currentUser.permissions.manageTime=false;context.currentUser.permissions.viewTime=false;context.applyTimeAccess();assert.equal(node('#time-nav').hidden,true,'manager without viewTime cannot discover private time');context.currentUser.permissions.viewTime=true;
context.currentUser.permissions.manageTime=false;context.showPage=page=>{context.openedPage=page};context.defaultPage=()=> 'dashboard';context.renderTimeOverview=()=>{};vm.runInContext(source.match(/const showPageWithoutTimeCards=showPage;[\s\S]*?showPage=function[^\r\n]+/)[0],context);context.showPage('timecards');assert.equal(context.openedPage,'timecards','view-only manager can open assigned time');context.currentUser.permissions.viewTime=false;context.showPage('timecards');assert.equal(context.openedPage,'dashboard','unauthorized time remains blocked');
assert.match(source,/save\.disabled=true;save\.textContent='Saving assignment…';try\{if\(editingAssignmentId\)/);assert.match(source,/finally\{save\.disabled=false;save\.textContent=previousLabel\}/);const styles=fs.readFileSync('styles.css','utf8');assert.match(styles,/@media\(max-width:760px\).*schedule-mobile-agenda\{display:grid/s);assert.match(styles,/#timecards-page \.timecard-record td:before\{content:attr\(data-label\)/);const index=fs.readFileSync('index.html','utf8');assert.match(index,/Choose both projects and crews/);assert.match(index,/app.js\?v=20261005-partial-day-leave/);
console.log('Core UX regression passed: read-only PM access, restricted actions, approved correction flow, running clocks, escaped/scoped phone agenda, bulk selection and responsive labels (VM/static; real visual QA pending).');

context.scheduleView='month';context.preferredLanguage='en';context.scheduleDate=value=>new Date((value||'2026-10-05')+'T12:00:00');context.scheduleWeekStart=()=>context.scheduleDate();context.schedulePeriodDays=()=>[{date:'2026-10-05',label:'5'}];context.isOfficeMember=()=>false;context.assignmentActualHours=()=>0;context.shiftHours=()=>8;context.window={PDLScheduleAvailability:require('./schedule-availability')};context.currentUser={role:'owner'};vm.runInContext(code('renderSchedule'),context);context.renderSchedule();assert.match(node('#schedule-board').innerHTML,/schedule-mobile-agenda/,'month also provides phone agenda');assert.match(node('#schedule-board').innerHTML,/schedule-month/,'desktop month grid retained');assert.match(styles,/#schedule-board \.schedule-grid,#schedule-board \.schedule-month\{display:none/,'wide grids hidden in phone rules');
