'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
function harness(){const elements=new Map(),requests=[],notices=[];let delegates=0,pages=[];
  function node(){return {value:'',textContent:'',files:[],children:[],open:false,hidden:false,disabled:false,dataset:{},listeners:{},style:{maxWidth:'',setProperty(){},removeProperty(){}},classList:{toggle(){}},append(...rows){this.children.push(...rows);for(const row of rows)if(row.id)elements.set('#'+row.id,row)},replaceChildren(...rows){this.children=[];this.append(...rows)},querySelector(selector){return element('hero:'+selector)},setAttribute(){},toggleAttribute(name,value){if(name==='hidden')this.hidden=value},addEventListener(event,fn){this.listeners[event]=fn},showModal(){this.open=true},close(){this.open=false;this.listeners.close?.()},remove(){}}}
  function element(id){if(!elements.has(id))elements.set(id,node());return elements.get(id)}
  const context={document:{createElement:node,body:{classList:{toggle(){}}}},$:element,$$:()=>[],currentUser:{id:2,memberId:11,role:'field',fieldAccessMode:'time_schedule_photos'},company:{id:'synthetic',features:{timeCards:true}},location:{origin:'http://local'},signedInCompanyId:()=>context.company.id,projects:[{id:101,name:'<script>hostile</script>'}],assignments:[{id:1,projectId:101,memberIds:[11],date:'2026-10-07',start:'07:00',end:'15:00',activity:'<img src=x onerror=bad>'}],timeCards:[],URL,companyTodayIso:()=> '2026-10-07',timeCardsOn:()=>true,crypto,fileAsData:async file=>file.data,renderMyDay:()=>{delegates++},showPage:page=>pages.push(page),loadRole:async()=>{},refreshTimeCards:async()=>{},openReport:()=>{delegates++},openProject:()=>{delegates++},notify:msg=>notices.push(msg),api:async(route,options)=>{requests.push({route,options});return context.response(route,options)},response:async()=>[]};
  vm.createContext(context);vm.runInContext(fs.readFileSync(__dirname+'/crew-field-ui.js','utf8'),context);return {context,element,requests,notices,pages,delegates:()=>delegates};
}
(async()=>{
  let h=harness();h.context.renderMyDay();assert.equal(h.delegates(),0,'restricted renderer never runs daily renderer or instructions');assert.equal(h.element('hero:h2').textContent,'Clock in');assert.equal(h.element('#crew-jobs-panel').children[1].textContent,'View / upload photos — <script>hostile</script>');h.context.showPage('reports');h.context.showPage('fieldday');h.context.showPage('timecards');assert.deepEqual(h.pages,['myday','myday','timecards']);h.context.openReport();h.context.openProject(101);assert.equal(h.delegates(),0);
  h.context.currentUser.fieldAccessMode='standard';h.context.renderMyDay();h.context.openReport();assert.equal(h.delegates(),2,'standard field functionality retained');h.context.currentUser.fieldAccessMode='time_schedule_photos';
  assert.equal(h.context.crewSafePhotoUrl('javascript:alert(1)'),'');assert.equal(h.context.crewSafePhotoUrl('https://user:password@example.invalid/x.png'),'');assert.equal(h.context.crewSafePhotoUrl('/uploads/image.png'),'/api/local-files/image.png');
  await h.context.openCrewPhotos(101);assert(h.element('#crew-photo-modal').open);assert.equal(h.requests[0].route,'/api/crew/photos?projectId=101');assert.equal(h.element('#crew-photo-title').textContent,'Job photos — <script>hostile</script>');
  const file={type:'image/png',size:10,data:'data:image/png;base64,YWJj'};h.element('#crew-photo-files').files=[file];let release;h.context.fileAsData=()=>new Promise(resolve=>release=resolve);const pending=h.element('#crew-photo-upload').onclick();await h.element('#crew-photo-upload').onclick();h.context.company.id='other-tenant';release(file.data);await pending;assert.equal(h.requests.length,1,'tenant change during byte preparation prevents writes');assert.equal(h.element('#crew-photo-upload').disabled,false);
  h=harness();await h.context.openCrewPhotos(101);h.element('#crew-photo-files').files=[file];h.context.response=async(route,options)=>{if(options)throw Error('Synthetic provider failure');return []};await h.element('#crew-photo-upload').onclick();assert.equal(h.element('#crew-photo-files').files[0],file);assert(h.element('#crew-photo-message').textContent.includes('retained'));const first=JSON.parse(h.requests[1].options.body);h.context.response=async()=>[];await h.element('#crew-photo-upload').onclick();const second=JSON.parse(h.requests[2].options.body);assert.equal(first.files[0].uploadId,second.files[0].uploadId,'retry reuses immutable upload identity');assert.equal(second.projectId,101);assert.deepEqual(Object.keys(second).sort(),['files','projectId']);assert.equal(h.element('#crew-photo-files').value,'');assert(h.requests.every(row=>!row.route.includes('reports')&&!row.route.includes('/api/photos')));
  h=harness();await h.context.openCrewPhotos(101);h.element('#crew-photo-files').files=[file];let mutation;h.context.response=(route,options)=>options?new Promise(resolve=>mutation=resolve):Promise.resolve([]);const busy=h.element('#crew-photo-upload').onclick();await new Promise(resolve=>setImmediate(resolve));await h.element('#crew-photo-upload').onclick();assert.equal(h.requests.length,2,'single upload while pending');h.element('#crew-photo-modal').close();mutation([]);await busy;assert.equal(h.requests.length,2,'closed viewer gets no stale gallery refresh');assert.equal(h.element('#crew-photo-list').children.length,0);
  h=harness();h.element('#crew-clock-project').value='101';await h.context.crewClock('in');assert.equal(h.requests[0].route,'/api/crew/clock-in');assert.deepEqual(JSON.parse(h.requests[0].options.body),{projectId:101});await h.context.crewClock('out',{id:7,fieldAccess:{revision:'synthetic-revision'}});assert.equal(h.requests[1].route,'/api/time-cards/7/clock-out');assert.deepEqual(JSON.parse(h.requests[1].options.body),{revision:'synthetic-revision'});
  console.log('Restricted crew UI behavior passed: daily routes/rendering blocked, standard field retained, safe text/images, own clock actions, explicit assigned photo flow, stable retries, duplicate and stale scope/close protection.');
})().catch(error=>{console.error(error);process.exitCode=1});
