'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {File}=require('node:buffer'),{indexedDB}=require('fake-indexeddb');
const {PhotoStore}=require('./daily-photo-store');
function storage(){const map=new Map();return{getItem:key=>map.get(key)||null,setItem:(key,value)=>map.set(key,value),removeItem:key=>map.delete(key)}}
function element(){return {value:'',dataset:{},files:[],open:false,disabled:false,textContent:'',children:[],parentElement:{last:null,querySelector(){return this.last},append(item){this.last=item}},listeners:{},addEventListener(name,fn){(this.listeners[name]||=[]).push(fn)},close(){this.open=false;(this.listeners.close||[]).forEach(fn=>fn())},replaceChildren(){this.children=[]},append(...children){this.children.push(...children)}}}
const savedStorage=storage();
function context(){
 const nodes=new Map(),node=key=>{if(!nodes.has(key))nodes.set(key,element());return nodes.get(key)};
 class Transfer{constructor(){this.files=[];this.items={add:file=>this.files.push(file)}}}
 const ctx={$:node,$$:()=>[node('#report-safety'),node('#report-next')],window:{indexedDB},PDLDailyPhotoStore:{PhotoStore},crypto:require('node:crypto').webcrypto,File,DataTransfer:Transfer,document:{createElement:element},localStorage:savedStorage,projects:[{id:101}],company:{id:'fictional-tenant'},currentUser:{id:11,memberId:11},signedInCompanyId:()=>ctx.company.id,currentRole:'office',assignments:[],reports:[],photos:[],workdays:[{id:1,projectId:101,memberIds:[11],status:'active'}],preferredLanguage:'en',editingReportId:null,reportAnalyzeSequence:0,extractedDraft:null,
  notify:message=>ctx.messages.push(message),messages:[],rememberActiveReport:()=>{},renderWorkdays:()=>ctx.events.push('render-clock'),renderMyDay:()=>{},renderReports:()=>{},showPage:()=>{},showReportMessage:message=>ctx.messages.push(message),events:[],
  encodeFiles:async files=>Array.from(files).map(file=>({name:file.name,type:file.type})),
  openEndDay:id=>{node('#end-day-id').value=id;node('#end-day-notes').value='';node('#end-day-next').value='';node('#end-day-modal').open=true},
  openReport:report=>{ctx.editingReportId=report.id;node('#report-modal').open=true;node('#field-notes').value=report.notes;node('#report-photos').files=[];node('#report-safety').value=report.safety;node('#report-project').value=0},
  saveDailyReport:async()=>{},openProjectPhoto:()=>{},openAssignment:()=>{},canManageSchedule:()=>true,loadRole:async()=>{},companyTodayIso:()=> '2026-10-06'};
 node('#ai-convert').onclick=async()=>{ctx.events.push('analyze');assert.equal(ctx.workdays[0].status,'complete','analysis must run after clock-out');node('#report-safety').value='Editable safety proposal';node('#report-next').value='AI next proposal';return true};
 node('#save-photos').onclick=async()=>{};node('#logout-button').onclick=async()=>{ctx.currentUser={id:99,memberId:99}};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync('daily-flow-ui.js','utf8'),ctx);return {ctx,node};
}
(async()=>{
 const first=context();first.ctx.openEndDay(1);first.node('#end-day-notes').value='Fictional work. Safety concern: opening.';first.node('#end-day-next').value='Bring guards';first.ctx.rememberEndDay();
 first.ctx.openEndDay(1);assert.equal(first.node('#end-day-notes').value,'Fictional work. Safety concern: opening.');assert.equal(first.node('#end-day-next').value,'Bring guards');
 first.ctx.openProjectPhoto(0,{workdayId:1});first.node('#photo-caption').value='Fictional incremental photo note';first.node('#photo-tags').value='progress';first.ctx.rememberProgressPhotoNotes();
 const file=new File(['synthetic bytes'],'fictional.jpg',{type:'image/jpeg',lastModified:1234}),input=first.node('#end-day-photos'),key=first.ctx.dailyPhotoKey('end',1);
 input.files=[file];await first.ctx.stageDailyPhotos(input,key);
 const refreshed=context();await refreshed.ctx.loadRole('office');await refreshed.ctx.restoreDailyPhotos(refreshed.node('#end-day-photos'),key);
 refreshed.ctx.openProjectPhoto(0,{workdayId:1});assert.equal(refreshed.node('#photo-caption').value,'Fictional incremental photo note');assert.equal(refreshed.node('#photo-tags').value,'progress');
 assert.equal(refreshed.node('#end-day-notes').value,'Fictional work. Safety concern: opening.');assert.equal(refreshed.node('#end-day-photos').files[0].name,'fictional.jpg');assert.equal(await refreshed.node('#end-day-photos').files[0].text(),'synthetic bytes');
 let calls=0;refreshed.ctx.api=async()=>{calls++;if(calls===1)throw Error('Synthetic lost response');return{workday:{id:1,projectId:101,memberIds:[11],status:'complete',reportId:10,endedAt:'2026-10-06T23:00:00Z'},report:{id:10,project:0,workdayId:1,status:'Draft',notes:'Fictional work. Safety concern: opening.',safety:'opening'}}};
 await refreshed.ctx.endDayWithRecovery();assert.equal(refreshed.ctx.workdays[0].status,'active');assert.ok(savedStorage.getItem(refreshed.ctx.dailyEndKey(1)),'unconfirmed end keeps recovery marker');
 await refreshed.ctx.endDayWithRecovery();assert.equal(refreshed.ctx.workdays[0].status,'complete');assert.equal(refreshed.ctx.reports.length,1);assert.equal(refreshed.node('#report-modal').open,true);assert.equal(refreshed.node('#report-photos').files.length,1);assert.equal(refreshed.node('#report-next').value,'Bring guards');assert.equal(refreshed.node('#report-safety').value,'Editable safety proposal');assert.deepEqual(refreshed.ctx.events,['render-clock','analyze']);
 assert.equal(savedStorage.getItem(refreshed.ctx.dailyEndKey(1)),null,'end marker clears only after files move durably to report');
 const reportKey=refreshed.ctx.dailyReportPhotoKey();assert.equal((await new PhotoStore(indexedDB).get(reportKey)).length,1,'review photos survive another refresh before upload');
 // Adversarial recovery: identities, quota errors, deletion ordering and stale callbacks.
 const edge=context(),photo=edge.node('#report-photos');edge.node('#report-project').value=0;edge.node('#report-date').value='2026-10-06';
 const edgeKey=edge.ctx.dailyReportPhotoKey();edge.node('#report-date').value='2026-10-07';assert.notEqual(edge.ctx.dailyReportPhotoKey(),edgeKey);edge.ctx.currentUser.id=77;assert.notEqual(edge.ctx.dailyReportPhotoKey(),edgeKey);edge.ctx.currentUser.id=11;edge.node('#report-date').value='2026-10-06';
 const sameName=new File(['other bytes'],'fictional.jpg',{type:'image/jpeg',lastModified:1234});photo.files=[file,sameName];await edge.ctx.stageDailyPhotos(photo,edgeKey);assert.equal(photo.files.length,2,'metadata equality must not drop distinct selections');
 await edge.ctx.restoreDailyPhotos(photo,edgeKey);const list=photo.parentElement.last;
 photo.files=[new File(['third'],'third.jpg',{type:'image/jpeg'})];const staging=edge.ctx.stageDailyPhotos(photo,edgeKey);await list.children[0].children[1].onclick();await staging;await edge.ctx.dailyPhotoReady(photo,edgeKey);assert.equal(photo.files.length,2,'removal waits behind older staging');assert.equal(photo.files.some(row=>row===file),false);
 const unavailable=context();vm.runInContext('dailyPhotoStore.put=async()=>{throw Error("Synthetic quota exceeded")}',unavailable.ctx);const unavailableInput=unavailable.node('#report-photos'),unavailableKey=unavailable.ctx.dailyReportPhotoKey();unavailableInput.files=[file];await assert.rejects(unavailable.ctx.stageDailyPhotos(unavailableInput,unavailableKey),/quota/);assert.equal((await unavailable.ctx.dailyPhotoReady(unavailableInput,unavailableKey)).length,1);assert.ok(unavailable.ctx.messages.some(row=>row.includes('quota')));
 const pending=context();pending.ctx.openEndDay(1);pending.node('#end-day-notes').value='Safety: unguarded opening.';pending.ctx.rememberEndDay();pending.ctx.workdays[0].status='complete';let resolveAnalysis;pending.node('#ai-convert').onclick=()=>new Promise(resolve=>resolveAnalysis=resolve);
 const reviewing=pending.ctx.openEndedDayReview({workday:{id:1},report:{id:44,status:'Draft',notes:'Safety: unguarded opening.'}});for(let i=0;i<20&&!resolveAnalysis;i++)await new Promise(resolve=>setImmediate(resolve));assert.ok(resolveAnalysis);assert.equal(pending.node('#report-safety').disabled,true);pending.node('#report-modal').close();assert.equal(pending.node('#report-safety').disabled,false,'closing pending analysis restores controls');pending.ctx.openReport({id:45,status:'Draft',notes:'Other report'});pending.node('#report-next').value='Other report next';resolveAnalysis(true);await reviewing;assert.equal(pending.node('#report-next').value,'Other report next','late review must not alter another report');
 const logout=context(),logoutInput=logout.node('#report-photos'),logoutKey=logout.ctx.dailyReportPhotoKey();let resolveRead;vm.runInContext('dailyPhotoStore.get=()=>new Promise(resolve=>{globalThis.resolvePhotoRead=resolve})',logout.ctx);const restoring=logout.ctx.restoreDailyPhotos(logoutInput,logoutKey);await logout.node('#logout-button').onclick();logout.ctx.resolvePhotoRead([{file,uploadId:'late'}]);await restoring;assert.equal(logoutInput.files.length,0,'late old-session restore remains invisible');
 console.log('Daily flow UI passed: notes survive reopen, photo bytes survive refresh, failed clock-out confirmation retains recovery, clock updates before analysis, editable safety/next review and durable photo transfer.');
})().catch(error=>{console.error(error);process.exitCode=1});
