'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'pdl-daily-work-')),companyId='11221122-1122-4122-8122-112211221122',token='synthetic-daily-work-session';
const db={company:{id:companyId,name:'Synthetic daily work',demo:true,timezone:'UTC',features:{timeCards:true}},projects:[{id:101,name:'Synthetic flooring job',estimateItems:[{id:1,name:'Flooring',plannedQuantity:100,unit:'SF',budgetHours:null}]}],team:[{id:11,name:'Synthetic worker',crew:'A'}],assignments:[],reports:[],photos:[],workdays:[],timeCards:[],users:[{id:1,name:'Synthetic owner',role:'owner',status:'Active',companyId}],sessions:[{companyId,userId:1,tokenHash:crypto.createHash('sha256').update(token).digest('hex'),expiresAt:'2099-01-01'}],customers:[],changes:[],catalog:[]};
const file=path.join(root,'db.json');fs.writeFileSync(file,JSON.stringify(db));fs.writeFileSync(path.join(root,'platform.json'),JSON.stringify({users:[],sessions:[]}));
Object.assign(process.env,{PDL_DB_FILE:file,PDL_PLATFORM_FILE:path.join(root,'platform.json'),PDL_REQUIRE_AUTH:'1',PDL_SUPABASE_ENABLED:'0',PDL_TRANSACTIONAL_DB:'off',PDL_EMAIL_DEV_MODE:'1'});for(const name of ['OPENAI_API_KEY','SENTRY_DSN','RESEND_API_KEY','STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET'])delete process.env[name];require('./database/supabase').loadLocalEnv=()=>{};
const {server}=require('./server'),nativeFetch=global.fetch;let base,mode='local',providerRequests=[];
global.fetch=async(url,options)=>{if(String(url).startsWith(base+'/'))return nativeFetch(url,options);assert.equal(String(url),'https://api.openai.com/v1/responses');providerRequests.push(JSON.parse(options.body));if(mode==='http-error')return {ok:false,status:503};if(mode==='malformed')return {ok:true,json:async()=>({output:[{content:[{type:'output_text',text:'invalid synthetic JSON'}]}]})};const productions=mode==='partial'?[{description:'Bathroom tile',evidence:'added three more tiles to the bathroom',quantity:3,unit:'EA',laborHours:8}]:[];return {ok:true,json:async()=>({output:[{content:[{type:'output_text',text:JSON.stringify({summary:'Synthetic provider draft',productions,originalLanguage:'en',englishTranslation:notes,labor:'',next:'',safety:'',customFieldSuggestions:[]})}]}]})}};
const notes='started on the stairs, added three more tiles to the bathroom, cleaned the upstairs and sweeper the main big bedroom up there and measured the trim for the main floor';
async function call(method,route,input){const response=await fetch(base+route,{method,signal:AbortSignal.timeout(10000),headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','x-pdl-company':companyId},...(input?{body:JSON.stringify(input)}:{})});return {status:response.status,data:await response.json()}}
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port;try{
 for(mode of ['local','empty','partial','http-error','malformed']){if(mode==='local')delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY='synthetic-provider-mock';const result=await call('POST','/api/ai/extract',{notes,estimateItems:[{id:1,name:'Flooring',unit:'SF'}]});assert.equal(result.status,200);assert.equal(result.data.productions.length,5,mode);assert(result.data.productions.every(row=>row.laborHours===0&&row.needsScopeConfirmation&&row.needsLaborConfirmation),mode);assert.equal(result.data.productions.find(row=>/tile/i.test(row.description)).quantity,3,mode);assert.equal(result.data.laborEvidence,null);assert(Array.isArray(result.data.safetyItems));assert.equal(result.data.next,'Needs confirmation');}
 assert(providerRequests.every(row=>row.instructions.includes('Flooring')));assert.deepEqual(providerRequests[0].text.format.schema.properties.productions.items.properties.quantity.type,['number','null']);
 delete process.env.OPENAI_API_KEY;const suggestions=(await call('POST','/api/ai/extract',{notes})).data.productions;
 const workday=await call('POST','/api/workdays/start',{projectId:101,memberIds:[11]});assert.equal(workday.status,201);mode='empty';process.env.OPENAI_API_KEY='synthetic-provider-mock';const beforeEndCalls=providerRequests.length,end=await call('POST','/api/workdays/'+workday.data.id+'/end',{notes});assert.equal(end.status,200);assert.equal(providerRequests.length,beforeEndCalls,'clock-out persistence stays independent from provider');assert.equal(end.data.report.workSuggestions.length,5);assert.equal(end.data.report.productionEntries.length,0);assert.equal(end.data.report.notes,notes);delete process.env.OPENAI_API_KEY;
 const created=await call('POST','/api/reports',{projectId:101,dateIso:'2026-10-05',status:'Draft',notes,workSuggestions:suggestions,productionEntries:[],laborEntries:[{memberId:11,hours:6.61}]});assert.equal(created.status,201);assert.equal(created.data.workSuggestions.length,5);assert.equal(created.data.flags.length,0,'unconfirmed scope is not declared extra');
 const state=await call('GET','/api/state'),saved=state.data.reports.find(row=>row.id===created.data.id);assert.equal(saved.workSuggestions[0].quantity,null);assert.equal(saved.workSuggestions[1].quantity,3);assert.equal(saved.notes,notes);
 const updated=await call('PATCH','/api/reports/'+created.data.id,{status:'Draft',notes,workSuggestions:suggestions,laborEntries:[{memberId:11,hours:6.61}],productionEntries:[]});assert.equal(updated.status,200);assert.equal(updated.data.workSuggestions.length,5);
 const rejected=await call('PATCH','/api/reports/'+created.data.id,{status:'Needs review',notes,laborEntries:[{memberId:11,hours:6.61}],productionEntries:[]});assert.equal(rejected.status,400,'allocation remains enforced');
 const reviewed=await call('PATCH','/api/reports/'+created.data.id,{status:'Needs review',notes,workSuggestions:suggestions,laborEntries:[{memberId:11,hours:6.61}],productionEntries:[{estimateItemId:1,description:'Flooring',quantity:0,unit:'SF',laborHours:5,quantityPending:true},{estimateItemId:null,description:'Confirmed custom tile repair',quantity:3,unit:'EA',laborHours:1.61,unplanned:true}]});assert.equal(reviewed.status,200);assert.equal(reviewed.data.workSuggestions,undefined);assert.equal(reviewed.data.flags[0].type,'unplanned_work');const stored=JSON.parse(fs.readFileSync(file));assert.equal(stored.changes.length,0,'daily suggestion never creates a priced change');assert.equal(stored.projects[0].estimateItems.length,1);
 console.log('Daily work API: no-key, empty/partial provider and failure normalization; nullable schema/context; Draft round-trip; allocation rejection and explicit custom review passed with intercepted provider transport.');
}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));global.fetch=nativeFetch;fs.rmSync(root,{recursive:true,force:true})}})().catch(error=>{console.error(error);process.exitCode=1;server.close()});
