'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('app.js','utf8'),html=fs.readFileSync('index.html','utf8');
const begin=source.indexOf('let pendingEmployeeArchive='),end=source.indexOf('\nfunction renderTeamDirectory()',begin);assert.ok(begin>=0&&end>begin);
assert.match(html,/<dialog id="employee-archive-modal" aria-labelledby="employee-archive-title" aria-describedby="employee-archive-copy">/);assert.match(html,/id="employee-archive-confirm" class="primary" type="button"/);assert.doesNotMatch(source.slice(begin,end),/\bconfirm\(/);
const nodes=new Map(),events={},requests=[];let notifications=[];
function node(key){if(!nodes.has(key))nodes.set(key,{open:false,disabled:false,hidden:false,dataset:{},textContent:'',listeners:{},focus(){this.focused=true},addEventListener(event,callback){this.listeners[event]=callback},showModal(){this.open=true},close(result){this.open=false;this.returnValue=result;this.listeners.close?.()}});return nodes.get(key)}
const context={$:node,$$:()=>['#employee-archive-confirm','#employee-archive-cancel','#employee-archive-back'].map(node),EmployeeRoster:require('./employee-roster'),team:[{id:10,name:'Synthetic Jeremy',archiveVersion:0}],currentUser:{id:1,role:'owner'},companyId:'synthetic-company',signedInCompanyId:()=>context.companyId,canManageEmployeeRoster:()=>['owner','admin'].includes(context.currentUser.role),window:{addEventListener(event,callback){events[event]=callback}},renderTeam(){},renderSchedule(){},notify(message){notifications.push(message)},async api(route,options){requests.push({route,body:JSON.parse(options.body)});return{id:10,name:'Synthetic Jeremy',archived:JSON.parse(options.body).archived,archiveVersion:JSON.parse(options.body).expectedVersion+1}}};
vm.createContext(context);vm.runInContext(source.slice(begin,end),context);
(async()=>{
 context.setEmployeeArchive(10);assert.equal(requests.length,0,'opening never submits');assert.equal(node('#employee-archive-modal').open,true);assert.equal(node('#employee-archive-cancel').focused,true);assert.match(node('#employee-archive-copy').textContent,/history will stay available/);
 node('#employee-archive-modal').close('cancel');await node('#employee-archive-confirm').onclick();assert.equal(requests.length,0,'Cancel clears operation');
 context.setEmployeeArchive(10);events.popstate();await node('#employee-archive-confirm').onclick();assert.equal(requests.length,0,'Back clears operation');
 context.setEmployeeArchive(10);context.team[0].archiveVersion=7;await node('#employee-archive-confirm').onclick();assert.equal(requests[0].body.expectedVersion,0,'confirmation uses originally reviewed version');assert.equal(context.team[0].archived,true);assert.equal(node('#employee-archive-modal').open,false);
 context.setEmployeeArchive(10);assert.match(node('#employee-archive-title').textContent,/Restore/);assert.equal(node('#employee-archive-confirm').textContent,'Restore employee');await node('#employee-archive-confirm').onclick();assert.equal(context.team[0].archived,false);
 context.setEmployeeArchive(10);context.currentUser.role='field';await node('#employee-archive-confirm').onclick();assert.equal(requests.length,2);assert.equal(node('#employee-archive-confirm').disabled,true);assert.match(node('#employee-archive-message').textContent,/account or workspace changed/);node('#employee-archive-modal').close('cancel');context.currentUser.role='owner';
 context.api=async()=>{requests.push('stale');const error=new Error('Refresh and review');error.status=409;error.code='employee_archive_stale';throw error};context.setEmployeeArchive(10);await node('#employee-archive-confirm').onclick();assert.equal(node('#employee-archive-modal').open,true);assert.equal(node('#employee-archive-message').hidden,false);assert.equal(node('#employee-archive-confirm').disabled,true);assert.equal(node('#employee-archive-cancel').disabled,false);await node('#employee-archive-confirm').onclick();assert.equal(requests.length,3,'stale cannot be silently retried');node('#employee-archive-modal').close('cancel');
 context.api=async()=>{const error=new Error('End active workday');error.status=409;throw error};context.setEmployeeArchive(10);await node('#employee-archive-confirm').onclick();assert.match(node('#employee-archive-message').textContent,/active workday/);assert.equal(node('#employee-archive-confirm').disabled,false);node('#employee-archive-modal').close('cancel');
 let release;context.api=()=>new Promise(resolve=>release=resolve);context.setEmployeeArchive(10);const pending=node('#employee-archive-confirm').onclick();assert.equal(node('#employee-archive-confirm').disabled,true);assert.equal(node('#employee-archive-cancel').disabled,true);let prevented=false;node('#employee-archive-modal').listeners.cancel({preventDefault(){prevented=true}});assert.equal(prevented,true,'Escape cannot disguise an in-flight confirmation');await node('#employee-archive-confirm').onclick();release({id:10,archived:true,archiveVersion:3});await pending;assert.equal(node('#employee-archive-modal').open,false);
 context.team=[{id:10,name:'Original employee',archiveVersion:3}];context.setEmployeeArchive(10);const otherPending=node('#employee-archive-confirm').onclick();context.companyId='other-company';context.currentUser={id:7,role:'owner'};context.team=[{id:10,name:'Other workspace employee',archiveVersion:0}];const beforeNotifications=notifications.length;release({id:10,name:'Original employee',archived:true,archiveVersion:4});await otherPending;assert.equal(context.team[0].name,'Other workspace employee');assert.equal(context.team[0].archived,undefined);assert.equal(notifications.length,beforeNotifications,'old workspace success cannot appear in the new workspace');assert.equal(node('#employee-archive-modal').open,false);
 context.api=()=>new Promise((resolve,reject)=>release=reject);context.setEmployeeArchive(10);const errorPending=node('#employee-archive-confirm').onclick();context.currentUser={id:8,role:'owner'};release(new Error('Old workspace failure'));await errorPending;assert.equal(node('#employee-archive-modal').open,false);assert.notEqual(node('#employee-archive-message').textContent,'Old workspace failure');
 console.log('Employee archive confirmation passed: no automatic submission, Cancel/Back, explicit archive/restore, captured version, role change, stale/open-shift feedback and in-flight controls.');
})().catch(error=>{console.error(error);process.exitCode=1});
