'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const crypto = require('node:crypto');
const {schema,instructions,normalizeEstimateExtraction} = require('./estimate-ai');
const oracle = require('./test-fixtures/estimates/smartsheet-painting-oracle');
assert.equal(crypto.createHash('sha256').update(fs.readFileSync(__dirname+'/test-fixtures/estimates/smartsheet-painting-public.pdf')).digest('hex'),'eec24768b1e3749779caf86a9bc001b93716323378a75d7b462e5e3ebfa64ace');
const normalized = normalizeEstimateExtraction(oracle);
assert.equal(normalized.lines.length,13); assert.equal(normalized.lineTotal,5133); assert.equal(normalized.lines.reduce((sum,item)=>sum+(item.budgetHours||0),0),70); assert.equal(normalized.lines.filter(item=>!item.unit).length,7); assert.equal(normalized.reconciled,true);
const line = {description:'Concrete slab',quantity:100,unit:'SF',unitPrice:50,amount:5000,internalCost:3000,budgetHours:null,scopeStatus:'included',confidence:'high',reviewNotes:[]};
const adjusted = normalizeEstimateExtraction({lines:[line,{...line,description:'Optional coating',scopeStatus:'excluded',amount:1000}],documentTotal:5300,adjustments:[{kind:'tax',description:'Tax',amount:500},{kind:'discount',description:'Discount',amount:-200}],reviewNotes:[]});
assert.equal(adjusted.lines.length,1); assert.equal(adjusted.lineTotal,5000); assert.equal(adjusted.adjustmentTotal,300); assert.equal(adjusted.reconciled,true); assert.equal(adjusted.lines[0].internalCost,3000); assert.equal(adjusted.lines[0].budgetHours,null); assert.match(adjusted.reviewWarnings.join(' '),/excluded/);
const hidden = normalizeEstimateExtraction({lines:[{...line,quantity:null,unit:'',amount:null,budgetHours:null,scopeStatus:'uncertain'}],documentTotal:null});
assert.equal(hidden.lines.length,1); assert.equal(hidden.lines[0].quantity,null); assert.equal(hidden.lines[0].unit,''); assert.equal(hidden.lines[0].amount,null); assert.equal(hidden.lines[0].budgetHours,null); assert.equal(hidden.lines[0].confidence,'low'); assert.equal(hidden.reconciled,false);
const malformed = normalizeEstimateExtraction({lines:[{...line,quantity:Infinity,amount:Infinity,budgetHours:-1}],documentTotal:Infinity});
assert.equal(malformed.lines[0].quantity,null); assert.equal(malformed.lines[0].amount,null); assert.equal(malformed.lines[0].budgetHours,null); assert.equal(malformed.documentTotal,null);
assert.equal(normalizeEstimateExtraction({lines:[null,line],adjustments:[null],documentTotal:5000}).lines.length,1);
assert.equal(normalizeEstimateExtraction(null).lines.length,0);
const excessive=normalizeEstimateExtraction({lines:[{...line,amount:Number.MAX_SAFE_INTEGER},{...line,amount:Number.MAX_SAFE_INTEGER}],documentTotal:5000}); assert.equal(excessive.lineTotal,null); assert.equal(excessive.reconciled,false);
const zero=normalizeEstimateExtraction({lines:[{...line,unitPrice:0,amount:0,budgetHours:0}],documentTotal:0}); assert.equal(zero.lines[0].amount,0); assert.equal(zero.lines[0].budgetHours,0); assert.equal(zero.documentTotal,0); assert.equal(zero.reconciled,true);
const equipment=normalizeEstimateExtraction({lines:[{...line,description:'Equipment rental',quantity:8,unit:'HR',unitPrice:50,amount:400,budgetHours:null}],documentTotal:400}); assert.equal(equipment.lines[0].budgetHours,null);
const taxInclusive=normalizeEstimateExtraction({lines:[{...line,description:'Tax-inclusive scope',quantity:146,unit:'SF',unitPrice:.33,amount:48.98,budgetHours:null}],documentTotal:48.98}); assert.equal(taxInclusive.lines[0].amount,48.98); assert.equal(taxInclusive.lines[0].confidence,'low'); assert.equal(taxInclusive.reconciled,true);
assert.deepEqual(schema.properties.lines.items.properties.quantity.type,['number','null']); assert.ok(schema.properties.lines.items.required.includes('internalCost')); assert.ok(schema.properties.lines.items.required.includes('budgetHours')); assert.ok(schema.properties.lines.items.required.includes('scopeStatus')); assert.match(instructions,/never assume column order/i); assert.match(instructions,/Not included/); assert.match(instructions,/Do not double-count/); assert.match(instructions,/not budgetHours/);
console.log('AI estimate contract: public-sample human oracle, hidden values, separate cost/sell price, explicit hours, optional scope and adjustments passed (no model invocation)');
