'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('app.js','utf8'),lines=source.split('\n');
function code(name){const start=lines.findIndex(line=>line.startsWith(`function ${name}(`)||line.startsWith(`async function ${name}(`));assert.ok(start>=0,name);if(lines[start].trimEnd().endsWith('}'))return lines[start];const end=lines.findIndex((line,index)=>index>start&&line.trimEnd()==='}');return lines.slice(start,end+1).join('\n')}
const today='2026-10-07';
function fixture(){
  const nodes=new Map(),events=new Map(),windowEvents=new Map(),calls=[];
  const node=selector=>{if(!nodes.has(selector))nodes.set(selector,{value:'',hidden:false,open:false,dataset:{},innerHTML:'',textContent:'',classList:{contains:()=>selector==='#dashboard-page'},setAttribute(name,value){this[name]=value},removeAttribute(name){delete this[name]},focus(){this.focused=true},scrollIntoView(){this.scrolled=true},addEventListener(name,fn){events.set(selector+':'+name,fn)},close(){this.open=false;events.get(selector+':close')?.()}});return nodes.get(selector)};
  const state={company:{id:'fixture-company',timezone:'UTC'},currentUser:{id:1,name:'QA Actor',role:'owner'},users:[{id:1,name:'QA Actor',role:'owner'}],team:[{id:7,name:'Crew Person'}],projects:[{id:10,name:'Other project',code:'O'},{id:20,name:'Market <Street>',code:'M'}],reports:[],assignments:[{id:50,projectId:20,date:today,memberIds:[7]}],workdays:[],dailyTemplates:[]};
  const history={state:{pdlIndex:0},pushState(next){this.state=next;calls.push(['push'])},replaceState(next){this.state=next;calls.push(['replace'])},back(){this.state={pdlIndex:0};calls.push(['back'])}};
  const context={...structuredClone(state),currentRole:'office',dailyTemplates:[],fieldActivityOpening:false,fieldActivityNavigationSequence:0,reportReturnActivity:null,reportReturnProjectId:null,activityReportForm:null,$:node,$$:()=>[],companyTodayIso:()=>today,formatDate:value=>value,projectBadgeColor:()=> '#eee',signedInCompanyId:()=>context.company.id,notify:message=>calls.push(['notify',message]),history,location:{href:'http://fixture/#dashboard'},window:{addEventListener:(name,fn)=>windowEvents.set(name,fn)},confirmReportDiscard:()=>true,api:async(url,options)=>{calls.push(['api',url,options]);assert.equal(url,'/api/state');assert.equal(options,undefined,'navigation must use read-only state');return structuredClone(state)},openReport:(report,options)=>{calls.push(['form',report,options]);node('#report-modal').open=true},showPage:page=>{calls.push(['page',page]);context.fieldActivityNavigationSequence++},renderReports:id=>calls.push(['view',id])};
  vm.createContext(context);for(const name of ['escapeHtml','activityDailyReports','activityReportTarget','activityDraftOwned','activityCanOpen','renderActivities','openActivityDaily','completeActivityReportForm','activityReportFingerprint'])vm.runInContext(code(name),context);
  const eventStart=lines.findIndex(line=>line.startsWith("$('#report-modal').addEventListener('close',()=>{"));const eventEnd=lines.findIndex((line,index)=>index>eventStart&&line.startsWith('function completeActivityReportForm('));vm.runInContext(lines.slice(eventStart,eventEnd).join('\n'),context);
  const target={projectId:20,dateIso:today,reportId:null,companyId:'fixture-company',userId:1,role:'owner'},link=node('[data-activity-project="20"]');
  return{state,context,node,calls,target,link,events,windowEvents,click:()=>context.openActivityDaily(target,link)};
}
function draft(overrides={}){return{id:8,project:1,dateIso:today,status:'Draft',foreman:'QA Actor',notes:'Existing draft',...overrides}}
(async()=>{
  let f=fixture();f.context.renderActivities();assert.match(f.node('#activity-list').innerHTML,/type="button" data-activity-project="20"/);assert.match(f.node('#activity-list').innerHTML,/Needs report.*Market &lt;Street&gt;.*2026-10-07/);assert.equal(f.node('#activity-date').textContent,today);
  await f.click();assert.equal(f.calls.find(call=>call[0]==='form')[1],null);assert.deepEqual({...f.calls.find(call=>call[0]==='form')[2]},{projectIndex:1,dateIso:today,templateId:'standard'});assert.ok(f.node('#field-notes').focused);assert.equal(f.state.reports.length,0);assert.equal(f.link['aria-busy'],undefined);
  f.node('#report-modal').close();assert.ok(f.calls.some(call=>call[0]==='back'));assert.ok(f.link.focused);assert.equal(f.context.activityReportForm,null);
  f=fixture();f.state.reports=[draft()];f.target.reportId=8;await f.click();assert.equal(f.calls.find(call=>call[0]==='form')[1].id,8,'resume exact own saved draft');
  f.context.completeActivityReportForm();f.node('#report-modal').close();assert.equal(f.calls.some(call=>call[0]==='back'),false,'save completion must not queue cancellation Back');
  f=fixture();f.state.reports=[draft()];await f.click();assert.equal(f.calls.find(call=>call[0]==='form')[1].id,8,'a draft created after render is reused');
  f=fixture();f.state.reports=[draft({foreman:'Other actor'})];await f.click();assert.equal(f.calls.find(call=>call[0]==='form')[1],null,'never edit another actor draft');
  for(const mutation of [f=>f.state.reports=[],f=>f.state.reports=[draft({project:0})],f=>f.state.reports=[draft({projectId:10})],f=>f.state.reports=[draft({dateIso:'2026-10-06'})],f=>f.state.reports=[draft({deletedAt:'2026-10-07'})],f=>f.state.projects.pop(),f=>f.state.projects[1].archived=true,f=>f.state.currentUser.id=2,f=>f.state.currentUser.role='field',f=>f.state.company.id='other-company',f=>f.state.users.push({id:2,name:'QA Actor'}),f=>f.state.team.push({id:8,name:'QA Actor'}),f=>f.state.users=[]]){
    f=fixture();f.state.reports=[draft()];f.target.reportId=8;mutation(f);await f.click();assert.ok(!f.calls.some(call=>['form','view'].includes(call[0])),'stale, unrelated or ambiguous target fails closed');assert.ok(f.calls.some(call=>call[0]==='notify'));
  }
  f=fixture();f.state.reports=[draft({status:'Needs review'})];f.target.reportId=8;f.node('#report-status-filter').value='Approved';await f.click();assert.equal(f.calls.find(call=>call[0]==='view')[1],8);assert.equal(f.node('#report-status-filter').value,'all');assert.ok(f.node('#report-detail').focused&&f.node('#report-detail').scrolled);assert.equal(f.node('#close-report-view').textContent,'Back to dashboard');
  f=fixture();f.state.reports=[draft({status:'Approved',dateIso:'2026-10-06'}),draft({id:9,project:0,status:'Approved'})];await f.click();assert.equal(f.calls.find(call=>call[0]==='form')[1],null,'wrong day and project never substitute');
  for(const role of ['field','foreman','support']){f=fixture();f.context.currentUser.role=role;await f.click();assert.equal(f.calls.length,0)}
  f=fixture();f.context.currentUser.role='project_manager';f.context.currentUser.permissions={};f.context.renderActivities();assert.ok(!f.node('#activity-list').innerHTML.includes('data-activity-project='));
  for(const allowed of [false,true]){f=fixture();f.context.currentUser.role='project_manager';f.context.currentUser.permissions={viewDailies:true};f.target.role='project_manager';f.state.currentUser={...f.context.currentUser,projectIds:allowed?[20]:[10]};await f.click();assert.equal(f.calls.some(call=>call[0]==='form'),allowed)}
  f=fixture();let release;f.context.api=async()=>{f.calls.push(['api']);return new Promise(resolve=>release=()=>resolve(structuredClone(f.state)))};const pending=f.click();await f.click();assert.equal(f.calls.length,1,'repeated clicks issue only one read');release();await pending;await f.click();assert.equal(f.calls.filter(call=>call[0]==='form').length,1,'open dialog is not reset by repeat clicks');
  for(const change of [f=>f.context.fieldActivityNavigationSequence++,f=>f.context.currentUser.id=2,f=>f.context.company.id='switched']){f=fixture();let release;f.context.api=()=>new Promise(resolve=>release=()=>resolve(structuredClone(f.state)));const pending=f.click();change(f);release();await pending;assert.ok(!f.calls.some(call=>call[0]==='form'),'late response cannot reopen or cross workspace');}
  f=fixture();f.target.dateIso='2026-10-06';await f.click();assert.ok(!f.calls.some(call=>call[0]==='api'),'overnight stale control is refused');
  f=fixture();await f.click();f.context.history.state={pdlIndex:0};f.context.confirmReportDiscard=()=>false;f.windowEvents.get('popstate')();assert.ok(f.node('#report-modal').open,'canceling discard keeps dialog open');assert.ok(f.context.history.state.pdlActivityReport);f.context.confirmReportDiscard=()=>true;f.context.history.state={pdlIndex:0};f.windowEvents.get('popstate')();assert.equal(f.node('#report-modal').open,false,'browser Back closes form');assert.equal(f.context.activityReportForm,null);
  f=fixture();f.state.reports=[draft()];f.target.reportId=8;await f.click();f.context.reportHasUnsavedInput=()=>false;let prompted=false;f.context.window.confirm=()=>{prompted=true;return false};vm.runInContext(code('confirmReportDiscard'),f.context);f.events.get('#report-modal:input')();assert.equal(f.context.confirmReportDiscard(),false,'detail-only edits on saved activity drafts require discard confirmation');assert.ok(prompted);f.context.history.state={pdlIndex:0};f.windowEvents.get('popstate')();assert.ok(f.node('#report-modal').open);
  f=fixture();f.state.reports=[draft()];f.target.reportId=8;f.node('#report-form').querySelectorAll=()=>[{id:'production-quantity',value:'1'}];await f.click();f.context.reportHasUnsavedInput=()=>false;f.context.window.confirm=()=>false;vm.runInContext(code('confirmReportDiscard'),f.context);f.node('#report-form').querySelectorAll=()=>[];assert.equal(f.context.confirmReportDiscard(),false,'removing a saved work line requires discard confirmation without input/change');
  f=fixture();f.context.reports=[draft({status:'Approved',reportType:'superintendent'}),draft({id:9,status:'Approved',templateId:'safety'})];f.context.renderActivities();assert.match(f.node('#activity-list').innerHTML,/Needs report/,'safety logs cannot satisfy a production daily');
  f=fixture();f.state.projects[1].templateIds=['safety','daily'];f.state.dailyTemplates=[{id:'safety',category:'safety'},{id:'daily',category:'daily'}];await f.click();assert.equal(f.calls.find(call=>call[0]==='form')[2].templateId,'daily');
  const timezoneContext={company:{timezone:'America/Los_Angeles'},localDateIso:()=> '2026-10-07'};vm.createContext(timezoneContext);vm.runInContext(code('companyTodayIso'),timezoneContext);assert.equal(timezoneContext.companyTodayIso(new Date('2026-10-07T02:00:00Z')),'2026-10-06');
  console.log('Field activity navigation passed: exact project/company date, scoped actor draft, fresh access, missing/stale/wrong targets, read-only repeated navigation, templates, focus, cancel and browser Back.');
})().catch(error=>{console.error(error);process.exitCode=1});
