const token=location.pathname.split('/').pop();
const companyId=new URLSearchParams(location.search).get('c');
const $=selector=>document.querySelector(selector);
let mode='progress',ticketDrafts=[],language=localStorage.getItem('pdl-guest-language')||(navigator.language.startsWith('es')?'es':'en');
const tr=(en,es)=>language==='es'?es:en;
function localDateTime(date){const offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,16)}
async function api(options={},path=''){const headers={'Content-Type':'application/json',...(companyId?{'x-pdl-company':companyId}:{}),...(options.headers||{})},response=await fetch(`/api/guest/${token}${path}`,{...options,headers}),data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data}
async function fileData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,type:file.type,data:reader.result});reader.onerror=reject;reader.readAsDataURL(file)})}
function showTimes(){const start=$('#start').value,end=$('#end').value;$('#time-status').textContent=start?`${tr('Arrived','Llegada')} ${new Date(start).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}${end?` · ${tr('Finished','Salida')} ${new Date(end).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`:''}`:tr('Tap “We arrived” when work begins.','Toque “Llegamos” cuando comience el trabajo.')}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function renderTickets(){
  $('#ticket-results').innerHTML=ticketDrafts.map((ticket,index)=>`<article class="ticket-draft ${ticket.confidence==='low'?'low-confidence':''}" data-ticket="${index}"><div class="ticket-heading"><strong>${escapeHtml(ticket.file.name)}</strong><span>${escapeHtml(ticket.confidence||'low')} ${tr('confidence','confianza')}</span></div><div class="ticket-grid"><label>${tr('Vendor','Proveedor')}<input data-field="vendor" value="${escapeHtml(ticket.vendor)}"></label><label>${tr('Ticket number','Número de boleto')}<input data-field="ticketNumber" value="${escapeHtml(ticket.ticketNumber)}"></label><label>${tr('Ticket date','Fecha')}<input data-field="ticketDate" type="date" value="${escapeHtml(ticket.ticketDate)}"></label></div><div class="ticket-lines"><strong>${tr('Material lines','Materiales')}</strong>${(ticket.lines||[]).map((line,lineIndex)=>`<div class="ticket-line" data-line="${lineIndex}"><input data-line-field="material" aria-label="${tr('Material','Material')}" placeholder="${tr('Material','Material')}" value="${escapeHtml(line.material)}"><input data-line-field="quantity" aria-label="${tr('Quantity','Cantidad')}" type="number" step="any" min="0" value="${Number(line.quantity)||0}"><input data-line-field="unit" aria-label="${tr('Unit','Unidad')}" placeholder="${tr('Unit','Unidad')}" value="${escapeHtml(line.unit)}"></div>`).join('')}</div>${ticket.needsReview?.length||ticket.confidence==='low'?`<p class="ticket-review">${tr('Please verify','Verifique')}: ${(ticket.needsReview||[]).map(escapeHtml).join(', ')||tr('AI confidence is low','La confianza de IA es baja')}</p>`:''}<label class="ticket-confirm"><input data-confirm type="checkbox" ${ticket.confirmed?'checked':''}> ${tr('I checked this ticket and the details are correct.','Revisé este boleto y los datos son correctos.')}</label></article>`).join('');
  $('#ticket-results').querySelectorAll('[data-ticket]').forEach(card=>{const index=Number(card.dataset.ticket);card.querySelectorAll('[data-field]').forEach(input=>input.oninput=()=>{ticketDrafts[index][input.dataset.field]=input.value});card.querySelectorAll('[data-line]').forEach(row=>{const lineIndex=Number(row.dataset.line);row.querySelectorAll('[data-line-field]').forEach(input=>input.oninput=()=>{ticketDrafts[index].lines[lineIndex][input.dataset.lineField]=input.type==='number'?Number(input.value):input.value})});card.querySelector('[data-confirm]').onchange=event=>{ticketDrafts[index].confirmed=event.target.checked}})
}
function labelFor(id,text){const node=$(`#${id}`)?.closest('label')?.firstChild;if(node)node.nodeValue=text}
function applyLanguage(){document.documentElement.lang=language;$('#guest-language').value=language;document.querySelector('header span').textContent=tr('Secure subcontractor daily','Reporte seguro de subcontratista');$('.access span').textContent=tr('Access limited to this project','Acceso limitado a este proyecto');$('#daily-form h2').textContent=tr('Today’s progress','Progreso de hoy');$('#daily-form>p').textContent=tr('A quick update for the office—no individual employee tracking.','Una actualización rápida para la oficina, sin rastreo individual de empleados.');$('#arrived').textContent=tr('We arrived','Llegamos');$('#finished').textContent=tr('We’re done for today','Terminamos por hoy');labelFor('start',tr('Start time','Hora de inicio'));labelFor('end',tr('End time','Hora de salida'));labelFor('crew',tr('Approximate crew count','Número aproximado de trabajadores'));labelFor('notes',tr('What did your crew complete?','¿Qué completó su cuadrilla?'));labelFor('materials',tr('Materials used','Materiales usados'));labelFor('equipment',tr('Equipment used','Equipo usado'));labelFor('delays',tr('Delays, extra work, or issues','Retrasos, trabajo extra o problemas'));labelFor('photos',tr('Progress photos','Fotos del progreso'));labelFor('tickets',tr('Ticket files','Archivos de boletos'));labelFor('signature',tr('Your name / signature','Su nombre / firma'));$('.ticket-capture h3').textContent=tr('Tickets & receipts','Boletos y recibos');$('.ticket-capture>p').textContent=tr('Photograph or upload pick tickets, delivery tickets, and material receipts. AI creates a draft; you confirm it before submission.','Fotografíe o cargue boletos de retiro, entrega y recibos de materiales. La IA crea un borrador que usted confirma antes de enviar.');$('#scan-tickets').textContent=tr('✦ Scan tickets with AI','✦ Escanear boletos con IA');$('#submit').textContent=mode==='tm'?tr('Submit T&M daily','Enviar reporte T&M'):tr('Submit progress update','Enviar progreso');showTimes();renderTickets()}
async function load(){try{const access=await api();mode=access.mode||'progress';document.body.classList.toggle('progress-mode',mode==='progress');$('#company').textContent=access.company.name;$('#project').textContent=access.project.name;$('#site').textContent=access.project.site;$('#subcontractor').textContent=access.subcontractor.name;$('#signature').value=access.subcontractor.name;if(mode==='tm'){const now=new Date(),start=new Date(now);start.setHours(7,0,0,0);$('#start').value=localDateTime(start);$('#end').value=localDateTime(now)}$('#loading').hidden=true;$('#guest-app').hidden=false;applyLanguage()}catch(error){$('#loading').textContent=error.message}}
$('#arrived').onclick=()=>{$('#start').value=localDateTime(new Date());$('#arrived').classList.add('done');$('#arrived').textContent='✓ Arrival recorded';showTimes()};
$('#finished').onclick=()=>{$('#end').value=localDateTime(new Date());$('#finished').classList.add('done');$('#finished').textContent='✓ Finish recorded';showTimes()};
$('#guest-language').onchange=()=>{language=$('#guest-language').value==='es'?'es':'en';localStorage.setItem('pdl-guest-language',language);applyLanguage()};
$('#tickets').onchange=()=>{ticketDrafts=[];$('#ticket-results').innerHTML='';$('#ticket-status').textContent=$('#tickets').files.length?'Ready to scan. AI will make a draft for you to check.':''};
$('#scan-tickets').onclick=async()=>{const button=$('#scan-tickets'),status=$('#ticket-status'),selected=[...$('#tickets').files],allowed=['application/pdf','image/jpeg','image/png','image/webp'];if(!selected.length)return status.textContent=tr('Choose at least one ticket first.','Seleccione al menos un boleto.');if(selected.length>5)return status.textContent=tr('Upload up to 5 tickets at a time.','Cargue hasta 5 boletos a la vez.');if(selected.some(file=>!allowed.includes(file.type)||file.size>10000000))return status.textContent=tr('Tickets must be PDF, JPG, PNG, or WebP and under 10 MB each.','Los boletos deben ser PDF, JPG, PNG o WebP y menos de 10 MB.');button.disabled=true;status.textContent=tr('Scanning tickets…','Escaneando boletos…');try{const files=await Promise.all(selected.map(fileData)),result=await api({method:'POST',body:JSON.stringify({files})},'/ticket-scan');ticketDrafts=(result.tickets||[]).map(ticket=>({...ticket,lines:ticket.lines?.length?ticket.lines:[{material:'',quantity:0,unit:'',amount:0}],confirmed:false,file:files[ticket.fileIndex]}));renderTickets();status.textContent=tr(`${ticketDrafts.length} ticket draft${ticketDrafts.length===1?'':'s'} ready. Check each one before submitting.`,`${ticketDrafts.length} borrador${ticketDrafts.length===1?'':'es'} listo${ticketDrafts.length===1?'':'s'}. Revise antes de enviar.`)}catch(error){status.textContent=error.message}finally{button.disabled=false}};
$('#daily-form').onsubmit=async event=>{event.preventDefault();const button=$('#submit'),message=$('#message');if($('#tickets').files.length&&!ticketDrafts.length){message.className='visible';message.textContent=tr('Scan the selected tickets before submitting.','Escanee los boletos seleccionados antes de enviar.');return}if(ticketDrafts.some(ticket=>!ticket.confirmed)){message.className='visible';message.textContent=tr('Check and confirm every ticket before submitting.','Revise y confirme cada boleto antes de enviar.');return}if(!$('#start').value)$('#start').value=localDateTime(new Date(Date.now()-60000));if(!$('#end').value)$('#end').value=localDateTime(new Date());button.disabled=true;message.className='visible';message.textContent=tr('Uploading and submitting…','Cargando y enviando…');try{const files=await Promise.all([...$('#photos').files].slice(0,8).map(fileData)),tickets=ticketDrafts.map(({file,...ticket})=>({...ticket,file})),result=await api({method:'POST',body:JSON.stringify({startedAt:new Date($('#start').value).toISOString(),endedAt:new Date($('#end').value).toISOString(),crewCount:+$('#crew').value,notes:$('#notes').value.trim(),materials:mode==='tm'?$('#materials').value.trim():'',equipment:mode==='tm'?$('#equipment').value.trim():'',delays:$('#delays').value.trim(),signature:$('#signature').value.trim(),files,tickets})});message.textContent=tr(`Progress submitted for office review. Confirmation #${result.reportId}.${result.tickets?` ${result.tickets} ticket${result.tickets===1?'':'s'} attached.`:''}`,`Progreso enviado para revisión. Confirmación #${result.reportId}.${result.tickets?` ${result.tickets} boleto${result.tickets===1?'':'s'} adjunto${result.tickets===1?'':'s'}.`:''}`);$('#daily-form').querySelectorAll('input,textarea,button').forEach(control=>control.disabled=true)}catch(error){message.textContent=error.message;button.disabled=false}};
load();
