const token=location.pathname.split('/').pop();
const companyId=new URLSearchParams(location.search).get('c');
const $=selector=>document.querySelector(selector);
let mode='progress',ticketDrafts=[];
function localDateTime(date){const offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,16)}
async function api(options={},path=''){const headers={'Content-Type':'application/json',...(companyId?{'x-pdl-company':companyId}:{}),...(options.headers||{})},response=await fetch(`/api/guest/${token}${path}`,{...options,headers}),data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data}
async function fileData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,type:file.type,data:reader.result});reader.onerror=reject;reader.readAsDataURL(file)})}
function showTimes(){const start=$('#start').value,end=$('#end').value;$('#time-status').textContent=start?`Arrived ${new Date(start).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}${end?` · Finished ${new Date(end).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`:''}`:'Tap “We arrived” when work begins.'}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function renderTickets(){
  $('#ticket-results').innerHTML=ticketDrafts.map((ticket,index)=>`<article class="ticket-draft" data-ticket="${index}"><div class="ticket-heading"><strong>${escapeHtml(ticket.file.name)}</strong><span>${escapeHtml(ticket.confidence||'low')} confidence</span></div><div class="ticket-grid"><label>Vendor<input data-field="vendor" value="${escapeHtml(ticket.vendor)}"></label><label>Ticket number<input data-field="ticketNumber" value="${escapeHtml(ticket.ticketNumber)}"></label><label>Ticket date<input data-field="ticketDate" type="date" value="${escapeHtml(ticket.ticketDate)}"></label><label>Material<input data-field="material" value="${escapeHtml(ticket.material)}"></label><label>Quantity<input data-field="quantity" type="number" step="any" min="0" value="${Number(ticket.quantity)||0}"></label><label>Unit<input data-field="unit" value="${escapeHtml(ticket.unit)}"></label></div>${ticket.needsReview?.length?`<p class="ticket-review">Check: ${ticket.needsReview.map(escapeHtml).join(', ')}</p>`:''}<label class="ticket-confirm"><input data-confirm type="checkbox" ${ticket.confirmed?'checked':''}> I checked this ticket and the details are correct.</label></article>`).join('');
  $('#ticket-results').querySelectorAll('[data-ticket]').forEach(card=>{const index=Number(card.dataset.ticket);card.querySelectorAll('[data-field]').forEach(input=>input.oninput=()=>{ticketDrafts[index][input.dataset.field]=input.type==='number'?Number(input.value):input.value});card.querySelector('[data-confirm]').onchange=event=>{ticketDrafts[index].confirmed=event.target.checked}})
}
async function load(){try{const access=await api();mode=access.mode||'progress';document.body.classList.toggle('progress-mode',mode==='progress');$('#company').textContent=access.company.name;$('#project').textContent=access.project.name;$('#site').textContent=access.project.site;$('#subcontractor').textContent=access.subcontractor.name;$('#signature').value=access.subcontractor.name;$('#submit').textContent=mode==='tm'?'Submit T&M daily':'Submit progress update';if(mode==='tm'){const now=new Date(),start=new Date(now);start.setHours(7,0,0,0);$('#start').value=localDateTime(start);$('#end').value=localDateTime(now)}$('#loading').hidden=true;$('#guest-app').hidden=false;showTimes()}catch(error){$('#loading').textContent=error.message}}
$('#arrived').onclick=()=>{$('#start').value=localDateTime(new Date());$('#arrived').classList.add('done');$('#arrived').textContent='✓ Arrival recorded';showTimes()};
$('#finished').onclick=()=>{$('#end').value=localDateTime(new Date());$('#finished').classList.add('done');$('#finished').textContent='✓ Finish recorded';showTimes()};
$('#tickets').onchange=()=>{ticketDrafts=[];$('#ticket-results').innerHTML='';$('#ticket-status').textContent=$('#tickets').files.length?'Ready to scan. AI will make a draft for you to check.':''};
$('#scan-tickets').onclick=async()=>{const button=$('#scan-tickets'),status=$('#ticket-status'),selected=[...$('#tickets').files],allowed=['application/pdf','image/jpeg','image/png','image/webp'];if(!selected.length)return status.textContent='Choose at least one ticket first.';if(selected.length>5)return status.textContent='Upload up to 5 tickets at a time.';if(selected.some(file=>!allowed.includes(file.type)||file.size>10000000))return status.textContent='Tickets must be PDF, JPG, PNG, or WebP and under 10 MB each.';button.disabled=true;status.textContent='Scanning tickets…';try{const files=await Promise.all(selected.map(fileData)),result=await api({method:'POST',body:JSON.stringify({files})},'/ticket-scan');ticketDrafts=(result.tickets||[]).map(ticket=>({...ticket,confirmed:false,file:files[ticket.fileIndex]}));renderTickets();status.textContent=`${ticketDrafts.length} ticket draft${ticketDrafts.length===1?'':'s'} ready. Check each one before submitting.`}catch(error){status.textContent=error.message}finally{button.disabled=false}};
$('#daily-form').onsubmit=async event=>{event.preventDefault();const button=$('#submit'),message=$('#message');if($('#tickets').files.length&&!ticketDrafts.length){message.className='visible';message.textContent='Scan the selected tickets before submitting.';return}if(ticketDrafts.some(ticket=>!ticket.confirmed)){message.className='visible';message.textContent='Check and confirm every ticket before submitting.';return}if(!$('#start').value)$('#start').value=localDateTime(new Date(Date.now()-60000));if(!$('#end').value)$('#end').value=localDateTime(new Date());button.disabled=true;message.className='visible';message.textContent='Uploading and submitting…';try{const files=await Promise.all([...$('#photos').files].slice(0,8).map(fileData)),tickets=ticketDrafts.map(({file,...ticket})=>({...ticket,file})),result=await api({method:'POST',body:JSON.stringify({startedAt:new Date($('#start').value).toISOString(),endedAt:new Date($('#end').value).toISOString(),crewCount:+$('#crew').value,notes:$('#notes').value.trim(),materials:mode==='tm'?$('#materials').value.trim():'',equipment:mode==='tm'?$('#equipment').value.trim():'',delays:$('#delays').value.trim(),signature:$('#signature').value.trim(),files,tickets})});message.textContent=`Progress submitted for office review. Confirmation #${result.reportId}.${result.tickets?` ${result.tickets} ticket${result.tickets===1?'':'s'} attached.`:''}`;$('#daily-form').querySelectorAll('input,textarea,button').forEach(control=>control.disabled=true)}catch(error){message.textContent=error.message;button.disabled=false}};
load();
