'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),email=require('./help-email'),{createFakeEmailIntegration}=require('./help-email-integration');
const now=()=>new Date('2026-10-08T12:00:00Z'),key='SyntheticLocalUnsubscribeKeyForFakeIntegration42';
function fixture(){let state={company:{id:'synthetic',timezone:'UTC'},users:[{id:1,companyId:'synthetic',role:'owner',status:'Active',email:'owner@example.invalid',emailVerifiedAt:'2026-10-01',helpGuidance:{emailTips:true}}],projects:[],team:[],reports:[]},revision=0;const events=[];
  const store={async load(){return {snapshot:structuredClone(state),revision}},async save(snapshot,expected){if(expected!==revision)throw Object.assign(Error('PDL_REVISION_CONFLICT'),{code:'PDL_REVISION_CONFLICT'});state=structuredClone(snapshot);return {revision:++revision}}};
  const provider={isFake:true,async send(message){events.push(message);return {id:'fake-'+crypto.randomUUID()}}};
  const options={store,provider,enabled:()=>true,now,unsubscribeKey:key};return {store,provider,events,options};
}
(async()=>{
  let f=fixture(),a=createFakeEmailIntegration(f.options),b=createFakeEmailIntegration(f.options);
  const stages=await Promise.all([a.reserve('synthetic',1,'project'),b.reserve('synthetic',1,'project')]);assert.deepEqual(stages.map(s=>s.status).sort(),['duplicate','reserved']);const receiptKey=stages[0].key;
  const dispatched=await Promise.all([a.attempt('synthetic',receiptKey),b.attempt('synthetic',receiptKey)]);assert.equal(dispatched.filter(r=>r.providerCalled).length,1);assert.equal(f.events.length,1);assert.equal((await f.store.load()).snapshot.helpEmailReceipts[0].status,'delivered');assert.equal((await createFakeEmailIntegration(f.options).attempt('synthetic',receiptKey)).status,'already-attempted');
  assert.equal(f.events[0].headers['List-Unsubscribe-Post'],'List-Unsubscribe=One-Click');assert.match(f.events[0].to,/@example\.invalid$/);assert.equal(f.events[0].idempotencyKey,receiptKey);
  f=fixture();f.provider.send=async message=>{f.events.push(message);throw Error('Accepted by fake provider but response lost')};a=createFakeEmailIntegration(f.options);const unknown=await a.reserve('synthetic',1,'project');assert.equal((await a.attempt('synthetic',unknown.key)).status,'unknown');assert.equal((await createFakeEmailIntegration(f.options).attempt('synthetic',unknown.key)).status,'already-attempted');assert.equal(f.events.length,1);
  f=fixture();a=createFakeEmailIntegration(f.options);const crash=await a.reserve('synthetic',1,'project');const realSave=f.store.save;f.store.save=async(...args)=>{const result=await realSave(...args);if(args[0].helpEmailReceipts[0].status==='sending')throw Error('Simulated process death after durable claim');return result};await assert.rejects(a.attempt('synthetic',crash.key),/Simulated process death/);f.store.save=realSave;assert.equal((await createFakeEmailIntegration(f.options).attempt('synthetic',crash.key)).status,'already-attempted');assert.equal(f.events.length,0);
  f=fixture();a=createFakeEmailIntegration(f.options);const withdrawn=await a.reserve('synthetic',1,'project');let reads=0;const realLoad=f.store.load;f.store.load=async()=>{if(++reads===2){const saved=await realLoad();const token=email.tokenFor(saved.snapshot,saved.snapshot.users[0],key);email.unsubscribe(saved.snapshot,email.verifyToken(token,key));await f.store.save(saved.snapshot,saved.revision)}return realLoad()};assert.equal((await a.attempt('synthetic',withdrawn.key)).status,'cancelled');assert.equal(f.events.length,0);assert.equal((await realLoad()).snapshot.users[0].helpGuidance.emailTips,false);
  f=fixture();a=createFakeEmailIntegration(f.options);const inflight=await a.reserve('synthetic',1,'project');f.provider.send=async message=>{f.events.push(message);const saved=await f.store.load();const token=email.tokenFor(saved.snapshot,saved.snapshot.users[0],key);email.unsubscribe(saved.snapshot,email.verifyToken(token,key));await f.store.save(saved.snapshot,saved.revision);return {id:'fake-accepted-in-flight'}};assert.equal((await a.attempt('synthetic',inflight.key)).status,'delivered');assert.equal((await f.store.load()).snapshot.users[0].helpGuidance.emailTips,false,'settlement preserves in-flight unsubscribe');assert.equal((await a.reserve('synthetic',1,'crew')).status,'ineligible');
  f=fixture();a=createFakeEmailIntegration({...f.options,enabled:()=>false});const disabled=await a.reserve('synthetic',1,'project');assert.equal((await a.attempt('synthetic',disabled.key)).status,'disabled');assert.equal(f.events.length,0);assert.throws(()=>createFakeEmailIntegration({}),/compare-and-swap/);
  f=fixture();a=createFakeEmailIntegration({...f.options,provider:{send:async()=>{throw Error('must not call')}}});const nonfake=await a.reserve('synthetic',1,'project');await assert.rejects(a.attempt('synthetic',nonfake.key),/fake provider/);
  f=fixture();const realRecipient=await f.store.load();realRecipient.snapshot.users[0].email='real@example.com';await f.store.save(realRecipient.snapshot,realRecipient.revision);a=createFakeEmailIntegration(f.options);const nonSynthetic=await a.reserve('synthetic',1,'project');await assert.rejects(a.attempt('synthetic',nonSynthetic.key),/synthetic/);assert.equal(f.events.length,0);
  console.log('Fake-only email integration passed: durable exclusive claims, concurrent reservation/dispatch, restart/crash/unknown suppression, preflight and in-flight unsubscribe, headers and disabled/customer-recipient gates.');
})().catch(e=>{console.error(e);process.exitCode=1});
