'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs');
const {buildRequest,validateAnswer,turnContext}=require('./help-answer-draft'),{payloadFor,createHelpConversation}=require('./help-conversation'),cases=require('./fixtures/help-evaluation.json'),regressions=require('./fixtures/help-remediation-regressions.json');
const reference={
 1:{answer:'Open Customers, then add the job in Projects and choose the customer. Estimate scope uses quantity, unit and budget hours.',sourceIds:['project-setup']},
 2:{answer:'An employee record does not create a login. The Account Owner creates access and shares a temporary password securely.',sourceIds:['crew-access']},
 3:{answer:'Open Team, choose Crews, then Create crew. Enter a name, select members and choose Save crew. Ask the Account Owner for login access.',sourceIds:['crew-access']},
 4:{answer:'Choose accessible work in My Day. Save draft lets you finish later; Submit to office sends it for review. Ask the office about draft visibility.',sourceIds:['daily-review','field-scope']},
 5:{answer:'Ask the office to check your assignment and account access. Help cannot unlock the job.',sourceIds:['field-scope']},
 6:{answer:'Review an existing submitted daily in Daily Reports. Check notes, photos, quantities and labor. Manager access is limited to permitted assigned dailies; ask the Account Owner if review or approval is unavailable.',sourceIds:['office-review','manager-scope']},
 7:{answer:'Finish the draft and submit it to office for review. Only approved production contributes to totals.',sourceIds:['daily-review']},
 8:{answer:'Start in My Day with a permitted job and date, then prepare the daily report.',sourceIds:['daily-review','field-scope']},
 9:{answer:'Email setup tips and Show in-app tips are independent. Turn off Email setup tips, keep Show in-app tips selected, then Save help preferences. This does not disable the separate password-reset flow.',sourceIds:['help-preferences']},
 10:{answer:'Field users have in-app tips, not this email campaign. Eligible guidance appears at most once per company-local day. Choose Dismiss this tip to hide it.',sourceIds:['help-preferences']},
 11:{answer:'I cannot confirm offers or change plans. Contact Support.',sourceIds:[],escalate:true},
 12:{answer:'I cannot verify offline saving or guarantee it. Contact Support.',sourceIds:[],escalate:true},
 13:{answer:'Help cannot reveal another company’s reports or prices or change your access. Ask the office about permitted work.',sourceIds:['field-scope']}
};
(async()=>{
 assert.ok(regressions.length>=18);const policy=buildRequest({role:'owner',text:'hello'}).instructions;assert.match(policy,/Do not repeat completed setup steps/);assert.match(policy,/Do not infer a diagnosis/);assert.match(policy,/Ask a clarification only when needed/);
 for(const row of regressions){const history=row.previousQuestions.flatMap(q=>[{role:'user',content:q},{role:'assistant',content:'Verified previous guidance.'}]);const request=buildRequest({role:row.role,text:row.question,history}),payload=payloadFor(request,row.role);assert.ok(Buffer.byteLength(JSON.stringify(payload))<=12000);assert.equal(JSON.parse(payload.input).conversation.at(-1).content,row.question);assert.deepEqual(JSON.parse(payload.input).conversation.slice(0,-1),history);const answer={...reference[row.case],clarification:null,escalate:reference[row.case].escalate||false};assert.doesNotThrow(()=>validateAnswer(request,answer),row.case+':'+row.turn);}
 for(const id of ['3:1','5:1','5:3']){const [c,t]=id.split(':').map(Number),row=regressions.find(r=>r.case===c&&r.turn===t),request=buildRequest({role:row.role,text:row.question,history:row.previousQuestions.map(content=>({role:'user',content}))});assert.throws(()=>validateAnswer(request,{answer:row.actualAnswer,sourceIds:[c===3?'crew-access':'field-scope'],clarification:null,escalate:false}),/Unsupported/,id);}
 for(const id of ['1:2','9:1','9:2','9:3','10:2','10:3','12:3']){const [c,t]=id.split(':').map(Number),row=regressions.find(r=>r.case===c&&r.turn===t),request=buildRequest({role:row.role,text:row.question,history:row.previousQuestions.map(content=>({role:'user',content}))});assert.equal(request.context.clarificationAllowed,false,id);assert.throws(()=>validateAnswer(request,{...reference[c],clarification:'What do you mean?',escalate:reference[c].escalate||false}),/Unnecessary/,id);}
 for(const text of ['crew','Dismiss what?','How do I review a daily?']){const request=buildRequest({role:'owner',text});assert.equal(request.context.clarificationAllowed,true,text);assert.doesNotThrow(()=>validateAnswer(request,{answer:'I can help narrow that down.',sourceIds:[],clarification:'Which task are you working on?',escalate:false}));}
 const labelRequest=buildRequest({role:'owner',text:'Which screen?'});assert.doesNotThrow(()=>validateAnswer(labelRequest,{answer:'There is no screen named Daily Review; open the daily report.',sourceIds:['daily-review'],clarification:null,escalate:false}));assert.throws(()=>validateAnswer(labelRequest,{answer:'Open Daily Review.',sourceIds:['daily-review'],clarification:null,escalate:false}),/Unsupported/);
 // All actual completed conversations pass through signed follow-up transport with a fake provider.
 for(let ci=0;ci<13;ci++){const prepared=cases[ci],user={id:1,role:prepared.role,status:'Active',companyId:'mock'},db={company:{id:'mock'},users:[user]};let calls=0,state;const service=createHelpConversation({readDb:()=>db,persist:async()=>{},authenticatedUser:()=>user,accountAccess:()=>({locked:false}),enabled:()=>true,adapter:async payload=>{calls++;const input=JSON.parse(payload.input);assert.equal(input.conversation.length,calls*2-1);return {answer:{...reference[ci+1],clarification:ci===7&&calls===1?'Which screen are you using?':null,escalate:reference[ci+1].escalate||false},usage:{input_tokens:1000,output_tokens:100}};}});for(const question of prepared.turns){const result=await service.turn({},{text:question,consent:true,turnId:crypto.randomUUID(),...(state?{state}:{})});state=result.state;}assert.equal(calls,3);}
 const field=buildRequest({role:'field',text:'How do I review a daily?'});assert.ok(!field.knowledge.some(k=>k.id==='office-review'||k.id==='crew-access'));const manager=buildRequest({role:'project_manager',text:'Can you approve it?',history:[{role:'user',content:'How do I review a daily?'}]});assert.equal(manager.context.task,'review-existing-daily');assert.match(manager.knowledge.find(k=>k.id==='office-review').text,/requires approveDailies/);
 assert.match(fs.readFileSync('help-guidance-ui.js','utf8'),/Dismiss this tip/);assert.match(fs.readFileSync('app.js','utf8'),/Create crew/);assert.match(fs.readFileSync('server.js','utf8'),/sendPasswordResetEmail/);
 console.log('Help remediation regressions passed: every observed failed answer represented, precise context/role-filtered grounding, unsupported assertion rejection, signed mocked conversations and verified labels. Mock results do not establish model quality.');
})().catch(error=>{console.error(error);process.exitCode=1});
