(function(){
const es={
'Overview':'Resumen','Action center':'Centro de acciones','Schedule':'Horario','Projects':'Proyectos','Customers':'Clientes','Team':'Equipo','Daily reports':'Reportes diarios','Production insights':'Análisis de producción','Time cards':'Tarjetas de tiempo','Time off':'Tiempo libre','Settings':'Configuración','More tools':'Más herramientas','Sign out':'Cerrar sesión','New daily':'Nuevo reporte','Help':'Ayuda',
'Good morning':'Buenos días','Good afternoon':'Buenas tardes','Good evening':'Buenas noches','Active projects':'Proyectos activos','People in the field':'Personal en campo','Reports submitted':'Reportes enviados','Weekly production':'Producción semanal','Production performance':'Rendimiento de producción','Recent activity':'Actividad reciente','Active projects overview':'Resumen de proyectos activos','No daily reports need attention':'Ningún reporte diario requiere atención','New field submissions will appear here.':'Los nuevos reportes de campo aparecerán aquí.','You’re all caught up':'Todo está al día','Review actions →':'Revisar acciones →',
'Add project':'Agregar proyecto','Add customer':'Agregar cliente','Add team member':'Agregar miembro','Add user account':'Agregar cuenta de usuario','Create daily report':'Crear reporte diario','Verify daily report':'Verificar reporte diario','Create account':'Crear cuenta','Save':'Guardar','Cancel':'Cancelar','Close':'Cerrar','Delete':'Eliminar','Edit':'Editar','Approve':'Aprobar','Unapprove':'Quitar aprobación','Submit':'Enviar','Search':'Buscar','Today':'Hoy','This week':'Esta semana','This month':'Este mes','All':'Todos','Active':'Activo','Draft':'Borrador','Approved':'Aprobado','Needs review':'Necesita revisión','Missing data':'Faltan datos','Pending':'Pendiente','Submitted':'Enviado',
'Choose job':'Elegir proyecto','Choose the job this report belongs to.':'Elija el proyecto al que pertenece este reporte.','Today’s job':'Proyecto de hoy','Address':'Dirección','Work':'Trabajo','Crew':'Cuadrilla','Date':'Fecha','Note language':'Idioma de las notas','No crew selected':'Ninguna cuadrilla seleccionada','Crews are managed from Team → Crews.':'Las cuadrillas se administran en Equipo → Cuadrillas.','Job-site weather':'CLIMA DEL SITIO','Refresh weather':'Actualizar clima','Enter manually':'Ingresar manualmente','Tell us what happened today':'Cuéntenos qué pasó hoy','Speak notes':'Dictar notas','No delays':'Sin retrasos','No incidents':'Sin incidentes','Tomorrow':'Mañana','Notes save automatically on this device':'Las notas se guardan automáticamente en este dispositivo','Daily photos':'Fotos diarias','Photo tags':'Etiquetas de fotos','Analyze notes and build report':'Analizar notas y crear reporte','Save notes as draft':'Guardar notas como borrador','Next: production & labor →':'Siguiente: producción y mano de obra →','Field notes & photos':'Notas y fotos de campo','Production & labor':'Producción y mano de obra','Verify before submitting':'Verifique antes de enviar','AI suggestions can be changed. Confirm every quantity and hour.':'Puede cambiar las sugerencias de IA. Confirme cada cantidad y hora.','Office summary':'Resumen para la oficina','Production completed':'Producción terminada','Suggest hour split':'Sugerir distribución de horas','Estimate item':'Partida del estimado','Custom work':'Trabajo adicional','Individual labor hours':'Horas individuales','Add another team member…':'Agregar otro miembro…','Add person':'Agregar persona','Materials used':'Materiales utilizados','Equipment used':'Equipo utilizado','Delays / issues':'Retrasos / problemas','Safety observations':'Observaciones de seguridad','Next step':'Siguiente paso','Foreman signature':'Firma del capataz','Back to notes':'Volver a las notas','Save draft':'Guardar borrador','Submit to office':'Enviar a la oficina','Report sent':'REPORTE ENVIADO','The office has it.':'La oficina lo recibió.','Done':'Listo',
'My field dashboard':'MI PANEL DE CAMPO','Start your day':'Comience su día','End your day':'Termine su día','Today’s assignment':'Trabajo de hoy','Coming up':'Próximamente','My recent dailies':'Mis reportes recientes','Acknowledge assignment':'Confirmar asignación','No assignment today':'No hay asignación hoy','No upcoming assignments':'No hay próximas asignaciones','No dailies uploaded yet':'Aún no hay reportes enviados','Start day now':'Comenzar día ahora','End day & build report':'Terminar día y crear reporte','What was completed?':'¿Qué se completó?','What happens next?':'¿Qué sigue?','End-of-day photos':'Fotos de fin de día','Not yet':'Todavía no',
'Project':'Proyecto','Customer':'Cliente','Project name':'Nombre del proyecto','Project type':'Tipo de proyecto','Project code':'Código del proyecto','Contract value':'Valor del contrato','Job-site address':'Dirección del sitio','Start date':'Fecha de inicio','Target finish':'Fecha estimada de término','Supervisor':'Supervisor','Job-site contact':'Contacto del sitio','Save project':'Guardar proyecto','Save & import estimate':'Guardar e importar estimado','Estimate & actual':'Estimado y real','Plans':'Planos','Reports':'Reportes','Changes & extra work':'Cambios y trabajo adicional','Add estimate item':'Agregar partida','Import estimate PDF':'Importar estimado PDF','Upload plans':'Subir planos','Open projects':'Abrir proyectos',
'Employees':'Empleados','Subcontractors':'Subcontratistas','User accounts':'Cuentas de usuario','Crews':'Cuadrillas','Full name':'Nombre completo','Job title':'Puesto','Role':'Rol','Phone':'Teléfono','Email':'Correo electrónico','Owner':'Propietario','Administrator':'Administrador','Project manager':'Gerente de proyecto','Foreman':'Capataz','Field user':'Usuario de campo','Save team member':'Guardar miembro','Temporary password':'Contraseña temporal','Copy':'Copiar','Reset password':'Restablecer contraseña',
'Company settings':'Configuración de la empresa','Company name':'Nombre de la empresa','Trade / specialty':'Oficio / especialidad','Timezone':'Zona horaria','Week starts on':'La semana comienza el','Pricing visibility':'Visibilidad de precios','Save settings':'Guardar configuración','Profile settings':'Configuración del perfil','Profile photo':'Foto de perfil','Display name':'Nombre para mostrar','Language preference':'Preferencia de idioma','Appearance':'Apariencia','Light':'Claro','Dark':'Oscuro','Use device setting':'Usar configuración del dispositivo','Save profile':'Guardar perfil','Your account':'SU CUENTA',
'Help Center':'Centro de ayuda','Search help':'Buscar ayuda','Choose a help topic':'Elija un tema de ayuda','Step-by-step guidance will appear here.':'La guía paso a paso aparecerá aquí.','Manage plan':'Administrar plan','Monthly':'Mensual','Annual · two months free':'Anual · dos meses gratis','Payment methods & invoices':'Métodos de pago y facturas','Account & billing':'CUENTA Y FACTURACIÓN','No approved production':'No hay producción aprobada','Export CSV':'Exportar CSV','Efficiency':'Eficiencia','Labor hours':'Horas de mano de obra','Completed':'Completado','Remaining':'Restante','Planned':'Planeado','Actual':'Real','No results':'Sin resultados','No projects yet':'Aún no hay proyectos','No customers yet':'Aún no hay clientes','Loading…':'Cargando…','Try again':'Intentar de nuevo','Required':'Obligatorio'
};
const placeholders={
'Search projects…':'Buscar proyectos…','Search customers…':'Buscar clientes…','Search team…':'Buscar equipo…','Search reports…':'Buscar reportes…','Search setup, dailies, production, mobile…':'Buscar configuración, reportes, producción, móvil…','Type full name to sign':'Escriba su nombre completo para firmar','Optional: planned work or site conditions':'Opcional: trabajo planeado o condiciones del sitio','Clear, rain, windy…':'Despejado, lluvia, viento…','progress, concrete, east wall':'avance, concreto, muro este','Concrete, fasteners, pipe…':'Concreto, sujetadores, tubería…','Pump, excavator, lift…':'Bomba, excavadora, elevador…','Cause and duration':'Causa y duración','Positive observations or incidents':'Observaciones positivas o incidentes','What should happen next? Leave blank if unknown.':'¿Qué debe suceder después? Déjelo en blanco si no se sabe.'
};
const esLower=Object.fromEntries(Object.entries(es).map(([key,value])=>[key.toLowerCase(),value]));
const original=new Map(),originalAttributes=new Map();let language='en',running=false;
function translated(value){const trim=value.trim();if(!trim)return value;let result=es[trim]||esLower[trim.toLowerCase()];if(result&&trim===trim.toUpperCase())result=result.toUpperCase();if(!result){result=trim.replace(/\bNo assignment today\b/gi,'No hay asignación hoy').replace(/\bNo upcoming assignments\b/gi,'No hay próximas asignaciones').replace(/\bDaily report\b/gi,'Reporte diario').replace(/\bField user\b/gi,'Usuario de campo').replace(/\bAdministrator\b/gi,'Administrador')}return result===trim?value:value.replace(trim,result)}
function walk(root=document.body){if(!root||language!=='es'||running)return;running=true;const nodes=[];if(root.nodeType===3)nodes.push(root);else{const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);while(walker.nextNode())nodes.push(walker.currentNode)}for(const node of nodes){if(node.parentElement?.closest('script,style,textarea,option[data-user-content]'))continue;const next=translated(node.nodeValue);if(next!==node.nodeValue){if(!original.has(node))original.set(node,node.nodeValue);node.nodeValue=next}}const elements=root.nodeType===1?[root,...root.querySelectorAll('input,textarea,[aria-label],[title]')]:[];for(const element of elements){for(const attr of ['placeholder','aria-label','title']){const value=element.getAttribute?.(attr);if(value&&placeholders[value]){if(!originalAttributes.has(element))originalAttributes.set(element,{});const saved=originalAttributes.get(element);if(!(attr in saved))saved[attr]=value;element.setAttribute(attr,placeholders[value])}}}running=false}
function restore(){running=true;for(const [node,value] of original){if(node.isConnected)node.nodeValue=value}for(const [element,values] of originalAttributes){if(element.isConnected)for(const [attr,value] of Object.entries(values))element.setAttribute(attr,value)}original.clear();originalAttributes.clear();running=false}
function set(next){const chosen=next==='es'?'es':'en';if(chosen==='en'&&language==='es')restore();language=chosen;document.documentElement.lang=language;document.body?.classList.toggle('app-spanish',language==='es');if(language==='es')walk();}
new MutationObserver(records=>{if(language!=='es'||running)return;for(const record of records){if(record.type==='characterData')walk(record.target);else record.addedNodes.forEach(walk)}}).observe(document.documentElement,{subtree:true,childList:true,characterData:true});
window.PDLLocale={set,refresh:()=>walk(),language:()=>language};
})();
