'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{execFileSync}=require('node:child_process');
if(!process.argv.includes('--zone')){for(const TZ of ['America/Los_Angeles','Pacific/Kiritimati','Etc/UTC'])execFileSync(process.execPath,[__filename,'--zone'],{env:{...process.env,TZ},stdio:'inherit'});process.exit(0)}
const source=fs.readFileSync(__dirname+'/app.js','utf8'),html=fs.readFileSync(__dirname+'/index.html','utf8'),nodes=new Map(),messages=[];
function node(id){if(!nodes.has(id))nodes.set(id,{value:'',checked:false,hidden:false,disabled:false,dataset:{},showModal(){this.open=true},close(){this.open=false}});return nodes.get(id)}
function fn(name){const lines=source.split('\n'),start=lines.findIndex(line=>new RegExp(`^(?:async )?function ${name}\\(`).test(line));assert.ok(start>=0,name);if(lines[start].trimEnd().endsWith('}'))return lines[start];return lines.slice(start,lines.findIndex((line,i)=>i>start&&line.trimEnd()==='}')+1).join('\n')}
const card={id:10,memberId:1,projectId:1,date:'2026-09-20',inAt:'2026-09-20T15:00:00.000Z',outAt:'2026-09-20T23:00:00.000Z',hours:7.5,status:'draft',breaks:[{type:'paid_rest',startedAt:'2026-09-20T16:00:00.000Z',endedAt:'2026-09-20T16:15:00.000Z'},{type:'unpaid_meal',startedAt:'2026-09-20T19:00:00.000Z',endedAt:'2026-09-20T19:30:00.000Z'}],fieldAccess:{canEdit:true,canSubmit:true,reason:'Review your times, then submit for office approval.',revision:'fresh-revision'}};
const context={$:node,company:{timezone:'America/Los_Angeles'},currentUser:{id:6,memberId:1,role:'field'},currentRole:'field',signedInCompanyId:()=>context.tenant,tenant:'a',team:[{id:1,name:'Synthetic Worker'}],projects:[{id:1,name:'Synthetic Job',code:'QA'}],timeCards:[card],notify:message=>messages.push(message),loadRole:async()=>{context.refreshes++},refreshTimeCards:async()=>{context.refreshes++},refreshes:0};
vm.createContext(context);
for(const name of ['escapeHtml','timeCardApproved','timeCardClock','timeCardLocalInput','timeCardFilters','timeCardRowMarkup','timeCardPageMessage','timeCardFormMessage','timeCardEditContext','openTimeCardEditor','timeCardEditedBreaks','timeCardEditedInstant'])vm.runInContext(fn(name),context);
vm.runInContext('let timeCardEditBusy=false,timeCardEditSequence=0;',context);
vm.runInContext(source.slice(source.indexOf("$('#timecard-edit-save').onclick="),source.indexOf('function openManualTimeCard()')),context);
const normalize=value=>JSON.parse(JSON.stringify(value));
let calls=[],resolve;
context.api=async(path,options)=>{calls.push({path,body:JSON.parse(options.body)});return new Promise(r=>resolve=r)};
const save=()=>node('#timecard-edit-save').onclick();
(async()=>{
  node('#timecard-from').value='2099-01-01';node('#timecard-status').value='approved';assert.deepEqual(normalize(context.timeCardFilters()),{projectId:'all',memberId:'all',status:'all',from:'',to:''},'hidden office filters never suppress old field cards');
  for(const instant of ['2025-11-02T09:30:37.123Z','2026-09-20T15:00:59.321Z'])assert.equal(context.timeCardEditedInstant(context.timeCardLocalInput(instant),instant),instant,'unchanged times preserve seconds and the correct repeated DST hour');
  const row=context.timeCardRowMarkup(card,false,false);assert.match(row,/Open \/ edit/);assert.match(row,/data-timecard-submit="10"/);assert.match(row,/2026-09-20/);assert.doesNotMatch(row,/data-timecard-(approve|unapprove|delete)/);
  for(const status of ['submitted','approved']){const locked={...card,status,fieldAccess:{canEdit:false,canSubmit:false,reason:'Ask office for a correction.'}};const markup=context.timeCardRowMarkup(locked,false,false);assert.doesNotMatch(markup,/data-timecard-(edit|submit|approve|delete)/);assert.match(markup,/Ask office/)}
  assert.doesNotMatch(context.timeCardRowMarkup({...card,memberId:2},false,false),/data-timecard-(edit|submit)/,'even malformed client access flags cannot show coworker mutations');
  context.openTimeCardEditor(card);assert.equal(node('#timecard-edit-modal').open,true);assert.equal(new Date(node('#timecard-edit-in').value).toISOString(),card.inAt,'local form round-trips actual instant across device zones');assert.match(node('#timecard-edit-zone').textContent,/device timezone/);assert.match(node('#timecard-edit-zone').textContent,/America\/Los_Angeles/);assert.equal(node('#timecard-meal-start').value,context.timeCardLocalInput(card.breaks[1].startedAt));
  await save();assert.match(node('#timecard-edit-message').textContent,/Explain why/);assert.equal(calls.length,0);
  node('#timecard-edit-reason').value='Correct missed end time';const pending=save();await save();assert.equal(calls.length,1,'double click sends once');assert.equal(node('#timecard-edit-save').disabled,true);assert.equal(calls[0].body.revision,'fresh-revision');assert.deepEqual(calls[0].body.breaks,card.breaks.map(row=>row.type==='unpaid_meal'?{...row,missed:false,interrupted:false}:row),'unrelated paid breaks survive editing');resolve({});await pending;assert.equal(node('#timecard-edit-modal').open,false);assert.equal(context.refreshes,1);assert.match(messages.at(-1),/Draft.*submit/);
  context.openTimeCardEditor(card);context.api=async()=>{throw Error('Network interrupted')};node('#timecard-edit-reason').value='Keep my correction';await save();assert.equal(node('#timecard-edit-modal').open,true);assert.equal(node('#timecard-edit-reason').value,'Keep my correction');assert.match(node('#timecard-edit-message').textContent,/Network interrupted/);assert.equal(node('#timecard-edit-save').disabled,false);
  node('#timecard-edit-modal').close();context.openTimeCardEditor(card);assert.equal(node('#timecard-edit-reason').value,'');assert.equal(node('#timecard-edit-message').hidden,true,'cancel and reopen clears old errors');
  context.api=async(path,options)=>{calls.push({path,body:JSON.parse(options.body)});return new Promise(r=>resolve=r)};node('#timecard-edit-reason').value='Late response';const late=save();context.tenant='b';resolve({});await late;assert.equal(context.refreshes,1,'old tenant response cannot refresh another workspace');const count=calls.length;await save();assert.equal(calls.length,count,'old draft cannot be sent from new tenant');assert.equal(node('#timecard-edit-modal').open,false);
  context.tenant='a';context.openTimeCardEditor({...card,fieldAccess:{canEdit:false,reason:'Closed payroll: ask office.'}});assert.equal(node('#timecard-edit-modal').open,false);assert.match(node('#timecard-page-message').textContent,/Closed payroll/);
  assert.match(html,/including earlier days and weeks/);assert.match(html,/id="timecard-edit-zone"/);assert.match(html,/<\/div><p class="form-message" id="timecard-page-message"/,'field errors are outside hidden office actions');
  console.log('Late-time UI passed in '+process.env.TZ+': historical visibility, ownership, locked guidance, date round trips, edit/save, preserved breaks, duplicate save, retry, cancel/reopen and tenant-switch protection.');
})().catch(error=>{console.error(error);process.exitCode=1});
