'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('app.js','utf8'),styles=fs.readFileSync('styles.css','utf8'),index=fs.readFileSync('index.html','utf8');
function code(name){const lines=source.split('\n'),start=lines.findIndex(line=>line.startsWith(`function ${name}(`));assert.ok(start>=0);if(lines[start].trimEnd().endsWith('}'))return lines[start];const end=lines.findIndex((line,i)=>i>start&&line.trimEnd()==='}');return lines.slice(start,end+1).join('\n')}
const nodes=new Map();function node(selector){if(!nodes.has(selector)){const classes=new Set();nodes.set(selector,{innerHTML:'',value:'',classList:{toggle:(key,on)=>on?classes.add(key):classes.delete(key),contains:key=>classes.has(key),remove:key=>classes.delete(key)},focus(){this.focused=true},scrollIntoView(){this.scrolled=true}})}return nodes.get(selector)}
let mobile=true,buttons=[];const context={$:node,$$:selector=>selector==='[data-customer]'?buttons:[],window:{matchMedia:()=>({matches:mobile})},customers:[{id:1,name:'First',contact:'One'},{id:2,name:'Second',contact:'<img src=x onerror=attack()>',email:'two@example.invalid',phone:'555-0002'}],projects:[],escapeHtml:value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'),budgetNumber:()=>0,moneyShort:()=>'$0',companyTracksContractValues:()=>false};vm.createContext(context);
for(const name of ['setCustomerDetailOpen','renderCustomers'])vm.runInContext(code(name),context);
vm.runInContext(source.match(/const renderCustomersBeforeContractValues=renderCustomers;[\s\S]*?\n};/)[0],context);
buttons=[{dataset:{customer:'1'}},{dataset:{customer:'2'}}];context.renderCustomers();buttons[1].onclick();
assert.equal(node('#customers-page .customer-layout').classList.contains('customer-detail-open'),true,'tap opens mobile detail');assert.match(node('#customer-detail').innerHTML,/two@example.invalid/);assert.match(node('#customer-detail').innerHTML,/555-0002/);assert.ok(!node('#customer-detail').innerHTML.includes('<img'));assert.equal(node('#customer-detail').focused,true);assert.equal(node('#customer-detail').scrolled,true);assert.equal(node('#customer-detail .customer-metrics .customer-metric:nth-child(3)').hidden,true,'contract-value redaction retained');
node('[data-customer-back]').onclick();assert.equal(node('#customers-page .customer-layout').classList.contains('customer-detail-open'),false);assert.equal(node('#customer-list').focused,true);
node('#customer-search').value='Second';context.renderCustomers(undefined,'Second');assert.ok(!node('#customer-list').innerHTML.includes('First'),'pricing wrapper preserves search filter');buttons[1].onclick();assert.match(node('#customer-detail').innerHTML,/Second/);
context.renderCustomers(undefined,'Missing');assert.equal(node('#customers-page .customer-layout').classList.contains('customer-detail-open'),false,'empty search closes stale detail');
mobile=false;node('#customer-detail').focused=false;node('#customer-detail').scrolled=false;context.setCustomerDetailOpen(true);assert.equal(node('#customer-detail').focused,false,'desktop selection keeps focus in list');
const back=source.match(/^\$\('#app-back-button'\)\.onclick=[^\r\n]+/m)[0];context.history={state:{pdlIndex:1},back:()=>{context.historyBack=true}};context.showPage=()=>{};vm.runInContext(back,context);mobile=true;node('#customers-page').classList.toggle('active',true);node('#app-back-button').onclick();assert.equal(node('#customers-page .customer-layout').classList.contains('customer-detail-open'),false);assert.equal(context.historyBack,undefined,'standalone app Back returns to list before leaving page');node('#app-back-button').onclick();assert.equal(context.historyBack,true);
assert.match(styles,/\.customer-layout\.customer-detail-open \.customer-detail\{display:block/);assert.match(styles,/\.customer-layout\.customer-detail-open \.customer-list\{display:none/);assert.match(styles,/\.customer-detail-back\{display:inline-flex;min-height:44px/);assert.match(index,/id="customer-detail" tabindex="-1"/);assert.match(index,/styles.css\?v=20261004-team-alerts/);assert.match(index,/app.js\?v=20261004-team-alerts/);assert.equal(JSON.parse(fs.readFileSync('manifest.webmanifest','utf8')).display,'standalone');
console.log('Mobile customer regression passed: tap/detail/back, contact escaping, search forwarding, pricing redaction, desktop focus and standalone Back (VM/static fixtures; real iOS QA unverified).');
