'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {officeWorkspaceTools}=require('./office-workspace'),{availableCompanyTabs}=require('./company-settings-tabs'),{payPeriodReviewMarkup}=require('./time-approval-controls');
const base={mode:'office',canViewTime:true,timeCards:true,settingsTabs:['company','periods','activity']};
assert.deepEqual(officeWorkspaceTools(base).map(t=>t.id),['schedule','timecards','payreports','settings']);
for(const mode of ['field','field_timeoff'])assert.deepEqual(officeWorkspaceTools({...base,mode}),[]);
assert.deepEqual(officeWorkspaceTools({...base,canViewTime:false,settingsTabs:[]}).map(t=>t.id),['schedule']);
assert.deepEqual(officeWorkspaceTools({...base,timeCards:false}).map(t=>t.id),['schedule','settings']);
const nodes=new Map(),listeners={};function node(key){if(!nodes.has(key))nodes.set(key,{hidden:true,innerHTML:'',focus(options){this.focused=options},scrollIntoView(options){this.scrolled=options}});return nodes.get(key)}
const context={currentRole:'office',currentUser:{role:'owner'},company:{features:{timeCards:true}},$:node,$$:()=>[node('report-shortcut')],canViewTime(){const u=context.currentUser;return u.role==='owner'||u.role==='admin'&&u.permissions?.manageTime===true||u.role==='project_manager'&&(u.permissions?.viewTime===true||u.permissions?.manageTime===true)},timeCardsOn:()=>context.company.features.timeCards===true,availableCompanyTabs,renderEverything(){context.renders=(context.renders||0)+1},showPage(page){context.opened=page},document:{addEventListener(type,fn){listeners[type]=fn}}};
vm.createContext(context);vm.runInContext(fs.readFileSync('office-workspace.js','utf8'),context);
assert.match(node('#office-workspace-tools').innerHTML,/Pay-period reports/);assert.equal(node('report-shortcut').hidden,false);
function click(id){listeners.click({target:{closest:()=>({dataset:{officeTool:id}})}})}
click('payreports');assert.equal(context.opened,'timecards');assert.equal(node('#pay-period-panel').scrolled.block,'start');assert.equal(node('#pay-period-panel').focused.preventScroll,true);
click('settings');assert.equal(context.opened,'settings');context.currentUser={role:'project_manager',permissions:{viewTime:true}};context.renderEverything();assert.match(node('#office-workspace-tools').innerHTML,/Time review/);assert.doesNotMatch(node('#office-workspace-tools').innerHTML,/data-office-tool="settings"/);context.opened=null;click('settings');assert.equal(context.opened,null);
context.currentUser={role:'admin',permissions:{}};context.renderEverything();assert.doesNotMatch(node('#office-workspace-tools').innerHTML,/Pay-period reports/);assert.equal(node('report-shortcut').hidden,true);context.opened=null;click('payreports');assert.equal(context.opened,null,'stale shortcut rechecks authorization');
context.currentRole='field';context.renderEverything();assert.equal(node('#office-workspace-tools').hidden,true);assert.equal(node('#office-workspace-tools').innerHTML,'');
context.currentRole='office';context.currentUser={role:'owner'};context.company.features.timeCards=false;context.renderEverything();context.opened=null;click('timecards');assert.equal(context.opened,null);assert.ok(context.renders>=4);
const summary={period:{from:'2026-10-01',to:'2026-10-15',timeZone:'America/Los_Angeles'},approvedHours:16,ready:false,review:{draft:1,submitted:2,running:0,missingScheduledEntries:1},datePolicy:'Inclusive dates',people:[{name:'<script>worker</script>',hours:16}],missingEntries:[{person:'<img src=x>',project:'Fixture',date:'2026-10-02'}]};
const markup=payPeriodReviewMarkup(summary,true);assert.match(markup,/16 <span>company total/);assert.match(markup,/Needs review/);assert.match(markup,/2 submitted/);assert.match(markup,/data-pay-capture disabled/);assert.ok(markup.indexOf('</details>')<markup.indexOf('data-pay-capture'));assert.match(markup,/&lt;script&gt;worker/);assert.doesNotMatch(markup,/<img|<script/);
const readonly=payPeriodReviewMarkup(summary,false);assert.match(readonly,/assigned total/);assert.doesNotMatch(readonly,/data-pay-capture|data-pay-download|data-pay-history/);assert.match(payPeriodReviewMarkup({...summary,ready:true},false),/Assigned checks clear/);
const ready=payPeriodReviewMarkup({...summary,ready:true,review:{},latestExport:{id:'fixed"<>',version:2,changed:true}},true);assert.match(ready,/Ready to export/);assert.match(ready,/data-pay-capture >/);assert.match(ready,/Create corrected export/);assert.match(ready,/data-pay-download="fixed&quot;&lt;&gt;"/);assert.match(ready,/Time changed since the latest fixed export/);assert.match(payPeriodReviewMarkup({...summary,ready:true},true,true),/data-pay-capture disabled/);
const html=fs.readFileSync('index.html','utf8');assert.match(html,/aria-label="Office shortcuts"/);assert.match(html,/id="pay-period-panel" class="panel" tabindex="-1"/);assert.ok(html.indexOf('company-settings-tabs.js')<html.indexOf('office-workspace.js'));
const {isPublicFile}=require('./public-file-policy');assert.equal(isPublicFile(process.cwd(),process.cwd()+'/office-workspace.js'),true);assert.equal(isPublicFile(process.cwd(),process.cwd()+'/office-workspace.test.js'),false);
const styles=fs.readFileSync('styles.css','utf8');assert.match(styles,/\.pay-review-status\.needs-review\{color:#8a5200\}/);assert.match(styles,/:root\[data-theme="dark"\] \.office-tool:focus-visible\{outline-color:#91b6ff\}/);
console.log('Recovered office navigation/pay review tests passed: roles/features, stale clicks, focus, visible export actions, escaping, private test files. Synthetic DOM only.');
