'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const policy=require('./pay-periods');
// Policy fixtures explicitly cover company-local calendar boundaries, including an overnight card.
assert.equal(policy.validDate('2028-02-29'),true);for(const date of ['2026-02-29','2026-02-30','10/04/2026','2026-13-01',''])assert.equal(policy.validDate(date),false);
assert.equal(policy.dateAt('2026-03-08T07:30:00Z','America/Los_Angeles'),'2026-03-07');assert.equal(policy.dateAt('2026-11-01T08:30:00Z','America/Los_Angeles'),'2026-11-01');assert.equal(policy.dateAt('2026-11-01T09:30:00Z','America/Los_Angeles'),'2026-11-01');assert.equal(policy.dateAt('2026-10-05','America/Los_Angeles'),null);
const actor={name:'Synthetic Owner'},fixture={company:{id:'synthetic',timezone:'America/Los_Angeles'},team:[{id:1,name:'=Synthetic person'}],projects:[{id:1,name:'Synthetic project'}],timeCards:[{id:1,memberId:1,projectId:1,inAt:'2026-10-05T06:00:00Z',outAt:'2026-10-05T10:00:00Z',hours:4,status:'approved'}]};
const oneDay=policy.savePeriod(fixture,{label:'One day',from:'2026-10-04',to:'2026-10-04'},actor);assert.equal(policy.summary(fixture,oneDay).approvedHours,4,'full overnight card assigned to local clock-in day');
assert.throws(()=>policy.savePeriod(fixture,{from:'2026-10-04',to:'2026-10-06'},actor),e=>e.statusCode===409);assert.throws(()=>policy.savePeriod(fixture,{from:'2026-10-06',to:'2026-10-05'},actor),e=>e.statusCode===400);
policy.savePeriod(fixture,{label:'Renamed',from:'2026-10-04',to:'2026-10-04',reason:'Clarify name'},actor,oneDay.id);assert.equal(fixture.auditLog.at(-1).before.label,'One day');assert.equal(fixture.auditLog.at(-1).after.label,'Renamed');
const boundaryDb={...fixture,timeCards:[{...fixture.timeCards[0],id:10,inAt:'2026-10-04T06:59:00Z',outAt:'2026-10-04T07:59:00Z',hours:1},{...fixture.timeCards[0],id:11,inAt:'2026-10-04T07:00:00Z',outAt:'2026-10-04T08:00:00Z',hours:1},{...fixture.timeCards[0],id:12,inAt:'2026-10-05T06:59:00Z',outAt:'2026-10-05T07:59:00Z',hours:1},{...fixture.timeCards[0],id:13,inAt:'2026-10-05T07:00:00Z',outAt:'2026-10-05T08:00:00Z',hours:1}]};assert.deepEqual(policy.summary(boundaryDb,oneDay).records.map(r=>r.id),[11,12],'exact local start and end boundaries included; adjacent days excluded');
const fixed=policy.capture(fixture,oneDay,{},actor);assert.match(policy.csv(fixed),/"'=Synthetic person"/);fixture.timeCards[0].hours=3;assert.equal(fixed.summary.approvedHours,4);assert.throws(()=>policy.savePeriod(fixture,{from:'2026-10-04',to:'2026-10-04',reason:'Locked'},actor,oneDay.id),e=>e.statusCode===409);
const corrected=policy.capture(fixture,oneDay,{supersedesId:fixed.id,reason:'Correct hours'},actor);assert.equal(corrected.summary.approvedHours,3);assert.equal(corrected.supersedesId,fixed.id);assert.throws(()=>policy.capture(fixture,oneDay,{supersedesId:fixed.id,reason:'Stale version'},actor),e=>e.statusCode===409);
fixture.assignments=[{date:'2026-10-04',projectId:1,memberIds:[1,2]}];assert.equal(policy.summary(fixture,oneDay).review.missingScheduledEntries,1);assert.equal(policy.summary(fixture,oneDay).missingEntries[0].memberId,'2');
for(const changed of [{outAt:null},{hours:null},{hours:true},{hours:' '},{outAt:'2026-10-05T05:00:00Z'},{outAt:'2026-10-05T10:00:00'},{status:'submitted'},{status:'draft'},{inAt:'invalid'}]){const db={...fixture,assignments:[],timeCards:[{...fixture.timeCards[0],...changed}]};assert.equal(policy.summary(db,oneDay).ready,false);assert.throws(()=>policy.capture(db,oneDay,{},actor),e=>e.statusCode===409)}

// Complete synthetic HTTP journey: two companies, roles, time review and immutable exports.
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'pdl-custom-period-'));
process.env.PDL_DB_FILE=path.join(temp,'db.json');process.env.PDL_PLATFORM_FILE=path.join(temp,'platform.json');process.env.PDL_SUPABASE_ENABLED='0';process.env.PDL_TRANSACTIONAL_DB='off';process.env.PDL_REQUIRE_AUTH='1';process.env.PDL_EMAIL_DEV_MODE='1';process.env.PDL_FOUNDER_ENABLED='0';process.env.PDL_PLATFORM_KEY='synthetic-platform-key-over-32-characters';
for(const key of ['SENTRY_DSN','RESEND_API_KEY','OPENAI_API_KEY','STRIPE_SECRET_KEY'])delete process.env[key];
fs.copyFileSync('data/db.json',process.env.PDL_DB_FILE);fs.copyFileSync('data/platform.json',process.env.PDL_PLATFORM_FILE);
const {server}=require('./server');let base,restarted;
function client(headers={}){const jar=new Map();return async(route,method='GET',input)=>{const response=await fetch(base+route,{method,headers:{'Content-Type':'application/json',Cookie:[...jar].map(([k,v])=>k+'='+v).join('; '),...headers},...(input===undefined?{}:{body:JSON.stringify(input)})});for(const cookie of response.headers.getSetCookie()){const pair=cookie.split(';')[0],i=pair.indexOf('=');jar.set(pair.slice(0,i),pair.slice(i+1))}return{status:response.status,data:(response.headers.get('content-type')||'').includes('application/json')?await response.json():await response.text()}}}
function seedUser(companyId,role,permissions={},scope={}){const file=path.join(temp,'tenants',companyId+'.json'),db=JSON.parse(fs.readFileSync(file)),id=db.users.length+1,token=crypto.randomBytes(20).toString('hex');db.users.push({id,name:'Synthetic '+role,role,status:'Active',permissions,companyId,...scope});db.sessions.push({id:crypto.randomUUID(),userId:id,companyId,tokenHash:crypto.createHash('sha256').update(token).digest('hex'),expiresAt:'2035-01-01T00:00:00Z'});fs.writeFileSync(file,JSON.stringify(db));return client({Authorization:'Bearer '+token,'X-PDL-Company':companyId})}
async function listen(){await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port}
(async()=>{await listen();const owner=client(),other=client(),platform=client({'x-pdl-platform-key':process.env.PDL_PLATFORM_KEY});try{
  const signup=await owner('/api/signup','POST',{companyName:'Synthetic Pacific',ownerName:actor.name,email:'period-owner@example.invalid',password:'SyntheticPassword!42',timezone:'America/Los_Angeles',legalAccepted:true});assert.equal(signup.status,201);const companyId=signup.data.company.id;
  assert.equal((await owner('/api/pay-periods')).status,404,'feature off');
  assert.equal((await platform('/api/platform/companies/'+companyId+'/features','PATCH',{timeCards:true})).status,200);
  const foreign=await other('/api/signup','POST',{companyName:'Synthetic Eastern',ownerName:'Other Owner',email:'other-period@example.invalid',password:'SyntheticPassword!42',timezone:'America/New_York',legalAccepted:true});assert.equal(foreign.status,201);await platform('/api/platform/companies/'+foreign.data.company.id+'/features','PATCH',{timeCards:true});
  const member=await owner('/api/team','POST',{name:'Synthetic person',crew:'Crew A',role:'field'});assert.equal(member.status,201,JSON.stringify(member.data));
  const project=await owner('/api/projects','POST',{name:'Synthetic project',code:'QA',contractType:'estimated',estimateItems:[]});assert.equal(project.status,201);
  const period=await owner('/api/pay-periods','POST',{label:'Company custom 4–9',from:'2026-10-04',to:'2026-10-09'});assert.equal(period.status,201);const id=period.data.id,summaryRoute='/api/pay-periods/'+id+'/summary',exportsRoute='/api/pay-periods/'+id+'/exports';
  assert.equal((await owner('/api/pay-periods','POST',{from:'2026-10-09',to:'2026-10-13'})).status,409,'inclusive overlap');assert.equal((await owner('/api/pay-periods','POST',{from:'2026-10-10',to:'2026-10-21'})).status,201,'adjacent custom dates');assert.equal((await owner('/api/pay-periods','POST',{from:'2026-02-30',to:'2026-03-01'})).status,400);
  assert.equal((await owner('/api/pay-periods/'+id,'PATCH',{label:'Custom 4–9 revised',from:'2026-10-04',to:'2026-10-09'})).status,400,'date edits require a reason');assert.equal((await owner('/api/pay-periods/'+id,'PATCH',{label:'Custom 4–9 revised',from:'2026-10-04',to:'2026-10-09',reason:'Clarify company period name'})).status,200);
  const eastern=await other('/api/pay-periods','POST',{label:'Other custom 5–17',from:'2026-10-05',to:'2026-10-17'});assert.equal(eastern.status,201);assert.equal(eastern.data.timeZone,'America/New_York');assert.equal((await other(summaryRoute)).status,404);assert.equal((await other('/api/pay-periods')).data.periods.length,1);
  const card=await owner('/api/time-cards','POST',{memberId:member.data.id,projectId:project.data.id,inAt:'2026-10-05T06:00:00Z',outAt:'2026-10-05T10:00:00Z',reason:'Synthetic overnight punches'});assert.equal(card.status,201);assert.equal(card.data.date,'2026-10-04');
  assert.equal((await owner(summaryRoute)).data.review.draft,1);assert.equal((await owner(exportsRoute,'POST',{})).status,409);assert.equal((await owner('/api/time-cards/'+card.data.id+'/submit','POST',{})).status,200);assert.equal((await owner(summaryRoute)).data.review.submitted,1);assert.equal((await owner('/api/time-cards/approve','POST',{ids:[card.data.id]})).status,200);
  const field=seedUser(companyId,'field',{}, {memberId:member.data.id}),adminDenied=seedUser(companyId,'admin',{}),admin=seedUser(companyId,'admin',{manageTime:true}),pm=seedUser(companyId,'project_manager',{viewTime:true},{projectIds:[project.data.id],assignedCrews:['Crew A']});
  for(const denied of [field,adminDenied]){assert.equal((await denied('/api/pay-periods')).status,403);const state=await denied('/api/state');assert.equal(state.status,200);assert.equal(Object.hasOwn(state.data,'payPeriods'),false);assert.equal(Object.hasOwn(state.data,'payPeriodExports'),false);if(denied===adminDenied)assert.equal(Object.hasOwn(state.data,'timeCards'),false);assert.ok(!(state.data.auditLog||[]).some(e=>String(e.type).startsWith('pay_period_')))}
  assert.equal((await pm(summaryRoute)).data.approvedHours,4);assert.equal((await pm('/api/pay-periods','POST',{from:'2026-11-01',to:'2026-11-05'})).status,403);assert.equal((await pm(exportsRoute)).status,403);assert.equal((await pm('/api/time-cards/'+card.data.id+'/unapprove','POST',{})).status,403);
  assert.equal((await admin('/api/pay-periods')).data.canConfigure,true);const captured=await admin(exportsRoute,'POST',{});assert.equal(captured.status,201,JSON.stringify(captured.data));assert.equal(captured.data.summary.approvedHours,4);assert.equal((await owner(summaryRoute)).data.latestExport.changed,false);
  const v1=exportsRoute+'/'+captured.data.id,originalCsv=(await owner(v1+'.csv')).data;assert.match(originalCsv,/Approved hours/);assert.equal((await other(v1)).status,404);assert.equal((await owner('/api/pay-periods/'+id,'PATCH',{label:'Changed',from:'2026-10-04',to:'2026-10-09',reason:'Should remain locked'})).status,409);
  assert.equal((await owner('/api/time-cards/'+card.data.id+'/unapprove','POST',{})).status,200);assert.equal((await owner('/api/time-cards/'+card.data.id,'PATCH',{outAt:'2026-10-05T09:00:00Z',reason:'Correct missed clock-out'})).status,200);assert.equal((await owner(exportsRoute,'POST',{supersedesId:captured.data.id,reason:'Unapproved correction'})).status,409);await owner('/api/time-cards/'+card.data.id+'/submit','POST',{});await owner('/api/time-cards/'+card.data.id+'/approve','POST',{});assert.equal((await owner(summaryRoute)).data.latestExport.changed,true);
  assert.equal((await owner(exportsRoute,'POST',{})).status,409);assert.equal((await owner(exportsRoute,'POST',{supersedesId:captured.data.id,reason:''})).status,400);const v2=await owner(exportsRoute,'POST',{supersedesId:captured.data.id,reason:'Verified corrected clock-out'});assert.equal(v2.status,201);assert.equal(v2.data.version,2);assert.equal(v2.data.summary.approvedHours,3);assert.equal((await owner(v1+'.csv')).data,originalCsv);assert.equal((await owner(exportsRoute,'POST',{supersedesId:captured.data.id,reason:'Stale'})).status,409);
  const hiddenMember=await owner('/api/team','POST',{name:'Hidden Crew B',crew:'Crew B',role:'field'}),hiddenProject=await owner('/api/projects','POST',{name:'Hidden project',code:'HID',contractType:'estimated',estimateItems:[]});assert.equal(hiddenMember.status,201);assert.equal(hiddenProject.status,201);
  const hiddenCard=await owner('/api/time-cards','POST',{memberId:hiddenMember.data.id,projectId:hiddenProject.data.id,inAt:'2026-10-06T15:00:00Z',outAt:'2026-10-06T17:00:00Z',reason:'Scope fixture'});assert.equal(hiddenCard.status,201);await owner('/api/time-cards/'+hiddenCard.data.id+'/submit','POST',{});await owner('/api/time-cards/'+hiddenCard.data.id+'/approve','POST',{});
  const pmSummary=(await pm(summaryRoute)).data;assert.equal(pmSummary.approvedHours,3);assert.ok(pmSummary.records.every(r=>r.projectId===project.data.id));assert.ok(!JSON.stringify(pmSummary).includes('Hidden project'));assert.equal((await owner(summaryRoute)).data.approvedHours,5);
  const pmManage=seedUser(companyId,'project_manager',{manageTime:true},{projectIds:[project.data.id],assignedCrews:['Crew A']});assert.equal((await pmManage('/api/time-cards/'+hiddenCard.data.id+'/unapprove','POST',{})).status,404);assert.equal((await pmManage(exportsRoute,'POST',{})).status,403);
  const otherMember=await other('/api/team','POST',{name:'Other person',crew:'Other',role:'field'}),otherProject=await other('/api/projects','POST',{name:'Other project',code:'OTH',contractType:'estimated',estimateItems:[]}),otherCard=await other('/api/time-cards','POST',{memberId:otherMember.data.id,projectId:otherProject.data.id,inAt:'2026-10-05T06:00:00Z',outAt:'2026-10-05T10:00:00Z',reason:'Same instant in Eastern timezone'});assert.equal(otherCard.status,201);assert.equal(otherCard.data.date,'2026-10-05');await other('/api/time-cards/'+otherCard.data.id+'/submit','POST',{});await other('/api/time-cards/'+otherCard.data.id+'/approve','POST',{});assert.equal((await other('/api/pay-periods/'+eastern.data.id+'/summary')).data.approvedHours,4);
  const file=path.join(temp,'tenants',companyId+'.json'),db=JSON.parse(fs.readFileSync(file));db.assignments.push({id:1,date:'2026-10-09',projectId:project.data.id,memberIds:[member.data.id]});db.timeCards.push({id:99,memberId:member.data.id,projectId:project.data.id,date:'2026-10-08',inAt:'2026-10-08T16:00:00Z',outAt:null,hours:null,status:'submitted'});fs.writeFileSync(file,JSON.stringify(db));assert.equal((await owner(summaryRoute)).data.review.missingScheduledEntries,1);assert.equal((await owner(exportsRoute,'POST',{supersedesId:v2.data.id,reason:'Incomplete'})).status,409);assert.equal((await owner('/api/time-cards/99/approve','POST',{})).status,409);assert.equal((await owner('/api/time-cards/approve','POST',{ids:[99]})).status,409);
  const audit=JSON.parse(fs.readFileSync(file)).auditLog;assert.ok(audit.some(a=>a.type==='pay_period_export_created'&&a.exportId===v2.data.id));assert.ok(JSON.parse(fs.readFileSync(file)).timeCards.find(c=>c.id===card.data.id).history.some(h=>h.action==='Times edited'&&h.reason==='Correct missed clock-out'));
  await new Promise(resolve=>server.close(resolve));
  restarted=require('node:child_process').spawn(process.execPath,['-e',"const {server}=require('./server');server.listen(0,'127.0.0.1',()=>process.send({port:server.address().port}));process.on('message',()=>server.close(()=>process.exit(0)));"],{cwd:__dirname,env:{...process.env},stdio:['ignore','ignore','pipe','ipc']});restarted.stderr.on('data',()=>{});const port=await new Promise((resolve,reject)=>{restarted.once('message',m=>resolve(m.port));restarted.once('error',reject);restarted.once('exit',code=>reject(Error('Restart process exited '+code)))});base='http://127.0.0.1:'+port;assert.deepEqual((await owner(v1)).data,captured.data,'immutable export survives a new server process reading persisted files');assert.deepEqual((await owner(exportsRoute+'/'+v2.data.id)).data,v2.data);assert.equal((await other('/api/pay-periods')).data.periods[0].from,'2026-10-05');
  assert.equal((await owner('/time-approval-controls.js')).status,200);assert.equal((await owner('/pay-periods.js')).status,404);
  console.log('Custom pay periods passed: tenant-specific dates/timezones, inclusive overnight/DST, invalid/overlap gates, complete/submitted approval, scoped roles, frozen CSV/version corrections, audit and process-restart persistence (synthetic local HTTP; no providers/browser).');
}finally{if(restarted&&restarted.exitCode===null){const exited=new Promise(resolve=>restarted.once('exit',resolve));restarted.send('stop');await exited}if(server.listening)await new Promise(resolve=>server.close(resolve));fs.rmSync(temp,{recursive:true,force:true})}})().catch(error=>{console.error(error);process.exitCode=1;server.close()});
