const $=selector=>document.querySelector(selector);
let data,audit=[],helpItems=[];
async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options}),result=await response.json();if(!response.ok)throw new Error(result.error);return result}
function safe(value){return String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function renderHelp(){const query=$('#platform-help-search').value.trim().toLowerCase(),items=helpItems.filter(item=>!query||`${item.title} ${item.category} ${item.summary}`.toLowerCase().includes(query));$('#platform-help').innerHTML=items.length?items.map(item=>`<div class="row help-row"><span><strong>${safe(item.title)}</strong><small>${safe(item.category)} · ${safe(item.summary)}</small></span><span class="badge">${safe(item.audience)}</span><b>${safe(item.status)}</b></div>`).join(''):'<p>No matching help content.</p>'}
function render(){const metrics=data.metrics;$('#metrics').innerHTML=[['COMPANIES',metrics.companies],['ACTIVE TRIALS',metrics.trials],['MONTHLY REVENUE',`$${metrics.monthlyRecurringRevenue}`],['CUSTOMER USERS',metrics.users]].map(item=>`<div class="metric"><small>${item[0]}</small><strong>${item[1]}</strong></div>`).join('');$('#companies').innerHTML=data.companies.map(company=>`<div class="row"><span><strong>${safe(company.name)}</strong><small>${safe(company.trade||'Trade not set')} · ${company.projects} projects · ${company.users} users</small></span><span class="badge">${safe(company.plan)}</span><b>$${company.planPrice}/mo</b></div>`).join('');$('#staff').innerHTML=data.staff.map(member=>`<div class="row"><span><strong>${safe(member.name)}</strong><small>${safe(member.email)}</small></span><span class="badge">${safe(member.role.replace('_',' '))}</span><b>${safe(member.status)}</b></div>`).join('');$('#audit').innerHTML=audit.length?audit.slice(0,25).map(event=>`<div class="row"><span><strong>${safe(event.action.replaceAll('_',' '))}</strong><small>${safe(event.actorName)} · ${safe(event.reason||'No reason')} · ${new Date(event.at).toLocaleString()}</small></span><span class="badge">${safe(event.companyId||'platform')}</span></div>`).join(''):'<p>No platform access events yet.</p>';renderHelp()}
async function load(){[data,audit,helpItems]=await Promise.all([api('/api/platform/overview'),api('/api/platform/audit'),api('/api/platform/help')]);render()}
$('#add-staff').onclick=()=>{$('#staff-code').innerHTML='';$('#staff-modal').showModal()};
$('#save-staff').onclick=async()=>{try{const created=await api('/api/platform/users',{method:'POST',body:JSON.stringify({name:$('#staff-name').value,email:$('#staff-email').value,role:$('#staff-role').value})});data.staff.push(created);render();$('#staff-code').innerHTML=`<div class="code">One-time setup code for ${safe(created.name)}<b>${safe(created.setupCode)}</b><small>Expires in 72 hours.</small></div>`}catch(error){$('#staff-code').textContent=error.message}};
$('#add-help').onclick=()=>{$('#help-editor').querySelector('form').reset();$('#help-editor-message').textContent='';$('#help-editor').showModal()};
$('#save-help').onclick=async()=>{try{const created=await api('/api/platform/help',{method:'POST',body:JSON.stringify({title:$('#help-title').value,category:$('#help-category').value,type:$('#help-type').value,audience:$('#help-audience').value,summary:$('#help-summary').value,content:$('#help-content').value,url:$('#help-url').value,status:$('#help-status').value})});helpItems.push(created);renderHelp();$('#help-editor-message').innerHTML='<div class="code"><strong>Help item saved.</strong><small>Published items are now visible in the customer Help Center.</small></div>'}catch(error){$('#help-editor-message').textContent=error.message}};
$('#platform-help-search').oninput=renderHelp;
$('#support-access').onclick=()=>{$('#support-company').innerHTML=data.companies.map(company=>`<option value="${company.id}">${safe(company.name)}</option>`).join('');$('#support-actor').innerHTML=data.staff.map(member=>`<option value="${member.id}">${safe(member.name)} · ${safe(member.role.replace('_',' '))}</option>`).join('');$('#support-reason').value='';$('#support-result').innerHTML='';$('#support-modal').showModal()};
$('#create-support').onclick=async()=>{try{const grant=await api('/api/platform/support-access',{method:'POST',body:JSON.stringify({companyId:$('#support-company').value,actorUserId:+$('#support-actor').value,reason:$('#support-reason').value,minutes:+$('#support-minutes').value})});$('#support-result').innerHTML=`<div class="code"><strong>Audited support session</strong><a href="${grant.url}" target="_blank">Open ${safe(grant.companyName)}</a><small>Expires ${new Date(grant.expiresAt).toLocaleTimeString()}</small></div>`;audit=await api('/api/platform/audit');render()}catch(error){$('#support-result').textContent=error.message}};
load();
