'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('platform.js','utf8'),html=fs.readFileSync('platform.html','utf8');
function element(id='',dataset={}){const classes=new Set(),attrs={};return{id,dataset,value:'',innerHTML:'',textContent:'',hidden:false,disabled:false,open:false,classList:{toggle(n,on){if(on)classes.add(n);else classes.delete(n)},contains:n=>classes.has(n)},setAttribute(k,v){attrs[k]=v},removeAttribute(k){delete attrs[k]},getAttribute:k=>attrs[k],focus(){this.focused=true},showModal(){this.open=true},close(){this.open=false},querySelector(){return{reset(){}}}}}
function company(id,name,extra={}){return{id,name,trade:'General contractor',plan:'growth',planPrice:100,subscriptionStatus:'Active',accountType:'standard',billingExempt:false,cohort:'',projects:2,users:3,reports:4,summary:'Account activity',health:{score:100,status:'Healthy',alerts:[]},...extra}}
const companies=[company('alpha','Alpha Construction',{cohort:'Founding 25',lastReport:'2026-10-01',createdAt:'2026-08-01'}),company('beta','Beta Concrete',{trade:'Concrete',subscriptionStatus:'Trial',health:{score:40,status:'At risk',alerts:['No dailies']},trialEndsAt:'2099-12-31',createdAt:'2026-09-01'}),company('demo','Sales Demo',{demo:true}),company('qa','QA Sandbox'),company('annual','Annual Builders',{planPrice:1200,lastReport:'2026-10-03',createdAt:'2026-10-01'}),company('exempt','Legacy Build',{billingExempt:true,planPrice:900,accountType:'legacy',subscriptionStatus:'Legacy'}),company('pending','Pending Build',{subscriptionStatus:'Incomplete',health:{score:60,status:'Watch',alerts:['Onboarding']}}),company('x"<&?','<Quoted Company>',{subscriptionStatus:'Past due',summary:'<img src=x>'})];
const fixture={companies,staff:[],onboardingOrders:[{id:'b',companyId:'beta',companyName:'Beta Concrete',package:'Guided',owner:'Owner',status:'Blocked',tasks:[{done:false}]},{id:'a',companyId:'alpha',companyName:'Alpha Construction',package:'Self serve',owner:'Owner',status:'Complete',tasks:[]}],supportTickets:[{id:'b',companyId:'beta',companyName:'Beta Concrete',subject:'Beta issue',status:'Open'},{id:'a',companyId:'alpha',companyName:'Alpha Construction',subject:'Alpha issue',status:'Closed'}],followUps:[{id:'b',companyId:'beta',companyName:'Beta Concrete',title:'Beta call',status:'Open'},{id:'a',companyId:'alpha',companyName:'Alpha Construction',title:'Alpha call',status:'Open'}]};
async function harness(hash='#overview'){
 const nodes=new Map(),get=id=>{if(!nodes.has(id))nodes.set(id,element(id));return nodes.get(id)};for(const n of ['scope','health','status'])get('company-'+n).value='all';get('company-sort').value='attention';
 const views=['overview','customers','onboarding','support','subscriptions','blog','help','team'],nav=views.map(view=>element('',{view})),listeners={},windows={},calls=[],pending=[];
 const location={hash,href:'/platform.html'+hash},stack=[hash];let index=0;
 const history={pushState(s,t,h){stack.splice(index+1);stack.push(h);index++;location.hash=h},replaceState(s,t,h){stack[index]=h;location.hash=h},back(){if(index){location.hash=stack[--index];windows.popstate();windows.hashchange()}},forward(){if(index<stack.length-1){location.hash=stack[++index];windows.popstate();windows.hashchange()}},get length(){return stack.length}};
 const document={title:'',querySelector(s){return get(s.startsWith('#')?s.slice(1):s)},querySelectorAll(s){if(s==='nav button')return nav;if(s==='.view')return views.map(v=>get(v+'-view'));if(s==='dialog[open]')return[...nodes.values()].filter(n=>n.open);throw Error('Unexpected '+s)},addEventListener(k,fn){(listeners[k]||=[]).push(fn)}};
 const response=(data,status=200)=>({ok:status<400,status,json:async()=>data});
 const ctx=vm.createContext({document,location,history,window:{addEventListener(k,fn){windows[k]=fn}},URLSearchParams,console,fetch:async(path,opts={})=>{const method=opts.method||'GET';calls.push({path,method,body:opts.body});const n=pending.findIndex(p=>p.path===path&&p.method===method);if(n>=0)return pending.splice(n,1)[0].promise;return response(path==='/api/config'?{authRequired:false}:path==='/api/platform/overview'?structuredClone(fixture):[])},alert(){throw Error('Unexpected alert')},confirm(){throw Error('Unexpected confirmation')}});
 vm.runInContext(source,ctx);await new Promise(r=>setImmediate(r));
 return{get,ctx,run:s=>vm.runInContext(s,ctx),calls,history,location,windows,document,nav,async click(selector,dataset={}){const target={dataset,closest:s=>s===selector?target:null};await Promise.all((listeners.click||[]).map(fn=>fn({target})))},async edit(id){for(const fn of listeners.input||[])await fn({target:{closest:s=>s==='dialog'?get(id):null}})},defer(path,method='POST'){let resolve;const promise=new Promise(r=>resolve=r);pending.push({path,method,promise});return(data={},status=200)=>resolve(response(data,status))}};
}
(async()=>{
 const h=await harness(),get=h.get,ids=()=>JSON.parse(h.run('JSON.stringify(filteredCompanies().map(c=>c.id))'));
 assert.equal(get('view-title').textContent,'Welcome back.');assert.equal(h.nav[0].getAttribute('aria-current'),'page');assert.match(get('metrics').innerHTML,/Configured plans/);assert.match(get('metrics').innerHTML,/\$1300/);assert.doesNotMatch(get('metrics').innerHTML,/MRR|Recurring monthly revenue/);
 get('company-scope').value='customers';get('company-scope').onchange();assert.equal(ids().length,6);get('company-health').value='At risk';get('company-health').onchange();assert.deepEqual(ids(),['beta']);get('company-filter-reset').onclick();assert.equal(ids().length,8);
 get('company-status').value='Incomplete';get('company-status').onchange();assert.deepEqual(ids(),['pending']);get('company-filter-reset').onclick();get('company-search').value='Founding';get('company-search').oninput();assert.deepEqual(ids(),['alpha']);get('company-filter-reset').onclick();get('company-sort').value='last-report';get('company-sort').onchange();assert.equal(ids()[0],'annual');get('company-sort').value='newest';get('company-sort').onchange();assert.equal(ids()[0],'annual');
 assert.match(get('companies').innerHTML,/&lt;Quoted Company&gt;/);assert.doesNotMatch(get('companies').innerHTML,/<img src=x/);assert.match(get('companies').innerHTML,/data-company-id="x&quot;&lt;&amp;\?"/);
 for(const s of ['Legacy','Demo','Complimentary','Incomplete','Trial ended','Pilot','<custom>']){const options=h.run(`subscriptionStatusOptions(${JSON.stringify(s)})`);assert.match(options,/<option value="" selected>Keep /);assert.equal((options.match(/ selected/g)||[]).length,1);assert.ok(!options.includes('<custom>'))}
 for(const s of ['Trial','Active','Past due','Paused','Cancelled'])assert.ok(h.run(`subscriptionStatusOptions(${JSON.stringify(s)})`).includes(`<option value="${s}" selected>`));
 get('company-search').value='nomatch';await h.click('[data-account-view]',{accountView:'customers',companyId:'beta'});assert.deepEqual(ids(),['beta']);assert.equal(get('company-filters').hidden,true);assert.equal(h.location.hash,'#customers?company=beta');await h.click('[data-account-view]',{accountView:'support',companyId:'beta'});assert.match(get('tickets').innerHTML,/Beta issue/);assert.doesNotMatch(get('tickets').innerHTML,/Alpha issue/);assert.equal(get('view-title').textContent,'Support');
 const size=h.history.length;await h.click('[data-account-view]',{accountView:'support',companyId:'beta'});assert.equal(h.history.length,size);get('add-ticket').onclick();assert.equal(get('work-modal').open,true);h.history.back();assert.equal(get('work-modal').open,false);assert.equal(get('view-title').textContent,'Customer health');h.history.forward();assert.equal(get('view-title').textContent,'Support');
 await h.click('[data-account-view]',{accountView:'subscriptions',companyId:'beta'});assert.match(get('account-context').innerHTML,/Owner Stripe reporting is account-wide/);assert.doesNotMatch(get('subscriptions').innerHTML,/Alpha Construction/);await h.click('[data-clear-account]');assert.match(get('subscriptions').innerHTML,/Alpha Construction/);
 h.location.hash='#customers?company=deleted';h.windows.hashchange();assert.match(get('account-context').innerHTML,/Account not available/);assert.equal(get('support-access').disabled,true);h.location.hash='#constructor';h.windows.hashchange();assert.equal(h.location.hash,'#overview');
 assert.ok(h.calls.every(c=>c.method==='GET'),'navigation is read-only');
 // Every delayed dialog result/error must leave a newer dialog intact after Back/reopen.
 for(const [open,save,modal,message,route] of [['add-ticket','save-work','work-modal','work-message','/api/platform/tickets'],['add-help','save-help','help-editor','help-editor-message','/api/platform/help'],['add-blog','save-blog','blog-editor','blog-editor-message','/api/platform/blog'],['add-staff','save-staff','staff-modal','staff-code','/api/platform/users'],['support-access','create-support','support-modal','support-result','/api/platform/support-access']]){
  for(const error of [false,true]){
   const x=await harness();x.run("showView('support',{companyId:'alpha'})");x.get(open).onclick();x.get('work-company').value='alpha';x.get('support-company').value='alpha';const resolve=x.defer(route),saving=x.get(save).onclick();await Promise.resolve();x.history.back();x.run("showView('support',{companyId:'beta'})");x.get(open).onclick();x.get(message).innerHTML='fresh';x.get(message).textContent='fresh';x.get('blog-title').value='Fresh draft';resolve(error?{error:'STALE ERROR'}:{name:'Stale',setupCode:'SYNTHETIC',url:'/old',companyName:'Alpha'},error?500:200);await saving;assert.equal(x.get(modal).open,true,open);assert.equal(x.get(message).textContent,'fresh');assert.equal(x.get(message).innerHTML,'fresh');assert.equal(x.get('blog-title').value,'Fresh draft');
  }
 }
 const edit=await harness();edit.get('support-access').onclick();const r=edit.defer('/api/platform/support-access'),saving=edit.get('create-support').onclick();await edit.edit('support-modal');r({url:'/old',companyName:'Old'});await saving;assert.equal(edit.get('support-result').innerHTML,'','changing recipient invalidates response');
 const owner=await harness();const finish=owner.defer('/api/platform/companies/alpha/owner-reset'),reset=owner.click('[data-owner-reset]',{ownerReset:'alpha'});owner.run("showView('team')");finish({email:'old@example.invalid',setupCode:'SYNTHETIC'});await reset;assert.equal(owner.get('work-modal').open,false);
 const reload=await harness(),resolveOld=reload.defer('/api/platform/overview','GET'),old=reload.run('reload()');await reload.run('reload()');resolveOld({...fixture,companies:[]});await old;assert.match(reload.get('companies').innerHTML,/Alpha Construction/,'older reload cannot replace newer overview');
 assert.ok(!source.includes('fixture.invalid')&&!source.includes('window.fetch='));assert.doesNotMatch(html,/SYNTHETIC PREVIEW|NO LIVE DATA|pdl-source-candidate|fixture\.invalid|connect-src 'none'/);assert.match(html,/id="view-title" tabindex="-1"/);assert.match(html,/id="platform-revenue"/);
 console.log('Recovered platform tests passed: filters/sort/escaping, exact scope/route/history, preserved status, stale dialogs/errors/recipient/owner reset and reload ordering. Synthetic DOM only.');
})().catch(e=>{console.error(e);process.exitCode=1});
