const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let data,audit=[],helpItems=[],blogPosts=[],editingBlogId=null,workType='onboarding',platformUser=null,currentView='overview',activeCompanyId='';
async function api(path,options={}){const response=await fetch(path,{credentials:'include',headers:{'Content-Type':'application/json'},...options}),result=await response.json();if(response.status===401){location.href='/platform-login.html';throw new Error('Your platform session expired.')}if(!response.ok)throw new Error(result.error);return result}
const safe=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const companyOptions=()=>data.companies.map(c=>`<option value="${safe(c.id)}" ${String(c.id)===activeCompanyId?'selected':''}>${safe(c.name)}</option>`).join('');
function row(title,detail,badge='',action=''){return `<div class="row"><span><strong>${safe(title)}</strong><small>${detail}</small></span>${badge?`<span class="badge">${safe(badge)}</span>`:''}${action}</div>`}
function renderHelp(){const q=$('#platform-help-search').value.trim().toLowerCase(),items=helpItems.filter(i=>!q||`${i.title} ${i.category} ${i.summary}`.toLowerCase().includes(q));$('#platform-help').innerHTML=items.length?items.map(i=>row(i.title,`${safe(i.category)} · ${safe(i.summary)}`,i.audience,`<b>${safe(i.status)}</b>`)).join(''):'<p class="empty">No matching content.</p>'}
function renderBlog(){const q=$('#platform-blog-search').value.trim().toLowerCase(),items=blogPosts.filter(post=>!q||`${post.title} ${post.category} ${post.excerpt}`.toLowerCase().includes(q));$('#platform-blog').innerHTML=items.length?items.map(post=>`<div class="row blog-admin-row"><span><strong>${safe(post.title)}</strong><small>${safe(post.category)} · ${safe(post.author)} · updated ${new Date(post.updatedAt).toLocaleDateString()}</small><small>${safe(post.excerpt)}</small></span><span class="badge">${safe(post.status)}</span><button class="small secondary" data-blog-edit="${post.id}">Edit</button><button class="small secondary" data-blog-delete="${post.id}">Delete</button></div>`).join(''):'<div class="empty-state"><b>No Field Notes yet</b><span>Create a draft, review it, and publish when it is ready.</span></div>'}
const internalAccount=c=>c.demo||/\b(test|qa|demo)\b|delete me|checkout verification/i.test(c.name||'');
function render(){const realCompanies=data.companies.filter(c=>!internalAccount(c)),realIds=new Set(realCompanies.map(c=>String(c.id))),openTickets=data.supportTickets.filter(t=>!['Resolved','Closed'].includes(t.status)&&realIds.has(String(t.companyId))).length,metricItems=[['Companies',realCompanies.length,'Real customer workspaces','customers'],['Active trials',realCompanies.filter(c=>c.subscriptionStatus==='Trial'&&c.trialEndsAt&&new Date(c.trialEndsAt)>new Date()).length,'Accounts evaluating PDL','customers'],['Configured plans',`$${realCompanies.filter(c=>c.subscriptionStatus==='Active'&&!c.billingExempt).reduce((sum,c)=>sum+(Number(c.planPrice)||0),0)}`,'Active account price total · not revenue','subscriptions'],['Customer users',realCompanies.reduce((sum,c)=>sum+(Number(c.users)||0),0),'People with account access','customers'],['At risk',realCompanies.filter(c=>c.health.status==='At risk').length,'Accounts needing action','customers'],['Open tickets',openTickets,'Unresolved support requests','support']];$('#metrics').innerHTML=metricItems.map(([label,value,detail,view])=>`<button class="metric" data-view-link="${view}" aria-label="${safe(label)}: ${safe(value)}. ${safe(detail)}"><small>${safe(label)}</small><strong>${safe(value)}</strong><span>${safe(detail)}</span></button>`).join('');const flagged=data.companies.filter(c=>c.health.alerts.length),attention=flagged.filter(c=>!internalAccount(c)),internal=flagged.filter(internalAccount);$('#attention').innerHTML=attention.length?attention.map(c=>row(c.name,c.health.alerts.map(safe).join(' · '),c.health.status,accountJump(c.id,'customers','View account'))).join(''):'<div class="empty-state"><b>Customer accounts are clear</b><span>No real customer workspace needs attention right now.</span></div>';$('#internal-account-note').innerHTML=internal.length?`<p class="internal-note">${internal.length} internal test ${internal.length===1?'account is':'accounts are'} excluded from this list.</p>`:'';const open=data.followUps.filter(f=>f.status==='Open');$('#followups-mini').innerHTML=open.length?open.slice(0,5).map(f=>row(f.title,`${safe(f.companyName)} · due ${safe(f.dueDate||'not set')}`,f.owner,accountJump(f.companyId,'support','View account'))).join(''):'<div class="empty-state compact"><b>Nothing waiting</b><span>Create a follow-up when a customer needs a call, answer, or next step.</span><button class="small" data-new-followup>＋ Add follow-up</button></div>';renderCompanies();renderOnboarding();renderSupport();renderSubscriptions();renderTeam();renderHelp();renderBlog();renderAccountContext()}
const scopedCompanies=()=>data.companies.filter(c=>!activeCompanyId||String(c.id)===activeCompanyId);
const scopedItems=items=>items.filter(item=>!activeCompanyId||String(item.companyId)===activeCompanyId);
function accountJump(id,view,label){return id==null?'':`<button class="small secondary" data-account-view="${safe(view)}" data-company-id="${safe(id)}">${safe(label)}</button>`}
function accountCount(items,id){return items.filter(item=>String(item.companyId)===String(id)).length}
function filteredCompanies(){
  const q=$('#company-search').value.trim().toLowerCase(),scope=$('#company-scope').value,health=$('#company-health').value,status=$('#company-status').value;
  const companies=scopedCompanies().filter(c=>activeCompanyId||
    ((scope==='all'||(scope==='internal'?internalAccount(c):!internalAccount(c)))&&
     (health==='all'||c.health.status===health)&&(status==='all'||c.subscriptionStatus===status)&&
     (!q||`${c.name} ${c.trade} ${c.plan} ${c.cohort} ${c.subscriptionStatus} ${c.accountType}`.toLowerCase().includes(q))));
  const dateValue=value=>Number.isFinite(Date.parse(value))?Date.parse(value):0;
  const byName=(a,b)=>String(a.name).localeCompare(String(b.name));
  const sorters={attention:(a,b)=>a.health.score-b.health.score||byName(a,b),name:byName,'last-report':(a,b)=>dateValue(b.lastReport)-dateValue(a.lastReport)||byName(a,b),newest:(a,b)=>dateValue(b.createdAt)-dateValue(a.createdAt)||byName(a,b)};
  return companies.sort(sorters[$('#company-sort').value]||sorters.attention);
}
function renderCompanies(){
  const status=$('#company-status'),selectedStatus=status.value||'all';
  const statuses=[...new Set(data.companies.map(c=>c.subscriptionStatus).filter(Boolean))].sort();
  status.innerHTML='<option value="all">All statuses</option>'+statuses.map(value=>`<option value="${safe(value)}">${safe(value)}</option>`).join('');
  status.value=statuses.includes(selectedStatus)?selectedStatus:'all';
  const companies=filteredCompanies();
  $('#company-filters').hidden=Boolean(activeCompanyId);
  $('#company-results').textContent=activeCompanyId?`${companies.length} account selected`:`Showing ${companies.length} of ${data.companies.length} accounts`;
  $('#company-filter-reset').disabled=!$('#company-search').value&&['scope','health','status'].every(id=>$('#company-'+id).value==='all')&&$('#company-sort').value==='attention';
  $('#companies').innerHTML=companies.map(c=>`<div class="customer-card"><div><strong>${safe(c.name)}${c.demo?' · Sales demo':''}</strong><small>${safe(c.trade||'Trade not set')} · ${safe(c.projects)} projects · ${safe(c.users)} users · ${safe(c.reports)} dailies</small><p>${safe(c.summary)}</p><div class="account-shortcuts" aria-label="Account details">${accountJump(c.id,'support',`Support (${accountCount(data.supportTickets.filter(t=>!['Resolved','Closed'].includes(t.status)),c.id)} open)`)}${accountJump(c.id,'onboarding',`Onboarding (${accountCount(data.onboardingOrders.filter(o=>!['Complete','Cancelled'].includes(o.status)),c.id)} open)`)}${accountJump(c.id,'subscriptions','Subscription')}</div><div class="account-actions"><button class="small secondary" data-time-cards="${safe(c.id)}" data-time-cards-on="${c.timeCards?'1':'0'}">${c.timeCards?'Time cards on':'Time cards off'}</button><button class="small secondary" data-templates="${safe(c.id)}" data-templates-on="${c.templates?'1':'0'}">${c.templates?'Templates on':'Templates off'}</button><button class="small secondary" data-owner-reset="${safe(c.id)}">Reset owner password</button>${platformUser?.role==='platform_owner'&&c.name==='DEMO | Alder Ridge Builders'?`<button class="small" data-prepare-sales-demo="${safe(c.id)}">${c.demo?'Check sales demo':'Prepare sales demo'}</button>`:''}${c.demoResetAvailable?`<button class="small" data-demo-reset="${safe(c.id)}">Reset demo data</button>`:''}</div></div><div class="health ${c.health.status==='At risk'?'at-risk':c.health.status==='Watch'?'watch':'healthy'}"><b>${safe(c.health.score)}</b><small>${safe(c.health.status)}</small></div><span class="badge">${safe(c.plan)} · ${safe(c.subscriptionStatus)}</span></div>`).join('')||'<div class="empty-state"><b>No matching accounts</b><span>Reset the filters or return to all accounts to broaden your view.</span></div>';
}
function resetCompanyFilters(){
  $('#company-search').value='';['scope','health','status'].forEach(id=>$('#company-'+id).value='all');$('#company-sort').value='attention';renderCompanies();
}
function renderOnboarding(){const orders=scopedItems(data.onboardingOrders);$('#onboarding').innerHTML=orders.length?orders.map(o=>{const done=o.tasks.filter(t=>t.done).length;return `<div class="work-card"><div><strong>${safe(o.companyName)}</strong><small>${safe(o.package)} · ${safe(o.owner)} · due ${safe(o.dueDate||'not set')}</small><div class="progress"><i style="width:${o.tasks.length?done/o.tasks.length*100:0}%"></i></div><small>${done}/${o.tasks.length} setup steps complete</small></div><select data-onboarding="${o.id}">${['Requested','Not started','In progress','Blocked','Complete','Cancelled'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></div>`}).join(''):'<p class="empty">No onboarding work orders yet.</p>'}
function renderSupport(){const tickets=scopedItems(data.supportTickets),followups=scopedItems(data.followUps);$('#tickets').innerHTML=tickets.length?tickets.map(t=>`<div class="work-card"><div><strong>${safe(t.subject)}</strong><small>${safe(t.companyName)} · ${safe(t.assignee)} · ${safe(t.priority)}</small></div><select data-ticket="${t.id}">${['Open','In progress','Waiting on customer','Resolved','Closed'].map(s=>`<option ${s===t.status?'selected':''}>${s}</option>`).join('')}</select></div>`).join(''):'<p class="empty">No support tickets.</p>';$('#followups').innerHTML=followups.length?followups.map(f=>`<div class="work-card"><div><strong>${safe(f.title)}</strong><small>${safe(f.companyName)} · ${safe(f.owner)} · due ${safe(f.dueDate||'not set')}</small><p>${safe(f.draft)}</p></div><button class="small secondary" data-followup="${f.id}" ${f.status==='Complete'?'disabled':''}>${f.status==='Complete'?'Complete':'Mark complete'}</button></div>`).join(''):'<p class="empty">No follow-ups.</p>'}
function subscriptionStatusOptions(current){
  const editable=['Trial','Active','Past due','Paused','Cancelled'];
  const preserve=editable.includes(current)?'':`<option value="" selected>Keep ${safe(current||'current status')}</option>`;
  return preserve+editable.map(status=>`<option value="${safe(status)}" ${status===current?'selected':''}>${safe(status)}</option>`).join('');
}
function renderSubscriptions(){$('#subscriptions').innerHTML=scopedCompanies().map(c=>`<div class="subscription"><div><strong>${safe(c.name)}</strong><small>${safe(c.plan)} · ${c.billingExempt?'No subscription charge':`$${safe(c.planPrice)} configured price`}</small><span class="badge commercial ${safe(c.accountType)}">${safe(c.accountType.replace('_',' '))}${c.cohort?` · ${safe(c.cohort)}`:''}</span></div><label>Account type<select data-sub-type="${safe(c.id)}">${[['standard','Standard'],['early_adopter','Early adopter'],['legacy','Legacy']].map(([value,label])=>`<option value="${value}" ${value===c.accountType?'selected':''}>${label}</option>`).join('')}</select></label><label>Configured price<input data-sub-price="${safe(c.id)}" type="number" min="0" value="${c.planPrice}"></label><label>Cohort<input data-sub-cohort="${safe(c.id)}" value="${safe(c.cohort||'')}" placeholder="Founding 25"></label><label>Discount %<input data-sub-discount="${safe(c.id)}" type="number" min="0" max="100" value="${c.discountPercent||0}"></label><label class="exempt-check"><input data-sub-exempt="${safe(c.id)}" type="checkbox" ${c.billingExempt?'checked':''}> No subscription charge</label><label>Account status<select data-sub-status="${safe(c.id)}">${subscriptionStatusOptions(c.subscriptionStatus)}</select></label><button class="small" data-save-sub="${safe(c.id)}">Save</button></div>`).join('')}
const actionLabel=value=>String(value||'Platform activity').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
function auditRow(e,full=false){const company=data.companies.find(c=>String(c.id)===String(e.companyId)),context=company?company.name:'Platform';return row(actionLabel(e.action),`${safe(e.actorName)} · ${safe(context)} · ${new Date(e.at).toLocaleString()}${e.reason?` · ${safe(e.reason)}`:''}`,full?(e.companyId?'Customer':'Platform'):'')}
function renderTeam(){$('#staff').innerHTML=data.staff.map(m=>row(m.name,safe(m.email),m.role.replace('_',' '),`<b>${safe(m.status)}</b>`)).join('');const recent=audit.length?audit.slice().reverse().slice(0,6).map(e=>auditRow(e)).join(''):'<p class="empty">No platform events.</p>',full=audit.length?audit.slice().reverse().slice(0,30).map(e=>auditRow(e,true)).join(''):'<p class="empty">No platform events.</p>';$('#audit').innerHTML=recent;$('#audit-full').innerHTML=full}
const platformViews={
  overview:['Welcome back.','Your SaaS command center.'],
  customers:['Customer health','See which customers are thriving and which need attention.'],
  onboarding:['Onboarding','Track setup progress and implementation work.'],
  support:['Support','Resolve issues and follow up before customers drift.'],
  subscriptions:['Subscriptions','Review configured plans and commercial account status.'],
  blog:['Field Notes blog','Publish practical Field Notes for contractors.'],
  help:['Help Center','Manage customer-facing education.'],
  team:['Platform team','Control internal access and review activity.']
};
const accountViews=['customers','onboarding','support','subscriptions'];
// A completed request may refresh data, but only its own dialog session may show its result.
const dialogVersions=new Map();
let reloadVersion=0,viewVersion=0;
function nextDialogVersion(id){const version=(dialogVersions.get(id)||0)+1;dialogVersions.set(id,version);return version}
function openDialog(id){nextDialogVersion(id);$('#'+id).showModal()}
function dialogAction(id){return {id,version:nextDialogVersion(id),view:currentView,companyId:activeCompanyId,viewVersion}}
function dialogActionCurrent(action,requireOpen=true){return dialogVersions.get(action.id)===action.version&&viewVersion===action.viewVersion&&currentView===action.view&&activeCompanyId===action.companyId&&(!requireOpen||$('#'+action.id).open)}
const invalidateDialogInput=event=>{const dialog=event.target.closest('dialog');if(dialog&&dialogVersions.has(dialog.id))nextDialogVersion(dialog.id)};
document.addEventListener('input',invalidateDialogInput);
document.addEventListener('change',invalidateDialogInput);
function renderAccountContext(){
  const context=$('#account-context'),company=data.companies.find(c=>String(c.id)===activeCompanyId);
  context.hidden=!activeCompanyId;
  ['primary-action','add-onboarding','add-ticket','add-followup','support-access'].forEach(id=>$('#'+id).disabled=Boolean(activeCompanyId&&!company));
  context.innerHTML=activeCompanyId?`<div><strong>${safe(company?.name||'Account not available')}</strong><small>${company?(currentView==='subscriptions'?'Configured plan for this account. Owner Stripe reporting is account-wide.':'Viewing this account only.'):'This account is no longer in the current overview.'}</small></div><div class="account-shortcuts">${accountViews.filter(view=>view!==currentView).map(view=>accountJump(activeCompanyId,view,platformViews[view][0])).join('')}<button class="small secondary" data-clear-account>View all accounts</button></div>`:'';
  $('#onboarding-view').classList.toggle('account-scoped',Boolean(activeCompanyId));
}
function showView(name,{companyId='',historyMode='push',focus=true}={}){
  name=Object.hasOwn(platformViews,name)?name:'overview';
  const nextCompanyId=accountViews.includes(name)?String(companyId||''):'';
  const accountChanged=activeCompanyId!==nextCompanyId;
  if(currentView!==name||accountChanged){viewVersion++;$$('dialog[open]').forEach(dialog=>dialog.close())}
  currentView=name;activeCompanyId=nextCompanyId;
  const hash=`#${name}${activeCompanyId?'?company='+encodeURIComponent(activeCompanyId):''}`;
  if(location.hash!==hash){
    if(historyMode==='replace')history.replaceState(null,'',hash);
    else if(historyMode==='push')history.pushState(null,'',hash);
  }
  $$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}-view`));
  $$('nav button').forEach(b=>{const selected=b.dataset.view===name;b.classList.toggle('active',selected);if(selected)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});
  const title=name==='overview'&&platformUser?`Welcome, ${platformUser.name.split(' ')[0]}.`:platformViews[name][0];
  $('#view-title').textContent=title;document.title=`${name==='overview'?'Platform Operations':title} · Pro Daily Link`;
  $('#view-description').textContent=platformViews[name][1];$('#primary-action').hidden=!['overview','onboarding'].includes(name);
  if(data){renderAccountContext();if(accountChanged){renderCompanies();renderOnboarding();renderSupport();renderSubscriptions()}}
  if(focus)$('#view-title').focus();
}
function readViewRoute(){
  const [name,query='']=location.hash.replace(/^#/,'').split('?');
  showView(name,{companyId:new URLSearchParams(query).get('company')||'',historyMode:'replace',focus:false});
}
window.addEventListener('popstate',readViewRoute);
window.addEventListener('hashchange',readViewRoute);
function openWork(type){workType=type;const configs={onboarding:['New onboarding work order',`<label>Company<select id="work-company">${companyOptions()}</select></label><div class="two"><label>Package<select id="work-package"><option>Guided setup</option><option>Full implementation</option><option>Self-serve</option></select></label><label>Owner<input id="work-owner" value="${safe(platformUser?.name||'')}"></label></div><label>Due date<input id="work-due" type="date"></label><label>Notes<textarea id="work-notes" rows="3"></textarea></label>`],ticket:['New support ticket',`<label>Company<select id="work-company">${companyOptions()}</select></label><label>Subject<input id="work-subject"></label><div class="two"><label>Priority<select id="work-priority"><option>Normal</option><option>Low</option><option>High</option><option>Urgent</option></select></label><label>Assignee<input id="work-assignee" value="${safe(platformUser?.name||'')}"></label></div><label>Details<textarea id="work-details" rows="4"></textarea></label>`],followup:['New customer follow-up',`<label>Company<select id="work-company">${companyOptions()}</select></label><label>Follow-up<input id="work-subject"></label><div class="two"><label>Owner<input id="work-owner" value="${safe(platformUser?.name||'')}"></label><label>Due date<input id="work-due" type="date"></label></div><label>Draft message or notes<textarea id="work-details" rows="5" placeholder="Leave blank to use the account summary"></textarea></label>`]};$('#work-title').textContent=configs[type][0];$('#work-fields').innerHTML=configs[type][1];$('#work-message').textContent='';openDialog('work-modal')}
async function reload(){const version=++reloadVersion,result=await Promise.all([api('/api/platform/overview'),api('/api/platform/audit'),api('/api/platform/help'),api('/api/platform/blog')]);if(version!==reloadVersion)return;[data,audit,helpItems,blogPosts]=result;render()}
$$('nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.addEventListener('click',e=>{const account=e.target.closest('[data-account-view]');if(account){showView(account.dataset.accountView,{companyId:account.dataset.companyId});return}if(e.target.closest('[data-clear-account]')){showView(currentView);return}const view=e.target.closest('[data-view-link]')?.dataset.viewLink;if(view)showView(view);if(e.target.closest('[data-new-followup]'))openWork('followup')});$('#primary-action').onclick=$('#add-onboarding').onclick=()=>openWork('onboarding');$('#add-ticket').onclick=()=>openWork('ticket');$('#add-followup').onclick=()=>openWork('followup');$('#company-search').oninput=renderCompanies;['scope','health','status','sort'].forEach(id=>$('#company-'+id).onchange=renderCompanies);$('#company-filter-reset').onclick=resetCompanyFilters;$('#platform-help-search').oninput=renderHelp;$('#platform-blog-search').oninput=renderBlog;
$('#save-work').onclick=async()=>{const action=dialogAction('work-modal');try{let path,payload;if(workType==='onboarding'){path='/api/platform/onboarding';payload={companyId:$('#work-company').value,package:$('#work-package').value,owner:$('#work-owner').value,dueDate:$('#work-due').value,notes:$('#work-notes').value}}else if(workType==='ticket'){path='/api/platform/tickets';payload={companyId:$('#work-company').value,subject:$('#work-subject').value,priority:$('#work-priority').value,assignee:$('#work-assignee').value,details:$('#work-details').value}}else{path='/api/platform/follow-ups';payload={companyId:$('#work-company').value,title:$('#work-subject').value,owner:$('#work-owner').value,dueDate:$('#work-due').value,draft:$('#work-details').value}}await api(path,{method:'POST',body:JSON.stringify(payload)});if(dialogActionCurrent(action))$('#work-modal').close();await reload()}catch(e){if(dialogActionCurrent(action))$('#work-message').textContent=e.message}};
document.addEventListener('change',async e=>{if(e.target.dataset.onboarding){await api(`/api/platform/onboarding/${e.target.dataset.onboarding}`,{method:'PATCH',body:JSON.stringify({status:e.target.value})});await reload()}if(e.target.dataset.ticket){await api(`/api/platform/tickets/${e.target.dataset.ticket}`,{method:'PATCH',body:JSON.stringify({status:e.target.value})});await reload()}});document.addEventListener('click',async e=>{if(e.target.dataset.timeCards){try{const enabled=e.target.dataset.timeCardsOn!=='1';await api(`/api/platform/companies/${encodeURIComponent(e.target.dataset.timeCards)}/features`,{method:'PATCH',body:JSON.stringify({timeCards:enabled})});await reload()}catch(error){alert(error.message)}return}if(e.target.dataset.templates){try{const enabled=e.target.dataset.templatesOn!=='1';await api(`/api/platform/companies/${encodeURIComponent(e.target.dataset.templates)}/features`,{method:'PATCH',body:JSON.stringify({templates:enabled})});await reload()}catch(error){alert(error.message)}return}if(e.target.dataset.ownerReset){const action=dialogAction('work-modal');try{const result=await api(`/api/platform/companies/${encodeURIComponent(e.target.dataset.ownerReset)}/owner-reset`,{method:'POST',body:'{}'});if(dialogActionCurrent(action,false)){$('#work-title').textContent='Owner setup code';$('#work-fields').innerHTML=`<div class="code"><strong>${safe(result.email)}</strong><b>${safe(result.setupCode)}</b><small>Expires in 72 hours. Give this only to the company owner.</small></div>`;$('#work-message').textContent='';openDialog('work-modal')}}catch(error){if(dialogActionCurrent(action,false))alert(error.message)}}if(e.target.dataset.followup){await api(`/api/platform/follow-ups/${e.target.dataset.followup}`,{method:'PATCH',body:JSON.stringify({status:'Complete'})});await reload()}if(e.target.dataset.saveSub){const id=e.target.dataset.saveSub;await api(`/api/platform/companies/${encodeURIComponent(id)}/subscription`,{method:'PATCH',body:JSON.stringify({status:$(`[data-sub-status="${id}"]`).value,planPrice:+$(`[data-sub-price="${id}"]`).value,accountType:$(`[data-sub-type="${id}"]`).value,billingExempt:$(`[data-sub-exempt="${id}"]`).checked,cohort:$(`[data-sub-cohort="${id}"]`).value,discountPercent:+$(`[data-sub-discount="${id}"]`).value})});await reload()}});
document.addEventListener('click',async e=>{if(!e.target.dataset.demoReset)return;if(!confirm('Reset the sales demo to its original projects, reports, schedules, and production data? Demo login credentials will be preserved.'))return;const result=await api(`/api/platform/companies/${encodeURIComponent(e.target.dataset.demoReset)}/demo-reset`,{method:'POST',body:'{}'});alert(`Demo reset complete: ${result.projects} projects and ${result.reports} reports restored.`);await reload()});
$('#add-staff').onclick=()=>{$('#staff-code').innerHTML='';openDialog('staff-modal')};$('#save-staff').onclick=async()=>{const action=dialogAction('staff-modal');try{const c=await api('/api/platform/users',{method:'POST',body:JSON.stringify({name:$('#staff-name').value,email:$('#staff-email').value,role:$('#staff-role').value})});if(dialogActionCurrent(action))$('#staff-code').innerHTML=`<div class="code">One-time setup code for ${safe(c.name)}<b>${safe(c.setupCode)}</b><small>Expires in 72 hours.</small></div>`;await reload()}catch(e){if(dialogActionCurrent(action))$('#staff-code').textContent=e.message}};
$('#add-help').onclick=()=>{$('#help-editor').querySelector('form').reset();$('#help-editor-message').textContent='';openDialog('help-editor')};$('#save-help').onclick=async()=>{const action=dialogAction('help-editor');try{await api('/api/platform/help',{method:'POST',body:JSON.stringify({title:$('#help-title').value,category:$('#help-category').value,type:$('#help-type').value,audience:$('#help-audience').value,summary:$('#help-summary').value,content:$('#help-content').value,url:$('#help-url').value,status:$('#help-status').value})});if(dialogActionCurrent(action))$('#help-editor').close();await reload()}catch(e){if(dialogActionCurrent(action))$('#help-editor-message').textContent=e.message}};
function openBlogEditor(post=null){editingBlogId=post?.id||null;$('#blog-editor-title').textContent=post?'Edit Field Note':'New Field Note';$('#blog-title').value=post?.title||'';$('#blog-slug').value=post?.slug||'';$('#blog-category').value=post?.category||'Field operations';$('#blog-author').value=post?.author||platformUser?.name||'Pro Daily Link';$('#blog-excerpt').value=post?.excerpt||'';$('#blog-content').value=post?.content||'';$('#blog-status').value=post?.status||'Draft';$('#blog-editor-message').textContent='';openDialog('blog-editor')}
$('#add-blog').onclick=()=>openBlogEditor();$('#blog-title').oninput=()=>{if(editingBlogId||$('#blog-slug').dataset.touched==='1')return;$('#blog-slug').value=$('#blog-title').value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90)};$('#blog-slug').oninput=()=>$('#blog-slug').dataset.touched='1';
$('#save-blog').onclick=async()=>{const action=dialogAction('blog-editor'),postId=editingBlogId,payload={title:$('#blog-title').value,slug:$('#blog-slug').value,category:$('#blog-category').value,author:$('#blog-author').value,excerpt:$('#blog-excerpt').value,content:$('#blog-content').value,status:$('#blog-status').value};try{await api(postId?`/api/platform/blog/${postId}`:'/api/platform/blog',{method:postId?'PATCH':'POST',body:JSON.stringify(payload)});if(dialogActionCurrent(action)){$('#blog-editor').close();editingBlogId=null;$('#blog-slug').dataset.touched=''}await reload()}catch(error){if(dialogActionCurrent(action))$('#blog-editor-message').textContent=error.message}};
document.addEventListener('click',async event=>{const edit=event.target.closest('[data-blog-edit]'),remove=event.target.closest('[data-blog-delete]');if(edit){const post=blogPosts.find(row=>row.id===edit.dataset.blogEdit);if(post)openBlogEditor(post);return}if(remove){const post=blogPosts.find(row=>row.id===remove.dataset.blogDelete);if(!post||!confirm(`Permanently delete “${post.title}”?`))return;try{await api(`/api/platform/blog/${post.id}`,{method:'DELETE'});await reload()}catch(error){alert(error.message)}}});
$('#support-access').onclick=()=>{$('#support-company').innerHTML=companyOptions();$('#support-actor').innerHTML=data.staff.map(m=>`<option value="${m.id}">${safe(m.name)} · ${safe(m.role.replace('_',' '))}</option>`).join('');$('#support-result').innerHTML='';openDialog('support-modal')};$('#create-support').onclick=async()=>{const action=dialogAction('support-modal');try{const g=await api('/api/platform/support-access',{method:'POST',body:JSON.stringify({companyId:$('#support-company').value,actorUserId:+$('#support-actor').value,reason:$('#support-reason').value,minutes:+$('#support-minutes').value})});if(dialogActionCurrent(action))$('#support-result').innerHTML=`<div class="code"><strong>Audited support session</strong><a href="${g.url}" target="_blank">Open ${safe(g.companyName)}</a><small>Expires ${new Date(g.expiresAt).toLocaleTimeString()}</small></div>`;await reload()}catch(e){if(dialogActionCurrent(action))$('#support-result').textContent=e.message}};
$('#platform-logout').onclick=async()=>{await api('/api/platform/auth/logout',{method:'POST',body:'{}'});location.href='/platform-login.html'};
async function boot(){const config=await fetch('/api/config',{credentials:'include'}).then(r=>r.json()).catch(()=>({authRequired:false}));if(config.authRequired){const me=await fetch('/api/platform/auth/me',{credentials:'include'});if(!me.ok){location.href='/platform-login.html';return}const user=await me.json();platformUser=user;$('#platform-logout').hidden=false}await reload();readViewRoute()}boot();
