'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const {defaultPeriod,periodError,money,currentOwner,validReport,createRevenueConsole}=require('./platform-revenue');
assert.deepEqual(defaultPeriod('2026-10-05T12:00:00Z'),{start:'2026-10-01',end:'2026-10-05'});
for(const dates of [['2026-02-29','2026-03-01'],['2026-10-05','2026-10-01'],['2024-01-01','2025-01-01'],['bad','2026-01-01']])assert.ok(periodError(...dates));
assert.equal(periodError('2024-01-01','2024-12-31'),'');assert.equal(periodError('2026-01-01','2026-01-01'),'');
assert.equal(money(10001,'usd',2),'USD 100.01');assert.equal(money(100,'jpy',0),'JPY 100');assert.equal(money(100,'isk',2),'ISK 1.00');
for(const args of [['100','usd',2],[NaN,'usd',2],[100,'<x>',2],[100,'usd',4],[Infinity,'usd',2]])assert.equal(money(...args),'Unavailable');
assert.equal(currentOwner({role:'platform_owner',revenueAccess:true}),true);for(const user of [null,{role:'owner',revenueAccess:true},{role:'platform_owner'},{role:'support',revenueAccess:true}])assert.equal(currentOwner(user),false);
class El{
 constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.attrs={};this.events={};this.hidden=false;this.value='';this.text='';this.classes=new Set();this.classList={add:(n)=>this.classes.add(n),toggle:(n,on)=>{if(on)this.classes.add(n);else this.classes.delete(n)},contains:n=>this.classes.has(n)};}
 set className(v){this.classes=new Set(v.split(/\s+/).filter(Boolean))}get className(){return [...this.classes].join(' ')}
 set textContent(v){this.text=String(v);this.children=[]}get textContent(){return this.text+this.children.map(c=>c.textContent).join(' ')}
 append(...items){this.children.push(...items)}replaceChildren(...items){this.text='';this.children=[...items]}setAttribute(k,v){this.attrs[k]=v}getAttribute(k){return this.attrs[k]}addEventListener(k,fn){(this.events[k]||=[]).push(fn)}
 emit(k,event={preventDefault(){}}){return Promise.all((this.events[k]||[]).map(fn=>fn(event)))}
}
const descendants=n=>[n,...n.children.flatMap(descendants)];
const owner={role:'platform_owner',revenueAccess:true};
function report(start='2026-10-01',end='2026-10-05'){return{status:'ready',mode:'live',asOf:'2026-10-05T12:00:00Z',period:{startDate:start,endDate:end,timezone:'UTC'},cash:[{currency:'usd',minorUnitExponent:2,receiptsMinor:120000,paymentReversalsMinor:0,refundDebitsMinor:2000,refundReversalsMinor:0,netBeforeFeesMinor:118000}],recurring:[{currency:'usd',minorUnitExponent:2,grossMrrMinor:10000,pastDueMrrMinor:0,subscriptionCount:1,annualSubscriptionCount:1}],companies:[{name:'<img src=x onerror=alert(1)>',linked:true,cash:[],recurring:[],failedPaymentCount:0}],activity:[{name:'<script>private</script>',date:'2026-10-05T00:00:00Z',type:'payment',amountMinor:120000,currency:'usd',minorUnitExponent:2,status:'succeeded'}],warnings:['<b>literal warning</b>'],failedPayments:{count:1},refundStatuses:{succeeded:1,pending:0,failed:0,canceled:0,requires_action:0,unknown:0},coverage:{excludedSubscriptionItems:0,activityLimit:100,activityTotal:1,unmatchedActivity:0,otherBalanceTransactions:0}}}
assert.equal(validReport(report(),'2026-10-01','2026-10-05'),true);assert.equal(validReport(report(),'2026-10-02','2026-10-05'),false);
const flush=async()=>{await new Promise(r=>setImmediate(r));await new Promise(r=>setImmediate(r))};
function harness({access=owner,response=report(),status=200,active=true}={}){
 const root=new El('section');root.id='platform-revenue';const view=new El('section');view.id='subscriptions-view';view.classList.toggle('active',active);
 const events={},winEvents={},calls=[],queue=[];let accessValue=access,reportValue=response,responseStatus=status;
 const doc={visibilityState:'visible',getElementById(id){return[root,view,...descendants(root)].find(n=>n.id===id)||null},createElement:t=>new El(t),addEventListener(k,fn){(events[k]||=[]).push(fn)}};
 const window={AbortController,addEventListener(k,fn){(winEvents[k]||=[]).push(fn)}};
 const responseOf=(data,code=200)=>({ok:code<400,status:code,json:async()=>data});
 const fetch=async(path,opts)=>{calls.push({path,opts});assert.equal(opts.method,'GET');assert.equal(opts.cache,'no-store');const pending=queue.shift();if(pending)return pending.promise;if(path==='/api/platform/auth/me')return responseOf(accessValue);if(path.startsWith('/api/platform/revenue?'))return responseOf(reportValue,responseStatus);throw Error('Unexpected endpoint')};
 const api=createRevenueConsole({document:doc,window,fetch,now:()=>Date.parse('2026-10-05T12:00:00Z')});
 return{root,view,doc,window,calls,api,get:id=>doc.getElementById(id),byClass:c=>descendants(root).find(n=>n.classes.has(c)),setAccess:a=>accessValue=a,setReport:(r,s=200)=>{reportValue=r;responseStatus=s},emitDoc(k,e){for(const f of events[k]||[])f(e)},emitWin(k){for(const f of winEvents[k]||[])f()},defer(){let resolve;const promise=new Promise(r=>resolve=r);queue.push({promise});return(data,code=200)=>resolve(responseOf(data,code))}};
}
(async()=>{
 for(const access of [{role:'support',revenueAccess:true},{role:'platform_owner',revenueAccess:false},{role:'owner',revenueAccess:true}]){const h=harness({access});await flush();assert.equal(h.root.hidden,true);assert.equal(h.calls.length,1);assert.equal(h.root.children.length,0)}
 const h=harness();await flush();assert.equal(h.root.hidden,false);assert.equal(h.calls.length,2);assert.match(h.root.textContent,/Account-wide/);assert.match(h.root.textContent,/USD 1,200.00/);assert.match(h.root.textContent,/USD 100.00/);assert.match(h.root.textContent,/Annual amounts are normalized by dividing by 12/);assert.match(h.root.textContent,/<img src=x/);assert.ok(!descendants(h.root).some(n=>['IMG','SCRIPT','B'].includes(n.tagName)),'provider strings are text, never HTML');
 assert.match(h.root.textContent,/not bank deposits or accounting revenue/);assert.equal(h.root.getAttribute('aria-busy'),'false');assert.equal(h.byClass('revenue-table-scroll').getAttribute('role'),'region');assert.equal(h.byClass('revenue-table-scroll').tabIndex,0);
 h.setReport({...report(),status:'unconfigured'});await h.api.refresh();assert.match(h.root.textContent,/not configured/);assert.equal(h.byClass('revenue-results').children.length,0);
 for(const [code,text] of [['incomplete','safe read limit'],['busy','Other Stripe reports'],['invalid_period','valid UTC'],['unknown','temporarily unavailable']]){h.setReport({status:'error',code,error:'SECRET PROVIDER DETAILS'},500);await h.api.refresh();assert.ok(h.root.textContent.includes(text));assert.ok(!h.root.textContent.includes('SECRET PROVIDER'));assert.equal(h.byClass('revenue-results').children.length,0)}
 h.setReport({...report(),cash:[],recurring:[],companies:[],activity:[],warnings:[]});await h.api.refresh();assert.match(h.root.textContent,/No Stripe payment balance activity/);assert.match(h.root.textContent,/No eligible current recurring/);
 h.setReport({...report(),period:{...report().period,startDate:'2000-01-01'}});await h.api.refresh();assert.match(h.root.textContent,/temporarily unavailable/);assert.equal(h.byClass('revenue-results').children.length,0);
 h.get('platform-revenue-start').value='2026-10-10';await h.get('platform-revenue-start').emit('input');const before=h.calls.length;await h.api.refresh();assert.equal(h.calls.length,before);assert.match(h.root.textContent,/start date must be on or before/);
 h.get('platform-revenue-start').value='2026-10-01';await h.get('platform-revenue-start').emit('input');h.setReport(report());await h.api.refresh();assert.match(h.root.textContent,/USD 1,200.00/);
 // A late auth or report response cannot reveal data after navigation, changed dates, or logout.
 const nav=harness({active:false});const auth=nav.defer();nav.view.classList.add('active');nav.api.sync();nav.view.classList.toggle('active',false);nav.api.sync();auth(owner);await flush();assert.equal(nav.root.hidden,true);assert.equal(nav.calls.length,1);
 const dates=harness();await flush();const dAuth=dates.defer(),dReport=dates.defer(),pending=dates.api.refresh();dAuth(owner);await flush();assert.equal(dates.calls.length,4,'delayed report request started before date edit');dates.get('platform-revenue-end').value='2026-10-04';await dates.get('platform-revenue-end').emit('input');dReport(report());await pending;assert.equal(dates.byClass('revenue-results').children.length,0);assert.match(dates.root.textContent,/Dates changed/);
 const log=harness();await flush();const lAuth=log.defer(),lReport=log.defer(),late=log.api.refresh();lAuth(owner);await flush();assert.equal(log.calls.length,4,'delayed report request started before logout');log.emitDoc('click',{target:{closest:s=>s==='#platform-logout'?{}:null}});lReport(report());await late;assert.equal(log.root.hidden,true);assert.equal(log.root.children.length,0);const last=log.calls.length;await log.api.refresh();assert.equal(log.calls.length,last);
 const vis=harness();await flush();vis.doc.visibilityState='hidden';vis.emitDoc('visibilitychange');assert.equal(vis.root.hidden,true);vis.setAccess({role:'support'});vis.doc.visibilityState='visible';vis.emitDoc('visibilitychange');await flush();assert.equal(vis.root.hidden,true);
 const exit=harness();await flush();const eAuth=exit.defer(),eReport=exit.defer(),exiting=exit.api.refresh();eAuth(owner);await flush();assert.equal(exit.calls.length,4);exit.view.classList.toggle('active',false);exit.api.sync();eReport(report());await exiting;assert.equal(exit.root.hidden,true);exit.view.classList.add('active');exit.api.sync();await flush();assert.equal(exit.root.hidden,false);assert.equal(exit.calls.length,6,'route reentry reauthorizes');
 const pages=harness();await flush();pages.emitWin('pagehide');assert.equal(pages.root.hidden,true);pages.setAccess({role:'support'});pages.emitWin('pageshow');await flush();assert.equal(pages.root.hidden,true);assert.equal(pages.calls.length,3,'page restoration rechecks access');
 const latest=harness();await flush();const oAuth=latest.defer(),oReport=latest.defer(),older=latest.api.refresh();oAuth(owner);await flush();assert.equal(latest.calls.length,4);latest.setReport({...report(),warnings:['NEWER RESULT']});await latest.api.refresh();oReport({...report(),warnings:['OLDER RESULT']});await older;assert.match(latest.root.textContent,/NEWER RESULT/);assert.ok(!latest.root.textContent.includes('OLDER RESULT'));
 const denied=harness();await flush();denied.setReport({error:'Forbidden'},403);await denied.api.refresh();assert.equal(denied.root.hidden,true);
 const bulk=harness({response:{...report(),activity:Array.from({length:140},()=>report().activity[0]),coverage:{...report().coverage,activityTotal:140,activityLimit:999}}});await flush();assert.match(bulk.root.textContent,/Showing 100 of 140/);assert.equal(descendants(bulk.byClass('revenue-table')).filter(n=>n.tagName==='TR').length,101);
 assert.equal(createRevenueConsole({document:{getElementById(){return null}},window:{}}),null);
 const html=fs.readFileSync('platform.html','utf8');assert.ok(html.indexOf('platform.js?')<html.indexOf('platform-revenue.js?'));assert.match(html,/id="platform-revenue" hidden/);assert.ok(!html.includes('fixture.invalid'));
 console.log('Recovered revenue UI tests passed: owner gating, currencies, date validation, text-only rendering, ready/empty/error/unconfigured states, lifecycle cancellation, revocation, and activity limits. No Stripe calls.');
})().catch(e=>{console.error(e);process.exitCode=1});
