'use strict';
const assert=require('node:assert/strict');
const {commandFor,createVoiceSession}=require('./project-assistant-voice');
function harness(Speech){const events={},documentEvents={},spoken=[],transcripts=[],commands=[],statuses=[];let allowed=true,timer,starts=0,aborts=0,last;const document={hidden:false,addEventListener:(key,callback)=>documentEvents[key]=callback};const window={addEventListener:(key,callback)=>events[key]=callback,speechSynthesis:{cancel(){},speak(utterance){spoken.push(utterance);}},SpeechSynthesisUtterance:class{constructor(text){this.text=text;}}};class Recognition{constructor(){last=this;}start(){starts++;}abort(){aborts++;this.onend?.();}};const voice=createVoiceSession({document,window,SpeechRecognition:Speech===null?null:Speech||Recognition,canContinue:()=>allowed,onTranscript:text=>transcripts.push(text),onCommand:command=>commands.push(command),onStatus:(text,listening)=>statuses.push({text,listening}),setTimer:callback=>{timer=callback;return 1;},clearTimer(){timer=null;}});return{voice,events,documentEvents,document,transcripts,commands,statuses,spoken,setAllowed:value=>allowed=value,get recognition(){return last;},get starts(){return starts;},get aborts(){return aborts;},expire(){timer?.();}};}
const row=(text,isFinal=true)=>Object.assign([{transcript:text}],{isFinal});
function main(){
  for(const [text,command]of [['Assistant suggest fields.','suggest'],['assistant preview changes','preview'],['assistant read preview!','read'],['assistant cancel preview','cancel'],['assistant stop listening','stop']])assert.equal(commandFor(text),command);
  for(const text of ['assistant confirm','assistant save changes','please assistant preview changes','Note: assistant preview changes','assistant preview changes and save','SQL UPDATE users'])assert.equal(commandFor(text),null);
  const h=harness();assert.equal(h.starts,0);assert.equal(h.voice.listening,false);assert.equal(h.voice.start(),true);assert.equal(h.recognition.continuous,true);assert.equal(h.recognition.interimResults,false);
  const old=h.recognition;old.onresult({resultIndex:0,results:[row('Frame west wall')]});old.onresult({resultIndex:0,results:[row('Frame west wall'),row('Check layout')]});assert.deepEqual(h.transcripts,['Frame west wall','Check layout']);old.onresult({resultIndex:2,results:[row('Frame west wall'),row('Check layout'),row('interim',false)]});assert.equal(h.transcripts.length,2);
  old.onresult({resultIndex:2,results:[row('Frame west wall'),row('Check layout'),row('assistant confirm')]});assert.equal(h.commands.length,0,'no voice mutation command');assert.equal(h.transcripts.at(-1),'assistant confirm');
  old.onresult({resultIndex:3,results:[row('Frame west wall'),row('Check layout'),row('assistant confirm'),row('assistant preview changes')]});assert.deepEqual(h.commands,['preview']);assert.equal(h.voice.listening,false);assert.equal(h.starts,1,'command pauses without automatic restart');old.onresult({resultIndex:4,results:[row('late') ]});assert.equal(h.commands.length,1);
  h.voice.start();h.recognition.onerror({error:'not-allowed'});assert.equal(h.voice.listening,false);assert.equal(h.starts,2);assert.match(h.statuses.at(-1).text,/permission/);
  h.voice.start();h.recognition.onend();assert.equal(h.voice.listening,false);assert.equal(h.starts,3,'browser disconnect never auto-restarts');h.voice.start();h.expire();assert.equal(h.voice.listening,false);assert.match(h.statuses.at(-1).text,/Five-minute/);
  h.voice.start();const hidden=h.recognition;h.document.hidden=true;h.documentEvents.visibilitychange();assert.equal(h.voice.listening,false);hidden.onresult({resultIndex:0,results:[row('private late text')]});assert.ok(!h.transcripts.includes('private late text'));assert.equal(h.voice.start(),false);
  h.document.hidden=false;h.voice.start();h.events.blur();assert.equal(h.voice.listening,false);h.voice.start();h.events.pagehide();assert.equal(h.voice.listening,false);
  h.voice.start();h.setAllowed(false);h.recognition.onresult({resultIndex:0,results:[row('after role/company change')]});assert.equal(h.voice.listening,false);assert.ok(!h.transcripts.includes('after role/company change'));h.setAllowed(true);
  h.voice.start();assert.equal(h.voice.read('Exact project Synthetic; every person/date; no email; Confirm button.'),true);assert.equal(h.voice.listening,false,'readback aborts microphone to avoid self-command echo');assert.equal(h.spoken.length,1);assert.match(h.spoken[0].text,/Exact project/);h.spoken[0].onend();assert.match(h.statuses.at(-1).text,/Confirm button/);assert.equal(h.voice.read('x'.repeat(20001)),false,'never truncate exact preview');
  const beforeStatus=h.statuses.length;h.voice.read('Visible preview');h.voice.stop();h.spoken.at(-1).onend();assert.equal(h.statuses.length,beforeStatus+2,'late speech completion ignored');
  const unsupported=harness(null);assert.equal(unsupported.voice.supported,false);assert.equal(unsupported.voice.start(),false);assert.equal(unsupported.starts,0);assert.match(unsupported.statuses.at(-1).text,/unavailable/);
  const throwing=harness(class{start(){throw Error('synthetic denied');}abort(){}});assert.equal(throwing.voice.start(),false);assert.equal(throwing.voice.listening,false);
  const constructorFailure=harness(class{constructor(){throw Error('synthetic unsupported');}});assert.equal(constructorFailure.voice.start(),false);assert.equal(constructorFailure.voice.listening,false);
  const synchronousEnd=harness(class{start(){this.onend();}abort(){}});assert.equal(synchronousEnd.voice.start(),false);assert.equal(synchronousEnd.voice.listening,false);assert.equal(synchronousEnd.statuses.at(-1).listening,false,'synchronous denial/end cannot restore a listening status');
  console.log('Active-page voice prototype tests passed: explicit start, cumulative final deduplication, bounded read-only commands, no voice saves, denial/stop/timeout, role/context/visibility/focus cancellation, exact readback with microphone off, unsupported fallback and no automatic restart.');
}
main();
