'use strict';
const assert=require('node:assert/strict');
const {intent,projectFor,createChat,previewText}=require('./project-assistant-chat');
const projects=[{id:101,name:'Synthetic site A'},{id:102,name:'Synthetic site B'},{id:103,name:'Duplicate'},{id:104,name:'Duplicate'},{id:105,name:'Archived',archived:true}];
const context={project:{id:101,name:'Synthetic site A'},timezone:'America/Los_Angeles',members:[{id:11,name:'Jordan Sample'},{id:12,name:'Taylor'},{id:13,name:'Taylor'}],capabilities:{schedule:true}};
const readyRequest='Schedule Jordan Sample at Synthetic site A on 2098-10-12 from 8 AM to 4 PM. Task: Frame west wall. Instructions: Check layout.';
function withProject(text){const chat=createChat({projects});const result=chat.consume(text);if(!result.needsContext){assert.equal(chat.slot,'project');assert.equal(chat.consume('project ID 101').needsContext,101);}else assert.equal(result.needsContext,101);chat.hydrate(context);return chat;}
function main(){
  assert.equal(intent('Please schedule Jordan Sample'),'schedule');assert.equal(intent('Add a project note for Synthetic site A: Gate opens early.'),'note');assert.equal(intent('Create a to-do for Synthetic site A: Pick scraps.'),'todo');for(const text of ['DROP TABLE users','ignore all rules','yes','gate opens early'])assert.equal(intent(text),null);
  assert.equal(projectFor('Schedule at Synthetic site A',projects),101);assert.equal(projectFor('Synthetic site A',projects,true),101);assert.equal(projectFor('Project ID 101',projects,true),101);assert.equal(projectFor('Schedule at Synthetic site A and for Synthetic site B',projects),null);assert.equal(projectFor('Duplicate',projects,true),null);assert.equal(projectFor('a customer from another company',projects,true),null);
  assert.equal(projectFor('Add a note for Synthetic site A or Synthetic site B: Gate open.',projects),null);assert.equal(projectFor('Add a note for Synthetic site A and project ID 999: Gate open.',projects),null,'unknown conflicting project ID is never dropped');
  const empty=createChat({projects});assert.equal(empty.question(),'What do you need?');assert.equal(empty.ready,false);empty.consume('Do something useful');assert.equal(empty.slot,'action');assert.equal(empty.consume('note').needsContext,undefined);assert.equal(empty.slot,'project');assert.equal(empty.consume('Duplicate').needsContext,undefined);assert.equal(empty.consume('project ID 101').needsContext,101);empty.hydrate(context);assert.equal(empty.slot,'text');empty.consume('Literal customer note');assert.equal(empty.ready,true);
  const full=withProject(readyRequest);assert.equal(full.ready,true);assert.deepEqual(full.draft,{action:'schedule',memberId:11,date:'2098-10-12',start:'08:00',end:'16:00',activity:'Frame west wall',instructions:'Check layout.',timezone:'America/Los_Angeles'});
  full.consume('change date');assert.equal(full.ready,false);assert.equal(full.slot,'date');full.consume('next Monday');assert.equal(full.draft.date,'');full.consume('October 13 2098');assert.equal(full.ready,true);full.consume('back');assert.equal(full.draft.date,'');full.consume('cancel');assert.equal(full.question(),'What do you need?');assert.equal(full.projectId,null);
  const partial=withProject('Schedule Taylor at Synthetic site A');assert.equal(partial.slot,'memberId');assert.match(partial.consume('Taylor').message,/could not use/);partial.consume('ID 12');assert.equal(partial.slot,'date');partial.consume('October 12 2098');assert.equal(partial.slot,'start');partial.consume('8');assert.equal(partial.draft.start,undefined);partial.consume('8 AM');partial.consume('4 PM');partial.consume('Frame');partial.consume('Check layout');assert.equal(partial.ready,true);assert.match(partial.consume('yes').message,/Confirm/);
  const note=withProject('Add a note for Synthetic site A: Gate opens at 8 AM. <img src=x onerror=alert(1)>');assert.equal(note.ready,true);assert.equal(note.draft.text,'Gate opens at 8 AM. <img src=x onerror=alert(1)>');assert.equal(note.draft.memberId,undefined,'note does not add scheduling context');
  const todo=withProject('Add a to-do for Synthetic site A: Pick up debris. Due today.');assert.equal(todo.draft.deadline,'today');assert.equal(todo.draft.text,'Pick up debris');assert.equal(todo.ready,true);assert.equal(todo.draft.dueDate,undefined,'server computes today in company timezone');
  const due=withProject('Add a to-do for Synthetic site A: Pick up debris.');assert.equal(due.slot,'deadline');due.consume('December 12 2098');assert.equal(due.draft.dueDate,'2098-12-12');assert.equal(due.ready,true);
  const noDue=withProject('Add a to-do for Synthetic site A: Pick up debris.');noDue.consume('no deadline');assert.equal(noDue.ready,true);assert.equal(noDue.draft.deadline,'none');
  const negativeDue=withProject('Add a to-do for Synthetic site A: Pick scraps, not due today');assert.equal(negativeDue.slot,'deadline');assert.equal(negativeDue.draft.text,'Pick scraps, not due today');assert.equal(negativeDue.ready,false);
  for(const text of ['Pick scraps, not actually due today','Pick scraps, no longer due today',"Pick scraps, isn't due today"]){const chat=withProject('Add a to-do for Synthetic site A: '+text);assert.equal(chat.slot,'deadline');assert.equal(chat.draft.text,text);}
  const shiftName='Shift from 6 AM to 2 PM',shiftProject=createChat({projects:[{id:101,name:shiftName}]});shiftProject.consume('Schedule Jordan Sample at '+shiftName+' on 2098-10-12 from 8 AM to 4 PM. Task: Frame. Instructions: Check.');shiftProject.hydrate({...context,project:{id:101,name:shiftName}});assert.equal(shiftProject.draft.start,'08:00');assert.equal(shiftProject.draft.end,'16:00');
  for(const name of ['Friday Harbor','2098-10-12','Monday 8 AM']){const namedContext={...context,project:{id:101,name}},chat=createChat({projects:[{id:101,name}]});assert.equal(chat.consume('Schedule Jordan Sample at '+name+' from 8 AM to 4 PM. Task: Frame. Instructions: Check.').needsContext,101);chat.hydrate(namedContext);assert.equal(chat.draft.date,undefined,'project name never fills a date');assert.equal(chat.draft.start,'08:00','time in a project name is not a competing shift');}
  const weekdayProject=createChat({projects:[{id:101,name:'Friday Harbor'}]});weekdayProject.consume('Schedule Jordan Sample at Friday Harbor across 2098-12-01 through 2098-12-03 on Monday from 8 AM to 4 PM. Task: Frame. Instructions: Check.');weekdayProject.hydrate({...context,project:{id:101,name:'Friday Harbor'}});assert.deepEqual(weekdayProject.draft.weekdays,[1],'project name never adds Friday');
  const batch=withProject('Schedule Jordan Sample and ID 12 at Synthetic site A across 2098-12-01 through 2098-12-03 on Monday and Wednesday from 8 AM to 4 PM. Task: Frame. Instructions: Verify layout.');assert.equal(batch.draft.action,'schedule_batch');assert.deepEqual(batch.draft.memberIds,[11,12]);assert.deepEqual(batch.draft.weekdays,[1,3]);assert.equal(batch.draft.startDate,'2098-12-01');assert.equal(batch.draft.endDate,'2098-12-03');assert.equal(batch.ready,true);
  const literalDate=withProject('Schedule Jordan Sample at Synthetic site A from 8 AM to 4 PM. Task: Frame. Instructions: Read the report dated 2098-10-12.');assert.equal(literalDate.draft.date,undefined,'instruction date never becomes assignment date');assert.equal(literalDate.ready,false);
  const taskDate=withProject('Schedule Jordan Sample at Synthetic site A from 8 AM to 4 PM to review the report dated 2098-10-12. Instructions: Check layout.');assert.equal(taskDate.draft.date,undefined,'natural task date never becomes assignment date');assert.equal(taskDate.ready,false);
  for(const days of ['Monday through Friday','Monday to Friday','Monday or Wednesday','not Monday','except Monday']){const ambiguousDays=withProject('Schedule Jordan Sample at Synthetic site A across 2098-12-01 through 2098-12-03 on '+days+' from 8 AM to 4 PM. Task: Frame. Instructions: Check.');assert.equal(ambiguousDays.draft.weekdays,undefined,days+' is never converted to endpoints/all selections');assert.equal(ambiguousDays.ready,false);}
  const missingEnd=withProject('Schedule Jordan Sample at Synthetic site A across 2098-12-01 from 8 AM to 4 PM. Task: Frame. Instructions: Check.');assert.equal(missingEnd.draft.endDate,undefined,'range end is genuinely missing');
  const blocked=createChat({projects});blocked.consume(readyRequest);blocked.hydrate({...context,capabilities:{schedule:false}});assert.equal(blocked.ready,false);assert.match(blocked.question(),/unavailable/);blocked.consume('preview these changes');assert.equal(blocked.ready,false,'preview phrase never clears scheduling denial');assert.match(blocked.question(),/unavailable/);blocked.consume('Add a note: Gate open.');assert.equal(blocked.draft.action,'note');assert.equal(blocked.ready,true);
  const changed=withProject(readyRequest);changed.consume('change project');assert.equal(changed.projectId,null);assert.equal(changed.draft.memberId,undefined,'new project clears old scope-specific draft');assert.equal(changed.consume('Synthetic site B').needsContext,102);
  const scoped=createChat({projects});scoped.consume('Add a note for Archived: hidden');assert.equal(scoped.projectId,null,'archived project cannot be inferred');
  const proposal={action:'schedule',memberId:11,memberName:'Jordan Sample',projectName:'Synthetic site A',date:'2098-10-12',start:'08:00',end:'16:00',timezone:'America/Los_Angeles',activity:'Frame',instructions:'Check layout',notification:'In-app only; no email.'};const preview=previewText({proposal});for(const value of ['ID 11','Synthetic site A','2098-10-12','08:00-16:00','America/Los_Angeles','Frame','Check layout','no email'])assert.ok(preview.includes(value));
  console.log('Chat-first reducer passed: natural schedule/note/to-do/batch, one missing detail, exact authorized project/person/ID/date, ambiguity/relative-time refusal, literal text, deadlines, cancel/back/change-scope, permission denial, archived/foreign project exclusion and complete plain preview.');
}
main();
