'use strict';

// Synthetic DOM/VM regressions only. This file does not start a server, use a
// browser, make network requests, or touch any production/customer records.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'project-notes-ui.js'),'utf8');
const app=fs.readFileSync(path.join(__dirname,'app.js'),'utf8');
const reporting=fs.readFileSync(path.join(__dirname,'reporting-controls.js'),'utf8');
const {projectNoteEscape,projectNoteTime,projectNoteCard,projectNotesList}=require('./project-notes-ui');
const {isPublicFile}=require('./public-file-policy');
const tests=[];
function test(name,run){tests.push({name,run})}
const flush=async()=>{await new Promise(resolve=>setImmediate(resolve));await new Promise(resolve=>setImmediate(resolve))};
function deferred(){let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no});return{promise,resolve,reject}}
const clone=value=>JSON.parse(JSON.stringify(value));
const decode=value=>String(value).replace(/&(#39|quot|lt|gt|amp);/g,(_,entity)=>({'#39':"'",quot:'"',lt:'<',gt:'>',amp:'&'}[entity]));
const attrKey=name=>name.slice(5).replace(/-([a-z])/g,(_,letter)=>letter.toUpperCase());
const dataName=name=>'data-'+name.replace(/[A-Z]/g,letter=>'-'+letter.toLowerCase());

// Minimal deterministic DOM with real tree membership, event bubbling,
// attribute selectors, parsed rendered controls, focus and disabled clicks.
// Deliberately no layout engine: CSS is checked separately as a contract.
class FixtureNode{
  constructor(tag='div',document){this.tagName=tag.toLowerCase();this.document=document;this.parentNode=null;this.children=[];this.attributes={};this.dataset={};this.listeners={};this.value='';this.hidden=false;this.disabled=false;this.open=false;this.tabIndex=0;this._text=''}
  get id(){return this.attributes.id||''}set id(value){this.attributes.id=String(value)}
  get className(){return this.attributes.class||''}set className(value){this.attributes.class=String(value)}
  get classList(){return{contains:name=>this.className.split(/\s+/).includes(name),toggle:(name,force)=>{const classes=new Set(this.className.split(/\s+/).filter(Boolean)),on=force===undefined?!classes.has(name):force;if(on)classes.add(name);else classes.delete(name);this.className=[...classes].join(' ');return on},add:(...names)=>names.forEach(name=>this.classList.toggle(name,true)),remove:(...names)=>names.forEach(name=>this.classList.toggle(name,false))}}
  setAttribute(name,value){value=String(value);if(name.startsWith('data-'))this.dataset[attrKey(name)]=value;else this.attributes[name]=value;if(name==='hidden')this.hidden=true;if(name==='disabled')this.disabled=true;if(name==='open')this.open=true;if(name==='value')this.value=value}
  getAttribute(name){if(name.startsWith('data-'))return this.dataset[attrKey(name)]??null;return this.attributes[name]??null}
  hasAttribute(name){return this.getAttribute(name)!==null}
  removeAttribute(name){if(name.startsWith('data-'))delete this.dataset[attrKey(name)];else delete this.attributes[name];if(name==='hidden')this.hidden=false;if(name==='disabled')this.disabled=false}
  append(...nodes){for(const node of nodes){node.remove();node.parentNode=this;this.children.push(node)}}
  prepend(node){node.remove();node.parentNode=this;this.children.unshift(node)}
  remove(){if(this.parentNode){const siblings=this.parentNode.children;siblings.splice(siblings.indexOf(this),1);this.parentNode=null}}
  get isConnected(){return this===this.document?.body||Boolean(this.parentNode?.isConnected)}
  get textContent(){return this.tagName==='#text'?this._text:this.children.map(node=>node.textContent).join('')}
  set textContent(value){this.children.forEach(node=>node.parentNode=null);this.children=[];if(String(value)){const node=new FixtureNode('#text',this.document);node._text=String(value);this.append(node)}}
  set innerHTML(value){this.children.forEach(node=>node.parentNode=null);this.children=[];parseHtml(String(value),this)}
  get innerHTML(){return this.children.map(serialize).join('')}
  insertAdjacentHTML(position,html){const fragment=new FixtureNode('fragment',this.document);parseHtml(html,fragment);const nodes=[...fragment.children];if(position==='beforeend')this.append(...nodes);else if(position==='afterbegin')nodes.reverse().forEach(node=>this.prepend(node));else throw Error('Unsupported fixture position: '+position)}
  matches(selector){return selector.split(',').some(part=>{part=part.trim();if(!part)return false;const attrs=[...part.matchAll(/\[([^\]=]+)(?:="([^"]*)")?\]/g)];if(attrs.some(([,key,value])=>!this.hasAttribute(key)||(value!==undefined&&this.getAttribute(key)!==value)))return false;const plain=part.replace(/\[[^\]]*\]/g,''),tag=plain.match(/^[a-z][\w-]*/i)?.[0],id=plain.match(/#([\w-]+)/)?.[1],classes=[...plain.matchAll(/\.([\w-]+)/g)].map(match=>match[1]);return(!tag||this.tagName===tag.toLowerCase())&&(!id||this.id===id)&&classes.every(name=>this.classList.contains(name))})}
  closest(selector){for(let node=this;node;node=node.parentNode)if(node.matches(selector))return node;return null}
  querySelectorAll(selector){const branches=selector.split(',').map(branch=>branch.trim().split(/\s+/));const matches=node=>branches.some(parts=>{if(!node.matches(parts.at(-1)))return false;let parent=node.parentNode;for(let i=parts.length-2;i>=0;i--){while(parent&&!parent.matches(parts[i]))parent=parent.parentNode;if(!parent)return false;parent=parent.parentNode}return true});const found=[];const visit=node=>{for(const child of node.children){if(child.tagName!=='#text'&&matches(child))found.push(child);visit(child)}};visit(this);return found}
  querySelector(selector){return this.querySelectorAll(selector)[0]||null}
  addEventListener(type,fn,options={}){(this.listeners[type]||=[]).push({fn,capture:options.capture===true})}
  focus(options){this.document.activeElement=this;this.focusOptions=options}
  click(){if(this.disabled)return;return this.document.dispatch('click',this)}
  showModal(){this.open=true}
  close(){this.open=false;this.document.dispatch('close',this)}
}
function serialize(node){if(node.tagName==='#text')return projectNoteEscape(node._text);const attributes={...node.attributes,...Object.fromEntries(Object.entries(node.dataset).map(([key,value])=>[dataName(key),value]))};return '<'+node.tagName+Object.entries(attributes).map(([key,value])=>' '+key+'="'+projectNoteEscape(value)+'"').join('')+'>'+node.innerHTML+'</'+node.tagName+'>'}
function parseHtml(html,parent){const stack=[parent];const voidTags=new Set(['input','br','hr','img','meta','link']);for(const match of html.matchAll(/<!--[\s\S]*?-->|<\/[a-z][^>]*>|<[a-z][^>]*>|[^<]+/gi)){const token=match[0];if(token.startsWith('<!--'))continue;if(token.startsWith('</')){const tag=token.slice(2,-1).trim().toLowerCase();while(stack.length>1){if(stack.pop().tagName===tag)break}continue}if(token[0]==='<'){const [,tag,attributes]=token.match(/^<([a-z][\w-]*)([\s\S]*?)\/?\s*>$/i),node=new FixtureNode(tag,parent.document);for(const attr of attributes.matchAll(/([\w:-]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/g))node.setAttribute(attr[1],decode(attr[2]??attr[3]??attr[4]??''));stack.at(-1).append(node);if(!voidTags.has(node.tagName))stack.push(node)}else{const node=new FixtureNode('#text',parent.document);node._text=decode(token);stack.at(-1).append(node)}}}
function fixtureDocument(){const document={listeners:{},activeElement:null,createElement(tag){return new FixtureNode(tag,this)},addEventListener(type,fn,options={}){(this.listeners[type]||=[]).push({fn,capture:options.capture===true})},querySelector(selector){return this.body.querySelector(selector)},querySelectorAll(selector){return this.body.querySelectorAll(selector)},getElementById(id){return this.querySelector('#'+id)},dispatch(type,target,extra={}){const event={type,target,defaultPrevented:false,preventDefault(){this.defaultPrevented=true},stopPropagation(){this.stopped=true},...extra},ancestors=[];for(let node=target;node;node=node.parentNode)ancestors.push(node);const invoke=(owner,capture)=>{event.currentTarget=owner;for(const listener of owner.listeners?.[type]||[])if(listener.capture===capture)listener.fn(event);if(!capture&&typeof owner['on'+type]==='function')owner['on'+type](event)};invoke(this,true);for(const node of [...ancestors].reverse())invoke(node,true);for(const node of ancestors){invoke(node,false);if(event.stopped)break}if(!event.stopped)invoke(this,false);return event}};document.body=new FixtureNode('body',document);return document}
function item(overrides={}){return{id:'synthetic-note',kind:'note',text:'Synthetic project update',completed:false,revision:1,createdBy:'Synthetic user',createdAt:'2026-10-04T18:00:00Z',updatedBy:'Synthetic user',updatedAt:'2026-10-04T18:00:00Z',history:[{action:'created',by:'Synthetic user',at:'2026-10-04T18:00:00Z',after:{text:'Synthetic project update',completed:false}}],...overrides}}
function sharedProjectSections(id){return '<div class="detail-meta" data-fixture-context>Shared project context '+id+'</div><section class="tm-summary" data-fixture-shared="summary"><h3>Time & material summary</h3><p>Approved amount: $1,250.00</p><input data-fixture-summary value="1250.00"></section><section class="project-ticket-section" data-fixture-shared="tickets"><h3>Tickets & receipts</h3><input id="project-ticket-search" value="Synthetic supplier"><select id="project-ticket-status"><option value="all">All statuses</option><option value="Verified">Verified</option></select><div id="project-ticket-list">Synthetic verified receipt</div></section><section class="panel" data-fixture-shared="rates"><h3>Rate for future office approvals</h3><label>Default labor rate<input id="pdl-default-rate" type="number" value="72.50"></label><label>Reason<textarea id="pdl-default-rate-reason"></textarea></label><div><button data-pdl-default-rate="'+id+'">Save future rate</button></div></section><section class="panel" data-fixture-other>Unrelated project information<section class="tm-summary" data-fixture-nested="summary">Nested summary context</section><section class="project-ticket-section" data-fixture-nested="tickets">Nested ticket context</section><section class="project-notes-shared-rates" data-fixture-nested="rates">Nested rate context</section><input data-fixture-other-input value="Keep other input"></section>'}
// This is a selector contract, not simulated browser layout. Read the real
// focus rule, then use its direct-child selectors against fixture membership.
function notesFocusRules(){return [...fs.readFileSync(path.join(__dirname,'project-notes-ui.css'),'utf8').replace(/\/\*[\s\S]*?\*\//g,'').matchAll(/([^{}]+)\{([^{}]*)\}/g)].filter(([,selectors])=>selectors.includes('project-notes-active'))}
function notesFocusHides(node){return notesFocusRules().some(([,selectors,body])=>/\bdisplay\s*:\s*none\b/.test(body)&&selectors.split(',').some(selector=>{const parts=selector.trim().split(/\s*>\s*/);assert.equal(parts.length,2,'Notes focus hiding must use a direct-child selector');return node.matches(parts[1])&&Boolean(node.parentNode?.matches(parts[0]))}))}
function assertNotesFocus(h,selected){const content=h.query('#project-detail-content');assert.equal(content.classList.contains('project-notes-active'),selected);for(const node of h.all('[data-fixture-shared]')){assert.equal(node.isConnected,true);assert.equal(notesFocusHides(node),selected,node.dataset.fixtureShared+' focus visibility');assert.equal(node.hidden,false,'Focus is CSS-only, not a hidden-attribute rewrite')}for(const node of h.all('[data-fixture-context],[data-fixture-other],[data-fixture-nested],.project-detail-tabs,.project-notes-pane'))assert.equal(notesFocusHides(node),false,'Unrelated context, tabs and Notes stay outside the shared-section hiding rule')}
function sharedSnapshot(h){return h.all('[data-fixture-shared],[data-fixture-other],[data-fixture-context]').map(node=>({node,markup:node.innerHTML,className:node.className,hidden:node.hidden,controls:node.querySelectorAll('input,select,textarea,button').map(control=>({control,value:control.value,disabled:control.disabled}))}))}
function assertSharedUnchanged(h,before){assert.deepEqual(sharedSnapshot(h),before);for(const row of before)assert.equal(row.node.isConnected,true)}
function assertReadOnlyNotes(h){assert.ok(h.calls.every(call=>call.method==='GET'&&/^\/api\/projects\/\d+\/notes-todos$/.test(call.route)),'Tab/editor navigation must neither write financial records nor mutate notes')}
function harness(options={}){
  const document=fixtureDocument(),calls=[],opens=[],windowListeners={},queues={GET:[],POST:[],PATCH:[]};let uuid=0;
  document.body.innerHTML='<dialog id="project-detail-modal"><h2 id="detail-project-name"></h2><div id="project-detail-content"></div></dialog><button id="logout-button"></button><button id="profile-logout-button"></button><button id="subscription-lock-logout"></button>';
  const context={console,document,Date,JSON,AbortController,crypto:{randomUUID:()=>`synthetic-request-${++uuid}`},currentUser:{id:1,role:'owner',memberId:1,projectIds:[1,2],permissions:{}},currentRole:'office',company:{id:'tenant-a'},tenant:'tenant-a',page:'projects',signedInCompanyId:()=>context.tenant,$:selector=>document.querySelector(selector),$$:selector=>document.querySelectorAll(selector),renderEverything(){context.renderCount=(context.renderCount||0)+1},loadRole:async role=>{context.loadedRole=role;return 'role-result'},showPage(page){context.page=page;return 'page-result'},api:async(route,apiOptions)=>{const method=apiOptions?.method||'GET',call={route,options:apiOptions,method,payload:apiOptions?.body?JSON.parse(apiOptions.body):undefined};calls.push(call);if(queues[method]?.length){const response=queues[method].shift();if(response instanceof Error)throw response;return await response}if(method==='GET')return{items:clone(options.items||[])};return item({id:route.split('/').length>5?decodeURIComponent(route.split('/').at(-1)):'created-'+calls.length,...call.payload,history:[]})},addEventListener(type,fn){(windowListeners[type]||=[]).push(fn)}};
  context.window=context;
  context.openProject=async(id,view)=>{opens.push({id,view});if(options.predecessor)await options.predecessor(id,view);if(view&&!view.current())return;renderBase(id);return 'project-result'};
  function renderBase(id){context.$('#detail-project-name').textContent='Synthetic project '+id;context.$('#project-detail-content').innerHTML='<div class="project-detail-tabs"><button class="active" data-project-detail-tab="estimate">Estimate</button><button data-project-detail-tab="dailies">Dailies</button>'+(options.sharedSections?['photos','plans','changes'].map(key=>'<button data-project-detail-tab="'+key+'">'+key+'</button>').join(''):'')+'</div><section class="project-detail-pane active" data-project-detail-pane="estimate">Original project detail</section><section class="project-detail-pane" data-project-detail-pane="dailies">Original daily detail</section>'+(options.sharedSections?['photos','plans','changes'].map(key=>'<section class="project-detail-pane" data-project-detail-pane="'+key+'">Original '+key+' detail</section>').join('')+sharedProjectSections(id):'');context.$('#project-detail-modal').showModal()}
  vm.createContext(context);if(options.beforeModule)options.beforeModule(context);vm.runInContext(source,context,{filename:'project-notes-ui.js'});
  return{context,document,calls,opens,renderBase,query:selector=>document.querySelector(selector),all:selector=>document.querySelectorAll(selector),respond(method,value){queues[method].push(value)},defer(method){const request=deferred();queues[method].push(request.promise);return request},async open(id=1){const result=await context.openProject(id);await flush();return result},click(selector){const node=document.querySelector(selector);assert.ok(node,'Missing synthetic control '+selector);node.click();return node},keydown(selector,key,extra={}){const node=document.querySelector(selector);assert.ok(node,'Missing synthetic key target '+selector);return document.dispatch('keydown',node,{key,...extra})},fireWindow(type,extra={}){for(const fn of windowListeners[type]||[])fn({type,...extra})}};
}

test('effective notes permissions gate create, edit and completion independently',async()=>{
  const h=harness({items:[item({kind:'todo'})]});h.respond('GET',{items:[item({kind:'todo'})],permissions:{view:true,create:false,edit:false,complete:true}});await h.open();
  assert.equal(h.query('[data-note-new="note"]').disabled,true);assert.equal(h.query('[data-note-edit]'),null);assert.ok(h.query('[data-note-toggle]'));const before=h.calls.length;h.click('[data-note-new="note"]');assert.equal(h.calls.length,before);
  h.respond('GET',{items:[item({kind:'todo'})],permissions:{view:true,create:true,edit:true,complete:false}});h.click('[data-notes-refresh]');await flush();assert.equal(h.query('[data-note-toggle]'),null);assert.equal(h.query('[data-note-new="note"]').disabled,false);assert.ok(h.query('[data-note-edit]'));
});
test('revoked viewing clears delivered items and editor on reload',async()=>{
  const h=harness({items:[item()]});await h.open();h.click('[data-note-edit]');h.query('[data-notes-text]').value='Local draft';h.respond('GET',Object.assign(new Error('Notes viewing disabled'),{status:403}));h.click('[data-notes-refresh]');await flush();assert.equal(h.all('[data-note-card]').length,0);assert.equal(h.query('[data-notes-editor]').hidden,true);assert.equal(h.query('[data-notes-text]').value,'');assert.equal(h.query('[data-note-new="note"]').disabled,true);
});
test('plain-text render escapes every note and history surface without mutating input',()=>{
  const attack='<img src=x onerror="attack()"> & <script>bad()</script>\'"',record=item({id:attack,text:attack,createdBy:attack,updatedBy:attack,revision:2,history:[{action:attack,by:attack,at:attack,before:{text:attack+' before'},after:{text:attack+' after',completed:true}}]}),before=clone(record),markup=projectNoteCard(record),document=fixtureDocument();document.body.innerHTML=markup;
  assert.equal(projectNoteEscape(null),'');assert.equal(projectNoteEscape(0),'0');assert.equal(projectNoteEscape('&<>"\''),'&amp;&lt;&gt;&quot;&#39;');assert.equal(projectNoteTime('not-a-date'),'Unknown time');assert.deepEqual(record,before);
  assert.ok(!markup.includes(attack));assert.ok(markup.includes('&lt;img'));assert.match(markup,/Previous text/);assert.equal(document.querySelectorAll('img,script').length,0);assert.equal(document.querySelectorAll('[onerror]').length,0);assert.equal(document.querySelector('[data-note-edit]').dataset.noteEdit,attack);assert.ok(document.body.textContent.includes(attack+' before'));assert.ok(document.body.textContent.includes(attack+' after'));
  assert.equal(projectNoteCard(item({history:undefined})).includes('History (0)'),true);
});
test('list distinguishes notes, open and completed to-dos and reverses only displayed history',()=>{
  const record=item({kind:'todo',history:[{action:'first-change',by:'a',at:'bad',after:{text:'old',completed:false}},{action:'last-change',by:'b',at:'bad',after:{text:'new',completed:true}}]}),markup=projectNotesList([record,item({id:'done',kind:'todo',completed:true}),item({id:'note'})]);
  assert.match(markup,/Open to-dos <span>1<\/span>/);assert.match(markup,/Completed to-dos \(1\)/);assert.match(markup,/Notes <span>1<\/span>/);assert.match(markup,/Mark complete/);assert.match(markup,/Reopen/);assert.ok(markup.indexOf('last-change')<markup.indexOf('first-change'));assert.equal(record.history[0].action,'first-change');
  assert.match(projectNotesList([]),/No open to-dos/);assert.match(projectNotesList([]),/No notes yet/);assert.match(projectNotesList([]),/reopen them anytime/);
});
test('loading disables new/edit/save and repeated reloads; failure exposes retry; empty load recovers',async()=>{
  const h=harness(),request=h.defer('GET');assert.equal(await h.open(),'project-result');
  assert.match(h.query('[data-notes-message]').textContent,/Loading/);assert.equal(h.query('[data-notes-message]').hidden,false);for(const button of h.all('.project-notes-pane button'))assert.equal(button.disabled,true);assert.equal(h.query('[data-notes-text]').disabled,true);
  h.click('[data-notes-refresh]');h.click('[data-note-new="note"]');assert.equal(h.calls.length,1);assert.equal(h.query('[data-notes-editor]').hidden,true);
  request.reject(new Error('Synthetic unavailable'));await flush();assert.equal(h.query('[data-notes-message]').getAttribute('role'),'alert');assert.match(h.query('[data-notes-message]').textContent,/Synthetic unavailable.*Reload/);assert.equal(h.query('[data-note-new="note"]').disabled,true);assert.equal(h.query('[data-notes-save]').disabled,true);assert.equal(h.query('[data-notes-refresh]').disabled,false);
  h.click('[data-notes-refresh]');await flush();assert.equal(h.calls.length,2);assert.match(h.query('[data-notes-list]').textContent,/No notes yet/);assert.equal(h.query('[data-note-new="note"]').disabled,false);assert.equal(h.query('[data-notes-message]').hidden,true);
});
test('note create validates, trims, preserves plain text and closes editor after server acknowledgement',async()=>{
  const h=harness();await h.open();h.click('[data-note-new="note"]');const textarea=h.query('[data-notes-text]');assert.equal(h.document.activeElement,textarea);assert.equal(textarea.focusOptions.preventScroll,true);assert.equal(textarea.getAttribute('maxlength'),'5000');assert.equal(h.query('[data-notes-editor-title]').textContent,'Add note');
  textarea.value='  \n ';h.click('[data-notes-save]');await flush();assert.equal(h.calls.length,1);assert.match(h.query('[data-notes-message]').textContent,/Write a note/);
  textarea.value='  First line\n<script>plain text</script>  ';h.click('[data-notes-save]');await flush();const call=h.calls.at(-1);assert.equal(call.route,'/api/projects/1/notes-todos');assert.equal(call.method,'POST');assert.deepEqual(call.payload,{kind:'note',text:'First line\n<script>plain text</script>',requestId:'synthetic-request-1'});assert.equal(h.query('[data-notes-editor]').hidden,true);assert.equal(textarea.value,'');assert.equal(h.document.activeElement,h.query('[data-note-new="note"]'));assert.match(h.query('[data-notes-list]').innerHTML,/&lt;script&gt;plain text&lt;\/script&gt;/);assert.equal(h.query('[data-notes-message]').textContent,'Saved.');
});
test('failed create retains draft and request ID; repeated Save or keyboard submission posts once',async()=>{
  const h=harness();await h.open();h.click('[data-note-new="todo"]');h.query('[data-notes-text]').value='Retry this synthetic task';const request=h.defer('POST');h.click('[data-notes-save]');h.click('[data-notes-save]');h.keydown('[data-notes-text]','Enter',{ctrlKey:true});await flush();assert.equal(h.calls.filter(call=>call.method==='POST').length,1);assert.equal(h.query('[data-notes-cancel]').disabled,true);
  request.reject(new Error('Synthetic connection lost'));await flush();assert.match(h.query('[data-notes-message]').textContent,/Your draft is still here/);assert.equal(h.query('[data-notes-editor]').hidden,false);assert.equal(h.query('[data-notes-text]').value,'Retry this synthetic task');assert.equal(h.query('[data-notes-save]').disabled,false);
  h.click('[data-notes-save]');await flush();const calls=h.calls.filter(call=>call.method==='POST');assert.equal(calls.length,2);assert.deepEqual(calls[1].payload,calls[0].payload);assert.equal(h.query('[data-project-detail-tab="notes"]').textContent,'Notes & To-dos (1)');
});
test('cancelled editor cannot save and new editor gets a different request ID',async()=>{
  const h=harness();await h.open();h.click('[data-note-new="note"]');h.query('[data-notes-text]').value='Discarded draft';h.click('[data-notes-cancel]');h.keydown('[data-notes-text]','Enter',{ctrlKey:true});h.click('[data-notes-save]');await flush();assert.equal(h.calls.length,1);assert.equal(h.query('[data-notes-editor]').hidden,true);assert.equal(h.query('[data-notes-text]').value,'');
  h.click('[data-note-new="note"]');h.query('[data-notes-text]').value='New draft';h.click('[data-notes-save]');await flush();assert.equal(h.calls.at(-1).payload.requestId,'synthetic-request-2');assert.ok(!h.query('[data-notes-list]').textContent.includes('Discarded draft'));
});
for(const key of ['ctrlKey','metaKey'])test(`${key} + Enter saves; plain Enter does not`,async()=>{
  const h=harness();await h.open();h.click('[data-note-new="todo"]');h.query('[data-notes-text]').value='Keyboard '+key;const plain=h.keydown('[data-notes-text]','Enter');assert.equal(plain.defaultPrevented,false);assert.equal(h.calls.length,1);const chord=h.keydown('[data-notes-text]','Enter',{[key]:true});await flush();assert.equal(chord.defaultPrevented,true);assert.equal(h.calls.at(-1).method,'POST');assert.equal(h.calls.at(-1).payload.kind,'todo');
});
test('edit uses scoped encoded ID/revision; conflict retains draft and history until success',async()=>{
  const original=item({id:'synthetic/id ?#',revision:4}),h=harness({items:[original]});await h.open();h.click('[data-note-edit]');assert.equal(h.query('[data-notes-editor-title]').textContent,'Edit note');assert.equal(h.query('[data-notes-text]').value,original.text);h.query('[data-notes-text]').value='Revised synthetic update';h.respond('PATCH',new Error('Synthetic revision conflict'));h.click('[data-notes-save]');await flush();assert.equal(h.calls.at(-1).route,'/api/projects/1/notes-todos/synthetic%2Fid%20%3F%23');assert.deepEqual(h.calls.at(-1).payload,{revision:4,text:'Revised synthetic update'});assert.equal(h.query('[data-notes-text]').value,'Revised synthetic update');assert.match(h.query('[data-notes-list]').textContent,/Synthetic project update/);assert.match(h.query('[data-notes-message]').textContent,/revision conflict.*draft is still here/);
  h.respond('PATCH',item({...original,text:'Revised synthetic update',revision:5,history:[...original.history,{action:'edited',by:'Another synthetic user',at:'2026-10-05T00:00:00Z',before:{text:original.text},after:{text:'Revised synthetic update'}}]}));h.click('[data-notes-save]');await flush();assert.equal(h.all('[data-note-card]').length,1);assert.match(h.query('[data-notes-list]').textContent,/History \(2\)/);assert.match(h.query('[data-notes-list]').textContent,/Previous text/);assert.equal(h.query('[data-notes-editor]').hidden,true);
});
test('complete/reopen updates counts, preserves notes, follows revision and focuses the moved to-do',async()=>{
  const task=item({id:'task',kind:'todo',text:'Synthetic to-do'}),h=harness({items:[task,item()]});await h.open();assert.equal(h.query('[data-project-detail-tab="notes"]').textContent,'Notes & To-dos (1)');h.respond('PATCH',item({...task,completed:true,revision:2}));const request=h.defer('PATCH'); // First response is immediate; next response is for reopen.
  h.click('[data-note-toggle="task"]');h.click('[data-note-toggle="task"]');await flush();assert.equal(h.calls.filter(call=>call.method==='PATCH').length,1);assert.deepEqual(h.calls.at(-1).payload,{revision:1,completed:true});assert.match(h.query('.project-completed-todos').textContent,/Synthetic to-do/);assert.equal(h.query('.project-completed-todos').open,true);assert.equal(h.query('[data-project-detail-tab="notes"]').textContent,'Notes & To-dos');assert.equal(h.document.activeElement,h.query('[data-note-toggle="task"]'));assert.equal(h.query('[data-notes-message]').textContent,'To-do completed.');
  h.click('[data-note-toggle="task"]');await flush();assert.deepEqual(h.calls.at(-1).payload,{revision:2,completed:false});request.resolve(item({...task,completed:false,revision:3}));await flush();assert.equal(h.query('[data-notes-message]').textContent,'To-do reopened.');assert.equal(h.query('[data-project-detail-tab="notes"]').textContent,'Notes & To-dos (1)');assert.equal(h.all('[data-note-card]').length,2);assert.equal(h.query('[data-note-toggle="task"]').closest('.project-completed-todos'),null);
});
test('failed completion preserves current to-do and successful reload retains existing list on later failure',async()=>{
  const h=harness({items:[item({id:'task',kind:'todo'})]});await h.open();h.respond('PATCH',new Error('Synthetic failed patch'));h.click('[data-note-toggle]');await flush();assert.match(h.query('[data-notes-message]').textContent,/Synthetic failed patch/);assert.equal(h.query('[data-note-toggle]').textContent,'Mark complete');assert.equal(h.query('[data-note-toggle]').disabled,false);h.respond('GET',new Error('Synthetic reload failed'));h.click('[data-notes-refresh]');await flush();assert.equal(h.all('[data-note-card]').length,1);assert.equal(h.query('[data-note-new="note"]').disabled,false);assert.match(h.query('[data-notes-message]').textContent,/Synthetic reload failed.*Reload/);
});
test('opening another create/edit cannot silently replace a current draft',async()=>{
  const h=harness({items:[item()]});await h.open();h.click('[data-note-new="todo"]');h.query('[data-notes-text]').value='Keep my current draft';for(const selector of ['[data-note-new="note"]','[data-note-new="todo"]','[data-note-edit]']){h.click(selector);assert.equal(h.query('[data-notes-text]').value,'Keep my current draft');assert.equal(h.query('[data-notes-editor-title]').textContent,'Add to-do');assert.match(h.query('[data-notes-message]').textContent,/Save or Cancel/)}h.click('[data-notes-save]');await flush();assert.equal(h.calls.at(-1).payload.kind,'todo');assert.equal(h.calls.at(-1).payload.requestId,'synthetic-request-1');
});
test('conflict Reload keeps draft/revision, escapes latest version and requires explicit review before Save or keyboard',async()=>{
  const original=item({id:'conflict',revision:4}),attack='<img src=x onerror="synthetic()">',latest=item({...original,revision:5,text:attack,updatedBy:attack}),h=harness({items:[original]});await h.open();h.click('[data-note-edit]');h.query('[data-notes-text]').value='My preserved correction';const conflict=Object.assign(new Error('Someone changed this item'),{status:409});h.respond('PATCH',conflict);h.click('[data-notes-save]');await flush();assert.match(h.query('[data-notes-message]').textContent,/Reload.*draft is still here/);h.respond('GET',{items:[latest]});h.click('[data-notes-refresh]');await flush();assert.equal(h.query('[data-notes-text]').value,'My preserved correction');assert.equal(h.query('[data-notes-save]').disabled,true);assert.equal(h.query('[data-notes-conflict]').hidden,false);assert.equal(h.query('[data-notes-conflict]').querySelector('img'),null);assert.match(h.query('[data-notes-conflict]').innerHTML,/&lt;img/);assert.equal(h.query('[data-notes-rebase]').textContent,'Use my draft with this version');const count=h.calls.length;h.click('[data-notes-save]');h.keydown('[data-notes-text]','Enter',{ctrlKey:true});h.keydown('[data-notes-text]','Enter',{metaKey:true});await flush();assert.equal(h.calls.length,count,'keyboard shortcuts must respect required review, not submit stale revisions');
  h.click('[data-notes-rebase]');assert.equal(h.query('[data-notes-save]').disabled,false);assert.equal(h.query('[data-notes-conflict]').hidden,true);assert.equal(h.query('[data-notes-text]').value,'My preserved correction');assert.equal(h.document.activeElement,h.query('[data-notes-text]'));h.respond('PATCH',item({...latest,text:'My preserved correction',revision:6}));h.click('[data-notes-save]');await flush();assert.deepEqual(h.calls.at(-1).payload,{revision:5,text:'My preserved correction'});assert.equal(h.query('[data-notes-editor]').hidden,true);
});
test('to-do concurrent completion review shows status and preserves draft without resetting completion',async()=>{
  const original=item({id:'task',kind:'todo',revision:1}),h=harness({items:[original]});await h.open();h.click('[data-note-edit]');h.query('[data-notes-text]').value='Edit completed task text';h.respond('GET',{items:[item({...original,revision:2,completed:true})]});h.click('[data-notes-refresh]');await flush();assert.match(h.query('[data-notes-conflict]').textContent,/Completed/);h.click('[data-notes-rebase]');h.respond('PATCH',item({...original,revision:3,completed:true,text:'Edit completed task text'}));h.click('[data-notes-save]');await flush();assert.deepEqual(h.calls.at(-1).payload,{revision:2,text:'Edit completed task text'});assert.equal(h.query('[data-note-toggle]').textContent,'Reopen');
});
test('ambiguous create with changed draft first replays original payload, then explicitly reviews before PATCH',async()=>{
  const h=harness();await h.open();h.click('[data-note-new="note"]');h.query('[data-notes-text]').value='Original attempted note';h.respond('POST',new Error('The server could not be reached. Nothing was saved—please try again.'));h.click('[data-notes-save]');await flush();assert.match(h.query('[data-notes-message]').textContent,/save could not be confirmed/);assert.doesNotMatch(h.query('[data-notes-message]').textContent,/Nothing was saved/);const original=h.calls.at(-1).payload;h.query('[data-notes-text]').value='Changed newer draft';h.click('[data-notes-save]');await flush();assert.equal(h.calls.filter(call=>call.method==='POST').length,1);assert.equal(h.query('[data-notes-text]').value,'Changed newer draft');assert.match(h.query('[data-notes-conflict]').textContent,/Original attempted note/);assert.ok(h.query('[data-notes-resolve-create]'));
  h.respond('POST',item({id:'recovered',text:'Original attempted note',revision:1}));h.click('[data-notes-resolve-create]');await flush();assert.deepEqual(h.calls.at(-1).payload,original);assert.equal(h.query('[data-notes-text]').value,'Changed newer draft');assert.equal(h.query('[data-notes-save]').disabled,true);assert.match(h.query('[data-notes-message]').textContent,/Original save confirmed/);assert.equal(h.all('[data-note-card]').length,1);h.click('[data-notes-rebase]');h.respond('PATCH',item({id:'recovered',text:'Changed newer draft',revision:2}));h.click('[data-notes-save]');await flush();assert.equal(h.calls.at(-1).route,'/api/projects/1/notes-todos/recovered');assert.deepEqual(h.calls.at(-1).payload,{revision:1,text:'Changed newer draft'});assert.equal(h.all('[data-note-card]').length,1);assert.equal(h.query('[data-notes-editor]').hidden,true);
});
test('definitive create validation rejection allows corrected text with the same request ID',async()=>{
  const h=harness();await h.open();h.click('[data-note-new="note"]');h.query('[data-notes-text]').value='Bad\u0000control';h.respond('POST',Object.assign(new Error('Control characters are not allowed'),{status:400,code:'invalid_text'}));h.click('[data-notes-save]');await flush();const first=h.calls.at(-1).payload;h.query('[data-notes-text]').value='Corrected clean text';h.click('[data-notes-save]');await flush();assert.equal(h.calls.filter(call=>call.method==='POST').length,2);assert.equal(h.calls.at(-1).payload.text,'Corrected clean text');assert.equal(h.calls.at(-1).payload.requestId,first.requestId);assert.equal(h.query('[data-notes-editor]').hidden,true);
});
for(const status of [409,500,503])test(`create ${status} retains original uncertain attempt instead of rotating request ID`,async()=>{
  const h=harness();await h.open();h.click('[data-note-new="todo"]');h.query('[data-notes-text]').value='Original attempt';h.respond('POST',Object.assign(new Error('Synthetic uncertain response'),{status}));h.click('[data-notes-save]');await flush();h.query('[data-notes-text]').value='Different draft';h.click('[data-notes-save]');await flush();assert.equal(h.calls.filter(call=>call.method==='POST').length,1);assert.ok(h.query('[data-notes-resolve-create]'));assert.equal(h.query('[data-notes-text]').value,'Different draft');
});
for(const status of [400,401,403,429])test(`an ambiguous create followed by ${status} cannot discard the original attempt`,async()=>{
  const h=harness();await h.open();h.click('[data-note-new="note"]');h.query('[data-notes-text]').value='Original uncertain note';h.respond('POST',new Error('Synthetic transport loss'));h.click('[data-notes-save]');await flush();const original=h.calls.at(-1).payload;h.respond('POST',Object.assign(new Error('Synthetic later rejection'),{status}));h.click('[data-notes-save]');await flush();assert.deepEqual(h.calls.at(-1).payload,original);h.query('[data-notes-text]').value='Newer changed draft';h.click('[data-notes-save]');await flush();assert.equal(h.calls.filter(call=>call.method==='POST').length,2);assert.ok(h.query('[data-notes-resolve-create]'));h.respond('POST',item({id:'already-saved',text:'Original uncertain note'}));h.click('[data-notes-resolve-create]');await flush();assert.deepEqual(h.calls.at(-1).payload,original);assert.equal(h.query('[data-notes-text]').value,'Newer changed draft');assert.ok(h.query('[data-notes-rebase]'));assert.equal(h.query('[data-notes-save]').disabled,true);
});
test('unauthenticated notes shows sign-in error without enabling mutations or requesting redirect',async()=>{
  const h=harness();h.respond('GET',Object.assign(new Error('Authentication required'),{status:401}));await h.open();assert.equal(h.query('[data-notes-message]').textContent,'Sign in to use Notes & To-dos.');assert.equal(h.query('[data-note-new="note"]').disabled,true);assert.equal(h.query('[data-notes-refresh]').disabled,false);assert.equal(h.calls[0].options.redirectOnUnauthorized,false);assert.ok(h.calls[0].options.signal instanceof AbortSignal);
});
test('GET, POST and PATCH carry the same abort signal and suppress unauthorized redirect',async()=>{
  const h=harness();await h.open();h.click('[data-note-new="todo"]');h.query('[data-notes-text]').value='Synthetic abortable item';h.click('[data-notes-save]');await flush();h.click('[data-note-toggle]');await flush();assert.deepEqual(h.calls.map(call=>call.method),['GET','POST','PATCH']);const signal=h.calls[0].options.signal;assert.equal(signal.aborted,false);for(const call of h.calls){assert.equal(call.options.signal,signal);assert.equal(call.options.redirectOnUnauthorized,false)}h.query('#project-detail-modal').close();assert.equal(signal.aborted,true);
});
test('tabs provide connected ARIA roles, roving tabindex, wraparound arrows, Home/End and click activation',async()=>{
  const h=harness();await h.open();const tabs=h.all('[data-project-detail-tab]'),notes=tabs.at(-1);assert.equal(h.query('.project-detail-tabs').getAttribute('role'),'tablist');assert.equal(h.query('.project-detail-tabs').getAttribute('aria-label'),'Project details');for(const tab of tabs){assert.equal(tab.getAttribute('role'),'tab');const pane=h.query('#'+tab.getAttribute('aria-controls'));assert.ok(pane);assert.equal(pane.getAttribute('aria-labelledby'),tab.id);assert.equal(pane.getAttribute('role'),'tabpanel');assert.equal(pane.tabIndex,0)}
  assert.equal(tabs[0].tabIndex,0);assert.equal(notes.tabIndex,-1);h.keydown('[data-project-detail-tab="estimate"]','ArrowLeft');assert.equal(h.document.activeElement,notes);assert.equal(notes.tabIndex,0);assert.equal(notes.getAttribute('aria-selected'),'true');assert.equal(h.query('[data-project-detail-pane="notes"]').classList.contains('active'),true);
  h.keydown('[data-project-detail-tab="notes"]','ArrowRight');assert.equal(h.document.activeElement,tabs[0]);h.keydown('[data-project-detail-tab="estimate"]','End');assert.equal(h.document.activeElement,notes);h.keydown('[data-project-detail-tab="notes"]','Home');assert.equal(h.document.activeElement,tabs[0]);const unhandled=h.keydown('[data-project-detail-tab="estimate"]','Escape');assert.equal(unhandled.defaultPrevented,false);h.click('[data-project-detail-tab="dailies"]');assert.equal(h.query('[data-project-detail-tab="dailies"]').getAttribute('aria-selected'),'true');assert.equal(h.query('[data-project-detail-pane="notes"]').classList.contains('active'),false);
});
test('Notes focus CSS hides exactly three named direct children and never generic panels or context',async()=>{
  const rules=notesFocusRules(),selectors=rules.flatMap(([,selector])=>selector.split(',').map(value=>value.trim().replace(/\s*>\s*/g,'>'))).sort();
  assert.deepEqual(selectors,['#project-detail-content.project-notes-active>.project-notes-shared-rates','#project-detail-content.project-notes-active>.project-ticket-section','#project-detail-content.project-notes-active>.tm-summary'].sort());for(const [,,body] of rules)assert.match(body,/^\s*display\s*:\s*none\s*(?:!important\s*)?;?\s*$/);
  const h=harness({sharedSections:true});await h.open();const rateSection=h.query('[data-fixture-shared="rates"]');assert.equal(h.query('[data-pdl-default-rate]').closest('section'),rateSection);assert.equal(rateSection.classList.contains('project-notes-shared-rates'),true);assert.equal(h.query('[data-fixture-other]').classList.contains('project-notes-shared-rates'),false);assertNotesFocus(h,false);h.click('[data-project-detail-tab="notes"]');assertNotesFocus(h,true);assertReadOnlyNotes(h);
});
test('repeated Notes and original tab clicks restore shared sections without changing values, records or history',async()=>{
  const records={projects:[{id:1,tmSettings:{defaultLaborRate:72.5},contractValue:1250}],reports:[{id:9,projectId:1,capturedRate:68,approved:true}],tickets:[{id:4,projectId:1,amount:120,history:['verified']}]},beforeRecords=clone(records),note=item({revision:2,history:[...item().history,{action:'edited',by:'Synthetic editor',at:'2026-10-05T00:00:00Z',before:{text:'Earlier note'},after:{text:'Synthetic project update'}}]}),beforeNote=clone(note),h=harness({sharedSections:true,items:[note],beforeModule:context=>{context.projects=records.projects;context.reports=records.reports;context.projectTickets=records.tickets}});await h.open();
  h.query('#project-ticket-search').value='Keep supplier filter';h.query('#project-ticket-status').value='Verified';h.query('#pdl-default-rate').value='83.75';h.query('#pdl-default-rate-reason').value='Unsubmitted rate reason';h.query('[data-fixture-other-input]').value='Keep unrelated draft';const before=sharedSnapshot(h),pane=h.query('.project-notes-pane'),list=h.query('[data-notes-list]'),history=h.query('.project-note-history');history.open=true;const historyMarkup=list.innerHTML;
  for(let pass=0;pass<3;pass++)for(const key of ['estimate','dailies','photos','plans','changes']){h.click('[data-project-detail-tab="notes"]');assertNotesFocus(h,true);assert.equal(h.query('.project-notes-pane'),pane);assert.equal(h.query('[data-notes-list]'),list);assert.equal(list.innerHTML,historyMarkup);assert.equal(history.open,true);h.click('[data-project-detail-tab="'+key+'"]');assertNotesFocus(h,false);assert.equal(h.query('[data-project-detail-pane="'+key+'"]').classList.contains('active'),true);assert.equal(h.query('[data-project-detail-tab="'+key+'"]').getAttribute('aria-selected'),'true');assertSharedUnchanged(h,before)}
  assert.deepEqual(records,beforeRecords);assert.deepEqual(note,beforeNote);assert.equal(h.calls.length,1);assertReadOnlyNotes(h);
});
test('keyboard tab cycles keep Notes focus state synchronized and preserve a note edit draft',async()=>{
  const note=item({id:'keyboard-context',revision:7}),h=harness({sharedSections:true,items:[note]});await h.open();h.keydown('[data-project-detail-tab="estimate"]','End');assertNotesFocus(h,true);h.click('[data-note-edit="keyboard-context"]');h.query('[data-notes-text]').value='Keep this project-specific edit';const pane=h.query('.project-notes-pane'),editor=h.query('[data-notes-editor]'),before=sharedSnapshot(h),tabKeys=['estimate','dailies','photos','plans','changes','notes'];
  for(let pass=0;pass<2;pass++)for(const direction of ['ArrowRight','ArrowLeft'])for(let step=0;step<tabKeys.length;step++){const selected=h.all('[data-project-detail-tab]').find(tab=>tab.classList.contains('active')),index=tabKeys.indexOf(selected.dataset.projectDetailTab),next=tabKeys[(index+(direction==='ArrowRight'?1:-1)+tabKeys.length)%tabKeys.length];h.keydown('[data-project-detail-tab="'+selected.dataset.projectDetailTab+'"]',direction);assertNotesFocus(h,next==='notes');assert.equal(h.document.activeElement,h.query('[data-project-detail-tab="'+next+'"]'));assert.equal(h.query('.project-notes-pane'),pane);assert.equal(h.query('[data-notes-editor]'),editor);assert.equal(editor.hidden,false);assert.equal(h.query('[data-notes-text]').value,'Keep this project-specific edit');assertSharedUnchanged(h,before)}
  h.keydown('[data-project-detail-tab="notes"]','Home');assertNotesFocus(h,false);h.keydown('[data-project-detail-tab="estimate"]','End');assertNotesFocus(h,true);assert.equal(h.query('[data-notes-editor-title]').textContent,'Edit note');assert.equal(h.query('[data-note-edit]').dataset.noteEdit,'keyboard-context');assert.equal(h.calls.length,1);assertReadOnlyNotes(h);
});
for(const editorKind of ['note','todo','existing'])test(`Cancel ${editorKind} editor stays on Notes with shared controls hidden and no writes`,async()=>{
  const note=item(),beforeNote=clone(note),h=harness({sharedSections:true,items:[note]});await h.open();h.click('[data-project-detail-tab="notes"]');const pane=h.query('.project-notes-pane'),list=h.query('[data-notes-list]'),markup=list.innerHTML,before=sharedSnapshot(h);h.click(editorKind==='existing'?'[data-note-edit]':'[data-note-new="'+editorKind+'"]');h.query('[data-notes-text]').value='Discard only this editor draft';h.click('[data-notes-cancel]');assertNotesFocus(h,true);assert.equal(h.query('[data-project-detail-tab="notes"]').getAttribute('aria-selected'),'true');assert.equal(h.query('.project-notes-pane'),pane);assert.equal(pane.classList.contains('active'),true);assert.equal(h.query('[data-notes-editor]').hidden,true);assert.equal(h.query('[data-notes-text]').value,'');assert.equal(h.document.activeElement,h.query('[data-note-new="note"]'));assert.equal(h.query('[data-notes-list]'),list);assert.equal(list.innerHTML,markup);assertSharedUnchanged(h,before);assert.deepEqual(note,beforeNote);assert.equal(h.query('#project-detail-modal').open,true);assertReadOnlyNotes(h);
});
test('Notes focus tolerates projects with no shared financial or ticket sections',async()=>{
  const h=harness();await h.open();assert.equal(h.all('.project-notes-shared-rates').length,0);h.click('[data-project-detail-tab="notes"]');assertNotesFocus(h,true);h.click('[data-project-detail-tab="estimate"]');assertNotesFocus(h,false);assertReadOnlyNotes(h);
});
test('notes affordances are non-financial and contain no delete action or external rich-text rendering',async()=>{
  const h=harness({items:[item(),item({id:'task',kind:'todo'})]});await h.open();const pane=h.query('.project-notes-pane'),markup=pane.innerHTML;assert.equal(pane.querySelectorAll('input,select,iframe,img,script,a').length,0);assert.doesNotMatch(markup,/data-(?:contract|rate|amount|delete)|\b(?:billing|price|budget|invoice|rate)\b/i);assert.match(pane.textContent,/Shared with your team on this project/);assert.equal(h.calls.every(call=>/^\/api\/projects\/1\/notes-todos/.test(call.route)),true);
});
for(const role of ['owner','admin','project_manager','foreman','field'])test(`${role} receives notes controls without financial permission`,async()=>{const h=harness();h.context.currentUser.role=role;h.context.currentUser.permissions={viewPricing:false};h.context.currentRole=role==='field'||role==='foreman'?'field':'office';await h.open();assert.ok(h.query('[data-note-new="note"]'));assert.equal(h.calls.length,1)});
for(const role of ['guest','subcontractor','viewer','office','unknown',undefined])test(`${String(role)} cannot mount or request notes`,async()=>{const h=harness();h.context.currentUser.role=role;await h.open();assert.equal(h.query('.project-notes-pane'),null);assert.equal(h.query('[data-project-detail-tab="notes"]'),null);assert.equal(h.calls.length,0)});
test('missing signed-in user cannot mount notes',async()=>{const h=harness();h.context.currentUser=null;await h.open();assert.equal(h.query('.project-notes-pane'),null);assert.equal(h.calls.length,0)});

const invalidations=[
  ['tenant header',h=>{h.context.tenant='tenant-b';h.context.renderEverything()}],
  ['company object',h=>{h.context.company.id='tenant-b';h.context.renderEverything()}],
  ['signed-in user',h=>{h.context.currentUser.id=2;h.context.renderEverything()}],
  ['account role',h=>{h.context.currentUser.role='guest';h.context.renderEverything()}],
  ['member identity',h=>{h.context.currentUser.memberId=2;h.context.renderEverything()}],
  ['assigned projects',h=>{h.context.currentUser.projectIds=[2];h.context.renderEverything()}],
  ['permissions',h=>{h.context.currentUser.permissions={viewPricing:false};h.context.renderEverything()}],
  ['view role',h=>{h.context.currentRole='field';h.context.renderEverything()}],
  ['role loader',h=>h.context.loadRole('field')],
  ['modal close',h=>h.query('#project-detail-modal').close()],
  ['modal cancel',h=>h.document.dispatch('cancel',h.query('#project-detail-modal'))],
  ['logout',h=>h.click('#logout-button')],
  ['profile logout',h=>h.click('#profile-logout-button')],
  ['subscription logout',h=>h.click('#subscription-lock-logout')],
  ['pagehide',h=>h.fireWindow('pagehide')],
  ['tenant storage',h=>h.fireWindow('storage',{key:'pdl-company-id'})],
  ['role storage',h=>h.fireWindow('storage',{key:'pdl-role'})],
  ['project navigation',h=>h.open(2)],
  ['same-project reopen',h=>h.open(1)],
  ['in-app navigation',h=>h.context.showPage('reports')],
  ['Back/Forward navigation',h=>h.fireWindow('popstate')],
  ['hash navigation',h=>h.fireWindow('hashchange')]
];
for(const [label,invalidate] of invalidations){
  test(`Notes focus class clears after ${label}, restoring shared sections without financial writes`,async()=>{
    const note=item(),beforeNote=clone(note),h=harness({sharedSections:true,items:[note]});await h.open();h.query('#project-ticket-search').value='Unchanged ticket search';h.query('#pdl-default-rate').value='91.25';h.query('#pdl-default-rate-reason').value='Unsubmitted reason';const content=h.query('#project-detail-content'),before=sharedSnapshot(h),oldPane=h.query('.project-notes-pane');h.click('[data-project-detail-tab="notes"]');assertNotesFocus(h,true);h.click('[data-note-new="note"]');h.query('[data-notes-text]').value='Old project draft';await invalidate(h);await flush();assert.equal(h.query('#project-detail-content'),content);assertNotesFocus(h,false);assert.equal(oldPane.isConnected,false);assert.equal(h.document.body.textContent.includes('Old project draft'),false);for(const row of before){assert.equal(row.node.innerHTML,row.markup);assert.equal(row.node.className,row.className);assert.equal(row.node.hidden,row.hidden);for(const control of row.controls){assert.equal(control.control.value,control.value);assert.equal(control.control.disabled,control.disabled)}}if(['project navigation','same-project reopen'].includes(label)){assert.equal(h.query('[data-project-detail-pane="estimate"]').classList.contains('active'),true);assert.equal(h.query('[data-notes-editor]').hidden,true);assert.equal(h.query('[data-notes-text]').value,'')}else assertSharedUnchanged(h,before);assert.deepEqual(note,beforeNote);assertReadOnlyNotes(h);
  });
  test(`stale list after ${label} cannot render old project text`,async()=>{
    const h=harness(),request=h.defer('GET');await h.open();const oldPane=h.query('.project-notes-pane');await invalidate(h);assert.equal(oldPane.isConnected,false,`${label} must immediately clear the old notes pane`);request.resolve({items:[item({text:'STALE LIST SECRET'})]});await flush();assert.ok(!h.document.body.textContent.includes('STALE LIST SECRET'));assert.equal(oldPane.querySelectorAll('[data-note-card]').length,0);if(h.query('.project-notes-pane'))assert.equal(h.query('.project-notes-pane').querySelectorAll('[data-note-card]').length,0);
  });
  for(const outcome of ['success','failure'])test(`stale save ${outcome} after ${label} cannot alter current pane or show old feedback`,async()=>{
    const h=harness();await h.open();h.click('[data-note-new="note"]');h.query('[data-notes-text]').value='OLD DRAFT SECRET';const request=h.defer('POST');h.click('[data-notes-save]');await flush();const oldPane=h.query('.project-notes-pane');await invalidate(h);assert.equal(oldPane.isConnected,false);if(!h.query('.project-notes-pane')&&h.context.currentUser?.role!=='guest')await h.open(2);const newPane=h.query('.project-notes-pane'),before=newPane?.innerHTML;
    if(outcome==='success')request.resolve(item({text:'STALE SAVED SECRET'}));else request.reject(new Error('STALE FAILURE SECRET'));await flush();assert.ok(!h.document.body.textContent.includes('STALE SAVED SECRET'));assert.ok(!h.document.body.textContent.includes('STALE FAILURE SECRET'));assert.ok(!h.document.body.textContent.includes('OLD DRAFT SECRET'));if(newPane)assert.equal(newPane.innerHTML,before,'stale result must not reset controls or feedback in the newer view');
  });
  test(`stale list failure after ${label} cannot show old error or reactivate old controls`,async()=>{
    const h=harness(),request=h.defer('GET');await h.open();const oldPane=h.query('.project-notes-pane'),signal=h.calls.at(-1).options.signal;await invalidate(h);assert.equal(signal.aborted,true,`${label} aborts old request`);request.reject(new Error('STALE LIST ERROR SECRET'));await flush();assert.ok(!h.document.body.textContent.includes('STALE LIST ERROR SECRET'));assert.equal(oldPane.querySelector('[data-note-new="note"]').disabled,true);
  });
  test(`stale completion after ${label} cannot update replacement project rows`,async()=>{
    const original=item({id:'task',kind:'todo'}),h=harness({items:[original]});await h.open();const request=h.defer('PATCH');h.click('[data-note-toggle]');await flush();const signal=h.calls.at(-1).options.signal;await invalidate(h);assert.equal(signal.aborted,true);if(!h.query('.project-notes-pane')&&h.context.currentUser?.role!=='guest')await h.open(2);const pane=h.query('.project-notes-pane'),before=pane?.innerHTML;request.resolve(item({...original,completed:true,revision:2,text:'STALE TO-DO SECRET'}));await flush();assert.ok(!h.document.body.textContent.includes('STALE TO-DO SECRET'));if(pane)assert.equal(pane.innerHTML,before);
  });
}
test('closing and reopening from Notes starts the original view and restores only the reopened project context',async()=>{
  const h=harness({sharedSections:true,items:[item({id:'first-project',text:'First project saved note'})]});await h.open(1);h.click('[data-project-detail-tab="notes"]');h.click('[data-note-edit]');h.query('[data-notes-text]').value='First project unsaved edit';h.query('#project-detail-modal').close();assertNotesFocus(h,false);h.respond('GET',{items:[item({id:'second-project',text:'Second project saved note'})]});await h.open(2);assertNotesFocus(h,false);assert.equal(h.query('[data-project-detail-tab="estimate"]').getAttribute('aria-selected'),'true');assert.equal(h.query('[data-notes-editor]').hidden,true);assert.equal(h.query('[data-notes-text]').value,'');h.click('[data-project-detail-tab="notes"]');assertNotesFocus(h,true);assert.match(h.query('[data-notes-list]').textContent,/Second project saved note/);assert.doesNotMatch(h.query('[data-notes-list]').textContent,/First project/);assert.equal(h.query('[data-pdl-default-rate]').dataset.pdlDefaultRate,'2');assertReadOnlyNotes(h);
});
test('identity guard works even before renderEverything has been called',async()=>{
  const h=harness(),request=h.defer('GET');await h.open();h.context.currentUser.id=2;request.resolve({items:[item({text:'UNRENDERED IDENTITY SECRET'})]});await flush();assert.ok(!h.document.body.textContent.includes('UNRENDERED IDENTITY SECRET'));const count=h.calls.length;h.click('[data-notes-refresh]');assert.equal(h.calls.length,count);h.context.renderEverything();assert.equal(h.query('.project-notes-pane'),null);
});
test('unrelated render/storage events preserve an active notes draft',async()=>{
  const h=harness();await h.open();h.click('[data-note-new="note"]');h.query('[data-notes-text]').value='Still here';const pane=h.query('.project-notes-pane');h.context.renderEverything();h.fireWindow('storage',{key:'unrelated-key'});assert.equal(h.query('.project-notes-pane'),pane);assert.equal(h.query('[data-notes-text]').value,'Still here');assert.equal(h.query('[data-notes-editor]').hidden,false);
});
test('newer opening wins when earlier predecessor resolves last',async()=>{
  const old=deferred(),h=harness({predecessor:id=>id===1?old.promise:undefined}),first=h.context.openProject(1);await flush();await h.open(2);assert.equal(h.query('#detail-project-name').textContent,'Synthetic project 2');old.resolve();await first;await flush();assert.equal(h.query('#detail-project-name').textContent,'Synthetic project 2');assert.equal(h.all('[data-project-detail-tab="notes"]').length,1);assert.equal(h.calls.filter(call=>call.route.includes('/1/')).length,0);assert.equal(h.opens[0].view.current(),false);assert.equal(h.opens[1].view.current(),true);
});
test('an old queued dialog close cannot cancel a newer project opening',async()=>{
  // Native dialog.close queues close on the user-interaction task source:
  // https://html.spec.whatwg.org/multipage/interactive-elements.html#close-the-dialog
  const queued=[],next=deferred(),h=harness({beforeModule:context=>{const dialog=context.$('#project-detail-modal');dialog.close=function(){if(!this.open)return;this.open=false;queued.push(()=>context.document.dispatch('close',this))}},predecessor:id=>id===2?next.promise:undefined});await h.open(1);h.context.showPage('reports');assert.equal(queued.length,1);const opening=h.context.openProject(2);await flush();queued.shift()();next.resolve();await opening;await flush();assert.equal(h.query('#detail-project-name').textContent,'Synthetic project 2');assert.equal(h.query('#project-detail-modal').open,true);assert.equal(h.all('[data-project-detail-tab="notes"]').length,1);
});
test('native close initiation invalidates a pending project before its queued close event',async()=>{
  const queued=[],next=deferred(),h=harness({beforeModule:context=>{const dialog=context.$('#project-detail-modal');dialog.close=function(){if(!this.open)return;this.open=false;queued.push(()=>context.document.dispatch('close',this))}},predecessor:id=>id===2?next.promise:undefined});await h.open(1);const opening=h.context.openProject(2);await flush();h.query('#project-detail-modal').close();next.resolve();await opening;await flush();assert.equal(h.query('#project-detail-modal').open,false,'a closed project must not reopen while the close notification is queued');assert.equal(h.query('.project-notes-pane'),null);for(const close of queued)close();
});
for(const [label,invalidate] of invalidations.filter(([label])=>!['project navigation','same-project reopen'].includes(label)))test(`pending predecessor is invalidated by ${label} before it opens a dialog`,async()=>{
  const request=deferred(),h=harness({predecessor:()=>request.promise}),opening=h.context.openProject(1);await flush();await invalidate(h);request.resolve();await opening;await flush();assert.equal(h.query('#project-detail-modal').open,false);assert.equal(h.query('.project-notes-pane'),null);assert.equal(h.calls.length,0);
});

// Extract original wrappers instead of reimplementing the new view propagation.
// Formatting anchors intentionally make additional wrappers require explicit QA.
function wrapperAfter(marker,sourceText=app){const markerIndex=sourceText.indexOf(marker);assert.ok(markerIndex>=0,'Missing source wrapper anchor '+marker);const start=sourceText.indexOf('openProject=async function',markerIndex);assert.ok(start>=0);const line=sourceText.slice(start).split('\n')[0];if(/};?\s*$/.test(line))return line;const end=sourceText.indexOf('\n}',start);assert.ok(end>=0);return sourceText.slice(start,end+2)}
const wrapperCases=[
  {name:'plans',marker:'const openProjectWithPlans=openProject;',previous:'openProjectWithPlans',beforeAwait:true},
  {name:'T&M estimate summary',marker:'const openProjectEstimateView=openProject;',previous:'openProjectEstimateView'},
  {name:'change tracking',marker:'const openProjectTmView=openProject;',previous:'openProjectTmView'},
  {name:'pricing restrictions',marker:'const openProjectForPricing=openProject;',previous:'openProjectForPricing'},
  {name:'project template',marker:'const openProjectBeforeTemplate=openProject;',previous:'openProjectBeforeTemplate'},
  {name:'tickets',marker:"$('#sub-link-result').addEventListener('click',async event=>",previous:'openProjectBeforeTickets'},
  {name:'contract value visibility',marker:'const openProjectBeforeContractValues=openProject;',previous:'openProjectBeforeContractValues'},
  {name:'reporting rate control',marker:'const pdlOpenProject=openProject;',previous:'pdlOpenProject',source:reporting}
];
for(const wrapper of wrapperCases)test(`actual ${wrapper.name} wrapper forwards the optional view and stops obsolete work`,async()=>{
  const wait=deferred(),calls=[],view={valid:true,current(){return this.valid}},sentinel=Symbol('result');let touches=0;
  const context={openProject(){},currentRole:'office',currentUser:{id:1,role:'owner'},projects:[{id:1,contractType:'tm'}],projectPlans:['new-current-plan'],projectTickets:[],company:{id:'a'},signedInCompanyId:()=> 'a',pdlContext:()=> 'identity',api:async(...args)=>{calls.push({api:args});return wait.promise},$:()=>{touches++;return null},document:{getElementById(){touches++;return null}},notify(){touches++},paintProjectTemplate(){touches++},applyContractValueVisibility(){touches++},canViewCompanyPricing(){touches++;return false}};
  context[wrapper.previous]=async(id,passedView)=>{calls.push({id,view:passedView});if(!wrapper.beforeAwait)await wait.promise;return sentinel};vm.createContext(context);vm.runInContext(wrapperAfter(wrapper.marker,wrapper.source),context);const pending=context.openProject(1,view);await flush();if(!wrapper.beforeAwait)assert.equal(calls[0].view,view);view.valid=false;wait.resolve([]);await pending;assert.equal(touches,0,'Obsolete wrapper must not inspect or modify DOM, financial state or notices');assert.deepEqual(context.projectPlans,['new-current-plan']);if(wrapper.beforeAwait)assert.equal(calls.some(call=>call.id===1),false);
});
test('actual plans wrapper passes live view to base and preserves it through success/failure',async()=>{
  for(const failed of [false,true]){const view={current:()=>true},calls=[],context={openProject(){},projectPlans:[],currentRole:'field',api:async()=>{if(failed)throw Error('synthetic');return['synthetic-plan']},openProjectWithPlans(id,passed){calls.push({id,passed});return 'base-result'}};vm.createContext(context);vm.runInContext(wrapperAfter('const openProjectWithPlans=openProject;'),context);assert.equal(await context.openProject(1,view),'base-result');assert.equal(calls[0].passed,view);assert.equal(context.projectPlans.length,failed?0:1)}
});
test('actual base renderer exits immediately for an obsolete view',()=>{
  const start=app.indexOf('function openProject(id,view){'),end=app.indexOf('\n}',start),context={};assert.ok(start>=0);vm.createContext(context);vm.runInContext(app.slice(start,end+2),context);assert.equal(context.openProject(1,{current:()=>false}),undefined);
});
for(const wrapper of wrapperCases.filter(row=>['T&M estimate summary','change tracking'].includes(row.name)))for(const failed of [false,true])test(`actual ${wrapper.name} drops delayed ${failed?'error':'success'} after its API await`,async()=>{
  const wait=deferred(),view={valid:true,current(){return this.valid}},writes=[],context={openProject(){},projects:[{id:1,contractType:'tm'}],currentRole:'office',canViewCompanyPricing:()=>true,companyTracksContractValues:()=>true,projectHealthDetails:()=>({status:'On track',reason:'Synthetic'}),escapeHtml:projectNoteEscape,$:()=>({querySelector:()=>null,insertAdjacentHTML:(position,markup)=>writes.push(markup)}),api:()=>wait.promise,notify:message=>writes.push(message)};context[wrapper.previous]=async()=>{};vm.createContext(context);vm.runInContext(wrapperAfter(wrapper.marker),context);const opening=context.openProject(1,view);await flush();const before=writes.length;view.valid=false;if(failed)wait.reject(Error('OBSOLETE WRAPPER FAILURE'));else wait.resolve(wrapper.name==='change tracking'?[]:{labor:[]});await opening;assert.equal(writes.length,before);
});
test('every project-opening layer accepts and forwards view, including reporting loaded before notes',()=>{
  const all=[...app.matchAll(/openProject=async function\(([^)]*)\)/g)];assert.equal(all.length,7,'Review/test any new app openProject layer');for(const match of all)assert.equal(match[1],'id,view');assert.match(reporting,/openProject=async function\(id,view\)/);assert.match(reporting,/await pdlOpenProject\(id,view\)/);
});

function installActualApi(context){
  const base=app.split('\n').find(line=>line.startsWith('async function api('));assert.ok(base);vm.runInContext(base,context);
  const aliases=['workspaceApi','apiBeforeSuperintendent','apiBeforeWorkspaceFeedback','apiBeforeReportLaborPreservation','apiBeforeTemplatePhotoTransaction'];
  assert.equal([...app.matchAll(/\bapi=async function\(/g)].length,aliases.length,'Review any additional API layer before shipping');
  for(const alias of aliases){const marker=`const ${alias}=api;`,start=app.indexOf(marker);assert.ok(start>=0);const assignment=app.indexOf('api=async function(',start),line=app.slice(assignment).split('\n')[0],body=/};?\s*$/.test(line)?line:app.slice(assignment,app.indexOf('\n};',assignment)+3);vm.runInContext(marker+'\n'+body,context)}
}
function apiFixture(response){
  const requests=[],updates=[],context={location:{href:'/unchanged'},signedInCompanyId:()=> 'synthetic tenant',wakeService:async()=>{},setWorkspaceUpdating:value=>updates.push(value),fetch:async(route,options)=>{requests.push({route,options});return response},reports:[],projects:[]};context.window=context;vm.createContext(context);installActualApi(context);return{context,requests,updates};
}
test('real base API plus all five wrappers preserve no-redirect notes behavior and strip custom fetch option',async()=>{
  const fixture=apiFixture({ok:false,status:401,headers:{get:()=> 'application/json'},json:async()=>({error:'Authentication required',code:'unauthenticated'})}),controller=new AbortController();await assert.rejects(fixture.context.api('/api/projects/1/notes-todos',{redirectOnUnauthorized:false,signal:controller.signal}),error=>error.message==='Authentication required'&&error.status===401&&error.code==='unauthenticated');assert.equal(fixture.context.location.href,'/unchanged');assert.equal(fixture.requests.length,1);assert.equal(fixture.requests[0].options.redirectOnUnauthorized,undefined);assert.equal(fixture.requests[0].options.signal,controller.signal);assert.equal(fixture.requests[0].options.headers['X-PDL-Company'],'synthetic tenant');assert.equal(fixture.requests[0].options.credentials,'include');assert.deepEqual(fixture.updates,[true,false]);
  await assert.rejects(fixture.context.api('/api/projects'),/Your session expired/);assert.equal(fixture.context.location.href,'/login.html?tenant=synthetic%20tenant');
});
test('real wrapped API keeps auth/me exempt and propagates structured validation status/code',async()=>{
  const unauthorized=apiFixture({ok:false,status:401,headers:{get:()=> 'application/json'},json:async()=>({error:'Authentication required'})});await assert.rejects(unauthorized.context.api('/api/auth/me'),error=>error.status===401);assert.equal(unauthorized.context.location.href,'/unchanged');
  const validation=apiFixture({ok:false,status:400,headers:{get:()=> 'application/json'},json:async()=>({error:'Control characters are not allowed',code:'invalid_text'})});await assert.rejects(validation.context.api('/api/projects/1/notes-todos',{method:'POST',body:'{}',redirectOnUnauthorized:false}),error=>error.status===400&&error.code==='invalid_text');assert.deepEqual(validation.updates,[true,false]);
});
for(const [label,invalidate] of invalidations.filter(([label])=>['tenant header','signed-in user','logout','in-app navigation','modal close'].includes(label)))test(`real wrapped API receives aborted signal if ${label} occurs while mutation awaits wakeService`,async()=>{
  const wake=deferred(),requests=[],accepted=[],h=harness({beforeModule:context=>{context.location={href:'/unchanged'};context.reports=[];context.projects=[];context.wakeService=()=>wake.promise;context.setWorkspaceUpdating=()=>{};context.fetch=async(route,options)=>{requests.push({route,options});if(options.signal?.aborted)throw options.signal.reason;accepted.push({route,options});return{ok:true,status:200,headers:{get:()=> 'application/json'},json:async()=>route.endsWith('/notes-todos')&&!options.method?{items:[]}:item({text:'MUST NOT BE ACCEPTED'})}};installActualApi(context)}});await h.open();h.click('[data-note-new="note"]');h.query('[data-notes-text]').value='Do not send after leaving';h.click('[data-notes-save]');await flush();assert.equal(requests.length,1);await invalidate(h);wake.resolve();await flush();assert.equal(requests.length,2);assert.equal(requests[1].options.signal.aborted,true);assert.equal(accepted.length,1,'A fetch implementation honoring AbortSignal cannot accept the abandoned mutation');assert.equal(h.query('.project-notes-pane'),null);
});
test('HTML loads versioned notes assets last and public-file policy exposes assets but no server/test source',()=>{
  const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8'),root=__dirname;assert.match(html,/<link rel="stylesheet" href="project-notes-ui\.css\?v=[^"]+"/);assert.match(html,/<script src="project-notes-ui\.js\?v=[^"]+"><\/script>/);assert.ok(html.indexOf('<script src="app.js')<html.indexOf('<script src="reporting-controls.js'));assert.ok(html.indexOf('<script src="reporting-controls.js')<html.indexOf('<script src="project-notes-ui.js'));assert.equal((html.match(/<script src="project-notes-ui\.js/g)||[]).length,1);for(const file of ['project-notes-ui.js','project-notes-ui.css'])assert.equal(isPublicFile(root,path.join(root,file)),true);for(const file of ['project-notes.js','project-notes-ui.test.js','server.js'])assert.equal(isPublicFile(root,path.join(root,file)),false);
});
test('responsive CSS preserves readable mobile controls, wrapping text, keyboard focus and hidden editor',()=>{
  const css=fs.readFileSync(path.join(__dirname,'project-notes-ui.css'),'utf8');assert.match(css,/@media\(max-width:760px\)/);assert.match(css,/font-size:max\(16px,1rem\);min-width:0;max-width:100%/);assert.match(css,/min-height:44px/);assert.match(css,/white-space:pre-wrap;overflow-wrap:anywhere/);assert.match(css,/\.project-notes-editor\[hidden\]\{display:none\}/);assert.match(css,/:focus-visible/);assert.match(css,/grid-template-columns:minmax\(0,1fr\)/);
});

(async()=>{let failed=0;for(const {name,run} of tests){try{await run()}catch(error){failed++;console.error('FAIL:',name);console.error(error)}}if(failed){console.error(`${failed}/${tests.length} project-notes UI fixture tests failed.`);process.exitCode=1}else console.log(`Project-notes UI: ${tests.length} synthetic fixtures passed (text/history, CRUD, keyboard, retries, role/context/navigation isolation, actual wrapper guards, asset/CSS contracts). Real browser/device QA is not claimed.`)})().catch(error=>{console.error(error);process.exitCode=1});
