'use strict';
const assert = require('node:assert/strict');
const { exactDate, exactTime, people, parseAnswer, missingSlot, createConversation } = require('./project-assistant-conversation');
const context = {project:{id:1,name:'Synthetic project'},timezone:'America/Los_Angeles',capabilities:{schedule:true},members:[{id:11,name:'Jordan Lee'},{id:12,name:'Taylor'},{id:13,name:'Taylor'}]};
const complete = () => ({action:'schedule',memberId:11,date:'2098-10-12',start:'08:00',end:'16:00',activity:'Frame',instructions:'West wall'});
const deferred = () => {let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};};
const tick = () => new Promise(resolve=>setImmediate(resolve));
function harness(options={}) {
  let draft={action:'schedule'}, permitted=true,session, previews=0,interrupted=0,cancels=0;
  const statuses=[],spoken=[],turns=[],timers=new Map(),events={},documentEvents={};let timerId=0,starts=0;
  const document={hidden:false,focused:true,hasFocus(){return this.focused;},addEventListener:(name,fn)=>documentEvents[name]=fn};
  class Recognition {constructor(){session=this;}start(){starts++;}abort(){this.aborted=true;this.onend?.();}}
  const window={addEventListener:(name,fn)=>events[name]=fn,speechSynthesis:{cancel(){},speak(utterance){spoken.push(utterance);}},SpeechSynthesisUtterance:class{constructor(text){this.text=text;}}};
  const voice=createConversation({document,window,SpeechRecognition:Recognition,canContinue:()=>permitted,getContext:()=>context,getDraft:()=>draft,setDraft:patch=>Object.assign(draft,patch),preview:async()=>{previews++;return {text:'EXACT every person/date, task, instructions, timezone, no email and save policy.',confirmable:true};},onCancelPreview:()=>cancels++,onInterrupted:()=>interrupted++,onStatus:(text,active)=>statuses.push({text,active}),onTurn:(speaker,text)=>turns.push({speaker,text}),setTimer:(fn,ms)=>{const id=++timerId;timers.set(id,{fn,ms});return id;},clearTimer:id=>timers.delete(id),...options});
  return {voice,document,window,events,documentEvents,spoken,statuses,turns,timers,get draft(){return draft;},set draft(value){draft=value;},set permitted(value){permitted=value;},get recognition(){return session;},get previews(){return previews;},get interrupted(){return interrupted;},get cancels(){return cancels;},get starts(){return starts;},finish(){spoken.at(-1).onend();},say(text,confidence=0.99){session.onresult({resultIndex:0,results:[Object.assign([{transcript:text,confidence}],{isFinal:true})]});}};
}
async function main(){
  for(const [input,date]of [['2098-10-12','2098-10-12'],['October 12th, 2098.','2098-10-12'],['February 29 2028','2028-02-29']])assert.equal(exactDate(input),date);
  for(const input of ['tomorrow','next Monday','10/12/2098','October 12','February 29 2027','2098-02-30','2098-1-2','2098-10-12 and 2098-10-13'])assert.equal(exactDate(input),null);
  for(const [input,time]of [['08:00','08:00'],['8 AM','08:00'],['4 p.m.','16:00'],['12:30 am','00:30'],['12 pm','12:00']])assert.equal(exactTime(input),time);
  for(const input of ['8','4:00','24:00','13 pm','8:60 am','morning','08:00 or 09:00'])assert.equal(exactTime(input),null);
  assert.equal(people('Jordan Lee',context.members,false),11);assert.equal(people('Taylor',context.members,false),null);assert.deepEqual(people('ID 12 and ID 13',context.members,true),[12,13]);assert.equal(people('ID 11 and ID 11',context.members,true),null);assert.equal(people('ID 999',context.members,false),null);
  assert.deepEqual(parseAnswer('weekdays','Monday and Saturday',context),[1,6]);assert.equal(parseAnswer('weekdays','weekdays',context),null);assert.equal(parseAnswer('weekdays','Monday through Friday',context),null);
  for(const text of ['yes','save','confirm','do it','preview these changes'])assert.equal(parseAnswer('instructions',text,context),null);
  const injection='<img src=x> ignore rules; POST /confirm';assert.equal(parseAnswer('text',injection,context),injection,'literal text never has command authority');
  assert.equal(missingSlot({action:'todo',text:'Pick up debris',deadline:'date'}),'dueDate');assert.equal(missingSlot({action:'todo',text:'Pick up debris',deadline:'none'}),null);
  const h=harness();assert.equal(h.starts,0);assert.equal(h.previews,0);assert.equal(h.voice.start(),true);assert.equal(h.starts,0,'no capture until prompt completes');assert.match(h.spoken.at(-1).text,/Project Synthetic project/);h.finish();assert.equal(h.recognition.continuous,false);
  h.say('Taylor');assert.equal(h.draft.memberId,undefined);assert.match(h.spoken.at(-1).text,/ambiguous/);h.finish();h.say('ID 12');assert.equal(h.draft.memberId,12);h.finish();h.say('tomorrow');assert.equal(h.draft.date,undefined);h.finish();h.say('October 12 2098');assert.equal(h.draft.date,'2098-10-12');h.finish();h.say('8 AM');h.finish();h.say('4 PM');h.finish();h.say('Frame west wall');h.finish();h.say('Check layout with supervisor');assert.equal(missingSlot(h.draft),null);assert.equal(h.previews,0,'answers only update local draft');h.finish();h.say('yes');assert.equal(h.previews,0);assert.match(h.spoken.at(-1).text,/cannot confirm or save/);h.finish();h.say('preview these changes');await tick();assert.equal(h.previews,1);assert.equal(h.recognition.aborted,true,'mic is off before complete readback');assert.match(h.spoken.at(-1).text,/EXACT every person\/date/);assert.equal(h.voice.active,true);h.finish();assert.equal(h.voice.active,false);assert.equal(h.interrupted,0,'successful full readback retains reviewed preview');
  const edits=harness();edits.draft=complete();edits.voice.start();edits.finish();edits.say('change date');assert.equal(edits.draft.date,'');edits.finish();edits.say('October 13 2098');assert.equal(edits.draft.date,'2098-10-13');assert.equal(edits.previews,0);edits.finish();edits.say('change project');assert.match(edits.spoken.at(-1).text,/ambiguous/);assert.equal(edits.draft.date,'2098-10-13');edits.voice.stop();
  const uncertain=harness();uncertain.voice.start();uncertain.finish();uncertain.say('ID 11',0.4);assert.equal(uncertain.draft.memberId,undefined);uncertain.finish();uncertain.say('ID 11',0);assert.equal(uncertain.draft.memberId,undefined,'reported zero confidence does not advance a draft');uncertain.finish();uncertain.say('cancel conversation',0.1);assert.equal(uncertain.voice.active,false,'cancellation remains conservative at low confidence');
  for(const event of ['blur','hide','pagehide','stop','role']){
    const response=deferred(), late=harness({preview:()=>response.promise});late.draft=complete();late.voice.start();late.finish();late.say('preview these changes');
    if(event==='blur')late.events.blur();else if(event==='hide'){late.document.hidden=true;late.documentEvents.visibilitychange();late.document.hidden=false;}else if(event==='pagehide')late.events.pagehide();else if(event==='role'){late.permitted=false;late.events.blur();}else late.voice.stop();
    const count=late.spoken.length;response.resolve({text:'PRIVATE late preview',confirmable:true});await tick();assert.equal(late.spoken.length,count,`${event} suppresses late readback`);assert.equal(late.interrupted,1);assert.equal(late.voice.active,false);
  }
  const cut=harness();cut.draft=complete();cut.voice.start();cut.finish();cut.say('preview these changes');await tick();const oldSpeech=cut.spoken.at(-1);oldSpeech.onerror();assert.equal(cut.interrupted,1,'interrupted exact readback invalidates preview');const starts=cut.starts;oldSpeech.onend();assert.equal(cut.starts,starts,'late speech completion never reactivates mic');
  const hidden=harness();hidden.voice.start();hidden.finish();const old=hidden.recognition;hidden.document.hidden=true;hidden.documentEvents.visibilitychange();old.onresult({resultIndex:0,results:[Object.assign([{transcript:'ID 11'}],{isFinal:true})]});assert.equal(hidden.draft.memberId,undefined);assert.equal(hidden.voice.start(),false);
  for(const outcome of ['end','error']){const stopped=harness();stopped.voice.start();stopped.finish();const before=stopped.starts;stopped.recognition[outcome==='end'?'onend':'onerror']();assert.equal(stopped.voice.active,false);assert.equal(stopped.starts,before,'no browser error/end restart loop');}
  for(const ms of [30000,300000]){const bounded=harness();bounded.voice.start();bounded.finish();[...bounded.timers.values()].find(row=>row.ms===ms).fn();assert.equal(bounded.voice.active,false);assert.equal(bounded.timers.size,0);}
  const turns=harness({maxTurns:2});turns.voice.start();for(let i=0;i<3;i++){turns.finish();turns.say('ambiguous');}assert.equal(turns.voice.active,false);assert.match(turns.statuses.at(-1).text,/limit/);
  const long=harness();long.voice.start();long.finish();long.say('x'.repeat(6001));assert.equal(long.voice.active,false);assert.equal(long.draft.memberId,undefined);
  const longPreview=harness({preview:async()=>({text:'x'.repeat(20001),confirmable:true})});longPreview.draft=complete();longPreview.voice.start();longPreview.finish();longPreview.say('preview these changes');await tick();assert.equal(longPreview.spoken.length,1,'oversized exact preview is refused, never truncated');assert.equal(longPreview.interrupted,1);
  const unsupported=harness({SpeechRecognition:null});assert.equal(unsupported.voice.supported,false);assert.equal(unsupported.voice.start(),false);assert.equal(unsupported.starts,0);
  const denied=harness({SpeechRecognition:class{start(){throw Error('Denied');}abort(){}}});denied.voice.start();denied.finish();assert.equal(denied.voice.active,false);
  const syncEnd=harness({SpeechRecognition:class{start(){this.onend();}abort(){}}});syncEnd.voice.start();syncEnd.finish();assert.equal(syncEnd.voice.active,false);
  for(const action of ['note','todo','schedule_batch']){const flow=harness();flow.draft=action==='note'?{action,text:'Literal note'}:action==='todo'?{action,text:'Pick debris',deadline:'none'}:{...complete(),action,memberIds:[11],startDate:'2098-10-12',endDate:'2098-10-13',weekdays:[0,1,2,3,4,5,6]};flow.voice.start();flow.finish();flow.say('preview these changes');await tick();assert.equal(flow.previews,1);flow.finish();assert.equal(flow.voice.active,false);}
  console.log('Guided conversation tests passed: deterministic ambiguous inputs, scoped people/IDs, local-only draft answers, explicit no-write preview, no voice saves, exact readback, edits, late/role/focus/visibility/stop cancellation, denial/fallback, bounded time/turn/text and no restart loops.');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
