'use strict';
const assert=require('node:assert/strict');
const {review}=require('./report-labor-review');
const dateIso='2026-10-06';
const own={id:11,project:0,dateIso,workdayId:7,status:'Needs review',laborEntries:[{memberId:4,hours:4.18}]};
const crew={id:12,project:0,dateIso,workdayId:6,status:'Needs review',laborEntries:[{memberId:3,hours:4.2},{memberId:4,hours:4}]};
const options={reports:[own,crew],team:[{id:3,name:'Person A'},{id:4,name:'Person B'}],workdays:[{id:6,memberIds:[3],startedAt:'2026-10-06T16:42:00Z',endedAt:'2026-10-06T20:55:00Z'},{id:7,memberIds:[4],startedAt:'2026-10-06T16:44:00Z',endedAt:'2026-10-06T20:54:00Z'}]};
const before=JSON.stringify(options);
assert.deepEqual(review(crew,options).map(w=>[w.memberId,w.hours,w.otherHours,w.otherReports[0].id]),[['4',4,4.18,11]],'the extra member in an overlapping crew daily must be visible');
assert.equal(review(own,options)[0].otherHours,4,'both reports expose the conflict');
assert.equal(JSON.stringify(options),before,'review must never change reports, shifts or cards');
assert.deepEqual(review({...crew,laborEntries:[{memberId:3,hours:4.2}]},options),[],'two people on separate reports are legitimate');
assert.deepEqual(review({...crew,project:1},options),[],'a different project is not a duplicate');
assert.deepEqual(review({...crew,dateIso:'2026-10-07'},options),[],'a different work date is not a duplicate');
assert.deepEqual(review(crew,{...options,reports:[own,crew,{...own,id:20,deletedAt:'2026-10-07',laborEntries:[{memberId:4,hours:9}]}]})[0].otherReports.map(r=>r.id),[11],'deleted reports cannot contribute');
const second={id:13,project:0,dateIso,workdayId:8,status:'Draft',laborEntries:[{memberId:4,hours:2}]};
const separate={...options,reports:[own,second],workdays:[...options.workdays,{id:8,memberIds:[4],startedAt:'2026-10-06T21:00:00Z',endedAt:'2026-10-06T23:00:00Z'}]};
assert.deepEqual(review(second,separate),[],'separate confirmed shifts on one project must be kept');
const touching={...separate,workdays:separate.workdays.map(w=>w.id===8?{...w,startedAt:'2026-10-06T20:54:00Z'}:w)};
assert.deepEqual(review(second,touching),[],'adjacent shifts are not overlapping');
const overlap={...separate,workdays:separate.workdays.map(w=>w.id===8?{...w,startedAt:'2026-10-06T20:00:00Z'}:w)};
assert.equal(review(second,overlap).length,1,'overlapping confirmed shifts need review');
const manual={...second,workdayId:null};
assert.equal(review(manual,{...separate,reports:[own,manual]}).length,1,'without shift evidence ask the user to compare, never infer deletion');
const cardOptions={reports:[own,manual],timeCards:[{id:7,memberId:4,reportId:11,inAt:'2026-10-06T16:44:00Z',outAt:'2026-10-06T20:54:00Z'},{id:8,memberId:4,reportId:13,inAt:'2026-10-06T21:00:00Z',outAt:'2026-10-06T23:00:00Z'}]};
assert.deepEqual(review(manual,cardOptions),[],'time-card evidence can establish separate shifts');
assert.equal(review(manual,{...cardOptions,timeCards:cardOptions.timeCards.map(c=>c.id===8?{...c,deletedAt:'2026-10-07'}:c)}).length,1,'deleted cards cannot establish a separate shift');
assert.equal(review({...crew,workdayId:null},{...options,reports:[own,crew],timeCards:[{id:7,memberId:4,reportId:11,inAt:'bad',outAt:'bad'}]}).length,1,'invalid evidence cannot hide a possible duplicate');
console.log('Report labor review passed: duplicate allocations, separate shifts/projects, deleted records, immutable evidence.');
