'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const server=fs.readFileSync(__dirname+'/server.js','utf8'),app=fs.readFileSync(__dirname+'/app.js','utf8');
function code(source,name){const lines=source.split('\n'),start=source.indexOf('function '+name+'(');assert.ok(start>=0,name);const text=source.slice(start),line=text.split('\n')[0];if(line.trimEnd().endsWith('}'))return line;const rest=text.split('\n'),end=rest.findIndex((line,i)=>i>0&&line.trimEnd()==='}');assert.ok(end>0,name);return rest.slice(0,end+1).join('\n')}
const c={dailyWork:require('./daily-work-extraction'),normalizeLanguageCode:value=>value,crewHourFact:()=>null,applyCrewHours(){},applyNextBackstop(){}};vm.createContext(c);
for(const name of ['pureNoDelayClaim','delayFromNotes','localExtract','reportHasOpenUnplanned','alignReportNarrative','holdupBackstop','finishAiExtract'])vm.runInContext(code(server,name),c);
const positives=['No delays','No delays today.','Without delays','Sin retrasos.','No hubo retrasos hoy.','Sin demoras.','None reported'];
for(const delays of positives){const report={delays,issue:delays,summary:delays,flags:[{type:'unplanned_work'}]};c.alignReportNarrative(report);assert.equal(report.delays,delays);assert.equal(report.issue,delays);assert.ok(report.summary.includes(delays));assert.match(report.summary,/office decision/)}
for(const value of ['',undefined]){const report={delays:value,issue:value,summary:'',flags:[]};c.alignReportNarrative(report);assert.equal(report.delays,value);assert.equal(report.issue,value)}
for(const notes of ['Installed tile. No delays today.','Instalamos azulejos. Sin retrasos.','Terminamos el trabajo. No hubo retrasos hoy.']){const extracted=c.localExtract(notes);assert.ok(extracted.delays);assert.ok(notes.includes(extracted.delays));assert.ok(extracted.summary.includes(extracted.delays))}
assert.equal(c.localExtract('Installed tile.').delays,'');assert.equal(c.localExtract('Sin materiales hoy.').delays,'','no unrelated negative inferred as a delay answer');
const translated=c.finishAiExtract({originalLanguage:'es',englishTranslation:'Installed tile. No delays today.',delays:'No delays today.',issue:'',productions:[]},'Instalamos azulejos. Sin retrasos.');assert.equal(translated.delays,'No delays today.');assert.equal(translated.englishTranslation,'Installed tile. No delays today.');
const missing=c.finishAiExtract({originalLanguage:'es',delays:'',issue:'',productions:[]},'Instalamos azulejos.');assert.equal(missing.delays,'');
const delayed=c.finishAiExtract({delays:'',issue:'',productions:[]},'Esperando al inspector.');assert.match(delayed.delays,/Waiting/,'real hold-up backstop retained');
for(const [notes,negative,positive] of [['Instalamos azulejos. Sin retrasos. Esperando al inspector.','Sin retrasos.',/Waiting/],['No hubo retrasos hoy. Inspector no vino.','No hubo retrasos hoy.',/inspector did not come/]]){const local=c.localExtract(notes),mixed=c.finishAiExtract(local,notes);assert.equal(mixed.delays,negative);assert.ok(mixed.issue.includes(negative));assert.match(mixed.issue,positive);assert.ok(mixed.summary.includes(negative),'source negative remains in narrative')}
for(const [notes,negative,positive] of [['Sin retrasos. Sin demoras. Esperando al inspector.','Sin retrasos. Sin demoras.',/Waiting/],['No delays today. Sin retrasos. Inspector no vino.','No delays today. Sin retrasos.',/inspector did not come/]]){const mixed=c.finishAiExtract(c.localExtract(notes),notes);assert.equal(mixed.delays,negative);assert.ok(mixed.issue.includes(negative));assert.match(mixed.issue,positive)}
const translatedMixed=c.finishAiExtract({originalLanguage:'es',englishTranslation:'Installed tile. No delays. Waiting on the inspector.',delays:'No delays.',issue:'No issues.',productions:[]},'Instalamos azulejos. Sin retrasos. Esperando al inspector.');assert.equal(translatedMixed.delays,'No delays.');assert.match(translatedMixed.issue,/^No issues\. Waiting/);assert.match(translatedMixed.englishTranslation,/No delays\. Waiting/);
const englishMixed=c.localExtract('No delays today. Pump arrived 45 minutes late.');assert.match(englishMixed.delays,/No delays today/);assert.match(englishMixed.delays,/45 minutes late/);
const view={};vm.createContext(view);for(const name of ['clearNoDelayClaim','reportHasOpenUnplanned','reportSummaryText','isNoDelayClaim'])vm.runInContext(code(app,name),view);vm.runInContext(app.split('\n').find(line=>line.startsWith('reportDelayText=function(report){const facts=')),view);
for(const value of positives){assert.equal(view.clearNoDelayClaim(value),value);assert.equal(view.reportDelayText({delays:value}),value);assert.ok(view.reportSummaryText({summary:value,flags:[{type:'unplanned_work'}]}).includes(value))}
assert.equal(view.reportDelayText({}), 'Not entered');assert.equal(view.reportDelayText({flags:[{type:'unplanned_work'}]}),'Unplanned work needs a decision');assert.equal(view.reportDelayText({delays:'Sin retrasos.',issue:'Waiting on inspection'}),'Waiting on inspection');
const i18n=fs.readFileSync(__dirname+'/i18n.js','utf8'),catalog=i18n.slice(i18n.indexOf('const es='),i18n.indexOf('const original=new Map()')),translate=code(i18n,'translated');vm.runInContext(catalog+'\n'+translate+'\nthis.translate=translated;',view);
assert.equal(view.translate('No delays.'),'Sin retrasos.');assert.equal(view.translate('Not entered'),'No ingresado');assert.notEqual(view.translate('No delays.'),view.translate('Not entered'));
console.log('Explicit delay facts passed: English/Spanish local extraction, translated structured fields, save preparation, separate unplanned notice, missing/explicit-none distinction, actual summary/delay rendering, positive issue precedence and translated display labels. No provider calls.');
