'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const policy=require('./restricted-field-access'),{createCrewHandler}=require('./crew-routes');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'pdl-restricted-crew-')),file=path.join(root,'db.json'),tenant='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',token=id=>'synthetic-crew-'+id;
const now=Date.now(),past=new Date(now-5*3600000).toISOString(),out=new Date(now-4*3600000).toISOString(),today=new Date().toISOString().slice(0,10),photoName='crew-synthetic-'+crypto.randomUUID()+'.png',photoFile=path.join(__dirname,'uploads',photoName),photoData='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jCQAAAABJRU5ErkJggg==';
const users=[{id:1,name:'Synthetic owner',role:'owner'},{id:2,name:'Synthetic restricted',role:'field',memberId:11,employeeId:11,fieldAccessMode:policy.MODE},{id:3,name:'Synthetic standard',role:'field',memberId:12},{id:4,name:'Synthetic admin',role:'admin'}].map(row=>({...row,companyId:tenant,email:'qa'+row.id+'@example.invalid',status:'Active',emailVerifiedAt:past}));
const fixture={company:{id:tenant,name:'Synthetic crew company',demo:true,timezone:'America/Los_Angeles',features:{timeCards:true,templates:true},planPrice:900,commercialNote:'PRIVATE'},users,sessions:users.map(user=>({companyId:tenant,userId:user.id,tokenHash:crypto.createHash('sha256').update(token(user.id)).digest('hex'),expiresAt:'2099-01-01'})),team:[{id:11,name:'Synthetic restricted',role:'Laborer',crew:'QA',email:'PRIVATE EMAIL',phone:'PRIVATE PHONE',hours:7},{id:12,name:'Synthetic standard',role:'Laborer',crew:'QA'}],projects:[{id:101,name:'Assigned synthetic job',site:'QA site',estimateItems:[{name:'SECRET ESTIMATE',cost:1}],budget:999},{id:202,name:'Unassigned synthetic job',estimateItems:[]}],assignments:[{id:1,projectId:101,memberIds:[11,12],date:today,start:'07:00',end:'15:00',activity:'Assigned work',note:'PRIVATE SCHEDULER NOTE',acknowledgements:{12:{at:past}}}],reports:[{id:1,project:0,foreman:'Synthetic standard',status:'Draft',notes:'PRIVATE DAILY',productionEntries:[],laborEntries:[]},{id:2,project:1,foreman:'Synthetic restricted',status:'Draft',notes:'PRIVATE HISTORICAL DAILY',laborEntries:[]}],photos:[{id:1,project:0,reportId:1,caption:'PRIVATE DAILY PHOTO CAPTION',tags:['PRIVATE'],uploader:'Synthetic standard',url:'/uploads/'+photoName,createdAt:past},{id:2,project:1,url:'/uploads/unassigned.png'}],projectPlans:[{id:1,projectId:101,url:'/uploads/plan.png',note:'PRIVATE PLAN'}],projectTickets:[],workdays:[{id:8,projectId:202,memberIds:[11],status:'complete',reportId:2}],timeCards:[{id:1,projectId:101,memberId:11,inAt:past,outAt:out,hours:1,status:'draft',reportId:1,hourlyRate:88},{id:2,projectId:101,memberId:12,inAt:past,outAt:out,hours:1,status:'draft'},{id:3,projectId:101,memberId:11,inAt:new Date(now-3*3600000).toISOString(),outAt:new Date(now-2*3600000).toISOString(),hours:1,status:'approved',approvedAt:past},{id:4,projectId:101,memberId:11,inAt:new Date(now-3600000).toISOString(),outAt:new Date(now-1800000).toISOString(),hours:.5,status:'draft',exportedAt:past}],auditLog:[],customers:[],subcontractors:[]};
fs.mkdirSync(path.join(root,'tenants'));fs.writeFileSync(file,JSON.stringify(fixture));fs.writeFileSync(path.join(root,'platform.json'),JSON.stringify({users:[],sessions:[]}));fs.writeFileSync(path.join(root,'tenants',other+'.json'),JSON.stringify({...fixture,company:{...fixture.company,id:other},users:[],sessions:[]}));fs.mkdirSync(path.dirname(photoFile),{recursive:true});fs.writeFileSync(photoFile,Buffer.from(photoData.split(',')[1],'base64'));
const read=()=>JSON.parse(fs.readFileSync(file)),write=db=>fs.writeFileSync(file,JSON.stringify(db));let server,base;const uploadedFiles=[];
async function request(method,route,id=2,input,companyId=tenant){const response=await fetch(base+route,{method,headers:{'Content-Type':'application/json','X-PDL-Company':companyId,Authorization:'Bearer '+token(id)},...(input===undefined?{}:{body:JSON.stringify(input)})});return{status:response.status,data:response.headers.get('content-type')?.includes('application/json')?await response.json():await response.text()}}
async function run(){
  Object.assign(process.env,{PDL_DB_FILE:file,PDL_PLATFORM_FILE:path.join(root,'platform.json'),PDL_REQUIRE_AUTH:'1',PDL_SUPABASE_ENABLED:'0',PDL_TRANSACTIONAL_DB:'off',PDL_FOUNDER_ENABLED:'0',PDL_EMAIL_DEV_MODE:'1'});for(const key of ['SENTRY_DSN','OPENAI_API_KEY','RESEND_API_KEY','STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET'])delete process.env[key];
  server=require('./server').server;await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port;
  let result=await request('GET','/api/state');assert.equal(result.status,200);assert.deepEqual(result.data.projects.map(row=>row.id),[101]);assert.deepEqual(result.data.team.map(row=>row.id),[11]);assert.equal(result.data.currentUser.fieldAccessMode,policy.MODE);assert.deepEqual(result.data.reports,[]);assert.deepEqual(result.data.workdays,[]);assert.deepEqual(result.data.dailyTemplates,[]);assert(!JSON.stringify(result.data).includes('PRIVATE'));assert(!JSON.stringify(result.data).includes('SECRET'));assert(!JSON.stringify(result.data).includes('reportId'));
  assert.equal((await request('GET','/api/auth/me')).data.fieldAccessMode,policy.MODE);assert.equal((await request('GET','/api/auth/me')).data.templates,false);
  assert.equal((await request('GET','/api/state?userId=3')).status,403);assert.equal((await request('GET','/api/state?memberId=12')).status,403);
  const beforeDenied=read();for(const [method,route] of [['GET','/api/reports'],['GET','/api/reports/1'],['POST','/api/reports'],['PATCH','/api/reports/1'],['PATCH','/api/reports/1/approve'],['POST','/api/ai/extract'],['GET','/api/projects/101/day-instructions?date='+today],['GET','/api/daily-templates'],['GET','/api/report-labor-suggestions?projectId=101&date='+today],['POST','/api/workdays/start'],['POST','/api/workdays/8/end'],['POST','/api/photos'],['PATCH','/api/projects/101'],['POST','/api/projects/101/estimate-proposals'],['GET','/api/projects/101/plans'],['GET','/api/projects/101/notes'],['GET','/api/reporting-exports'],['GET','/api/production'],['POST','/api/assignments'],['GET','/api/users'],['GET','/api/team/12'],['POST','/api/time-cards/company-clock'],['GET','/api/time-cards.csv'],['POST','/api/time-cards/approve'],['DELETE','/api/time-cards/1']])assert.equal((await request(method,route,2,method==='GET'?undefined:{})).status,403,route);assert.deepEqual(read(),beforeDenied);
  assert.equal((await request('GET','/api/local-files/'+photoName)).status,200);assert.equal((await request('GET','/api/local-files/plan.png')).status,404);assert.equal((await request('GET','/api/crew/photos?projectId=202')).status,404);assert.equal((await request('GET','/api/crew/photos?projectId=101')).data.length,1);
  result=await request('GET','/api/time-cards');assert.deepEqual(result.data.map(row=>row.id),[1,3,4]);assert(!JSON.stringify(result.data).includes('hourlyRate'));assert(!JSON.stringify(result.data).includes('reportId'));assert.equal((await request('GET','/api/time-cards?memberId=12')).status,403);
  assert.equal((await request('PATCH','/api/time-cards/2',2,{})).status,404);assert.equal((await request('PATCH','/api/time-cards/3',2,{})).status,409);assert.equal((await request('PATCH','/api/time-cards/4',2,{})).status,409);
  assert.equal((await request('PATCH','/api/time-cards/1',2,{revision:'stale',inAt:past,outAt:out,reason:'QA'})).status,409);
  const own=(await request('GET','/api/time-cards')).data.find(row=>row.id===1);assert.equal((await request('PATCH','/api/time-cards/1',2,{revision:own.fieldAccess.revision,memberId:12,inAt:past,outAt:out,reason:'QA'})).status,400);
  // Existing internal Draft labor synchronization stays authoritative; it does
  // not return the report or grant direct daily access.
  result=await request('PATCH','/api/time-cards/1',2,{revision:own.fieldAccess.revision,inAt:past,outAt:out,reason:'Synthetic own correction',breaks:[]});assert.equal(result.status,200);assert.equal(result.data.reportSynced,true);assert(!JSON.stringify(result.data).includes('PRIVATE DAILY'));assert.equal(read().reports[0].laborEntries[0].memberId,11);
  assert.equal((await request('POST','/api/time-cards/1/submit',2,{})).status,200);
  assert.equal((await request('POST','/api/crew/clock-in',2,{projectId:202})).status,403);assert.equal((await request('POST','/api/crew/clock-in',2,{projectId:101,memberId:12})).status,400);
  const daysBefore=read().workdays,reportsBefore=read().reports;const parallel=await Promise.all([request('POST','/api/crew/clock-in',2,{projectId:101}),request('POST','/api/crew/clock-in',2,{projectId:101})]);assert.deepEqual(parallel.map(row=>row.status).sort(),[201,409]);const card=parallel.find(row=>row.status===201).data;assert.equal(card.memberId,11);assert.deepEqual(read().workdays,daysBefore);assert.deepEqual(read().reports,reportsBefore);
  result=await request('POST','/api/time-cards/'+card.id+'/clock-out',2,{});assert.equal(result.status,200);const savedOut=result.data.outAt;assert(savedOut);assert.equal((await request('POST','/api/time-cards/'+card.id+'/clock-out',2,{})).data.outAt,savedOut);assert.deepEqual(read().reports,reportsBefore);assert.deepEqual(read().workdays,daysBefore);
  // Separate photo upload: stable identity, no daily linkage, tenant/assignment
  // scope and duplicate/replay protection, including conflicting batch IDs.
  const uploadId=crypto.randomUUID(),files=[{type:'image/png',data:photoData,uploadId}];assert.equal((await request('POST','/api/crew/photos',2,{projectId:202,files})).status,403);assert.equal((await request('POST','/api/crew/photos',2,{projectId:101,files,reportId:1})).status,400);
  const attempts=await Promise.all([request('POST','/api/crew/photos',2,{projectId:101,files}),request('POST','/api/crew/photos',2,{projectId:101,files})]);assert.deepEqual(attempts.map(row=>row.status),[201,201]);assert.equal(attempts[0].data[0].id,attempts[1].data[0].id);const uploaded=read().photos.find(row=>row.uploadId===uploadId);uploadedFiles.push(path.join(__dirname,uploaded.url.slice(1)));assert.equal(uploaded.reportId,null);assert.equal(uploaded.workdayId,null);assert.equal(read().photos.filter(row=>row.uploadId===uploadId).length,1);assert.equal((await request('GET','/api/local-files/'+path.basename(uploaded.url))).status,200);
  const conflicting={...files[0],data:'data:image/png;base64,YWJj'};assert.equal((await request('POST','/api/crew/photos',2,{projectId:101,files:[conflicting]})).status,409);assert.equal((await request('POST','/api/crew/photos',2,{projectId:101,files:[{...files[0],uploadId:crypto.randomUUID()},conflicting]})).status,409);
  for(const bad of [{type:'image/png',data:'data:image/jpeg;base64,YWJj',uploadId:crypto.randomUUID()},{type:'image/svg+xml',data:'data:image/svg+xml;base64,YWJj',uploadId:crypto.randomUUID()},{type:'image/png',data:'data:image/png;base64,',uploadId:crypto.randomUUID()}])assert.equal((await request('POST','/api/crew/photos',2,{projectId:101,files:[bad]})).status,400);
  assert.equal((await request('GET','/api/state',2,undefined,other)).status,401);
  let db=read();db.assignments=[];write(db);assert.deepEqual((await request('GET','/api/state')).data.photos,[]);assert.equal((await request('GET','/api/local-files/'+photoName)).status,404);assert.equal((await request('POST','/api/crew/photos',2,{projectId:101,files})).status,403);db.assignments=fixture.assignments;write(db);
  // Standard field users retain dailies. Owners can explicitly select mode;
  // unrelated edits preserve it, promotion clears it, and a later role change
  // never restores restricted mode implicitly from another role.
  assert((await request('GET','/api/state',3)).data.reports.some(row=>row.notes==='PRIVATE DAILY'));assert.equal((await request('POST','/api/crew/clock-in',3,{projectId:101})).status,403);
  assert.equal((await request('PATCH','/api/users/2',4,{fieldAccessMode:'standard'})).status,403);assert.equal((await request('PATCH','/api/users/2',1,{fieldAccessMode:'unknown'})).status,400);assert.equal((await request('PATCH','/api/users/2',1,{preferredLanguage:'es'})).status,200);assert.equal(read().users[1].fieldAccessMode,policy.MODE);assert.equal((await request('GET','/api/team/11',1)).data.account.fieldAccessMode,policy.MODE);
  assert.equal((await request('PATCH','/api/users/2',1,{role:'admin',fieldAccessMode:policy.MODE})).status,400);assert.equal((await request('PATCH','/api/users/2',1,{role:'admin'})).status,200);assert.equal(read().users[1].fieldAccessMode,null);assert.equal((await request('PATCH','/api/users/2',1,{role:'field',memberId:11,fieldAccessMode:policy.MODE})).status,200);
  db=read();db.users[1].status='Deactivated';write(db);assert.equal((await request('POST','/api/crew/clock-in',2,{projectId:101})).status,401);db.users[1].status='Active';write(db);
  db.team.push({id:99,name:'Synthetic new crew employee',role:'Laborer',crew:'QA',email:'new-crew@example.invalid'});write(db);const teamBefore=read().team;
  assert.equal((await request('POST','/api/team/99/account',1,{role:'field',fieldAccessMode:'unknown'})).status,400);
  result=await request('POST','/api/team/99/account',4,{role:'field',fieldAccessMode:policy.MODE,permissions:{manageTime:true,viewDailies:true}});assert.equal(result.status,201);assert.equal(result.data.account.fieldAccessMode,policy.MODE);assert.deepEqual(read().team,teamBefore);assert.deepEqual(read().users.at(-1).permissions,{});assert.equal((await request('POST','/api/team/99/account',1,{role:'field',fieldAccessMode:policy.MODE})).status,409);
  // Actual slow HTTP bodies: a new pay-period lock or other external integrity
  // write must be preserved, rather than overwritten from the request snapshot.
  const http=require('node:http');async function slowBody(route,payload,mutate){const text=JSON.stringify(payload);return new Promise((resolve,reject)=>{const req=http.request(base+route,{method:route.includes('/crew/')?'POST':'PATCH',headers:{'Content-Type':'application/json','X-PDL-Company':tenant,Authorization:'Bearer '+token(2)}},res=>{let body='';res.on('data',chunk=>body+=chunk);res.on('end',()=>resolve({status:res.statusCode,data:JSON.parse(body)}))});req.on('error',reject);req.write(text.slice(0,10));setTimeout(()=>{mutate();req.end(text.slice(10))},100)})}
  for(const route of ['/api/time-cards/1','/api/crew/clock-in']){write(structuredClone(fixture));const initial=(await request('GET','/api/time-cards')).data.find(row=>row.id===1);let preserved;const outcome=await slowBody(route,route.includes('/crew/')?{projectId:101}:{revision:initial.fieldAccess.revision,inAt:past,outAt:out,reason:'Synthetic pending correction',breaks:[]},()=>{preserved=read();preserved.payPeriods=[{id:99,status:'closed',from:'2000-01-01',to:'2099-12-31',timeZone:'America/Los_Angeles'}];write(preserved)});assert.equal(outcome.status,409);assert.deepEqual(read(),preserved)}
  // Transition safety: an existing shared crew workday is never closed by one
  // restricted person. A solo workday can close, without inventing a daily.
  db=structuredClone(fixture);db.workdays=[{id:50,projectId:101,memberIds:[11,12],status:'active',startedAt:past}];db.timeCards=[{id:50,projectId:101,memberId:11,workdayId:50,status:'draft',inAt:past,outAt:null},{id:51,projectId:101,memberId:12,workdayId:50,status:'draft',inAt:past,outAt:null}];write(db);const sharedBefore=read();assert.equal((await request('POST','/api/time-cards/50/clock-out',2,{})).status,409);assert.deepEqual(read(),sharedBefore);db.workdays[0].memberIds=[11];db.timeCards.pop();write(db);const dailyBefore=read().reports;result=await request('POST','/api/time-cards/50/clock-out',2,{});assert.equal(result.status,200);assert.equal(read().workdays[0].status,'complete');assert.deepEqual(read().reports,dailyBefore);assert.equal(read().timeCards[0].reportId,undefined);
  db=structuredClone(fixture);db.timeCards=[{id:50,projectId:101,memberId:11,status:'draft',inAt:past,outAt:null},{id:51,projectId:101,memberId:11,status:'draft',inAt:new Date(now-2*3600000).toISOString(),outAt:new Date(now-3600000).toISOString()}];write(db);const overlapBefore=read();assert.equal((await request('POST','/api/time-cards/50/clock-out',2,{})).status,409);assert.deepEqual(read(),overlapBefore);
  // Probe the actual asynchronous route: revocation after bytes were stored
  // cannot link a photo record or disclose it. Existing retry objects untouched.
  let resolve,storageCalls=0,writes=0,actor={...users[1]},unitDb=structuredClone(fixture),response;
  const pending=new Promise(done=>resolve=done),handler=createCrewHandler({readDb:()=>unitDb,writeDb:()=>writes++,body:async()=>({projectId:101,files:[{...files[0],uploadId:crypto.randomUUID()}]}),json:(res,status,data)=>{response={status,data}},savePhoto:async()=>{storageCalls++;await pending;return{url:'/uploads/synthetic-orphan.png'}},assertCurrent:()=>policy.restricted(actor)?actor:null,nextId:rows=>rows.length+1});
  const upload=handler({method:'POST',auth:{user:actor}},{},new URL('http://local/api/crew/photos'));await new Promise(resolve=>setImmediate(resolve));actor.fieldAccessMode='standard';resolve();await upload;assert.equal(response.status,403);assert.equal(writes,0);assert.equal(unitDb.photos.length,fixture.photos.length);assert.equal(storageCalls,1);
  // Execute the actual fresh-snapshot guard during asynchronous photo storage.
  const vm=require('node:vm'),source=fs.readFileSync(path.join(__dirname,'server.js'),'utf8'),guard=source.slice(source.indexOf('function currentCrewAccount('),source.indexOf('const handleCrew='));unitDb=structuredClone(fixture);write(unitDb);const context={fs,crypto,crewAccess:policy,activeDbFile:()=>file};vm.createContext(context);vm.runInContext(guard,context);const req={method:'POST',auth:{user:unitDb.users[1]},crewIdentity:{memberId:11}};assert(context.currentCrewAccount(unitDb,req));let finish;const storageWait=new Promise(done=>finish=done),actualGuardHandler=createCrewHandler({readDb:()=>unitDb,writeDb:()=>writes++,body:async()=>({projectId:101,files:[{...files[0],uploadId:crypto.randomUUID()}]}),json:()=>{throw Error('A stale upload must not return success')},savePhoto:async()=>{await storageWait;return{url:'/uploads/synthetic-stale.png'}},assertCurrent:context.currentCrewAccount,nextId:rows=>rows.length+1});const guardedUpload=actualGuardHandler(req,{},new URL('http://local/api/crew/photos'));await new Promise(resolve=>setImmediate(resolve));const preserved=read();preserved.payPeriodExports=[{id:'synthetic-new-export'}];write(preserved);finish();await assert.rejects(guardedUpload,error=>error.code==='PDL_REVISION_CONFLICT');assert.equal(writes,0);assert.deepEqual(read(),preserved);assert.equal(unitDb.photos.length,fixture.photos.length);
  console.log('Restricted crew security passed: no daily/AI/finance/other-crew access; own locked/revision-safe time, assigned photo view/upload, retries, revoked scope and unchanged standard field behavior. Synthetic isolated only.');
}
run().catch(error=>{console.error(error);process.exitCode=1}).finally(async()=>{if(server){server.closeAllConnections();await new Promise(resolve=>server.close(resolve))}for(const candidate of [photoFile,...uploadedFiles]){const resolved=path.resolve(candidate),allowed=path.resolve(__dirname,'uploads')+path.sep;assert(resolved.startsWith(allowed));if(fs.existsSync(resolved))fs.unlinkSync(resolved)}fs.rmSync(root,{recursive:true,force:true})});
