'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process'),{once}=require('node:events');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'pdl-revenue-access-')),dbFile=path.join(temp,'db.json'),platformFile=path.join(temp,'platform.json');
const hash=value=>crypto.createHash('sha256').update(value).digest('hex'),roles=['platform_owner','customer_success','onboarding','support','billing','engineering'],bootstrapKey='synthetic-platform-bootstrap-key-only';
function platform(){const users=roles.map((role,i)=>({id:i+1,role,status:'Active',name:'Synthetic '+role,email:role+'@example.invalid'}));users.push({id:20,role:'platform_owner',status:'Inactive',email:'inactive@example.invalid'},{id:21,role:'platform_owner',status:'Active',mustSetPassword:true,email:'reset@example.invalid'});return{users,sessions:[...users.map(u=>({userId:u.id,tokenHash:hash('platform-'+u.id),expiresAt:'2099-01-01T00:00:00Z'})),{userId:1,tokenHash:hash('expired'),expiresAt:'2000-01-01T00:00:00Z'}],notes:[]};}
function reset(){const db=JSON.parse(fs.readFileSync(path.join(__dirname,'data/db.json'),'utf8'));db.company.demo=true;db.users=[{id:1,role:'owner',status:'Active',name:'Synthetic tenant owner',email:'tenant@example.invalid'}];db.sessions=[{userId:1,tokenHash:hash('tenant-owner'),expiresAt:'2099-01-01T00:00:00Z'}];fs.writeFileSync(dbFile,JSON.stringify(db));fs.writeFileSync(platformFile,JSON.stringify(platform()));}
let child,base,log='';
async function stop(){if(!child||child.exitCode!==null)return;const ended=once(child,'exit');child.kill();await ended;}
async function start(auth,mode='configured',delay=0){reset();log='';const env={...process.env,PDL_DB_FILE:dbFile,PDL_PLATFORM_FILE:platformFile,PDL_SUPABASE_ENABLED:'0',PDL_TRANSACTIONAL_DB:'off',PDL_REQUIRE_AUTH:auth?'1':'0',PDL_PLATFORM_KEY:bootstrapKey,PDL_EMAIL_DEV_MODE:'1'};for(const key of ['SENTRY_DSN','OPENAI_API_KEY','RESEND_API_KEY','STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET','DATABASE_URL'])delete env[key];const script=`const r=require('./revenue-reporting'),create=r.createRevenueReporter;r.createRevenueReporter=()=>{const client={};for(const k of ['balanceTransactions','charges','refunds','subscriptions','subscriptionItems'])client[k]={list:async()=>{await new Promise(r=>setTimeout(r,${delay}));${mode==='error'?"throw new Error('PRIVATE PROVIDER ERROR');":"return {data:[],has_more:false};"}}};return create({getSecret:()=>${mode==='unconfigured'?"''":"'synthetic_test_credential'"},createClient:()=>client});};global.fetch=()=>{throw new Error('Unexpected external request in synthetic test')};const {server}=require('./server');server.listen(0,'127.0.0.1',()=>console.log('REVENUE_TEST_PORT='+server.address().port));`;child=spawn(process.execPath,['-e',script],{cwd:__dirname,env,stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Synthetic start timed out: '+log)),15000);child.stdout.on('data',bytes=>{log+=String(bytes);const m=log.match(/REVENUE_TEST_PORT=(\d+)/);if(m){base='http://127.0.0.1:'+m[1];clearTimeout(timer);resolve();}});child.stderr.on('data',bytes=>log+=String(bytes));child.once('error',e=>{clearTimeout(timer);reject(e)});child.once('exit',code=>{clearTimeout(timer);reject(new Error('Test child exited '+code+': '+log));});});}
async function call(token,options={}){const response=await fetch(base+'/api/platform/revenue'+(options.query||''),{method:options.method||'GET',headers:{...(token?{cookie:'pdl_platform='+token}:{}),...options.headers}});return{status:response.status,headers:response.headers,body:await response.json()};}
(async()=>{let checks=0;for(const auth of [true,false]){
 await start(auth);
 for(const token of [null,'unknown','expired','platform-20','platform-21','tenant-owner',...roles.slice(1).map((_,i)=>'platform-'+(i+2))]){const r=await call(token);assert.equal(r.status,403,`${auth}: ${token}`);assert.equal(r.body.cash,undefined);checks++;}
 for(const headers of [{'x-pdl-platform-key':bootstrapKey},{authorization:'Bearer tenant-owner'},{cookie:'pdl_session=tenant-owner'}]){assert.equal((await call(null,{headers})).status,403);checks++;}
 const beforeDb=fs.readFileSync(dbFile,'utf8'),beforePlatform=fs.readFileSync(platformFile,'utf8'),good=await call('platform-1',{headers:{'x-pdl-company':'invalid-other-tenant'}});
 assert.equal(good.status,200);assert.equal(good.body.status,'ready');assert.equal(good.body.mode,'test');assert.deepEqual(good.body.cash,[]);assert.match(good.headers.get('cache-control'),/no-store/);assert.equal(fs.readFileSync(dbFile,'utf8'),beforeDb);assert.equal(fs.readFileSync(platformFile,'utf8'),beforePlatform);assert.equal((await call(null,{headers:{authorization:'Bearer platform-1'}})).status,200);checks++;
 for(const method of ['POST','PATCH','DELETE']){const r=await call('platform-1',{method});assert.equal(r.status,405);assert.equal(r.headers.get('allow'),'GET');checks++;}
 assert.equal((await call('platform-1',{query:'?start=not-a-date'})).status,400);checks++;
 const me=await fetch(base+'/api/platform/auth/me',{headers:{cookie:'pdl_platform=platform-1'}}).then(r=>r.json());assert.equal(me.revenueAccess,true);checks++;
 if(!auth){assert.equal((await fetch(base+'/api/platform/auth/me').then(r=>r.json())).revenueAccess,false);checks++;}
 for(const headers of [{cookie:'pdl_platform=platform-4'},{cookie:'pdl_platform=platform-5'},{'x-pdl-platform-key':bootstrapKey},{}]){
  const response=await fetch(base+'/api/platform/users',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({name:'Escalated owner',email:'escalation@example.invalid',role:'platform_owner'})});assert.ok([401,403].includes(response.status));assert.equal((await response.json()).setupCode,undefined);assert.ok(!JSON.parse(fs.readFileSync(platformFile,'utf8')).users.some(u=>u.email==='escalation@example.invalid'));checks++;
  const claimed=await fetch(base+'/api/platform/auth/claim',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'escalation@example.invalid',setupCode:'not-issued',password:'SyntheticPassword!42'})});assert.equal(claimed.status,401);checks++;
 }
 for(const headers of [{cookie:'pdl_platform=platform-4'},{}]){const response=await fetch(base+'/api/platform/auth/bootstrap',{method:'POST',headers});assert.equal(response.status,401);assert.equal((await response.json()).setupCode,undefined);checks++;}
 const malformedKey='\u00e9'.repeat(bootstrapKey.length);assert.equal((await fetch(base+'/api/platform/auth/bootstrap',{method:'POST',headers:{'x-pdl-platform-key':malformedKey}})).status,401);checks++;
 if(auth){assert.equal((await fetch(base+'/api/platform/overview',{headers:{'x-pdl-platform-key':malformedKey}})).status,401);checks++;}
 for(const asset of ['/revenue-reporting.js','/revenue-reporting.test.js','/revenue-companies.js','/revenue-companies.test.js','/revenue-access.test.js','/platform-revenue-ui.test.js']){assert.equal((await fetch(base+asset)).status,404);checks++;}
 assert.ok(!log.includes('PRIVATE'));await stop();
 }
 await start(true,'unconfigured');const missing=await call('platform-1');assert.equal(missing.status,200);assert.equal(missing.body.status,'unconfigured');assert.equal(missing.body.cash,undefined);checks++;await stop();
 await start(true,'error');const unavailable=await call('platform-1');assert.equal(unavailable.status,502);assert.equal(unavailable.body.status,'error');assert.equal(unavailable.body.cash,undefined);assert.ok(!JSON.stringify(unavailable.body).includes('PRIVATE'));assert.ok(!log.includes('PRIVATE'));checks++;await stop();
 await start(true,'configured',200);const pending=call('platform-1');await new Promise(r=>setTimeout(r,80));const revoked=platform();revoked.users[0].status='Inactive';fs.writeFileSync(platformFile,JSON.stringify(revoked));const denied=await pending;assert.equal(denied.status,403);assert.equal(denied.body.cash,undefined);checks++;await stop();
 await start(true,'configured');
 const http=require('node:http');let request;
 const creating=new Promise((resolve,reject)=>{request=http.request(base+'/api/platform/users',{method:'POST',headers:{cookie:'pdl_platform=platform-1','Content-Type':'application/json'}},response=>{let data='';response.on('data',chunk=>data+=chunk);response.on('end',()=>resolve({status:response.statusCode,body:JSON.parse(data)}));});request.on('error',reject);request.write('{\"name\":');});
 await new Promise(r=>setTimeout(r,80));const ownerRevoked=platform();ownerRevoked.users[0].status='Inactive';fs.writeFileSync(platformFile,JSON.stringify(ownerRevoked));request.end('\"Late owner\",\"email\":\"late@example.invalid\",\"role\":\"platform_owner\"}');
 const creationDenied=await creating;assert.equal(creationDenied.status,403);assert.ok(!JSON.parse(fs.readFileSync(platformFile,'utf8')).users.some(u=>u.email==='late@example.invalid'));checks++;await stop();
 console.log(`${checks} reconstructed revenue access assertions passed, auth on/off, read-only, escalation and revocation.`);
})().catch(e=>{console.error(e);console.error('Synthetic server log:',log);process.exitCode=1}).finally(async()=>{await stop();fs.rmSync(temp,{recursive:true,force:true})});
