'use strict';
const assert = require('node:assert/strict');
const { createRevenueReporter, parsePeriod, minorUnitExponent, companyResolver, API_VERSION } = require('./revenue-reporting');
const NOW = new Date('2026-10-05T12:00:00Z'), created = Date.parse('2026-10-03T12:00:00Z') / 1000, period = { start: '2026-10-01', end: '2026-10-04' };
const companies = [{ id: 'a', name: 'Company A', stripeCustomerId: 'cus_a', stripeSubscriptionId: 'sub_year' }, { id: 'b', name: '<Company B>', stripeCustomerId: 'cus_b' }];
const getCompanies = async () => companies;
function charge(id, customer = 'cus_a', extra = {}) { return { id, object: 'charge', customer, created, status: 'succeeded', amount: 120000, currency: 'usd', billing_details: { email: 'PRIVATE@example.invalid' }, payment_method_details: { card: { last4: '9876' } }, ...extra }; }
function txn(id, reporting_category, amount, source, currency = 'usd') { return { id, reporting_category, amount, source, currency, created, status: 'available' }; }
function item(id, unit = 120000, interval = 'year', extra = {}) { return { id, quantity: 1, price: { id: 'price_' + id, unit_amount: unit, currency: 'usd', billing_scheme: 'per_unit', tax_behavior: 'exclusive', recurring: { usage_type: 'licensed', interval, interval_count: 1 } }, ...extra }; }
function sub(id, items = [item('si_' + id)], extra = {}) { return { id, status: 'active', currency: 'usd', customer: 'cus_a', created, items: { data: items, has_more: false }, ...extra }; }
function fake(input = {}) {
  const calls = [], client = { calls };
  for (const resource of ['balanceTransactions', 'charges', 'refunds', 'subscriptions', 'subscriptionItems']) client[resource] = {
    list: async (params, options) => { calls.push({ resource, method: 'list', params, options }); if (input[resource] instanceof Error) throw input[resource]; return typeof input[resource] === 'function' ? input[resource](params) : { data: input[resource] || [], has_more: false }; },
    retrieve: async (id, params, options) => { calls.push({ resource, method: 'retrieve', id, options }); if (!input.lookups?.[id]) throw new Error('Missing synthetic lookup'); return input.lookups[id]; }
  };
  return client;
}
const reporter = (client, options = {}) => createRevenueReporter({ getSecret: () => 'synthetic_test_credential', createClient: () => client, now: () => NOW, cacheMs: 0, ...options });
let count = 0;
async function test(name, fn) { await fn(); count++; console.log('PASS ' + name); }
(async () => {
  await test('strict inclusive UTC dates, leap range, snapshot cap and invalid bounds', () => {
    const result = parsePeriod(period, NOW); assert.equal(result.startInclusive, '2026-10-01T00:00:00.000Z'); assert.equal(result.endExclusive, '2026-10-05T00:00:00.000Z'); assert.equal(parsePeriod({}, NOW).endExclusive, NOW.toISOString());
    for (const input of [{ start: '2026-02-30' }, { start: '2026-9-1' }, { start: '2025-01-01' }, { end: '2026-10-06' }, { start: '2026-10-04', end: '2026-10-03' }, { start: '2026-10-03T00:00Z' }]) assert.throws(() => parsePeriod(input, NOW));
    assert.equal(parsePeriod({ start: '2024-01-01', end: '2024-12-31' }, NOW).startDate, '2024-01-01'); assert.equal(API_VERSION, '2026-08-26.dahlia');
  });
  await test('Stripe zero/two/three and ISK/UGX legacy exponents', () => { for (const [code, exponent] of [['jpy', 0], ['usd', 2], ['bhd', 3], ['isk', 2], ['ugx', 2]]) assert.equal(minorUnitExponent(code), exponent); });
  await test('missing key and invalid dates never load companies or call Stripe', async () => { let invoked = false; const report = createRevenueReporter({ getSecret: () => '', now: () => NOW, createClient: () => { invoked = true; } }); const result = await report(period, () => { invoked = true; }); assert.equal(result.status, 'unconfigured'); assert.equal(result.cash, undefined); assert.equal((await report({ start: 'bad' })).code, 'invalid_period'); assert.equal(invoked, false); });
  await test('successful empty report is distinct from unavailable and invents no currency', async () => { const result = await reporter(fake())(period, getCompanies); assert.equal(result.status, 'ready'); assert.deepEqual(result.cash, []); assert.deepEqual(result.recurring, []); assert.equal(result.failedPayments.count, 0); });
  await test('ledger cash, annual receipt, refund/reversal and failed-attempt semantics', async () => {
    const original = charge('ch_year'), old = charge('ch_old', 'cus_b', { created: 1600000000 });
    const transactions = [txn('t1', 'charge', 120000, original), txn('t2', 'charge', 5000, original), txn('t3', 'partial_capture_reversal', -1000, { id: 're_capture', object: 'refund', charge: 'ch_year' }), txn('t4', 'charge_failure', -1000, original), txn('t5', 'refund', -10000, { id: 're_old', object: 'refund', charge: 'ch_old', status: 'succeeded' }), txn('t6', 'refund', -2000, { id: 're_failed', object: 'refund', charge: 'ch_old', status: 'failed' }), txn('t7', 'refund_failure', 2000, { id: 're_failed', object: 'refund', charge: 'ch_old', status: 'failed' }), txn('t8', 'charge', 4000, charge('ch_unknown', null), 'jpy'), txn('t9', 'payout', -10000, null)];
    const client = fake({ balanceTransactions: [...transactions, transactions[0]], charges: [original, charge('ch_fail1', 'cus_a', { status: 'failed', amount: 900 }), charge('ch_fail2', 'cus_a', { status: 'failed', amount: 900 })], lookups: { ch_old: old }, refunds: [{ id: 're_old', created, status: 'succeeded' }, { id: 're_failed', created, status: 'failed' }, { id: 're_pending', created, status: 'pending' }, { id: 're_capture', created, status: 'succeeded', reason: 'partial_capture' }], subscriptions: [sub('sub_year')] });
    const result = await reporter(client)(period, getCompanies); assert.equal(result.status, 'ready'); assert.equal(result.mode, 'test');
    assert.deepEqual(result.cash.find(row => row.currency === 'usd'), { currency: 'usd', minorUnitExponent: 2, receiptsMinor: 125000, paymentReversalsMinor: -2000, refundDebitsMinor: 12000, refundReversalsMinor: 2000, netBeforeFeesMinor: 113000 });
    assert.equal(result.cash.find(row => row.currency === 'jpy').receiptsMinor, 4000); assert.equal(result.recurring[0].grossMrrMinor, 10000); assert.equal(result.recurring[0].annualSubscriptionCount, 1); assert.equal(result.failedPayments.count, 2);
    assert.equal(result.refundStatuses.succeeded, 1); assert.equal(result.refundStatuses.failed, 1); assert.equal(result.refundStatuses.pending, 1); assert.equal(result.coverage.otherBalanceTransactions, 1); assert.equal(result.coverage.unmatchedActivity, 1); assert.equal(result.companies.find(row => row.id === 'b').cash[0].netBeforeFeesMinor, -10000); assert.equal(client.calls.filter(row => row.method === 'retrieve').length, 1);
    for (const secret of ['PRIVATE@example.invalid', '9876', 'cus_a', 'ch_old', 'synthetic_test_credential', 'billing_details', 'payment_method']) assert.ok(!JSON.stringify(result).includes(secret));
    assert.ok(client.calls.every(row => ['list', 'retrieve'].includes(row.method) && row.options.maxNetworkRetries === 0 && row.options.timeout <= 5000));
  });
  await test('unexpanded payment-refund IDs resolve exact companies for debit and reversal', async () => {
    const client = fake({ balanceTransactions: [txn('t_refund', 'refund', -500, 'pyr_existing'), txn('t_refund_reversal', 'refund_failure', 500, 'pyr_existing')], lookups: { pyr_existing: { id: 'pyr_existing', object: 'refund', charge: 'py_original', status: 'failed' }, py_original: charge('py_original', 'cus_b', { created: 1600000000 }) } });
    const result = await reporter(client)(period, getCompanies); assert.equal(result.status, 'ready'); assert.equal(result.coverage.unmatchedActivity, 0); assert.equal(result.companies[0].id, 'b'); assert.equal(result.companies[0].cash[0].netBeforeFeesMinor, 0); assert.equal(client.calls.filter(call => call.resource === 'refunds' && call.method === 'retrieve').length, 1);
  });
  await test('current gross MRR interval/quantity, past due, canceled/trial/unpaid/paused exclusions', async () => {
    const monthly = item('si_month', 9900, 'month', { quantity: 2 }), quarter = item('si_quarter', 1500, 'month'); quarter.price.currency = 'eur'; quarter.price.recurring.interval_count = 3;
    const bad = [item('si_meter'), item('si_inclusive'), item('si_tier'), item('si_transform'), item('si_null'), item('si_trial')]; bad[0].price.recurring.usage_type = 'metered'; bad[1].price.tax_behavior = 'inclusive'; bad[2].price.billing_scheme = 'tiered'; bad[3].price.transform_quantity = { divide_by: 5 }; bad[4].price.unit_amount = null; bad[5].trial_end = created + 999999;
    const client = fake({ subscriptions: [sub('sub_year'), sub('sub_month', [monthly]), sub('sub_due', [quarter], { status: 'past_due', customer: 'cus_b', currency: 'eur' }), ...['canceled', 'trialing', 'unpaid', 'paused'].map(status => sub('sub_' + status, undefined, { status })), sub('sub_pause', undefined, { pause_collection: { behavior: 'void' } }), sub('sub_bad', bad), sub('sub_discount', [item('si_discount', 1000, 'month')], { discounts: ['synthetic_discount'] })] });
    const result = await reporter(client)(period, getCompanies); assert.equal(result.status, 'ready'); assert.equal(result.recurring.find(row => row.currency === 'usd').grossMrrMinor, 30800); assert.equal(result.recurring.find(row => row.currency === 'eur').grossMrrMinor, 500); assert.equal(result.recurring.find(row => row.currency === 'eur').pastDueMrrMinor, 500); assert.equal(result.coverage.excludedSubscriptionItems, 7); assert.equal(client.calls.find(row => row.resource === 'subscriptions').params.created.lt, NOW.valueOf() / 1000);
  });
  await test('all subscription/item pages deduplicate without losing quantities', async () => { const first = sub('sub_first', [item('si_first', 100, 'month')]); first.items.has_more = true; const second = sub('sub_second', [item('si_second', 200, 'month')]); const client = fake({ subscriptions: p => p.starting_after ? { data: [first, second], has_more: false } : { data: [first], has_more: true }, subscriptionItems: p => p.starting_after ? { data: [item('si_first', 100, 'month'), item('si_third', 300, 'month')], has_more: false } : { data: [item('si_first', 100, 'month')], has_more: true } }); const result = await reporter(client)(period, getCompanies); assert.equal(result.status, 'ready'); assert.equal(result.recurring[0].grossMrrMinor, 600); assert.equal(result.recurring[0].subscriptionCount, 2); });
  await test('multi-currency price and inclusive/unknown effective tax never misprice MRR', async () => { const mismatch = sub('s_currency', undefined, { currency: 'eur' }), a = sub('s_default', undefined, { default_tax_rates: [{ inclusive: true }] }), b = sub('s_item', [item('si_tax', 120000, 'year', { tax_rates: [{ inclusive: true }] })]), c = sub('s_unknown', undefined, { default_tax_rates: ['txr_unknown'] }), d = sub('s_auto', undefined, { automatic_tax: { enabled: true } }); d.items.data[0].price.tax_behavior = 'unspecified'; const good = sub('s_good', undefined, { default_tax_rates: [{ inclusive: false }] }); const result = await reporter(fake({ subscriptions: [mismatch, a, b, c, d, good] }))(period, getCompanies); assert.equal(result.status, 'ready'); assert.equal(result.recurring[0].grossMrrMinor, 10000); assert.equal(result.coverage.excludedSubscriptionItems, 5); });
  await test('exact stored links only; duplicate/conflicting links stay unmatched', () => { const resolve = companyResolver([...companies, { id: 'c', name: 'Company A', stripeCustomerId: 'cus_a' }]); for (const pair of [['cus_a', null], ['cus_a', 'sub_year'], ['cus_b', 'sub_year'], ['missing', null]]) assert.equal(resolve(...pair).linked, false); assert.equal(resolve(null, 'sub_year').id, 'a'); assert.equal(resolve({ id: 'cus_b' }, null).id, 'b'); });
  await test('response timestamps are also bounded and end-exclusive', async () => { const one = txn('inside', 'charge', 50, charge('ch_one')); const result = await reporter(fake({ balanceTransactions: [one, { ...one, id: 'old', created: 0 }, { ...one, id: 'edge', created: Date.parse('2026-10-05T00:00Z') / 1000 }] }))(period, getCompanies); assert.equal(result.cash[0].receiptsMinor, 50); });
  await test('provider errors, corrupt money and impossible signs expose no raw errors or partial zero', async () => { for (const fixture of [{ charges: new Error('PRIVATE PROVIDER') }, { balanceTransactions: [txn('bad', 'charge', .5, null)] }, { balanceTransactions: [txn('bad', 'refund', 1, null)] }, { balanceTransactions: [{ ...txn('bad', 'charge', 1, null), created: 'bad' }] }]) { const result = await reporter(fake(fixture))(period, getCompanies); assert.equal(result.status, 'error'); assert.equal(result.cash, undefined); assert.ok(!JSON.stringify(result).includes('PRIVATE')); } });
  await test('pagination loops, empty continuation, limits and late-page errors fail closed', async () => { for (const input of [() => ({ data: [charge('same')], has_more: true }), () => ({ data: [], has_more: true })]) assert.equal((await reporter(fake({ charges: input }))(period, getCompanies)).code, 'incomplete'); assert.equal((await reporter(fake(), { maxRequests: 2 })(period, getCompanies)).code, 'incomplete'); const later = fake({ charges: p => { if (p.starting_after) throw new Error('private'); return { data: [charge('one')], has_more: true }; } }); assert.equal((await reporter(later)(period, getCompanies)).status, 'error'); });
  await test('single-flight cache, changing and missing keys', async () => { const client = fake(); let secret = 'synthetic_test_one'; const report = reporter(client, { cacheMs: 60000, getSecret: () => secret }); await Promise.all([report(period, getCompanies), report(period, getCompanies)]); assert.equal(client.calls.length, 4); await report(period, getCompanies); assert.equal(client.calls.length, 4); secret = 'synthetic_test_two'; await report(period, getCompanies); assert.equal(client.calls.length, 8); secret = ''; assert.equal((await report(period, getCompanies)).status, 'unconfigured'); });
  await test('activity cap never truncates period totals', async () => { const result = await reporter(fake({ balanceTransactions: Array.from({ length: 101 }, (_, i) => txn('t' + i, 'charge', 100, charge('ch_' + i))) }))(period, getCompanies); assert.equal(result.cash[0].receiptsMinor, 10100); assert.equal(result.activity.length, 100); assert.equal(result.coverage.activityTotal, 101); });
  await test('overall deadline includes company loading and releases occupied slot', async () => { const client = fake(); let signal; const report = reporter(client, { maxDurationMs: 20 }); const result = await report(period, options => { signal = options.signal; return new Promise(() => {}); }); assert.equal(result.code, 'incomplete'); assert.equal(signal.aborted, true); assert.equal(client.calls.length, 0); assert.equal((await report(period, getCompanies)).status, 'ready'); });
  await test('removed key during company read starts no Stripe calls', async () => { const client = fake(); let secret = 'synthetic_test_one', release; const report = reporter(client, { getSecret: () => secret }); const pending = report(period, () => new Promise(resolve => { release = resolve; })); await new Promise(resolve => setImmediate(resolve)); secret = ''; release(companies); assert.equal((await pending).status, 'error'); assert.equal(client.calls.length, 0); });
  await test('rotating key during Stripe reads cannot return or cache old results', async () => { let release, secret = 'synthetic_test_old'; const client = fake({ charges: () => new Promise(resolve => { release = resolve; }) }); const report = reporter(client, { getSecret: () => secret, cacheMs: 60000 }); const pending = report(period, getCompanies); await new Promise(resolve => setImmediate(resolve)); secret = 'synthetic_test_new'; release({ data: [], has_more: false }); assert.equal((await pending).status, 'error'); });
  await test('failure stops sibling pagination and waits for in-flight provider read', async () => { let release, settled = false; const client = fake({ charges: new Error('private'), balanceTransactions: () => new Promise(resolve => { release = () => { settled = true; resolve({ data: [txn('wait', 'charge', 1, null)], has_more: true }); }; }) }); const pending = reporter(client)(period, getCompanies); await new Promise(resolve => setImmediate(resolve)); release(); assert.equal((await pending).status, 'error'); assert.equal(settled, true); assert.equal(client.calls.filter(c => c.resource === 'balanceTransactions').length, 1); });
  await test('two in-flight ranges bound fan-out and recover after completion', async () => { const releases = [], report = reporter(fake()); const load = () => new Promise(resolve => releases.push(() => resolve(companies))); const a = report(period, load), b = report({ start: '2026-10-02', end: '2026-10-04' }, load); assert.equal((await report({ start: '2026-10-03', end: '2026-10-04' }, load)).code, 'busy'); releases.forEach(release => release()); assert.equal((await a).status, 'ready'); assert.equal((await b).status, 'ready'); assert.equal((await report(period, getCompanies)).status, 'ready'); });
  console.log(`${count} reconstructed revenue reporting cases passed with synthetic read-only clients.`);
})().catch(error => { console.error(error); process.exitCode = 1; });
