'use strict';
const assert=require('node:assert/strict');
const {loadRevenueCompanies}=require('./revenue-companies');
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const company=(n,extra={})=>({id:id(n),name:`Synthetic ${n}`,stripeCustomerId:`cus_${n}`,persistence:{revision:1,updatedAt:'2026-10-01T00:00:00Z'},...extra});
function adapter(rows=[],cap=500){const calls=[];return{calls,configured:()=>true,request:async(url,options)=>{calls.push({url,options});const cursor=url.match(/id=gt\.([a-f0-9-]+)/)?.[1];return{ok:true,json:async()=>rows.filter(row=>!cursor||row.id>cursor).slice(0,cap)}}};}
let count=0;async function test(name,fn){await fn();count++;console.log('PASS '+name);}
(async()=>{
 await test('unconfigured source returns minimized local records',async()=>{const source={configured:()=>false};const result=await loadRevenueCompanies({localCompanies:[company(1,{notes:'private',users:[{email:'private'}]})],supabase:source});assert.equal(result.length,1);assert.deepEqual(Object.keys(result[0]).sort(),['id','name','persistence','stripeCustomerId','stripeSubscriptionId'].sort());assert.ok(!JSON.stringify(result).includes('private'));});
 await test('more than1000 companies with provider caps paginate until empty',async()=>{const rows=Array.from({length:1201},(_,n)=>({id:id(n+1),company:company(n+1)})),source=adapter(rows,200);const result=await loadRevenueCompanies({supabase:source});assert.equal(result.length,1201);assert.equal(source.calls.length,8);assert.ok(source.calls.every(c=>c.url.startsWith('/rest/v1/companies?select=id,company:data->company&order=id.asc&limit=500')&&c.options.method==='GET'&&c.options.signal));assert.ok(source.calls.slice(1).every(c=>/id=gt\./.test(c.url)));});
 await test('newest revision beats remote order and timestamp',async()=>{const local=company(1,{stripeCustomerId:'cus_latest',persistence:{revision:9,updatedAt:'2026-10-01'}}),remote=company(1,{stripeCustomerId:'cus_old',persistence:{revision:2,updatedAt:'2026-10-04'}});const result=await loadRevenueCompanies({localCompanies:[local],supabase:adapter([{id:id(1),company:remote}])});assert.equal(result[0].stripeCustomerId,'cus_latest');});
 await test('equal revision chooses newer date and respects explicit cleared link',async()=>{const local=company(1),remote=company(1,{stripeCustomerId:null,persistence:{revision:1,updatedAt:'2026-10-02'}});const result=await loadRevenueCompanies({localCompanies:[local],supabase:adapter([{id:id(1),company:remote}])});assert.equal(result[0].stripeCustomerId,null);});
 await test('equal-version customer/subscription conflicts fail closed',async()=>{for(const link of [{stripeCustomerId:'cus_other'},{stripeSubscriptionId:'sub_other'}])await assert.rejects(loadRevenueCompanies({localCompanies:[company(1)],supabase:adapter([{id:id(1),company:company(1,link)}])}),e=>e.code==='mapping_conflict');});
 await test('duplicate Stripe links across companies remain visible for ambiguity handling',async()=>{const result=await loadRevenueCompanies({localCompanies:[company(1,{stripeCustomerId:'cus_same'}),company(2,{stripeCustomerId:'cus_same',archivedDuplicate:true,demo:true})],supabase:adapter()});assert.equal(result.length,2);assert.ok(result.every(c=>c.stripeCustomerId==='cus_same'));});
 await test('exclude platform metadata and keep legacy IDs separate from row cursor',async()=>{const result=await loadRevenueCompanies({localCompanies:[company(1)],excludeCompanyId:id(1),supabase:adapter([{id:id(2),company:company(2,{id:'northstar'})}])});assert.equal(result.length,1);assert.equal(result[0].id,'northstar');});
 await test('invalid metadata fails closed without coercing malformed revisions/IDs',async()=>{for(const bad of [null,{},company(1,{id:' bad'}),company(1,{persistence:{revision:-1}}),company(1,{persistence:{updatedAt:'invalid'}}),company(1,{stripeCustomerId:{id:'cus_x'}})])await assert.rejects(loadRevenueCompanies({localCompanies:[bad],supabase:adapter()}),e=>e.code==='invalid_data');});
 await test('malformed, unordered and repeated pages cannot look complete',async()=>{for(const rows of [[{id:'not_uuid',company:company(1)}],[{id:id(2),company:company(2)},{id:id(1),company:company(1)}],Array.from({length:501},(_,n)=>({id:id(n+1),company:company(n+1)}))]){const source={configured:()=>true,request:async()=>({json:async()=>rows})};await assert.rejects(loadRevenueCompanies({supabase:source}),e=>e.code==='invalid_data');}const source={configured:()=>true,request:async()=>({json:async()=>[{id:id(1),company:company(1)}]})};await assert.rejects(loadRevenueCompanies({supabase:source}),e=>e.code==='invalid_data');});
 await test('nonempty page budget exhaustion returns incomplete',async()=>{let n=0;const source={configured:()=>true,request:async()=>({json:async()=>[{id:id(++n),company:company(n)}]})};await assert.rejects(loadRevenueCompanies({supabase:source}),e=>e.code==='incomplete');assert.equal(n,40);});
 await test('provider exception and failed status are sanitized',async()=>{for(const request of [async()=>{throw new Error('PRIVATE URL AND KEY')},async()=>({ok:false,json:async()=>[]})])await assert.rejects(loadRevenueCompanies({supabase:{configured:()=>true,request}}),e=>!e.message.includes('PRIVATE'));});
 await test('already-aborted and mid-read caller signals stop reads',async()=>{const a=new AbortController();a.abort();await assert.rejects(loadRevenueCompanies({supabase:adapter(),signal:a.signal}),e=>e.code==='aborted');const b=new AbortController();let localSignal;const pending=loadRevenueCompanies({signal:b.signal,supabase:{configured:()=>true,request:async(url,options)=>{localSignal=options.signal;return new Promise(()=>{})}}});await new Promise(r=>setImmediate(r));b.abort();await assert.rejects(pending,e=>e.code==='aborted');assert.equal(localSignal.aborted,true);});
 await test('five-second deadline includes hung JSON body parsing',async()=>{let signal;const start=Date.now();await assert.rejects(loadRevenueCompanies({supabase:{configured:()=>true,request:async(url,options)=>{signal=options.signal;return{json:()=>new Promise(()=>{})}}}}),e=>e.code==='incomplete');assert.ok(Date.now()-start>=4900);assert.ok(Date.now()-start<8000);assert.equal(signal.aborted,true);});
 console.log(`${count} reconstructed company-loader cases passed.`);
})().catch(error=>{console.error(error);process.exitCode=1});
