'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{execFileSync}=require('node:child_process');
if(!process.argv.includes('--zone')){for(const zone of ['America/Los_Angeles','Pacific/Kiritimati','Etc/UTC'])execFileSync(process.execPath,[__filename,'--zone'],{env:{...process.env,TZ:zone},stdio:'inherit'});process.exit(0)}
const source=fs.readFileSync('app.js','utf8'),nodes=new Map();
const node=id=>{if(!nodes.has(id))nodes.set(id,{value:'',checked:false,hidden:false,innerHTML:'',textContent:'',classList:{contains(){return true}}});return nodes.get(id)};
const context={$:id=>id==='dialog[open]'?(context.openDialog?node(id):null):node(id),$$:()=>[],document:{visibilityState:'visible'},draggedScheduleWork:null,window:{PDLScheduleAvailability:require('./schedule-availability')},signedInCompanyId:()=>context.companyId,companyId:'tenant-a',currentUser:{id:1,role:'owner'},currentRole:'office',scheduleAnchorDate:'2026-10-10',scheduleView:'week',preferredLanguage:'en',interfaceLocale:()=> 'en-US',canManageSchedule:()=>true,formatDate:value=>value,escapeHtml:value=>String(value).replaceAll('<','&lt;').replaceAll('>','&gt;'),displayTime:value=>value,assignmentActualHours:()=>0,projects:[{id:1,name:'Synthetic project',code:'QA'}],team:[{id:1,name:'Synthetic Worker',initials:'SW',role:'Crew lead',crew:'QA'},{id:2,name:'Other Worker',initials:'OW',role:'Laborer',crew:'Other'},{id:3,name:'Office Worker',initials:'OF',role:'Office',crew:'Office'}],assignments:[],scheduleAvailability:[{memberId:1,startDate:'2026-10-10',endDate:'2026-10-10'},{memberId:3,startDate:'2026-10-10',endDate:'2026-10-10'}],scheduleAvailabilityStatus:'ready',scheduleAvailabilitySequence:0};
vm.createContext(context);vm.runInContext(source.match(/^const localDateIso=.*$/m)[0],context);
function fn(name){const lines=source.split('\n'),start=lines.findIndex(l=>new RegExp(`^(?:async )?function ${name}\\(`).test(l));assert.ok(start>=0,name);if(lines[start].trimEnd().endsWith('}'))return lines[start];const end=lines.findIndex((l,i)=>i>start&&l.trimEnd()==='}');return lines.slice(start,end+1).join('\n')}
for(const name of ['isOfficeMember','shiftHours','scheduleDate','scheduleWeekStart','schedulePeriodDays','chooseScheduleDate','shiftSchedulePeriod','scheduleUnavailable','scheduleLeaveMarkup','scheduleDayLeaveMarkup','scheduleAvailabilityKey','scheduleUnavailableSummary','scheduleMobileMarkup','renderSchedule','refreshScheduleAvailability'])vm.runInContext(fn(name),context);
function board(){context.renderSchedule();return node('#schedule-board').innerHTML}
function cell(html,member,date){return html.match(new RegExp(`data-schedule-date="${date}" data-schedule-member="${member}">([\\s\\S]*?)(?=</div><div class="schedule-cell|</div></div>)`))?.[1]||''}
for(const view of ['day','week','month']){context.scheduleView=view;const html=board();assert.match(html,/Synthetic Worker · Unavailable/,'mobile/month show named approved absence');assert.doesNotMatch(html,/Office Worker/,'office filter respected');if(view!=='month'){assert.match(cell(html,1,'2026-10-10'),/Unavailable · Approved time off/);assert.doesNotMatch(cell(html,1,'2026-10-10'),/>Available</);assert.match(cell(html,2,'2026-10-10'),/>Available</)}}
const monthlySummary=context.scheduleUnavailableSummary(context.schedulePeriodDays(),[context.team[0],context.team[1]]);assert.match(monthlySummary,/Unavailable this month/);assert.match(monthlySummary,/1 person/);assert.match(monthlySummary,/Oct 10/);assert.doesNotMatch(monthlySummary,/Other Worker|Office Worker/);
context.scheduleView='week';let phone=context.scheduleMobileMarkup(context.schedulePeriodDays(),[context.team[0],context.team[1]]);assert.ok(phone.indexOf('schedule-unavailable-summary')<phone.indexOf('schedule-agenda-day'),'unavailable people appear before any day or assignment');assert.match(phone,/Unavailable this week/);assert.match(phone,/Synthetic Worker<\/strong><span>Oct 10/,'Saturday absence visible in summary above Sunday agenda');
context.scheduleView='day';context.chooseScheduleDate('2026-10-10');assert.match(context.scheduleUnavailableSummary(context.schedulePeriodDays(),[context.team[0]]),/Unavailable on this day/);context.shiftSchedulePeriod(1);assert.doesNotMatch(context.scheduleUnavailableSummary(context.schedulePeriodDays(),[context.team[0]]),/Synthetic Worker/,'day navigation removes out-of-range absence');context.scheduleView='week';context.chooseScheduleDate('2026-10-10');context.shiftSchedulePeriod(1);assert.doesNotMatch(context.scheduleUnavailableSummary(context.schedulePeriodDays(),[context.team[0]]),/Synthetic Worker/,'week navigation uses selected range');context.chooseScheduleDate('2026-10-10');
context.scheduleView='week';context.assignments=[{id:1,projectId:1,date:'2026-10-10',memberIds:[1],start:'07:00',end:'15:00',activity:'Existing work'}];let html=board();assert.match(cell(html,1,'2026-10-10'),/Schedule conflict · Reassign this work/);assert.match(cell(html,1,'2026-10-10'),/Existing work/,'existing assignment remains visible');
node('#schedule-crew-filter').value='Other';html=board();assert.doesNotMatch(html,/Synthetic Worker/);assert.doesNotMatch(html,/· Unavailable|Unavailable · Approved/);assert.match(html,/No approved time off for these people and dates/);node('#schedule-crew-filter').value='all';node('#schedule-show-office').checked=true;assert.match(board(),/Office Worker · Unavailable/);
context.team[0].name='<img src=x onerror=alert(1)>';assert.doesNotMatch(board(),/<img/,'absence names are escaped');context.team[0].name='Synthetic Worker';
context.scheduleAvailability=[{memberId:1,startDate:'2026-10-30',endDate:'2026-11-03'}];context.scheduleAnchorDate='2026-11-01';context.scheduleView='week';html=board();for(const date of ['2026-11-01','2026-11-02','2026-11-03'])assert.match(cell(html,1,date),/Unavailable/);assert.match(cell(html,1,'2026-11-04'),/>Available</);
context.assignments=[];context.scheduleAvailability=[];context.scheduleAvailabilityStatus='loading';assert.match(board(),/Checking availability/);assert.doesNotMatch(board(),/>Available</);assert.match(board(),/Checking approved time off/);assert.doesNotMatch(board(),/No approved time off/);context.scheduleAvailabilityStatus='error';assert.match(board(),/Availability unavailable/);assert.match(node('#schedule-summary').innerHTML,/could not be refreshed/);assert.match(board(),/Availability could not be refreshed/);assert.doesNotMatch(board(),/No approved time off/);assert.doesNotMatch(board(),/>Available</);
(async()=>{
 let pending=[];context.api=()=>new Promise((resolve,reject)=>pending.push({resolve,reject}));
 const first=context.refreshScheduleAvailability(),second=context.refreshScheduleAvailability();pending[1].resolve([{memberId:1,startDate:'2026-11-01',endDate:'2026-11-01'}]);await second;pending[0].resolve([]);await first;assert.equal(context.scheduleUnavailable(1,'2026-11-01'),true,'older response cannot overwrite newer approved leave');
 pending=[];const tenantRequest=context.refreshScheduleAvailability();context.companyId='tenant-b';context.scheduleAvailability=[];pending[0].resolve([{memberId:1,startDate:'2026-11-01',endDate:'2026-11-01'}]);await tenantRequest;assert.equal(context.scheduleAvailability.length,0,'late cross-tenant response ignored');
 pending=[];const userRequest=context.refreshScheduleAvailability();context.currentUser={id:2,role:'owner'};pending[0].resolve([{memberId:1,startDate:'2026-11-01',endDate:'2026-11-01'}]);await userRequest;assert.equal(context.scheduleAvailability.length,0,'late cross-account response ignored');
 pending=[];const roleRequest=context.refreshScheduleAvailability();context.currentRole='field';pending[0].resolve([{memberId:1,startDate:'2026-11-01',endDate:'2026-11-01'}]);await roleRequest;assert.equal(context.scheduleAvailability.length,0,'late role-preview response ignored');context.currentRole='office';
 pending=[];const failure=context.refreshScheduleAvailability();pending[0].reject(new Error('offline'));await failure;assert.equal(context.scheduleAvailabilityStatus,'error');assert.doesNotMatch(node('#schedule-board').innerHTML,/>Available</);
 pending=[];const retry=context.refreshScheduleAvailability();pending[0].resolve([]);await retry;assert.equal(context.scheduleAvailabilityStatus,'ready');assert.match(node('#schedule-board').innerHTML,/>Available</,'successful refresh recovers');
 assert.match(source,/page==='schedule'&&currentRole==='office'\)refreshScheduleAvailability\(\)/,'navigation refreshes availability');assert.match(source,/renderTimeOff\(\);await refreshScheduleAvailability\(\);notify\(`Time-off request/,'approval/decline repaint schedule');assert.match(source,/scheduleAvailabilitySequence\+\+;scheduleAvailability=\[\];scheduleAvailabilityStatus='loading';timeOffRequests=\[\]/,'role load clears old tenant/account absence data');
 pending=[];const dragging=context.refreshScheduleAvailability({background:true});context.draggedScheduleWork={assignmentId:1};pending[0].resolve([{memberId:1,startDate:'2026-11-01',endDate:'2026-11-01'}]);await dragging;assert.equal(context.scheduleAvailability.length,0,'background result cannot replace cache or DOM during a drag that began in flight');context.draggedScheduleWork=null;
 pending=[];const dialog=context.refreshScheduleAvailability({background:true});context.openDialog=true;pending[0].resolve([{memberId:1,startDate:'2026-11-01',endDate:'2026-11-01'}]);await dialog;assert.equal(context.scheduleAvailability.length,0,'background result defers when a dialog opened in flight');context.openDialog=false;
 pending=[];const deferredRetry=context.refreshScheduleAvailability({background:true});pending[0].resolve([{memberId:1,startDate:'2026-11-01',endDate:'2026-11-01'}]);await deferredRetry;assert.equal(context.scheduleUnavailable(1,'2026-11-01'),true,'next unobstructed background refresh still detects the deferred change');
 // Rejection and repeated submit: the save button must recover without throwing ReferenceError.
 node('#save-assignment').textContent='Assign to site';context.editingAssignmentId=null;context.notify=()=>{};const conflictCalls=[];context.api=async path=>{conflictCalls.push(path);if(path==='/api/schedule-availability')return [{memberId:1,startDate:'2026-10-10',endDate:'2026-10-10'}];throw new Error('Approved time-off conflict: Synthetic Worker unavailable on 2026-10-10')};node('#assignment-type').value='individual';node('#assignment-target').value='1';node('#assignment-project').value='1';node('#assignment-date').value='2026-10-10';node('#assignment-start').value='07:00';node('#assignment-end').value='15:00';node('#assignment-activity').value='Work';node('#assignment-warning').classList={remove(){},add(){}};
 vm.runInContext(source.match(/^\$\('#save-assignment'\)\.onclick=.*$/m)[0],context);await node('#save-assignment').onclick();assert.equal(node('#save-assignment').disabled,false);assert.equal(node('#save-assignment').textContent,'Assign to site');assert.match(node('#assignment-warning').textContent,/Approved time-off conflict/);await node('#save-assignment').onclick();assert.equal(node('#save-assignment').disabled,false);assert.equal(conflictCalls.filter(path=>path==='/api/schedule-availability').length,2,'each leave rejection refreshes server availability');assert.equal(context.scheduleUnavailable(1,'2026-10-10'),true);
 console.log(`Schedule availability UI passed in ${process.env.TZ}: day/week/month/mobile markup, filters, conflict preservation, loading/error, late responses, role/account/tenant isolation and repeat-submit recovery.`);
})().catch(error=>{console.error(error);process.exitCode=1});
