'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{execFileSync}=require('node:child_process');
if(!process.argv.includes('--zone')){for(const zone of ['America/Los_Angeles','Pacific/Kiritimati','Etc/UTC'])execFileSync(process.execPath,[__filename,'--zone'],{env:{...process.env,TZ:zone},stdio:'inherit'});process.exit(0)}
const source=fs.readFileSync('app.js','utf8'),nodes=new Map();
function node(id){if(!nodes.has(id))nodes.set(id,{dataset:{},value:'',hidden:false,focus(){this.focused=true},showModal(){this.open=true},close(){this.open=false},addEventListener(type,fn){this[type]=fn}});return nodes.get(id)}
let renders=0;const context={$:node,scheduleView:'week',scheduleAnchorDate:'2026-09-28',interfaceLocale:()=> 'en-US',renderSchedule(){renders++}};vm.createContext(context);
vm.runInContext(source.match(/^const localDateIso=.*$/m)[0],context);
for(const name of ['scheduleDate','scheduleMonday','shiftSchedulePeriod','schedulePeriodDays','chooseScheduleDate','openScheduleDatePicker','commitScheduleDateSelection'])vm.runInContext(source.split('\n').find(l=>l.startsWith(`function ${name}(`)),context);
for(const mode of ['day','week','month']){context.scheduleView=mode;assert.equal(context.chooseScheduleDate('2026-10-02'),true);assert.equal(context.scheduleView,mode);assert.equal(context.scheduleAnchorDate,'2026-10-02');const days=context.schedulePeriodDays();if(mode==='day')assert.equal(days[0].date,'2026-10-02');if(mode==='week'){assert.equal(days[0].date,'2026-09-28');assert.equal(days.at(-1).date,'2026-10-02')}if(mode==='month'){assert.equal(days[0].date,'2026-10-01');assert.equal(days.at(-1).date,'2026-10-31')}}
for(const date of ['2026-03-08','2026-11-01','2028-02-29','2027-01-01']){assert.equal(context.chooseScheduleDate(date),true);assert.equal(context.scheduleAnchorDate,date,'local day retained across timezone/DST')}
for(const date of ['','2026-02-30','2026-13-01','2026-10-02T00:00:00Z','invalid']){const previous=context.scheduleAnchorDate,count=renders;assert.equal(context.chooseScheduleDate(date),false);assert.equal(context.scheduleAnchorDate,previous);assert.equal(renders,count)}
const count=renders,previous=context.scheduleAnchorDate;context.openScheduleDatePicker();assert.equal(node('#schedule-date-dialog').open,true);assert.equal(node('#schedule-date-input').value,previous);assert.equal(node('#schedule-date-input').focused,true);assert.equal(renders,count,'opening does not change schedule');node('#schedule-date-input').value='2026-12-12';node('#schedule-date-dialog').close();assert.equal(context.scheduleAnchorDate,previous,'cancel leaves anchor untouched');
node('#schedule-date-input').showPicker=()=>{throw new Error('unsupported')};context.openScheduleDatePicker();assert.equal(node('#schedule-date-dialog').open,true,'visible native field remains fallback');node('#schedule-date-input').showPicker=()=>{node('#schedule-date-input').pickerOpened=true};context.openScheduleDatePicker();assert.equal(node('#schedule-date-input').pickerOpened,true);
context.scheduleView='day';context.chooseScheduleDate('2026-12-31');context.shiftSchedulePeriod(1);assert.equal(context.scheduleAnchorDate,'2027-01-01');context.scheduleView='week';context.shiftSchedulePeriod(-1);assert.equal(context.scheduleAnchorDate,'2026-12-25');context.scheduleView='month';context.shiftSchedulePeriod(1);assert.equal(context.scheduleAnchorDate,'2027-01-01');
vm.runInContext(source.match(/^\$\('#schedule-date-form'\)\.onsubmit=.*$/m)[0],context);vm.runInContext(source.match(/^\$\('#schedule-date-input'\)\.onchange=.*$/m)[0],context);vm.runInContext(source.match(/^\$\('#schedule-date-dialog'\)\.addEventListener\('pointerdown'.*$/m)[0],context);
for(const mode of ['day','week','month']){context.scheduleView=mode;context.openScheduleDatePicker();const before=context.scheduleAnchorDate,renderCount=renders;node('#schedule-date-input').value='2026-09-30';assert.equal(context.scheduleAnchorDate,before,'intermediate value/input does not commit');assert.equal(renders,renderCount);node('#schedule-date-input').onchange();assert.equal(context.scheduleAnchorDate,'2026-09-30');assert.equal(context.scheduleView,mode);assert.equal(node('#schedule-date-dialog').open,false);const once=renders;node('#schedule-date-input').value='2026-10-03';node('#schedule-date-input').onchange();assert.equal(renders,once,'late repeated change cannot alter a closed picker');assert.equal(context.scheduleAnchorDate,'2026-09-30')}
context.openScheduleDatePicker();node('#schedule-date-input').value='2026-10-03';node('#schedule-date-input').onchange();assert.equal(context.scheduleAnchorDate,'2026-10-03','reopening allows another selection');
context.openScheduleDatePicker();node('#schedule-date-input').value='2026-12-12';node('#schedule-date-dialog').pointerdown({target:{closest:()=>true}});node('#schedule-date-input').onchange();assert.equal(context.scheduleAnchorDate,'2026-10-03','Cancel pointerdown guards blur/change before cancel click');node('#schedule-date-dialog').close();node('#schedule-date-input').onchange();assert.equal(context.scheduleAnchorDate,'2026-10-03','dismissed picker ignores late events');
context.openScheduleDatePicker();node('#schedule-date-input').value='';node('#schedule-date-input').onchange();assert.equal(node('#schedule-date-dialog').open,true);assert.equal(node('#schedule-date-error').hidden,false);node('#schedule-date-input').value='2026-09-30';node('#schedule-date-form').onsubmit({preventDefault(){}});assert.equal(context.scheduleAnchorDate,'2026-09-30','keyboard Enter fallback commits');assert.equal(node('#schedule-date-dialog').open,false);
context.scheduleWeekOffset=4;vm.runInContext(source.match(/^\$\('#schedule-today'\)\.onclick=.*$/m)[0],context);node('#schedule-today').onclick();assert.equal(context.scheduleAnchorDate,vm.runInContext('localDateIso()',context));assert.equal(context.scheduleWeekOffset,0);
const index=fs.readFileSync('index.html','utf8');assert.match(index,/id="schedule-pick-date" aria-haspopup="dialog"/);assert.match(index,/id="schedule-date-input" type="date" required/);assert.match(index,/id="schedule-show-office"[^>]*><span>Show office staff<\/span>/);
assert.ok(!index.includes('Go to date'));assert.ok(!source.includes("$('#schedule-date-input').oninput="));
console.log(`Schedule date picker auto-commit passed in ${process.env.TZ}: mode/date boundaries, invalid dates, cancel, native fallback and arrows (VM; visual QA pending).`);
