'use strict';
const assert = require('node:assert/strict');
const { fixture } = require('./fixtures/project-assistant');
const schedule = require('./scheduling-access');
const outbox = require('./assignment-email-outbox');
const { createAssignmentRows } = require('./assignment-records');
const { canonicalHash } = require('./database/transactional-repository');
const { guard } = require('./scheduling-route-guard');
const db = fixture(), pm = db.users[1], auth = { user: pm, session: db.sessions[1] };
const policy = () => ({ version: 1, revision: 1, roles: Object.fromEntries(schedule.roles.map(role => [role, schedule.ceiling(role)])) });
const target = { projectId: 101, memberIds: [11] };
assert.equal(schedule.inScope(db, pm, target, 'create'), true);
assert.equal(schedule.inScope(db, pm, { projectId: 102, memberIds: [11] }, 'create'), false);
assert.equal(schedule.inScope(db, pm, { projectId: 101, memberIds: [11, 13] }, 'edit'), false);
for (const role of ['field', 'foreman', 'crew', 'platform_owner']) assert.equal(schedule.access(db, { ...pm, role, permissions: { scheduleCrews: true } }).create, false);
for (const key of ['owner', 'crew', 'billing', '__proto__']) { const value = policy(); Object.defineProperty(value.roles, key, { value: {}, enumerable: true }); assert.throws(() => schedule.validatePolicy(value)); }
const bad = policy(); bad.roles.field.create = true; assert.throws(() => schedule.validatePolicy(bad));
const newPolicy = policy(); newPolicy.roles.project_manager.create = false; db.company.schedulingRolePolicy = newPolicy;
assert.equal(schedule.access(db, pm).create, false); assert.equal(schedule.access(db, pm).edit, true);
assert.equal(schedule.actor(db, pm, false), null); assert.equal(schedule.access(db, db.users[0]).create, true);
delete db.company.schedulingRolePolicy; db.company.schedulingPolicyRequired = true;
assert.equal(schedule.access(db, pm).view, false); delete db.company.schedulingPolicyRequired;
const rejected = guard(db, pm, 'POST', new URL('http://test/api/assignments'), { ...target, id: 999, requestId: 'synthetic-request' }); assert.equal(rejected.status, 400);
const rows = createAssignmentRows(db, { ...target, date: '2098-01-01', start: '08:00', end: '16:00', activity: 'Synthetic' }, ['2098-01-01']); db.assignments.push(...rows);
outbox.enqueue(db, auth, rows);
const job = db.assignmentEmailOutbox[0]; assert.equal(job.status, 'queued'); assert.equal(outbox.authorised(db, job, Date.now()), true);
const before = canonicalHash(db);
const copied = structuredClone(db); copied.users[1].permissions.scheduleCrews = false; assert.equal(outbox.authorised(copied, copied.assignmentEmailOutbox[0], Date.now()), false);
copied.users[1].permissions.scheduleCrews = true; copied.assignmentEmailOutbox[0].payload.url = 'https://malicious.invalid'; assert.equal(outbox.authorised(copied, copied.assignmentEmailOutbox[0], Date.now()), false);
assert.equal(canonicalHash(db), before);
(async () => {
  let revision = 1, stored = structuredClone(db), sends = 0;
  const dispatcher = outbox.createDispatcher({ accountAllowed: db => db.company.demo === true, load: async () => ({ snapshot: structuredClone(stored), revision }), commit: async (candidate, expected) => { if (expected !== revision) throw Object.assign(Error('Conflict'), { code: 'PDL_REVISION_CONFLICT' }); stored = structuredClone(candidate); revision++; }, send: async (payload, key) => { sends++; assert.equal(stored.assignmentEmailOutbox[0].status, 'dispatching'); assert.match(key, /^pdl-assignment\//); assert.equal(payload.to, db.users[3].email); return { id: 'synthetic-provider-id' }; } });
  await dispatcher.dispatch(db.company.id, job.id); assert.equal(sends, 1); assert.equal(stored.assignmentEmailOutbox[0].status, 'sent');
  await dispatcher.dispatch(db.company.id, job.id); assert.equal(sends, 1);
  stored = structuredClone(db); stored.users[1].status = 'Deactivated';
  assert.equal((await dispatcher.dispatch(db.company.id, job.id)).cancelled, true); assert.equal(sends, 1);
  console.log('Typed scheduling roles/actions/scopes and finite assignment outbox unit tests passed.');
})().catch(error => { console.error(error); process.exitCode = 1; });
