'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{execFileSync}=require('node:child_process');
if(!process.argv.includes('--zone')){for(const zone of ['America/Los_Angeles','Pacific/Kiritimati','Etc/UTC'])execFileSync(process.execPath,[__filename,'--zone'],{env:{...process.env,TZ:zone},stdio:'inherit'});process.exit(0)}
const source=fs.readFileSync('app.js','utf8'),nodes=new Map();
function node(id){if(!nodes.has(id))nodes.set(id,{dataset:{},value:'',hidden:false,focus(){this.focused=true},showModal(){this.open=true},close(){this.open=false},addEventListener(type,fn){this[type]=fn}});return nodes.get(id)}
let renders=0;const context={$:node,scheduleView:'week',scheduleAnchorDate:'2026-09-28',interfaceLocale:()=> 'en-US',renderSchedule(){renders++}};context.EmployeeRoster=require('./employee-roster');vm.createContext(context);
vm.runInContext(source.match(/^const localDateIso=.*$/m)[0],context);
for(const name of ['scheduleDate','scheduleWeekStart','shiftSchedulePeriod','schedulePeriodDays','chooseScheduleDate','openScheduleDatePicker','commitScheduleDateSelection'])vm.runInContext(source.split('\n').find(l=>l.startsWith(`function ${name}(`)),context);
for(const mode of ['day','week','month']){context.scheduleView=mode;assert.equal(context.chooseScheduleDate('2026-10-02'),true);assert.equal(context.scheduleView,mode);assert.equal(context.scheduleAnchorDate,'2026-10-02');const days=context.schedulePeriodDays();if(mode==='day')assert.equal(days[0].date,'2026-10-02');if(mode==='week'){assert.equal(days[0].date,'2026-09-27');assert.equal(days.at(-1).date,'2026-10-03')}if(mode==='month'){assert.equal(days[0].date,'2026-10-01');assert.equal(days.at(-1).date,'2026-10-31')}}
for(const date of ['2026-03-08','2026-11-01','2028-02-29','2027-01-01']){assert.equal(context.chooseScheduleDate(date),true);assert.equal(context.scheduleAnchorDate,date,'local day retained across timezone/DST')}
for(const date of ['','2026-02-30','2026-13-01','2026-10-02T00:00:00Z','invalid']){const previous=context.scheduleAnchorDate,count=renders;assert.equal(context.chooseScheduleDate(date),false);assert.equal(context.scheduleAnchorDate,previous);assert.equal(renders,count)}
const count=renders,previous=context.scheduleAnchorDate;context.openScheduleDatePicker();assert.equal(node('#schedule-date-dialog').open,true);assert.equal(node('#schedule-date-input').value,previous);assert.equal(node('#schedule-date-input').focused,true);assert.equal(renders,count,'opening does not change schedule');node('#schedule-date-input').value='2026-12-12';node('#schedule-date-dialog').close();assert.equal(context.scheduleAnchorDate,previous,'cancel leaves anchor untouched');
node('#schedule-date-input').showPicker=()=>{throw new Error('unsupported')};context.openScheduleDatePicker();assert.equal(node('#schedule-date-dialog').open,true,'visible native field remains fallback');node('#schedule-date-input').showPicker=()=>{node('#schedule-date-input').pickerOpened=true};context.openScheduleDatePicker();assert.equal(node('#schedule-date-input').pickerOpened,true);
context.scheduleView='day';context.chooseScheduleDate('2026-12-31');context.shiftSchedulePeriod(1);assert.equal(context.scheduleAnchorDate,'2027-01-01');context.scheduleView='week';context.shiftSchedulePeriod(-1);assert.equal(context.scheduleAnchorDate,'2026-12-25');context.scheduleView='month';context.shiftSchedulePeriod(1);assert.equal(context.scheduleAnchorDate,'2027-01-01');
vm.runInContext(source.match(/^\$\('#schedule-date-form'\)\.onsubmit=.*$/m)[0],context);vm.runInContext(source.match(/^\$\('#schedule-date-input'\)\.onchange=.*$/m)[0],context);vm.runInContext(source.match(/^\$\('#schedule-date-dialog'\)\.addEventListener\('pointerdown'.*$/m)[0],context);
for(const mode of ['day','week','month']){context.scheduleView=mode;context.openScheduleDatePicker();const before=context.scheduleAnchorDate,renderCount=renders;node('#schedule-date-input').value='2026-09-30';assert.equal(context.scheduleAnchorDate,before,'intermediate value/input does not commit');assert.equal(renders,renderCount);node('#schedule-date-input').onchange();assert.equal(context.scheduleAnchorDate,'2026-09-30');assert.equal(context.scheduleView,mode);assert.equal(node('#schedule-date-dialog').open,false);const once=renders;node('#schedule-date-input').value='2026-10-03';node('#schedule-date-input').onchange();assert.equal(renders,once,'late repeated change cannot alter a closed picker');assert.equal(context.scheduleAnchorDate,'2026-09-30')}
context.openScheduleDatePicker();node('#schedule-date-input').value='2026-10-03';node('#schedule-date-input').onchange();assert.equal(context.scheduleAnchorDate,'2026-10-03','reopening allows another selection');
context.openScheduleDatePicker();node('#schedule-date-input').value='2026-12-12';node('#schedule-date-dialog').pointerdown({target:{closest:()=>true}});node('#schedule-date-input').onchange();assert.equal(context.scheduleAnchorDate,'2026-10-03','Cancel pointerdown guards blur/change before cancel click');node('#schedule-date-dialog').close();node('#schedule-date-input').onchange();assert.equal(context.scheduleAnchorDate,'2026-10-03','dismissed picker ignores late events');
context.openScheduleDatePicker();node('#schedule-date-input').value='';node('#schedule-date-input').onchange();assert.equal(node('#schedule-date-dialog').open,true);assert.equal(node('#schedule-date-error').hidden,false);node('#schedule-date-input').value='2026-09-30';node('#schedule-date-form').onsubmit({preventDefault(){}});assert.equal(context.scheduleAnchorDate,'2026-09-30','keyboard Enter fallback commits');assert.equal(node('#schedule-date-dialog').open,false);
context.scheduleWeekOffset=4;vm.runInContext(source.match(/^\$\('#schedule-today'\)\.onclick=.*$/m)[0],context);node('#schedule-today').onclick();assert.equal(context.scheduleAnchorDate,vm.runInContext('localDateIso()',context));assert.equal(context.scheduleWeekOffset,0);
const index=fs.readFileSync('index.html','utf8');assert.match(index,/id="schedule-pick-date" aria-haspopup="dialog"/);assert.match(index,/id="schedule-date-input" type="date" required/);assert.match(index,/id="schedule-show-office"[^>]*><span>Show office staff<\/span>/);
assert.ok(!index.includes('Go to date'));assert.ok(!source.includes("$('#schedule-date-input').oninput="));
console.log(`Schedule date picker auto-commit passed in ${process.env.TZ}: mode/date boundaries, invalid dates, cancel, native fallback and arrows (VM; visual QA pending).`);

context.scheduleView='week';
for(const [selected,start,end] of [['2026-10-04','2026-10-04','2026-10-10'],['2026-10-03','2026-09-27','2026-10-03'],['2026-10-05','2026-10-04','2026-10-10'],['2026-03-08','2026-03-08','2026-03-14'],['2026-11-01','2026-11-01','2026-11-07']]){context.chooseScheduleDate(selected);assert.equal(context.scheduleAnchorDate,selected);const days=context.schedulePeriodDays();assert.equal(days.length,7);assert.equal(days[0].date,start);assert.equal(days[6].date,end);assert.ok(days.some(day=>day.date===selected),'selected weekend remains visible')}
context.chooseScheduleDate('2026-10-04');context.shiftSchedulePeriod(-1);assert.equal(context.schedulePeriodDays()[0].date,'2026-09-27');context.shiftSchedulePeriod(1);assert.equal(context.schedulePeriodDays()[0].date,'2026-10-04');
context.currentUser={};context.$$=()=>[];context.canManageSchedule=()=>false;context.preferredLanguage='en';context.team=[{id:1,name:"Synthetic Person",initials:"SP",role:"Worker",crew:"QA"}];context.assignments=[];context.projects=[];context.reports=[];context.window={PDLScheduleAvailability:require('./schedule-availability'),PDLScheduleApprovedLabor:require('./schedule-approved-labor')};context.scheduleAvailability=[];context.scheduleAvailabilityStatus='ready';context.isOfficeMember=()=>false;context.formatDate=value=>value;context.escapeHtml=value=>String(value);context.displayTime=value=>value;
function fn(name){const lines=source.split('\n'),start=lines.findIndex(l=>l.startsWith('function '+name+'('));if(lines[start].trimEnd().endsWith('}'))return lines[start];const end=lines.findIndex((l,i)=>i>start&&l.trimEnd()==='}');return lines.slice(start,end+1).join('\n')}
for(const name of ['scheduleUnavailable','timeOffHoursLabel','scheduleLeaveRanges','scheduleLeaveConflict','scheduleLeaveMarkup','scheduleDayLeaveMarkup','scheduleUnavailableSummary','scheduleMobileMarkup'])vm.runInContext(fn(name),context);vm.runInContext(fn('renderSchedule'),context);context.renderSchedule();assert.match(node('#schedule-week-label').textContent,/October 4.*October 10, 2026/);assert.match(node('#schedule-board').innerHTML,/data-schedule-date="2026-10-04"/);assert.match(node('#schedule-board').innerHTML,/data-schedule-date="2026-10-10"/);
context.scheduleView='month';context.renderSchedule();assert.match(node('#schedule-board').innerHTML,/<span>SUN<\/span><span>MON<\/span>/);assert.equal((node('#schedule-board').innerHTML.match(/schedule-month-day outside/g)||[]).length,4,'October Thursday aligns after Sun-Wed');
context.scheduleView='day';context.renderSchedule();assert.match(node('#schedule-week-label').textContent,/Sunday, October 4, 2026/);node('#schedule-today').onclick();assert.equal(context.scheduleAnchorDate,vm.runInContext('localDateIso()',context));
console.log('Sunday schedule alignment passed: Oct4 Sunday, Oct3 Saturday, Oct5 Monday, DST, all-seven-day agenda/grid, Sunday month headers, selected-day label and Today/arrows.');
