'use strict';
// Scheduled-but-not-on-site action-center alerts (server-side rule).
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('server.js','utf8'),lines=source.split('\n');
function code(name){const start=lines.findIndex(l=>l.startsWith(`function ${name}(`)||l.startsWith(`async function ${name}(`));assert.ok(start>=0,name);if(lines[start].trimEnd().endsWith('}'))return lines[start];const end=lines.findIndex((l,i)=>i>start&&l.trim()==='}');return lines.slice(start,end+1).join('\n')}
const anchor=lines.findIndex(l=>l.startsWith('buildActionCenterBeforeScheduleNoShow=buildActionCenter;'));assert.ok(anchor>=0,'wrapper anchor');
const start=lines.findIndex((l,i)=>i>anchor&&l.startsWith('buildActionCenter=function'));assert.ok(start>anchor,'wrapper start');
const end=lines.findIndex((l,i)=>i>start&&l.trim()==='};');assert.ok(end>start,'wrapper end');
const wrapper=lines.slice(start,end+1).join('\n');
const scheduleAvailability=require('./schedule-availability.js');
const context={scheduleAvailability,buildActionCenterBeforeScheduleNoShow:()=>({items:[],counts:{urgent:0,high:0,medium:0,total:0}}),console};
vm.createContext(context);
vm.runInContext([code('companyDateIso'),code('companyTime24'),wrapper].join('\n'),context);
const alerts=(db,now)=>context.buildActionCenter(db,now).items.filter(item=>item.type==='scheduled_no_show');
const base={company:{id:'syn',timezone:'UTC'},team:[{id:7,name:'Chloe',crew:'A'},{id:8,name:'Andi',crew:'A'}],projects:[{id:101,name:'North Ridge'}],assignments:[{id:1,projectId:101,date:'2026-10-09',start:'13:00',end:'21:00',crew:'A',memberIds:[7,8]}],workdays:[],timeCards:[],timeOffRequests:[]};
const at=(time)=>new Date(`2026-10-09T${time}:00Z`);
let result=alerts(structuredClone(base),at('13:20'));
assert.equal(result.length,1,'20 minutes past a 13:00 start (default 15-minute grace) alerts');
assert.equal(result[0].severity,'high');assert.equal(result[0].id,'noshow-1');
assert.match(result[0].detail,/^A · North Ridge · scheduled 1:00 PM/);assert.match(result[0].detail,/Chloe, Andi/);assert.equal(result[0].projectId,101);
assert.equal(alerts(structuredClone(base),at('13:10')).length,0,'10 minutes late is inside the default grace');
result=alerts(structuredClone(base),at('14:05'));
assert.equal(result.length,1);assert.equal(result[0].severity,'urgent','an hour or more late escalates to urgent');
const wideGrace={...structuredClone(base),company:{id:'syn',timezone:'UTC',scheduleGraceMinutes:30}};
assert.equal(alerts(wideGrace,at('13:20')).length,0,'custom 30-minute grace respected');
assert.equal(alerts(wideGrace,at('13:40')).length,1);
const clampedGrace={...structuredClone(base),company:{id:'syn',timezone:'UTC',scheduleGraceMinutes:99999}};
assert.equal(alerts(clampedGrace,at('13:20')).length,0,'out-of-range grace is clamped, not fatal');
const onLeave={...structuredClone(base),timeOffRequests:[{memberId:7,status:'approved',startDate:'2026-10-09',endDate:'2026-10-09'}]};
result=alerts(onLeave,at('13:20'));
assert.equal(result.length,1,'a crew with one member on leave still alerts for the expected member');
assert.match(result[0].detail,/not clocked in: Andi$/);assert.doesNotMatch(result[0].detail,/Chloe, Andi/);
const allOnLeave={...structuredClone(base),timeOffRequests:[{memberId:7,status:'approved',startDate:'2026-10-09',endDate:'2026-10-09'},{memberId:8,status:'approved',startDate:'2026-10-09',endDate:'2026-10-09'}]};
assert.equal(alerts(allOnLeave,at('13:20')).length,0,'nobody expected means nobody flagged');
const partialDayLeave={...structuredClone(base),timeOffRequests:[{memberId:7,status:'approved',startDate:'2026-10-09',endDate:'2026-10-09',allDay:false,startTime:'16:00',endTime:'18:00'}]};
result=alerts(partialDayLeave,at('13:20'));
assert.equal(result.length,1,'partial-day leave outside the shift does not excuse the member');
const chloeClockedIn={...structuredClone(base),workdays:[{id:5,projectId:101,memberIds:[7],status:'active',startedAt:'2026-10-09T13:05:00Z'}]};
assert.equal(alerts(chloeClockedIn,at('13:20')).length,0,'one expected member on site suppresses the alert');
const chloeDone={...structuredClone(base),workdays:[{id:5,projectId:101,memberIds:[7],status:'complete',startedAt:'2026-10-09T13:00:00Z',endedAt:'2026-10-09T21:30:00Z'}]};
assert.equal(alerts(chloeDone,at('13:20')).length,0,'a completed workday today suppresses the alert');
const chloeCard={...structuredClone(base),timeCards:[{memberId:7,date:'2026-10-09',projectId:101}]};
assert.equal(alerts(chloeCard,at('13:20')).length,0,'a same-project time card today counts as presence');
const chloeOtherJob={...structuredClone(base),timeCards:[{memberId:7,date:'2026-10-09',projectId:999}]};
assert.equal(alerts(chloeOtherJob,at('13:20')).length,1,'a time card for a different job does not suppress the alert');
const wrongJobWorkday={...structuredClone(base),workdays:[{id:5,projectId:999,memberIds:[7],status:'active',startedAt:'2026-10-09T13:05:00Z'}]};
assert.equal(alerts(wrongJobWorkday,at('13:20')).length,1,'a workday on a different project does not suppress the alert');
const yesterday={...structuredClone(base),assignments:[{...base.assignments[0],date:'2026-10-08'}]};
assert.equal(alerts(yesterday,at('13:20')).length,0,'past assignments are not flagged');
const tomorrow={...structuredClone(base),assignments:[{...base.assignments[0],date:'2026-10-10'}]};
assert.equal(alerts(tomorrow,at('13:20')).length,0,'future assignments are not flagged');
const noStart={...structuredClone(base),assignments:[{...base.assignments[0],start:''}]};
assert.equal(alerts(noStart,at('13:20')).length,0,'assignments without a start time are skipped');
const db=structuredClone(base),before=JSON.stringify(db),full=context.buildActionCenter(db,at('13:20'));
assert.equal(full.items.filter(item=>item.type==='scheduled_no_show').length,1);
assert.ok(full.counts.high>=1,'counts include the new alert');
assert.equal(JSON.stringify(db),before,'alert derivation never alters the database');
console.log('Scheduled no-show alerts passed: grace default/custom/clamped, escalation, time-off exclusion (all-day, partial, all-excused), workday/time-card presence, wrong-project suppression, date window, counts, no mutation (synthetic VM).');

// API round-trip: the grace setting persists through the company PATCH whitelist,
// survives saves that do not mention it, and clamps out-of-range values.
const os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const apiRoot=fs.mkdtempSync(path.join(os.tmpdir(),'pdl-noshow-api-')),apiCompany='aabbccdd-aabb-4a4a-8a8a-aabbccddeeff',apiToken='synthetic-noshow-session';
const apiDb={company:{id:apiCompany,name:'Synthetic no-show',demo:true,timezone:'UTC'},projects:[],team:[],assignments:[],reports:[],photos:[],workdays:[],timeCards:[],users:[{id:1,name:'Synthetic owner',role:'owner',status:'Active',companyId:apiCompany}],sessions:[{companyId:apiCompany,userId:1,tokenHash:crypto.createHash('sha256').update(apiToken).digest('hex'),expiresAt:'2099-01-01'}],customers:[],changes:[],catalog:[]};
const apiFile=path.join(apiRoot,'db.json');fs.writeFileSync(apiFile,JSON.stringify(apiDb));fs.writeFileSync(path.join(apiRoot,'platform.json'),JSON.stringify({users:[],sessions:[]}));
Object.assign(process.env,{PDL_DB_FILE:apiFile,PDL_PLATFORM_FILE:path.join(apiRoot,'platform.json'),PDL_REQUIRE_AUTH:'1',PDL_SUPABASE_ENABLED:'0',PDL_TRANSACTIONAL_DB:'off',PDL_EMAIL_DEV_MODE:'1'});for(const name of ['OPENAI_API_KEY','SENTRY_DSN','RESEND_API_KEY','STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET'])delete process.env[name];
require('./database/supabase').loadLocalEnv=()=>{};
const {server}=require('./server');
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;
const call=(method,route,input)=>fetch(base+route,{method,signal:AbortSignal.timeout(10000),headers:{Authorization:'Bearer '+apiToken,'Content-Type':'application/json','x-pdl-company':apiCompany},...(input?{body:JSON.stringify(input)}:{})}).then(async response=>({status:response.status,data:await response.json()}));
try{
  const settings={name:'Synthetic no-show',timezone:'UTC',trade:'',email:'',phone:'',weekStart:'monday',overtimeRule:'weekly40',pricingAccess:{enabled:false,officeMode:'all',userIds:[]}};
  let saved=await call('PATCH','/api/company',{...settings,scheduleGraceMinutes:30});assert.equal(saved.status,200);
  let state=await call('GET','/api/state');assert.equal(state.data.company.scheduleGraceMinutes,30,'grace setting persists through company PATCH');
  saved=await call('PATCH','/api/company',{...settings,name:'Synthetic no-show renamed'});assert.equal(saved.status,200);
  state=await call('GET','/api/state');assert.equal(state.data.company.scheduleGraceMinutes,30,'saves that do not mention the setting preserve it');
  saved=await call('PATCH','/api/company',{...settings,scheduleGraceMinutes:99999});assert.equal(saved.status,200);
  state=await call('GET','/api/state');assert.equal(state.data.company.scheduleGraceMinutes,120,'out-of-range values clamp to 120');
  console.log('Grace setting API round-trip passed: persist, preserve-on-unrelated-save, clamp.');
}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));fs.rmSync(apiRoot,{recursive:true,force:true})}})().catch(error=>{console.error(error);process.exitCode=1;server.close()});
