const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const zlib = require('node:zlib');
const { AsyncLocalStorage } = require('node:async_hooks');
const supabase = require('./database/supabase');
const { stableUuid } = require('./database/migrate-json');

const ROOT = __dirname;
supabase.loadLocalEnv(ROOT);
const DB_FILE = process.env.PDL_DB_FILE || path.join(ROOT, 'data', 'db.json');
const PLATFORM_FILE = process.env.PDL_PLATFORM_FILE || path.join(path.dirname(DB_FILE),'platform.json');
const PORT = Number(process.env.PORT || 4173);
const MIME = {'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.pdf':'application/pdf','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp'};

const dbContext=new AsyncLocalStorage();
function activeDbFile(){return dbContext.getStore()?.file||DB_FILE}
function readDb(){ return JSON.parse(fs.readFileSync(activeDbFile(), 'utf8')); }
function writeDb(db){ const file=activeDbFile(),tmp=file+'.tmp'; fs.writeFileSync(tmp, JSON.stringify(db,null,2)); fs.renameSync(tmp,file); }
function requestDbFile(req){const companyId=String(req.headers['x-pdl-company']||'').trim();if(!companyId)return DB_FILE;const primary=JSON.parse(fs.readFileSync(DB_FILE,'utf8'));if(companyId===String(primary.company.id))return DB_FILE;if(!/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(companyId))return null;const file=path.join(path.dirname(DB_FILE),'tenants',`${companyId}.json`);return fs.existsSync(file)?file:null}
function readPlatform(){return fs.existsSync(PLATFORM_FILE)?JSON.parse(fs.readFileSync(PLATFORM_FILE,'utf8')):{users:[],notes:[]}}
function writePlatform(data){const tmp=PLATFORM_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(data,null,2));fs.renameSync(tmp,PLATFORM_FILE)}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
function body(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>30_000_000)reject(new Error('Request too large'));});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch(e){reject(e)}});req.on('error',reject);});}
function nextId(rows){return rows.reduce((max,row)=>Math.max(max,Number(row.id)||0),0)+1}
function tenantUuid(db){return /^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(String(db.company.id))?db.company.id:stableUuid('company',db.company.id)}
async function saveAsset(db,bucket,filename,bytes,contentType,localDirectory='uploads'){
  if(supabase.configured())return supabase.upload(bucket,`${tenantUuid(db)}/${Date.now()}-${crypto.randomUUID()}-${filename.replace(/[^a-zA-Z0-9._-]/g,'_')}`,bytes,contentType);
  const directory=path.join(ROOT,localDirectory);fs.mkdirSync(directory,{recursive:true});const localName=`${Date.now()}-${crypto.randomUUID()}-${filename.replace(/[^a-zA-Z0-9._-]/g,'_')}`;fs.writeFileSync(path.join(directory,localName),bytes);return{bucket:null,objectKey:null,url:`/${localDirectory.replaceAll('\\','/')}/${localName}`};
}
function credentialHash(value,salt=crypto.randomBytes(16).toString('hex')){return{salt,hash:crypto.scryptSync(value,salt,64).toString('hex')}}
function pdfText(buffer){const source=buffer.toString('latin1'),chunks=[];for(const match of source.matchAll(/stream\r?\n([\s\S]*?)\r?\nendstream/g)){let bytes=Buffer.from(match[1],'latin1');try{bytes=zlib.inflateSync(bytes)}catch{}const text=bytes.toString('latin1');for(const literal of text.matchAll(/\(([^()]*(?:\\.[^()]*)*)\)\s*Tj/g))chunks.push(literal[1].replace(/\\([()\\])/g,'$1'));for(const array of text.matchAll(/\[([\s\S]*?)\]\s*TJ/g))for(const literal of array[1].matchAll(/\(([^()]*)\)/g))chunks.push(literal[1])}return chunks.join(' ').replace(/\s+/g,' ').trim()}
function estimateDraft(text){const units='EA|SF|LF|CY|SY|TON|HR|DAY|LS',lines=[];for(const match of text.matchAll(new RegExp(`([A-Za-z][A-Za-z0-9 ,/&().'-]{3,80}?)\\s+(\\d+(?:,\\d{3})*(?:\\.\\d+)?)\\s+(${units})\\s+(?:\\$?([\\d,]+(?:\\.\\d{2})?))?`,'gi'))){const quantity=Number(match[2].replaceAll(',','')),amount=match[4]?Number(match[4].replaceAll(',','')):null;lines.push({description:match[1].trim(),quantity,unit:match[3].toUpperCase(),amount,confidence:amount==null?'medium':'high'})}const totals=[...text.matchAll(/(?:total|estimate total)\s*\$?([\d,]+(?:\.\d{2})?)/gi)],documentTotal=totals.length?Number(totals.at(-1)[1].replaceAll(',','')):null,lineTotal=lines.reduce((sum,line)=>sum+(line.amount||0),0);return{lines,documentTotal,lineTotal,reconciled:documentTotal!=null&&Math.abs(documentTotal-lineTotal)<.01,requiresOcr:text.length<40}}
function catalogWords(value){return new Set(String(value||'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(word=>word.length>2).map(word=>word.endsWith('s')?word.slice(0,-1):word))}
function catalogSuggestions(line,catalog){const words=catalogWords(line.description);return (catalog||[]).map(item=>{const itemWords=catalogWords(`${item.name} ${item.description||''}`),shared=[...words].filter(word=>itemWords.has(word)).length,union=new Set([...words,...itemWords]).size,textScore=union?shared/union:0,unitMatch=String(item.unit).toUpperCase()===String(line.unit).toUpperCase(),score=Math.min(1,textScore+(unitMatch?.25:0));return{id:item.id,name:item.name,unit:item.unit,score:Math.round(score*100)}}).filter(item=>item.score>=35).sort((a,b)=>b.score-a.score).slice(0,3)}
function enrichEstimateDraft(draft,catalog){return{...draft,lines:draft.lines.map(line=>({...line,catalogSuggestions:catalogSuggestions(line,catalog)}))}}
async function aiEstimateDraft(bytes,filename){
  if(!process.env.OPENAI_API_KEY)throw new Error('AI OCR is not configured');
  const line={type:'object',additionalProperties:false,properties:{description:{type:'string'},quantity:{type:'number'},unit:{type:'string'},amount:{type:'number'},confidence:{type:'string',enum:['high','medium','low']}},required:['description','quantity','unit','amount','confidence']};
  const schema={type:'object',additionalProperties:false,properties:{estimateNumber:{type:'string'},documentTotal:{type:'number'},lines:{type:'array',items:line}},required:['estimateNumber','documentTotal','lines']};
  const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.4-mini',store:false,instructions:'Extract construction estimate line items from the attached PDF. Read scanned pages visually when needed. Never invent a line, quantity, unit, amount, estimate number, or total. Use an empty string or zero when absent. Amount means the line total, not unit price.',input:[{role:'user',content:[{type:'input_file',filename,file_data:`data:application/pdf;base64,${bytes.toString('base64')}`},{type:'input_text',text:'Extract this estimate for an office user to review before import.'}]}],text:{format:{type:'json_schema',name:'estimate_import',strict:true,schema}}})});
  if(!response.ok)throw new Error(`AI OCR service returned ${response.status}`);const data=await response.json(),output=data.output?.flatMap(item=>item.content||[]).find(item=>item.type==='output_text')?.text;if(!output)throw new Error('AI OCR service returned no structured output');const parsed=JSON.parse(output),lines=(parsed.lines||[]).filter(item=>item.description&&item.quantity>0).map(item=>({...item,unit:String(item.unit||'EA').toUpperCase(),amount:Number(item.amount)||0})),lineTotal=lines.reduce((sum,item)=>sum+item.amount,0),documentTotal=Number(parsed.documentTotal)||null;return{lines,documentTotal,lineTotal,reconciled:documentTotal!=null&&Math.abs(documentTotal-lineTotal)<.01,requiresOcr:false,estimateNumber:parsed.estimateNumber||null,extractionMethod:'ai_ocr'}
}
function verifyCredential(value,salt,expected){if(!value||!salt||!expected)return false;const actual=crypto.scryptSync(value,salt,64),stored=Buffer.from(expected,'hex');return actual.length===stored.length&&crypto.timingSafeEqual(actual,stored)}
function bearer(req){const header=String(req.headers.authorization||'');return header.startsWith('Bearer ')?header.slice(7):null}
function platformAllowed(req){if(process.env.PDL_REQUIRE_AUTH!=='1')return true;const supplied=String(req.headers['x-pdl-platform-key']||''),expected=String(process.env.PDL_PLATFORM_KEY||'');if(expected.length>=32&&supplied.length===expected.length&&crypto.timingSafeEqual(Buffer.from(supplied),Buffer.from(expected)))return true;const cookieToken=String(req.headers.cookie||'').split(';').map(value=>value.trim()).find(value=>value.startsWith('pdl_platform='))?.slice(13),platform=readPlatform(),token=bearer(req)||cookieToken,tokenHash=token&&crypto.createHash('sha256').update(token).digest('hex'),session=(platform.sessions||[]).find(row=>row.tokenHash===tokenHash&&new Date(row.expiresAt)>new Date()),user=session&&(platform.users||[]).find(row=>row.id===session.userId&&row.status==='Active');if(session&&user){req.platformAuth={session,user};return true}return false}

function localExtract(notes){
  const workers=notes.match(/(\d+)\s*(?:person|people|worker|workers|man|men|person crew)/i);
  const hours=notes.match(/(\d+(?:\.\d+)?)\s*(?:labor\s*)?(?:hour|hours|hrs|hr)\b/i);
  const qty=notes.match(/(?:poured|set|installed|placed|framed|completed|excavated)?\s*(\d+(?:\.\d+)?)\s*(yards?|yds?|cy|panels?|feet|ft|tons?|units?|squares?)/i);
  const productions=[...notes.matchAll(/(?:poured|set|installed|placed|framed|completed|excavated|stripped)?\s*(\d+(?:\.\d+)?)\s*(yards?|yds?|cy|panels?|feet|ft|tons?|units?|squares?|sf|lf|ea)\b/gi)].map(match=>({description:(match[0].replace(/^\s*\d[\s\S]*$/,'')||'Reported field production').trim(),quantity:Number(match[1]),unit:match[2].toUpperCase()}));
  const delay=notes.match(/([^.!]*(?:delay|late|waiting|held up|rfi|breakdown|rain)[^.!]*[.!]?)/i);
  const next=notes.match(/(?:tomorrow|next)[:\s,-]*([^.!]+)/i);
  const labor=workers||hours?[workers?`${workers[1]} people`:'',hours?`${hours[1]} hours`:''].filter(Boolean).join(' · '):'';
  return {summary:notes?`Field work recorded: ${notes.slice(0,180)}${notes.length>180?'…':''}`:'',labor,quantity:qty?`${qty[1]} ${qty[2]}`:'',productions,materials:'',equipment:'',delays:delay?delay[1].trim():'',safety:'',issue:delay?delay[1].trim():'',next:next?next[1].trim():'',originalLanguage:'en',englishTranslation:notes,source:'local'};
}

async function aiExtract(notes,preferredLanguage='auto'){
  if(!process.env.OPENAI_API_KEY){const local=localExtract(notes),spanish=String(preferredLanguage).startsWith('es');return{...local,originalLanguage:spanish?'es':'en',englishTranslation:spanish?'Translation unavailable until AI is configured':notes,source:'local'}}
  const schema={type:'object',additionalProperties:false,properties:{originalLanguage:{type:'string'},englishTranslation:{type:'string'},summary:{type:'string'},labor:{type:'string'},quantity:{type:'string'},productions:{type:'array',items:{type:'object',additionalProperties:false,properties:{description:{type:'string'},quantity:{type:'number'},unit:{type:'string'},laborHours:{type:'number'}},required:['description','quantity','unit','laborHours']}},materials:{type:'string'},equipment:{type:'string'},delays:{type:'string'},safety:{type:'string'},issue:{type:'string'},next:{type:'string'}},required:['originalLanguage','englishTranslation','summary','labor','quantity','productions','materials','equipment','delays','safety','issue','next']};
  const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.4-mini',store:false,instructions:`The note language preference is ${preferredLanguage}. Detect the actual language, preserve meaning, translate the complete note into clear English, and convert it into concise office-ready construction facts. Never invent numbers. Use Needs confirmation when absent. All structured office fields must be English.`,input:notes,text:{format:{type:'json_schema',name:'daily_report',strict:true,schema}}})});
  if(!response.ok) throw new Error(`AI service returned ${response.status}`);
  const data=await response.json();
  const output=data.output?.flatMap(item=>item.content||[]).find(item=>item.type==='output_text')?.text;
  if(!output) throw new Error('AI service returned no structured output');
  return {...JSON.parse(output),source:'openai'};
}

async function api(req,res,url){
  if(req.method==='GET'&&url.pathname==='/api/health'){const cloud=await supabase.health();return json(res,cloud.configured&&!cloud.reachable?503:200,{ok:!cloud.configured||cloud.reachable,ai:Boolean(process.env.OPENAI_API_KEY),cloud,time:new Date().toISOString()})}
  if(url.pathname.startsWith('/api/platform/')&&!url.pathname.startsWith('/api/platform/auth/')&&!platformAllowed(req))return json(res,401,{error:'Platform authentication required'});
  if(req.method==='POST'&&url.pathname==='/api/platform/auth/bootstrap'){const platform=readPlatform(),owner=(platform.users||[]).find(user=>user.role==='platform_owner'&&user.status==='Active');if(!owner||owner.passwordHash||owner.setupHash)return json(res,409,{error:'Platform Owner setup has already been initialized'});if(process.env.PDL_REQUIRE_AUTH==='1'&&!platformAllowed(req))return json(res,401,{error:'Platform bootstrap authorization required'});const setupCode=crypto.randomBytes(8).toString('base64url'),credential=credentialHash(setupCode);owner.setupHash=credential.hash;owner.setupSalt=credential.salt;owner.setupExpiresAt=new Date(Date.now()+30*60000).toISOString();owner.mustSetPassword=true;writePlatform(platform);return json(res,200,{email:owner.email,setupCode,expiresAt:owner.setupExpiresAt})}
  if(req.method==='POST'&&url.pathname==='/api/platform/auth/claim'){const input=await body(req),platform=readPlatform(),user=(platform.users||[]).find(row=>row.email.toLowerCase()===String(input.email||'').toLowerCase()&&row.status==='Active');if(!user||!user.setupHash||new Date(user.setupExpiresAt)<new Date()||!verifyCredential(input.setupCode,user.setupSalt,user.setupHash))return json(res,401,{error:'Invalid or expired platform setup code'});if(String(input.password||'').length<12)return json(res,400,{error:'Platform password must be at least 12 characters'});const credential=credentialHash(input.password);user.passwordHash=credential.hash;user.passwordSalt=credential.salt;user.mustSetPassword=false;delete user.setupHash;delete user.setupSalt;delete user.setupExpiresAt;writePlatform(platform);return json(res,200,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/platform/auth/login'){const input=await body(req),platform=readPlatform(),user=(platform.users||[]).find(row=>row.email.toLowerCase()===String(input.email||'').toLowerCase()&&row.status==='Active');if(!user||user.mustSetPassword||!verifyCredential(input.password,user.passwordSalt,user.passwordHash))return json(res,401,{error:'Invalid platform email or password'});const token=crypto.randomBytes(32).toString('base64url');platform.sessions ||= [];platform.sessions.push({id:crypto.randomUUID(),userId:user.id,tokenHash:crypto.createHash('sha256').update(token).digest('hex'),createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+8*3600000).toISOString()});writePlatform(platform);res.writeHead(200,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Set-Cookie':`pdl_platform=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${process.env.NODE_ENV==='production'?'; Secure':''}`});return res.end(JSON.stringify({token,expiresIn:28800,user:{id:user.id,name:user.name,email:user.email,role:user.role}}))}
  if(req.method==='GET'&&url.pathname==='/api/platform/auth/me'){if(!platformAllowed(req))return json(res,401,{error:'Platform authentication required'});return json(res,200,{id:req.platformAuth?.user.id||null,name:req.platformAuth?.user.name||'Platform key',email:req.platformAuth?.user.email||null,role:req.platformAuth?.user.role||'platform_owner'})}
  if(req.method==='POST'&&url.pathname==='/api/platform/auth/logout'){const platform=readPlatform(),token=bearer(req),tokenHash=token&&crypto.createHash('sha256').update(token).digest('hex');platform.sessions=(platform.sessions||[]).filter(row=>row.tokenHash!==tokenHash);writePlatform(platform);return json(res,200,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/signup'){const input=await body(req),plans={starter:{price:79,maxUsers:10,maxProjects:5},growth:{price:179,maxUsers:30,maxProjects:25},pro:{price:349,maxUsers:75,maxProjects:null}},employeeCount=Math.max(1,Number(input.employeeCount)||1),projectCount=Math.max(1,Number(input.projectCount)||1),recommended=employeeCount<=10&&projectCount<=5?'starter':employeeCount<=30&&projectCount<=25?'growth':'pro',plan=plans[input.plan]?input.plan:recommended;if(!input.companyName?.trim()||!input.ownerName?.trim()||!/^\S+@\S+\.\S+$/.test(String(input.email||'')))return json(res,400,{error:'Company name, owner name, and valid email are required'});const tenantId=crypto.randomUUID(),setupCode=crypto.randomBytes(6).toString('base64url'),credential=credentialHash(setupCode),now=new Date().toISOString(),tenant={company:{id:tenantId,name:input.companyName.trim(),trade:String(input.trade||'General contractor').trim(),plan,planPrice:plans[plan].price,trialEndsAt:new Date(Date.now()+14*86400000).toISOString(),onboarding:{employeeCount,projectCount,completedSteps:['company','plan'],recommendedPlan:recommended},createdAt:now},users:[{id:1,companyId:tenantId,name:input.ownerName.trim(),email:input.email.trim().toLowerCase(),role:'owner',status:'Active',projectIds:[],memberId:null,mustSetPassword:true,setupHash:credential.hash,setupSalt:credential.salt,setupExpiresAt:new Date(Date.now()+72*3600000).toISOString(),createdAt:now}],customers:[],projects:[],team:[],subcontractors:[],assignments:[],reports:[],photos:[],workdays:[],changes:[],subcontractorLinks:[],catalog:[],sessions:[]},tenantDir=path.join(path.dirname(DB_FILE),'tenants');fs.mkdirSync(tenantDir,{recursive:true});fs.writeFileSync(path.join(tenantDir,`${tenantId}.json`),JSON.stringify(tenant,null,2),{flag:'wx'});return json(res,201,{company:{id:tenantId,name:tenant.company.name,plan,trialEndsAt:tenant.company.trialEndsAt},owner:{name:input.ownerName.trim(),email:input.email.trim().toLowerCase()},setupCode,recommendedPlan:recommended,next:'/signup.html?complete=1'})}
  if(req.method==='GET'&&url.pathname==='/api/platform/overview'){const platform=readPlatform(),primary=readDb(),tenantDir=path.join(path.dirname(DB_FILE),'tenants'),tenantFiles=fs.existsSync(tenantDir)?fs.readdirSync(tenantDir).filter(file=>file.endsWith('.json')):[],tenants=[primary,...tenantFiles.map(file=>JSON.parse(fs.readFileSync(path.join(tenantDir,file),'utf8')))];const companies=tenants.map(tenant=>({id:tenant.company.id,name:tenant.company.name,trade:tenant.company.trade||'',plan:tenant.company.plan||'pilot',planPrice:Number(tenant.company.planPrice)||0,trialEndsAt:tenant.company.trialEndsAt||null,users:(tenant.users||[]).length,projects:(tenant.projects||[]).length,onboarding:tenant.company.onboarding||null,createdAt:tenant.company.createdAt||null}));return json(res,200,{companies,staff:(platform.users||[]).map(({setupHash,setupSalt,...user})=>user),metrics:{companies:companies.length,trials:companies.filter(row=>row.trialEndsAt&&new Date(row.trialEndsAt)>new Date()).length,monthlyRecurringRevenue:companies.reduce((sum,row)=>sum+row.planPrice,0),users:companies.reduce((sum,row)=>sum+row.users,0)}})}
  if(req.method==='POST'&&url.pathname==='/api/platform/users'){const input=await body(req),roles=['platform_owner','customer_success','onboarding','support','billing','engineering'],platform=readPlatform();platform.users ||= [];if(!input.name?.trim()||!/^\S+@\S+\.\S+$/.test(String(input.email||''))||!roles.includes(input.role))return json(res,400,{error:'Name, valid email, and platform role are required'});if(platform.users.some(user=>user.email.toLowerCase()===input.email.toLowerCase()))return json(res,409,{error:'Platform user already exists'});const setupCode=crypto.randomBytes(6).toString('base64url'),credential=credentialHash(setupCode),row={id:nextId(platform.users),name:input.name.trim(),email:input.email.trim().toLowerCase(),role:input.role,status:'Active',setupHash:credential.hash,setupSalt:credential.salt,setupExpiresAt:new Date(Date.now()+72*3600000).toISOString(),createdAt:new Date().toISOString()};platform.users.push(row);writePlatform(platform);const{setupHash,setupSalt,...safe}=row;return json(res,201,{...safe,setupCode})}
  if(req.method==='POST'&&url.pathname==='/api/platform/support-access'){const input=await body(req),platform=readPlatform(),primary=readDb(),tenantDir=path.join(path.dirname(DB_FILE),'tenants'),tenantFiles=fs.existsSync(tenantDir)?fs.readdirSync(tenantDir).filter(file=>file.endsWith('.json')):[],tenants=[primary,...tenantFiles.map(file=>JSON.parse(fs.readFileSync(path.join(tenantDir,file),'utf8')))],tenant=tenants.find(row=>row.company.id===input.companyId),actor=(platform.users||[]).find(row=>row.id===Number(input.actorUserId)&&row.status==='Active'),reason=String(input.reason||'').trim(),minutes=Math.min(120,Math.max(15,Number(input.minutes)||30));if(!tenant||!actor||!reason)return json(res,400,{error:'Company, active platform user, and support reason are required'});const token=crypto.randomBytes(32).toString('base64url'),now=new Date().toISOString(),grant={id:crypto.randomUUID(),companyId:tenant.company.id,companyName:tenant.company.name,actorUserId:actor.id,actorName:actor.name,reason,status:'Active',tokenHash:crypto.createHash('sha256').update(token).digest('hex'),createdAt:now,expiresAt:new Date(Date.now()+minutes*60000).toISOString()};platform.supportGrants ||= [];platform.auditEvents ||= [];platform.supportGrants.push(grant);platform.auditEvents.push({id:crypto.randomUUID(),action:'support_access_granted',companyId:grant.companyId,actorUserId:actor.id,actorName:actor.name,reason,at:now,grantId:grant.id});writePlatform(platform);return json(res,201,{id:grant.id,companyId:grant.companyId,companyName:grant.companyName,actorName:grant.actorName,reason:grant.reason,expiresAt:grant.expiresAt,url:`/support.html?token=${token}`})}
  const revokeSupport=url.pathname.match(/^\/api\/platform\/support-access\/([a-f0-9-]+)$/);if(req.method==='DELETE'&&revokeSupport){const platform=readPlatform(),grant=(platform.supportGrants||[]).find(row=>row.id===revokeSupport[1]);if(!grant)return json(res,404,{error:'Support grant not found'});grant.status='Revoked';grant.revokedAt=new Date().toISOString();platform.auditEvents ||= [];platform.auditEvents.push({id:crypto.randomUUID(),action:'support_access_revoked',companyId:grant.companyId,actorUserId:grant.actorUserId,actorName:grant.actorName,reason:grant.reason,at:grant.revokedAt,grantId:grant.id});writePlatform(platform);return json(res,200,{ok:true})}
  if(req.method==='GET'&&url.pathname==='/api/platform/audit'){const platform=readPlatform();return json(res,200,(platform.auditEvents||[]).slice().reverse())}
  const supportSession=url.pathname.match(/^\/api\/support-session\/([A-Za-z0-9_-]{43})$/);if(req.method==='GET'&&supportSession){const platform=readPlatform(),tokenHash=crypto.createHash('sha256').update(supportSession[1]).digest('hex'),grant=(platform.supportGrants||[]).find(row=>row.tokenHash===tokenHash&&row.status==='Active'&&new Date(row.expiresAt)>new Date());if(!grant)return json(res,404,{error:'Support session is invalid or expired'});const primary=readDb(),tenantDir=path.join(path.dirname(DB_FILE),'tenants'),file=grant.companyId===primary.company.id?null:path.join(tenantDir,`${grant.companyId}.json`),tenant=file&&fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):primary;if(tenant.company.id!==grant.companyId)return json(res,404,{error:'Support session is invalid or expired'});platform.auditEvents ||= [];platform.auditEvents.push({id:crypto.randomUUID(),action:'support_session_viewed',companyId:grant.companyId,actorUserId:grant.actorUserId,actorName:grant.actorName,reason:grant.reason,at:new Date().toISOString(),grantId:grant.id});writePlatform(platform);return json(res,200,{banner:{companyName:tenant.company.name,actorName:grant.actorName,reason:grant.reason,expiresAt:grant.expiresAt},summary:{projects:(tenant.projects||[]).length,users:(tenant.users||[]).length,reports:(tenant.reports||[]).length,plan:tenant.company.plan||'pilot',onboarding:tenant.company.onboarding||null}})}
  if(req.method==='POST'&&url.pathname==='/api/auth/claim'){const input=await body(req),db=readDb(),user=(db.users||[]).find(row=>row.email.toLowerCase()===String(input.email||'').toLowerCase()&&row.status==='Active');if(!user||!user.mustSetPassword||new Date(user.setupExpiresAt)<new Date()||!verifyCredential(input.setupCode,user.setupSalt,user.setupHash))return json(res,401,{error:'Invalid or expired setup code'});if(String(input.password||'').length<10)return json(res,400,{error:'Password must be at least 10 characters'});const credential=credentialHash(input.password);user.passwordHash=credential.hash;user.passwordSalt=credential.salt;user.mustSetPassword=false;delete user.setupHash;delete user.setupSalt;delete user.setupExpiresAt;writeDb(db);return json(res,200,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/auth/login'){const input=await body(req),db=readDb(),user=(db.users||[]).find(row=>row.email.toLowerCase()===String(input.email||'').toLowerCase()&&row.status==='Active');if(!user||user.mustSetPassword||!verifyCredential(input.password,user.passwordSalt,user.passwordHash))return json(res,401,{error:'Invalid email or password'});const token=crypto.randomBytes(32).toString('base64url'),tokenHash=crypto.createHash('sha256').update(token).digest('hex');db.sessions ||= [];db.sessions.push({id:crypto.randomUUID(),tokenHash,userId:user.id,companyId:user.companyId||db.company.id,createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+12*3600000).toISOString()});writeDb(db);return json(res,200,{token,expiresIn:43200,user:{id:user.id,name:user.name,email:user.email,role:user.role,companyId:user.companyId||db.company.id}})}
  if(req.method==='GET'&&url.pathname==='/api/auth/me'){const db=readDb(),token=bearer(req),tokenHash=token&&crypto.createHash('sha256').update(token).digest('hex'),session=(db.sessions||[]).find(row=>row.tokenHash===tokenHash&&new Date(row.expiresAt)>new Date()),user=session&&(db.users||[]).find(row=>row.id===session.userId&&row.status==='Active');if(!session||!user)return json(res,401,{error:'Authentication required'});return json(res,200,{id:user.id,name:user.name,email:user.email,role:user.role,companyId:session.companyId,projectIds:user.projectIds||[],memberId:user.memberId||null})}
  if(req.method==='POST'&&url.pathname==='/api/auth/logout'){const db=readDb(),token=bearer(req),tokenHash=token&&crypto.createHash('sha256').update(token).digest('hex');db.sessions=(db.sessions||[]).filter(row=>row.tokenHash!==tokenHash);writeDb(db);return json(res,200,{ok:true})}
  if(process.env.PDL_REQUIRE_AUTH==='1'&&!url.pathname.startsWith('/api/guest/')){const db=readDb(),token=bearer(req),tokenHash=token&&crypto.createHash('sha256').update(token).digest('hex'),session=(db.sessions||[]).find(row=>row.tokenHash===tokenHash&&new Date(row.expiresAt)>new Date()),user=session&&(db.users||[]).find(row=>row.id===session.userId&&row.status==='Active');if(!session||!user)return json(res,401,{error:'Authentication required'});if(session.companyId!==db.company.id)return json(res,404,{error:'Resource not found'});req.auth={session,user,companyId:session.companyId};const ownerRoute=url.pathname==='/api/users'||/^\/api\/users\//.test(url.pathname);if(ownerRoute&&user.role!=='owner')return json(res,403,{error:'Account owner permission required'});const officeRoute=['/api/production','/api/exceptions','/api/action-center','/api/changes','/api/catalog','/api/estimate-imports'].some(route=>url.pathname.startsWith(route))||url.pathname.includes('/approve')||url.pathname.includes('/disposition');if(officeRoute&&!['owner','admin','project_manager'].includes(user.role))return json(res,403,{error:'Office permission required'})}
  const cloudFile=url.pathname.match(/^\/api\/files\/(project-photos|estimate-documents)\/(.+)$/);if(req.method==='GET'&&cloudFile){if(!supabase.configured())return json(res,404,{error:'File not found'});const objectKey=cloudFile[2].split('/').map(decodeURIComponent).join('/'),db=readDb();if(!objectKey.startsWith(`${tenantUuid(db)}/`))return json(res,404,{error:'File not found'});const response=await supabase.download(cloudFile[1],objectKey);const bytes=Buffer.from(await response.arrayBuffer());res.writeHead(200,{'Content-Type':response.headers.get('content-type')||'application/octet-stream','Cache-Control':'private, max-age=300','Content-Length':bytes.length});return res.end(bytes)}
  if(req.method==='GET'&&url.pathname==='/api/production'){const db=readDb(),approved=db.reports.filter(r=>r.status==='Approved'),projects=db.projects.map((project,projectIndex)=>({projectId:project.id,items:(project.estimateItems||[]).map(item=>{const entries=approved.filter(r=>r.project===projectIndex).flatMap(r=>(r.productionEntries||[]).filter(entry=>entry.estimateItemId===item.id).map(entry=>({entry,report:r}))),actualQuantity=entries.reduce((sum,x)=>sum+Number(x.entry.quantity||0),0),actualLaborHours=entries.reduce((sum,x)=>{if(Number(x.entry.laborHours)>0)return sum+Number(x.entry.laborHours);const reportTotal=(x.report.laborEntries||[]).reduce((total,labor)=>total+Number(labor.hours||0),0);return sum+((x.report.productionEntries||[]).length===1?reportTotal:0)},0);return{estimateItemId:item.id,name:item.name,unit:item.unit,plannedQuantity:Number(item.plannedQuantity)||0,budgetHours:Number(item.budgetHours)||0,actualQuantity,actualLaborHours,quantityPercent:item.plannedQuantity?actualQuantity/Number(item.plannedQuantity)*100:0,laborPercent:item.budgetHours?actualLaborHours/Number(item.budgetHours)*100:0}})}));return json(res,200,{projects,approvedReports:approved.length})}
  if(req.method==='GET'&&url.pathname==='/api/exceptions'){const db=readDb(),items=db.reports.flatMap(report=>(report.flags||[]).filter(flag=>!flag.resolution).map(flag=>({reportId:report.id,projectId:db.projects[report.project]?.id,date:report.date,foreman:report.foreman,status:report.status,...flag})));return json(res,200,items)}
  if(req.method==='GET'&&url.pathname==='/api/action-center'){const db=readDb(),items=[],now=new Date(),today=now.toISOString().slice(0,10);for(const report of db.reports){const project=db.projects[report.project];if(report.status==='Needs review')items.push({id:`review-${report.id}`,type:'approval',severity:'high',title:'Daily report awaiting approval',detail:`${project?.name||'Project'} · ${report.foreman} · ${report.date}`,reportId:report.id,projectId:project?.id});for(const flag of report.flags||[])if(!flag.resolution)items.push({id:`exception-${report.id}`,type:'exception',severity:'urgent',title:'Unplanned work needs a decision',detail:`${project?.name||'Project'} · ${flag.message}`,reportId:report.id,projectId:project?.id})}for(const assignment of db.assignments||[]){if(assignment.date>today)continue;const projectIndex=db.projects.findIndex(project=>project.id===assignment.projectId),hasReport=db.reports.some(report=>report.project===projectIndex&&report.dateIso===assignment.date);if(!hasReport)items.push({id:`missing-${assignment.id}`,type:'missing_daily',severity:assignment.date<today?'urgent':'high',title:'Scheduled work has no daily',detail:`${db.projects[projectIndex]?.name||'Project'} · ${assignment.date} · ${assignment.activity}`,projectId:assignment.projectId})}for(const subcontractor of db.subcontractors||[]){if(!subcontractor.insuranceExpiration)continue;const days=Math.ceil((new Date(`${subcontractor.insuranceExpiration}T23:59:59`)-now)/86400000);if(days<=30)items.push({id:`insurance-${subcontractor.id}`,type:'insurance',severity:days<0?'urgent':'medium',title:days<0?'Subcontractor insurance expired':'Subcontractor insurance expiring',detail:`${subcontractor.name} · ${days<0?`${Math.abs(days)} days overdue`:`${days} days remaining`}`,subcontractorId:subcontractor.id})}for(const project of db.projects)if(project.status==='At risk'||Number(project.production)<90)items.push({id:`risk-${project.id}`,type:'project_risk',severity:'medium',title:'Project production needs review',detail:`${project.name} · ${project.production||0}% production`,projectId:project.id});const rank={urgent:0,high:1,medium:2,low:3};items.sort((a,b)=>rank[a.severity]-rank[b.severity]);return json(res,200,{generatedAt:now.toISOString(),items,counts:{urgent:items.filter(item=>item.severity==='urgent').length,high:items.filter(item=>item.severity==='high').length,medium:items.filter(item=>item.severity==='medium').length,total:items.length}})}
  if(req.method==='GET'&&url.pathname==='/api/users'){const db=readDb();return json(res,200,(db.users||[]).map(({setupHash,setupSalt,...user})=>user))}
  if(req.method==='POST'&&url.pathname==='/api/users'){const input=await body(req),roles=['owner','admin','project_manager','field'],db=readDb();db.users ||= [];if(!input.name?.trim()||!input.email?.trim()||!roles.includes(input.role))return json(res,400,{error:'Name, email, and valid role are required'});if(db.users.some(user=>user.email.toLowerCase()===input.email.toLowerCase()))return json(res,409,{error:'A user with that email already exists'});if(input.role==='owner'&&db.users.some(user=>user.role==='owner'&&user.status==='Active'))return json(res,409,{error:'Transfer ownership instead of creating another owner'});const setupCode=crypto.randomBytes(6).toString('base64url'),credential=credentialHash(setupCode),row={id:nextId(db.users),companyId:db.company.id,name:input.name.trim(),email:input.email.trim().toLowerCase(),role:input.role,preferredLanguage:input.preferredLanguage==='es'?'es':'en',projectIds:[...new Set((input.projectIds||[]).map(Number))],memberId:Number(input.memberId)||null,status:'Active',mustSetPassword:true,setupHash:credential.hash,setupSalt:credential.salt,setupExpiresAt:new Date(Date.now()+72*3600000).toISOString(),createdAt:new Date().toISOString()};db.users.push(row);writeDb(db);const{setupHash,setupSalt,...safe}=row;return json(res,201,{...safe,setupCode})}
  const userUpdate=url.pathname.match(/^\/api\/users\/(\d+)$/);if(req.method==='PATCH'&&userUpdate){const input=await body(req),db=readDb(),user=(db.users||[]).find(row=>row.id===Number(userUpdate[1]));if(!user)return json(res,404,{error:'User not found'});if(input.status&&['Active','Deactivated'].includes(input.status))user.status=input.status;if(input.role&&['admin','project_manager','field'].includes(input.role)&&user.role!=='owner')user.role=input.role;if(Array.isArray(input.projectIds))user.projectIds=[...new Set(input.projectIds.map(Number))];user.updatedAt=new Date().toISOString();writeDb(db);const{setupHash,setupSalt,...safe}=user;return json(res,200,safe)}
  const userReset=url.pathname.match(/^\/api\/users\/(\d+)\/reset-code$/);if(req.method==='POST'&&userReset){const db=readDb(),user=(db.users||[]).find(row=>row.id===Number(userReset[1]));if(!user||user.status!=='Active')return json(res,404,{error:'Active user not found'});const setupCode=crypto.randomBytes(6).toString('base64url'),credential=credentialHash(setupCode);user.setupHash=credential.hash;user.setupSalt=credential.salt;user.setupExpiresAt=new Date(Date.now()+72*3600000).toISOString();user.mustSetPassword=true;writeDb(db);return json(res,200,{setupCode,expiresAt:user.setupExpiresAt})}
  if(req.method==='GET'&&url.pathname==='/api/changes'){const db=readDb(),projectId=Number(url.searchParams.get('projectId'));return json(res,200,(db.changes||[]).filter(change=>!projectId||change.projectId===projectId))}
  if(req.method==='GET'&&url.pathname==='/api/catalog'){const db=readDb(),items=(db.catalog||[]).map(item=>{const entries=db.reports.filter(report=>report.status==='Approved').flatMap(report=>(report.productionEntries||[]).filter(entry=>entry.catalogItemId===item.id)),quantity=entries.reduce((sum,entry)=>sum+Number(entry.quantity||0),0),laborHours=entries.reduce((sum,entry)=>sum+Number(entry.laborHours||0),0);return{...item,history:{approvedEntries:entries.length,totalQuantity:quantity,totalLaborHours:laborHours,actualHoursPerUnit:quantity?laborHours/quantity:null}}});return json(res,200,items)}
  if(req.method==='POST'&&url.pathname==='/api/catalog'){const input=await body(req),db=readDb();db.catalog ||= [];if(!input.name?.trim()||!input.unit?.trim())return json(res,400,{error:'Item name and unit are required'});const row={id:nextId(db.catalog),name:input.name.trim(),category:String(input.category||'General').trim(),unit:input.unit.trim().toUpperCase(),targetHoursPerUnit:Math.max(0,Number(input.targetHoursPerUnit)||0),description:String(input.description||'').slice(0,500),createdAt:new Date().toISOString()};db.catalog.push(row);writeDb(db);return json(res,201,row)}
  const catalogApply=url.pathname.match(/^\/api\/catalog\/(\d+)\/apply$/);if(req.method==='POST'&&catalogApply){const input=await body(req),db=readDb(),item=(db.catalog||[]).find(row=>row.id===Number(catalogApply[1])),project=db.projects.find(row=>row.id===Number(input.projectId)),quantity=Number(input.plannedQuantity);if(!item||!project||!(quantity>0))return json(res,400,{error:'Catalog item, project, and planned quantity are required'});project.estimateItems ||= [];const estimateItem={id:nextId(project.estimateItems),catalogItemId:item.id,name:item.name,plannedQuantity:quantity,unit:item.unit,budgetHours:Math.round(quantity*item.targetHoursPerUnit*100)/100,cost:0};project.estimateItems.push(estimateItem);writeDb(db);return json(res,201,estimateItem)}
  if(req.method==='POST'&&url.pathname==='/api/estimate-imports/analyze'){const input=await body(req),match=String(input.data||'').match(/^data:application\/pdf;base64,(.+)$/);if(!match)return json(res,400,{error:'A PDF estimate is required'});const bytes=Buffer.from(match[1],'base64');if(bytes.length>15_000_000)return json(res,400,{error:'PDF must be smaller than 15 MB'});const text=pdfText(bytes),db=readDb();let draft={...estimateDraft(text),extractionMethod:'embedded_text'},ocrWarning=null,estimateNumber=text.match(/(?:estimate|quote)\s*(?:#|no\.?|number)?\s*([A-Z0-9-]{2,30})/i)?.[1]||null;if(draft.requiresOcr&&process.env.OPENAI_API_KEY){try{draft=await aiEstimateDraft(bytes,String(input.filename||'estimate.pdf'));estimateNumber=draft.estimateNumber||estimateNumber}catch(error){ocrWarning=error.message}}draft=enrichEstimateDraft(draft,db.catalog||[]);db.estimateImports ||= [];fs.mkdirSync(path.join(ROOT,'uploads','estimates'),{recursive:true});const filename=`${Date.now()}-${crypto.randomUUID()}.pdf`;fs.writeFileSync(path.join(ROOT,'uploads','estimates',filename),bytes);const row={id:nextId(db.estimateImports),filename:String(input.filename||'estimate.pdf').slice(0,180),url:`/uploads/estimates/${filename}`,estimateNumber,status:'Draft',createdAt:new Date().toISOString(),textPreview:text.slice(0,500),...draft,ocrWarning,duplicate:estimateNumber?db.estimateImports.some(item=>item.estimateNumber===estimateNumber):false};db.estimateImports.push(row);writeDb(db);return json(res,201,row)}
  const approveImport=url.pathname.match(/^\/api\/estimate-imports\/(\d+)\/approve$/);if(req.method==='POST'&&approveImport){const input=await body(req),db=readDb(),row=(db.estimateImports||[]).find(item=>item.id===Number(approveImport[1])),project=db.projects.find(item=>item.id===Number(input.projectId)),lines=Array.isArray(input.lines)?input.lines:row?.lines;if(!row||!project||!lines?.length)return json(res,400,{error:'Import, project, and at least one confirmed line are required'});project.estimateItems ||= [];const created=[];for(const line of lines){if(!line.description?.trim()||!(Number(line.quantity)>0)||!line.unit)continue;const selectedId=Number(line.catalogItemId)||null,catalog=selectedId?(db.catalog||[]).find(item=>item.id===selectedId):null;if(selectedId&&!catalog)return json(res,400,{error:'A selected catalog item no longer exists'});const exact=catalog||(db.catalog||[]).find(item=>item.name.toLowerCase()===line.description.trim().toLowerCase()&&item.unit===line.unit.toUpperCase()),item={id:nextId(project.estimateItems),catalogItemId:exact?.id||null,name:line.description.trim(),plannedQuantity:Number(line.quantity),unit:line.unit.toUpperCase(),budgetHours:exact?Math.round(Number(line.quantity)*exact.targetHoursPerUnit*100)/100:0,cost:Number(line.amount)||0,sourceImportId:row.id};project.estimateItems.push(item);created.push(item)}if(!created.length)return json(res,400,{error:'No valid estimate lines were confirmed'});row.status='Approved';row.projectId=project.id;row.approvedAt=new Date().toISOString();row.approvedLines=created.length;writeDb(db);return json(res,200,{import:row,items:created})}
  const guestAccess=url.pathname.match(/^\/api\/guest\/([a-f0-9]{48})$/);if(req.method==='GET'&&guestAccess){const db=readDb(),tokenHash=crypto.createHash('sha256').update(guestAccess[1]).digest('hex'),link=(db.subcontractorLinks||[]).find(row=>row.tokenHash===tokenHash&&row.status==='Active');if(!link||new Date(link.expiresAt)<new Date())return json(res,404,{error:'This guest link is invalid or expired'});const subcontractor=(db.subcontractors||[]).find(row=>row.id===link.subcontractorId),project=db.projects.find(row=>row.id===link.projectId);if(!subcontractor||!project)return json(res,404,{error:'Guest access is no longer available'});const safeProject={id:project.id,name:project.name,code:project.code,site:project.site};return json(res,200,{company:{name:db.company.name},subcontractor:{id:subcontractor.id,name:subcontractor.name,trade:subcontractor.trade},project:safeProject,mode:link.mode||'progress',permissions:['start_day','end_day','daily_report','photos'],expiresAt:link.expiresAt})}
  if(req.method==='POST'&&guestAccess){const input=await body(req),db=readDb(),tokenHash=crypto.createHash('sha256').update(guestAccess[1]).digest('hex'),link=(db.subcontractorLinks||[]).find(row=>row.tokenHash===tokenHash&&row.status==='Active');if(!link||new Date(link.expiresAt)<new Date())return json(res,404,{error:'This guest link is invalid or expired'});const subcontractor=(db.subcontractors||[]).find(row=>row.id===link.subcontractorId),projectIndex=db.projects.findIndex(row=>row.id===link.projectId);if(!subcontractor||projectIndex<0)return json(res,404,{error:'Guest access is no longer available'});if(!input.notes?.trim()||!input.startedAt||!input.endedAt||new Date(input.endedAt)<=new Date(input.startedAt))return json(res,400,{error:'Valid start time, end time, and work notes are required'});const crewCount=Math.max(1,Number(input.crewCount)||1),hours=Math.round(((new Date(input.endedAt)-new Date(input.startedAt))/3600000)*100)/100,now=new Date().toISOString(),report={id:nextId(db.reports),project:projectIndex,date:new Date(input.endedAt).toLocaleDateString('en-US',{month:'short',day:'numeric'}),dateIso:String(input.endedAt).slice(0,10),foreman:subcontractor.name,status:'Needs review',notes:input.notes.trim(),summary:`${subcontractor.name} reported ${crewCount} people on site for ${hours} hours each.`,labor:`${crewCount} people · ${(crewCount*hours).toFixed(2)} total hours`,quantity:'Needs office verification',next:String(input.next||'').slice(0,500),weather:'',temperature:'',productionEntries:[],laborEntries:[],materials:String(input.materials||'').slice(0,1000),equipment:String(input.equipment||'').slice(0,1000),delays:String(input.delays||'').slice(0,1000),safety:'',signature:String(input.signature||subcontractor.name).slice(0,120),source:'subcontractor',subcontractorId:subcontractor.id,guestTime:{startedAt:input.startedAt,endedAt:input.endedAt,crewCount,hoursPerPerson:hours},flags:[],history:[{action:'Submitted by subcontractor',by:subcontractor.name,at:now}]};db.reports.unshift(report);db.photos ||= [];const allowed={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'},created=[];fs.mkdirSync(path.join(ROOT,'uploads'),{recursive:true});for(const file of (input.files||[]).slice(0,8)){const ext=allowed[file.type],match=String(file.data||'').match(/^data:[^;]+;base64,(.+)$/);if(!ext||!match)continue;const bytes=Buffer.from(match[1],'base64');if(bytes.length>6_000_000)continue;const filename=`${Date.now()}-${crypto.randomUUID()}.${ext}`,photo={id:nextId(db.photos),project:projectIndex,reportId:report.id,source:'field',phase:'end',caption:'Subcontractor daily photo',uploader:subcontractor.name,createdAt:now,url:`/uploads/${filename}`};fs.writeFileSync(path.join(ROOT,'uploads',filename),bytes);db.photos.push(photo);created.push(photo)}writeDb(db);return json(res,201,{reportId:report.id,status:report.status,photos:created.length})}
  const tmSummary=url.pathname.match(/^\/api\/projects\/(\d+)\/tm-summary$/);if(req.method==='GET'&&tmSummary){const db=readDb(),projectIndex=db.projects.findIndex(p=>p.id===Number(tmSummary[1])),project=db.projects[projectIndex];if(!project)return json(res,404,{error:'Project not found'});const reports=db.reports.filter(r=>r.project===projectIndex&&r.status==='Approved'),rate=Number(project.tmSettings?.defaultLaborRate)||0,groups=new Map();for(const report of reports)for(const entry of report.laborEntries||[]){const member=db.team.find(m=>m.id===entry.memberId),key=member?.role||'Unclassified labor',current=groups.get(key)||{classification:key,hours:0};current.hours+=Number(entry.hours)||0;groups.set(key,current)}const labor=[...groups.values()].map(row=>({...row,rate,amount:row.hours*rate})),laborHours=labor.reduce((sum,row)=>sum+row.hours,0),laborAmount=labor.reduce((sum,row)=>sum+row.amount,0);return json(res,200,{projectId:project.id,approvedDailies:reports.length,laborHours,laborAmount,materialEntries:reports.filter(r=>r.materials).length,equipmentEntries:reports.filter(r=>r.equipment).length,labor,materialMarkup:Number(project.tmSettings?.materialMarkup)||0,equipmentMarkup:Number(project.tmSettings?.equipmentMarkup)||0})}
  if(req.method==='GET'&&url.pathname==='/api/state'){
    const db=readDb();
    const userId=Number(url.searchParams.get('userId')),accountUser=(db.users||[]).find(user=>user.id===userId);
    if(userId&&!accountUser)return json(res,404,{error:'User not found'});
    if(accountUser?.status!=='Active'&&userId)return json(res,403,{error:'User access is deactivated'});
    if(accountUser?.role==='field'){url.searchParams.set('role','field');url.searchParams.set('memberId',accountUser.memberId)}
    if(accountUser?.role==='project_manager'){
      const allowedIds=new Set(accountUser.projectIds||[]),pairs=db.projects.map((project,index)=>({project,index})).filter(row=>allowedIds.has(row.project.id)),indexMap=new Map(pairs.map((row,newIndex)=>[row.index,newIndex])),projects=pairs.map(row=>row.project),customerIds=new Set(projects.map(project=>project.customerId));
      return json(res,200,{company:db.company,currentUser:{id:accountUser.id,name:accountUser.name,role:accountUser.role},customers:db.customers.filter(customer=>customerIds.has(customer.id)),projects,team:db.team,assignments:(db.assignments||[]).filter(assignment=>allowedIds.has(assignment.projectId)),reports:db.reports.filter(report=>indexMap.has(report.project)).map(report=>({...report,project:indexMap.get(report.project)})),photos:(db.photos||[]).filter(photo=>indexMap.has(photo.project)).map(photo=>({...photo,project:indexMap.get(photo.project)})),workdays:(db.workdays||[]).filter(workday=>allowedIds.has(workday.projectId)),subcontractors:db.subcontractors||[],subcontractorLinks:(db.subcontractorLinks||[]).filter(link=>allowedIds.has(link.projectId)).map(({tokenHash,...link})=>link)});
    }
    if(url.searchParams.get('role')!=='field'){const{sessions,...publicDb}=db,officeUser=accountUser||(db.users||[]).find(user=>user.status==='Active'&&['owner','admin','project_manager'].includes(user.role)),safe={...publicDb,currentUser:officeUser?{id:officeUser.id,name:officeUser.name,role:officeUser.role,preferences:officeUser.preferences||{}}:null,users:(db.users||[]).map(({setupHash,setupSalt,passwordHash,passwordSalt,...user})=>user),subcontractorLinks:(db.subcontractorLinks||[]).map(({tokenHash,...link})=>link)};return json(res,200,safe)}
    const memberId=Number(url.searchParams.get('memberId'));
    const member=db.team.find(m=>m.id===memberId);
    if(!member) return json(res,404,{error:'Field user not found'});
    const ownAssignments=db.assignments.filter(a=>a.memberIds.includes(memberId));
    const ownWorkdays=(db.workdays||[]).filter(w=>w.memberIds.includes(memberId));
    const ownReports=db.reports.filter(r=>r.foreman===member.name||(r.laborEntries||[]).some(x=>x.memberId===memberId)||ownWorkdays.some(w=>w.reportId===r.id));
    const allowedIds=new Set([...ownAssignments.map(a=>a.projectId),...ownWorkdays.map(w=>w.projectId),...ownReports.map(r=>db.projects[r.project]?.id)].filter(Boolean));
    const pairs=db.projects.map((project,index)=>({project,index})).filter(x=>allowedIds.has(x.project.id));
    const indexMap=new Map(pairs.map((x,newIndex)=>[x.index,newIndex]));
    const projects=pairs.map(({project})=>{const safe={...project};delete safe.budget;delete safe.tmSettings;safe.estimateItems=(safe.estimateItems||[]).map(({cost,...item})=>item);return safe});
    const reports=ownReports.filter(r=>indexMap.has(r.project)).map(r=>({...r,project:indexMap.get(r.project)}));
    const photos=(db.photos||[]).filter(p=>indexMap.has(p.project)).map(p=>({...p,project:indexMap.get(p.project)}));
    const fieldAccount=(db.users||[]).find(user=>user.memberId===member.id&&user.role==='field'&&user.status==='Active');
    return json(res,200,{company:db.company,currentUser:{memberId:member.id,name:member.name,role:'field',preferredLanguage:fieldAccount?.preferredLanguage||'en'},customers:[],projects,team:db.team.filter(m=>m.crew===member.crew),assignments:ownAssignments.map(a=>({...a,memberIds:[memberId]})),reports,photos,workdays:ownWorkdays});
  }
  if(req.method==='GET'&&url.pathname==='/api/weather'){const lat=Number(url.searchParams.get('lat')),lon=Number(url.searchParams.get('lon'));if(!Number.isFinite(lat)||!Number.isFinite(lon))return json(res,400,{error:'Valid latitude and longitude are required'});try{const weatherResponse=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat.toFixed(4)}&longitude=${lon.toFixed(4)}&current=temperature_2m,weather_code,wind_speed_10m&temperature_unit=fahrenheit&wind_speed_unit=mph`);if(!weatherResponse.ok)throw new Error('Weather provider unavailable');const weather=await weatherResponse.json();return json(res,200,weather.current)}catch(error){return json(res,502,{error:'Could not load job-site weather'})}}
  if(req.method==='POST'&&url.pathname==='/api/ai/extract'){const input=await body(req);if(!input.notes?.trim())return json(res,400,{error:'Field notes are required'});try{return json(res,200,await aiExtract(input.notes.trim(),input.language||'auto'))}catch(error){return json(res,200,{...localExtract(input.notes.trim()),originalLanguage:String(input.language||'unknown').split('-')[0],englishTranslation:input.language?.startsWith('es')?'Translation unavailable until AI is configured':input.notes.trim(),source:'fallback',warning:error.message})}}
  if(req.method==='POST'&&url.pathname==='/api/reports'){const input=await body(req),db=readDb();if(!db.projects[input.project]||!input.notes?.trim())return json(res,400,{error:'Valid project and notes are required'});const extracted=input.extracted||localExtract(input.notes);const report={...extracted,id:nextId(db.reports),project:Number(input.project),date:input.dateLabel||new Date().toLocaleDateString('en-US',{month:'short',day:'numeric'}),dateIso:input.dateIso||null,foreman:input.foreman||'Levi Foreman',status:input.status==='Draft'?'Draft':'Needs review',notes:input.notes,originalNotes:input.notes,noteLanguage:input.noteLanguage||extracted.originalLanguage||'en',englishTranslation:input.englishTranslation||extracted.englishTranslation||input.notes,summary:input.summary||'',labor:input.labor||'',quantity:input.quantity||'',next:input.next||'',weather:input.weather||'',temperature:input.temperature||'',productionEntries:Array.isArray(input.productionEntries)?input.productionEntries:[],laborEntries:Array.isArray(input.laborEntries)?input.laborEntries:[],materials:input.materials||'',equipment:input.equipment||'',delays:input.delays||'',safety:input.safety||'',signature:input.signature||'',history:[{action:input.status==='Draft'?'Draft saved':'Submitted',by:input.foreman||'Levi Foreman',at:new Date().toISOString()}]};report.flags=report.productionEntries.some(entry=>!entry.estimateItemId)?[{type:'unplanned_work',message:'Daily contains work not found on the estimate'}]:[];delete report.source;delete report.warning;db.reports.unshift(report);writeDb(db);return json(res,201,report)}
  if(req.method==='POST'&&url.pathname==='/api/photos'){
    const input=await body(req),db=readDb();
    if(!db.projects[input.project]||!['office','field'].includes(input.source)||!Array.isArray(input.files)||!input.files.length)return json(res,400,{error:'Project, source, and photos are required'});
    const allowed={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'},created=[];db.photos ||= [];
    for(const file of input.files.slice(0,8)){const ext=allowed[file.type];const match=String(file.data||'').match(/^data:[^;]+;base64,(.+)$/);if(!ext||!match)continue;const bytes=Buffer.from(match[1],'base64');if(bytes.length>6_000_000)continue;const stored=await saveAsset(db,'project-photos',`photo.${ext}`,bytes,file.type);const photo={id:nextId(db.photos),project:Number(input.project),reportId:input.reportId||null,workdayId:input.workdayId||null,phase:input.phase||null,source:input.source,caption:String(input.caption||'').slice(0,500),uploader:input.uploader||'Levi Foreman',createdAt:new Date().toISOString(),url:stored.url,storageBucket:stored.bucket,storageKey:stored.objectKey};db.photos.push(photo);created.push(photo)}
    if(!created.length)return json(res,400,{error:'No valid photos were uploaded'});writeDb(db);return json(res,201,created);
  }
  if(req.method==='POST'&&url.pathname==='/api/assignments'){const input=await body(req),db=readDb();const memberIds=[...new Set((input.memberIds||[]).map(Number))],project=db.projects.find(p=>p.id===Number(input.projectId));if(!project||!memberIds.length||!input.date||!input.start||!input.end)return json(res,400,{error:'Project, people, date, and shift times are required'});if(input.start>=input.end)return json(res,400,{error:'Shift end must be after start'});const conflicts=db.assignments.filter(a=>a.date===input.date&&a.memberIds.some(id=>memberIds.includes(id))&&input.start<a.end&&input.end>a.start);if(conflicts.length){const conflictIds=[...new Set(conflicts.flatMap(a=>a.memberIds).filter(id=>memberIds.includes(id)))],names=db.team.filter(m=>conflictIds.includes(m.id)).map(m=>m.name);return json(res,409,{error:`Schedule conflict: ${names.join(', ')} already assigned during this time`,conflictMemberIds:conflictIds})}const row={id:nextId(db.assignments),projectId:Number(input.projectId),memberIds,crew:input.crew||null,date:input.date,start:input.start,end:input.end,activity:String(input.activity||'Scheduled work').slice(0,120)};db.assignments.push(row);writeDb(db);return json(res,201,row)}
  if(req.method==='POST'&&url.pathname==='/api/workdays/start'){const input=await body(req),db=readDb();db.workdays ||= [];const memberIds=[...new Set((input.memberIds||[]).map(Number))],project=db.projects.find(p=>p.id===Number(input.projectId));if(!project||!memberIds.length)return json(res,400,{error:'Choose a project and at least one team member'});const busy=db.workdays.filter(w=>w.status==='active'&&w.memberIds.some(id=>memberIds.includes(id))).flatMap(w=>w.memberIds).filter(id=>memberIds.includes(id));if(busy.length){const names=db.team.filter(m=>busy.includes(m.id)).map(m=>m.name);return json(res,409,{error:`Already clocked in: ${names.join(', ')}`})}const row={id:nextId(db.workdays),projectId:project.id,memberIds,status:'active',startedAt:new Date().toISOString(),endedAt:null,startNote:String(input.startNote||'').slice(0,500),endNotes:'',reportId:null};db.workdays.push(row);writeDb(db);return json(res,201,row)}
  const userPreferences=url.pathname.match(/^\/api\/users\/(\d+)\/preferences$/);if(req.method==='PATCH'&&userPreferences){const input=await body(req),db=readDb(),user=(db.users||[]).find(row=>row.id===Number(userPreferences[1]));if(!user)return json(res,404,{error:'User not found'});const preferences={...(user.preferences||{})};if(Object.hasOwn(input,'scheduleCrew'))preferences.scheduleCrew=String(input.scheduleCrew||'all').slice(0,60);if(Object.hasOwn(input,'scheduleShowOffice'))preferences.scheduleShowOffice=Boolean(input.scheduleShowOffice);if(Object.hasOwn(input,'displayName'))preferences.displayName=String(input.displayName||user.name).trim().slice(0,100);if(['light','dark','system'].includes(input.theme))preferences.theme=input.theme;if(Object.hasOwn(input,'profilePhoto')){const photo=String(input.profilePhoto||'');if(photo&&(!/^data:image\/(jpeg|png|webp);base64,/.test(photo)||photo.length>2_100_000))return json(res,400,{error:'Profile photo must be a JPG, PNG, or WebP smaller than 1.5 MB'});preferences.profilePhoto=photo}user.preferences=preferences;writeDb(db);return json(res,200,user.preferences)}
  if(req.method==='PATCH'&&url.pathname==='/api/company'){const input=await body(req),db=readDb();if(!String(input.name||'').trim())return json(res,400,{error:'Company name is required'});db.company={...db.company,name:String(input.name).trim().slice(0,120),trade:String(input.trade||'').trim().slice(0,120),email:String(input.email||'').trim().slice(0,160),phone:String(input.phone||'').trim().slice(0,40),timezone:['America/Los_Angeles','America/Denver','America/Chicago','America/New_York'].includes(input.timezone)?input.timezone:'America/Los_Angeles',weekStart:input.weekStart==='sunday'?'sunday':'monday'};writeDb(db);return json(res,200,db.company)}
  const subLink=url.pathname.match(/^\/api\/subcontractors\/(\d+)\/links$/);if(req.method==='POST'&&subLink){const input=await body(req),db=readDb(),subcontractor=(db.subcontractors||[]).find(row=>row.id===Number(subLink[1])),project=db.projects.find(row=>row.id===Number(input.projectId));if(!subcontractor||!project)return json(res,404,{error:'Subcontractor or project not found'});const expiresAt=input.expiresAt?new Date(`${input.expiresAt}T23:59:59`).toISOString():new Date(Date.now()+30*86400000).toISOString(),token=crypto.randomBytes(24).toString('hex'),mode=input.mode==='tm'?'tm':'progress',row={id:nextId(db.subcontractorLinks||[]),subcontractorId:subcontractor.id,projectId:project.id,mode,tokenHash:crypto.createHash('sha256').update(token).digest('hex'),status:'Active',createdAt:new Date().toISOString(),expiresAt};db.subcontractorLinks ||= [];db.subcontractorLinks.push(row);writeDb(db);return json(res,201,{id:row.id,subcontractorId:row.subcontractorId,projectId:row.projectId,mode:row.mode,status:row.status,createdAt:row.createdAt,expiresAt:row.expiresAt,url:`/guest/${token}`})}
  const subLinkRevoke=url.pathname.match(/^\/api\/subcontractor-links\/(\d+)$/);if(req.method==='DELETE'&&subLinkRevoke){const db=readDb(),link=(db.subcontractorLinks||[]).find(row=>row.id===Number(subLinkRevoke[1]));if(!link)return json(res,404,{error:'Guest link not found'});link.status='Revoked';link.revokedAt=new Date().toISOString();writeDb(db);return json(res,200,{ok:true})}
  const endWorkday=url.pathname.match(/^\/api\/workdays\/(\d+)\/end$/);if(req.method==='POST'&&endWorkday){const input=await body(req),db=readDb(),workday=(db.workdays||[]).find(w=>w.id===Number(endWorkday[1]));if(!workday||workday.status!=='active')return json(res,404,{error:'Active workday not found'});if(!input.notes?.trim())return json(res,400,{error:'Add a short note about what was completed'});workday.endedAt=new Date().toISOString();workday.status='complete';workday.endNotes=input.notes.trim();const hours=Math.max(0,Math.round(((new Date(workday.endedAt)-new Date(workday.startedAt))/3600000)*100)/100),projectIndex=db.projects.findIndex(p=>p.id===workday.projectId),extracted=localExtract(workday.endNotes),report={...extracted,id:nextId(db.reports),project:projectIndex,date:new Date().toLocaleDateString('en-US',{month:'short',day:'numeric'}),dateIso:new Date().toISOString().slice(0,10),foreman:input.foreman||'Field team',status:'Draft',notes:workday.endNotes,summary:extracted.summary||'',labor:hours?`${workday.memberIds.length} people · ${hours} hours each`:'',quantity:extracted.quantity||'',next:String(input.next||extracted.next||'').trim().slice(0,500),weather:'',temperature:'',productionEntries:[],laborEntries:workday.memberIds.map(memberId=>({memberId,hours})),materials:'',equipment:'',delays:extracted.delays||'',safety:'',signature:'',workdayId:workday.id,history:[{action:'Draft created from workday',by:input.foreman||'Field team',at:new Date().toISOString()}]};delete report.source;db.reports.unshift(report);workday.reportId=report.id;writeDb(db);return json(res,200,{workday,report})}
  for(const resource of ['customers','projects','team','subcontractors']){if(req.method==='POST'&&url.pathname===`/api/${resource}`){const input=await body(req),db=readDb();db[resource] ||= [];const row={id:nextId(db[resource]),...input};db[resource].push(row);writeDb(db);return json(res,201,row)}}
  const disposition=url.pathname.match(/^\/api\/reports\/(\d+)\/disposition$/);if(req.method==='PATCH'&&disposition){const input=await body(req),allowed=['mapped','non_billable','tm','potential_change'];if(!allowed.includes(input.resolution))return json(res,400,{error:'Choose a valid office disposition'});const db=readDb(),report=db.reports.find(r=>r.id===Number(disposition[1]));if(!report)return json(res,404,{error:'Report not found'});const unresolved=(report.flags||[]).filter(flag=>!flag.resolution);if(!unresolved.length)return json(res,400,{error:'This report has no unresolved exceptions'});const resolvedAt=new Date().toISOString(),note=String(input.note||'').slice(0,500);for(const flag of unresolved)Object.assign(flag,{resolution:input.resolution,resolutionNote:note,resolvedBy:'Office',resolvedAt});db.changes ||= [];let change=null;if(input.resolution==='potential_change'){const project=db.projects[report.project],number=`PC-${String(db.changes.filter(row=>row.projectId===project.id).length+1).padStart(3,'0')}`;change={id:nextId(db.changes),projectId:project.id,reportId:report.id,number,title:note||(report.productionEntries||[]).filter(entry=>!entry.estimateItemId).map(entry=>entry.description).join(', ')||'Unplanned field work',status:'Potential',amount:0,createdAt:resolvedAt,history:[{action:'Created from daily exception',by:'Office',at:resolvedAt}]};db.changes.push(change)}report.history ||= [];report.history.push({action:`Exception resolved: ${input.resolution.replace('_',' ')}`,by:'Office',at:resolvedAt});writeDb(db);return json(res,200,{report,change})}
  const changeUpdate=url.pathname.match(/^\/api\/changes\/(\d+)$/);if(req.method==='PATCH'&&changeUpdate){const input=await body(req),statuses=['Potential','Submitted','Approved','Rejected','Void'],db=readDb(),change=(db.changes||[]).find(row=>row.id===Number(changeUpdate[1]));if(!change)return json(res,404,{error:'Change not found'});if(input.status&&!statuses.includes(input.status))return json(res,400,{error:'Invalid change status'});if(input.status)change.status=input.status;if(Object.hasOwn(input,'amount'))change.amount=Math.max(0,Number(input.amount)||0);if(input.title)change.title=String(input.title).slice(0,160);change.history ||= [];change.history.push({action:`Updated to ${change.status}`,by:'Office',at:new Date().toISOString()});writeDb(db);return json(res,200,change)}
  const approval=url.pathname.match(/^\/api\/reports\/(\d+)\/approve$/);if(req.method==='PATCH'&&approval){const db=readDb(),report=db.reports.find(r=>r.id===Number(approval[1]));if(!report)return json(res,404,{error:'Report not found'});if((report.flags||[]).some(flag=>!flag.resolution))return json(res,409,{error:'Resolve unplanned work before approving this report'});report.status='Approved';report.history ||= [];report.history.push({action:'Approved',by:'Office',at:new Date().toISOString()});writeDb(db);return json(res,200,report)}
  const reportEdit=url.pathname.match(/^\/api\/reports\/(\d+)$/);if(req.method==='PATCH'&&reportEdit){const input=await body(req),db=readDb(),report=db.reports.find(r=>r.id===Number(reportEdit[1]));if(!report)return json(res,404,{error:'Report not found'});const allowed=['dateIso','foreman','status','notes','weather','temperature','productionEntries','laborEntries','materials','equipment','delays','safety','signature','summary','labor','quantity','issue','next'];for(const key of allowed)if(Object.hasOwn(input,key))report[key]=input[key];report.flags=(report.productionEntries||[]).some(entry=>!entry.estimateItemId)?[{type:'unplanned_work',message:'Daily contains work not found on the estimate'}]:[];report.history ||= [];report.history.push({action:'Corrected',by:input.foreman||'Field user',at:new Date().toISOString()});writeDb(db);return json(res,200,report)}
  const projectArchive=url.pathname.match(/^\/api\/projects\/(\d+)\/archive$/);if(req.method==='PATCH'&&projectArchive){const input=await body(req),db=readDb(),project=db.projects.find(row=>row.id===Number(projectArchive[1]));if(!project)return json(res,404,{error:'Project not found'});if(input.archived&&(db.workdays||[]).some(row=>row.projectId===project.id&&row.status==='active'))return json(res,409,{error:'End the active workday before archiving this project'});project.archived=Boolean(input.archived);project.archivedAt=project.archived?new Date().toISOString():null;writeDb(db);return json(res,200,project)}
  const estimate=url.pathname.match(/^\/api\/projects\/(\d+)\/estimate-items$/);if(req.method==='POST'&&estimate){const input=await body(req),db=readDb(),project=db.projects.find(p=>p.id===Number(estimate[1]));if(!project)return json(res,404,{error:'Project not found'});if(!input.name||!(Number(input.plannedQuantity)>0))return json(res,400,{error:'Scope and planned quantity are required'});project.estimateItems ||= [];const item={id:nextId(project.estimateItems),name:String(input.name).slice(0,120),plannedQuantity:Number(input.plannedQuantity),unit:String(input.unit||'EA').slice(0,10),budgetHours:Number(input.budgetHours)||0,cost:Number(input.cost)||0};project.estimateItems.push(item);writeDb(db);return json(res,201,item)}
  const assignmentDelete=url.pathname.match(/^\/api\/assignments\/(\d+)$/);if(req.method==='DELETE'&&assignmentDelete){const db=readDb(),index=db.assignments.findIndex(a=>a.id===Number(assignmentDelete[1]));if(index<0)return json(res,404,{error:'Assignment not found'});const memberId=Number(url.searchParams.get('memberId'));if(memberId){const assignment=db.assignments[index];assignment.memberIds=assignment.memberIds.filter(id=>id!==memberId);if(!assignment.memberIds.length)db.assignments.splice(index,1)}else db.assignments.splice(index,1);writeDb(db);return json(res,200,{ok:true,assignmentId:Number(assignmentDelete[1]),memberId:memberId||null})}
  return json(res,404,{error:'Not found'});
}

const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){const file=requestDbFile(req);if(!file)return json(res,404,{error:'Company workspace not found'});return await dbContext.run({file},()=>api(req,res,url))}let requested=decodeURIComponent(url.pathname==='/'?'/index.html':/^\/guest\/[a-f0-9]{48}$/.test(url.pathname)?'/guest.html':url.pathname);let file=path.resolve(ROOT,'.'+requested);if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':MIME[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res)}catch(error){console.error(error);json(res,500,{error:'Unexpected server error',requestId:crypto.randomUUID()})}});
if(require.main===module) server.listen(PORT,()=>console.log(`Pro Daily Link running at http://localhost:${PORT}`));
module.exports={server,localExtract};
