'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('server.js','utf8'),lines=source.split('\n');
function code(name){const start=lines.findIndex(l=>l.startsWith(`function ${name}(`)||l.startsWith(`async function ${name}(`));assert.ok(start>=0);if(lines[start].trimEnd().endsWith('}'))return lines[start];const end=lines.findIndex((l,i)=>i>start&&l.trim()==='}');return lines.slice(start,end+1).join('\n')}
const context={buildActionCenterBeforeCompliance:()=>({items:[{id:'other',type:'other',severity:'low'},{id:'old-insurance',type:'insurance'}]}),console};vm.createContext(context);
for(const name of ['subcontractorArchived','subcontractorRequirements','runAutomaticComplianceReminders'])vm.runInContext(code(name),context);
const builder=lines.find(l=>l.startsWith('buildActionCenter=function(db,now=new Date()){const result=buildActionCenterBeforeCompliance'));assert.ok(builder);vm.runInContext(builder,context);
const now=new Date('2026-10-04T12:00:00Z'),archived=Array.from({length:7},(_,i)=>({id:i+1,name:'Synthetic archived '+i,archivedAt:'2026-10-01T12:00:00Z',status:'Archived',autoComplianceReminders:true,email:'synthetic@example.invalid'})),db={subcontractors:archived};
vm.runInContext(builder.replace('if(subcontractorArchived(sub))continue;',''),context);assert.equal(context.buildActionCenter(db,now).items.filter(x=>x.type==='subcontractor_compliance').length,7,'pre-fix builder reproduces seven alerts for hidden archived records');vm.runInContext(builder,context);
const before=JSON.stringify(db);let result=context.buildActionCenter(db,now);assert.equal(result.items.filter(x=>x.type==='subcontractor_compliance').length,0,'all-archived directory has no open compliance alerts');assert.equal(result.counts.total,1);assert.equal(JSON.stringify(db),before,'alert derivation never alters records/history');
const active={id:20,name:'Synthetic active'},statusOnly={id:21,name:'Status archived',status:'Archived'},timestampOnly={id:22,name:'Timestamp archived',archivedAt:'2026-10-01'};db.subcontractors=[active,statusOnly,timestampOnly];result=context.buildActionCenter(db,now);assert.deepEqual(Array.from(result.items.filter(x=>x.type==='subcontractor_compliance'),x=>x.subcontractorId),[20]);assert.equal(result.counts.high,1);db.subcontractors=[{...timestampOnly,archivedAt:null,status:'Active'}];assert.equal(context.buildActionCenter(db,now).items.filter(x=>x.type==='subcontractor_compliance').length,1,'restored records are eligible again');
db.subcontractors=[{...active,id:30,name:'Same display name'},{...active,id:31,name:'Same display name'}];result=context.buildActionCenter(db,now);assert.deepEqual(Array.from(result.items.filter(x=>x.type==='subcontractor_compliance'),x=>x.id),['compliance-30','compliance-31'],'distinct records are not merged by name');
db.subcontractors=[{...active,insuranceExpiration:'2027-01-01',workersCompExpiration:'2027-01-01',licenseExpiration:'2027-01-01',w9Received:true,agreementSigned:true}];assert.equal(context.buildActionCenter(db,now).items.filter(x=>x.type==='subcontractor_compliance').length,0);
(async()=>{const reminded=[];context.sendComplianceReminder=async(db,sub)=>{reminded.push(sub.id);return true};assert.equal(await context.runAutomaticComplianceReminders({subcontractors:archived},now),false);assert.deepEqual(reminded,[]);assert.equal(await context.runAutomaticComplianceReminders({subcontractors:[{...active,email:'synthetic@example.invalid',autoComplianceReminders:true},statusOnly,timestampOnly]},now),true);assert.deepEqual(reminded,[20]);console.log('Subcontractor alerts passed: archived timestamp/status exclusion, active/restored/compliant records, counts, distinct IDs and no archived automatic reminder calls (synthetic VM).')})().catch(error=>{console.error(error);process.exitCode=1});
