'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {timePeople,timeCardComplete,timePeriodDate}=require('./time-approval-controls'),{availableCompanyTabs}=require('./company-settings-tabs');
const cards=[{id:1,memberId:1,date:'2026-10-04',projectId:1,inAt:'2026-10-05T06:00:00Z',outAt:'2026-10-05T10:00:00Z',hours:4,status:'submitted',historyLines:['Synthetic correction']},{id:2,memberId:1,date:'2026-10-06',projectId:1,inAt:'2026-10-06T15:00:00Z',outAt:'2026-10-06T17:00:00Z',hours:2,status:'draft'},{id:3,memberId:2,date:'2026-10-06',projectId:1,inAt:'2026-10-06T15:00:00Z',outAt:'2026-10-06T18:00:00Z',hours:3,status:'approved'},{id:4,memberId:1,date:'2026-10-07',projectId:1,inAt:'2026-10-07T15:00:00Z',outAt:null,hours:null,status:'submitted'}];
const team=[{id:1,name:'<Synthetic Alice>'},{id:2,name:'Synthetic Bob'}],approved=c=>c.status==='approved';
const people=timePeople(cards,team,approved);assert.equal(people[0].hours,6);assert.equal(people[0].submitted,1);assert.equal(people[0].draft,1);assert.equal(people[0].running,1);assert.equal(timePeople(cards,team,approved,'bOB').length,1);assert.equal(timeCardComplete(cards[3]),false);assert.equal(timeCardComplete({...cards[0],outAt:'2026-10-05T10:00:00'}),false);assert.equal(timePeriodDate(cards[0],'America/New_York'),'2026-10-05');assert.equal(timePeriodDate(cards[0],'America/Los_Angeles'),'2026-10-04');
assert.deepEqual(availableCompanyTabs({role:'owner'},{timeCards:true,templates:true},'office'),['company','periods','forms','activity']);assert.deepEqual(availableCompanyTabs({role:'admin',permissions:{}},{timeCards:true},'office'),['company','activity']);assert.deepEqual(availableCompanyTabs({role:'project_manager'},{timeCards:true,templates:true},'office'),['forms']);assert.deepEqual(availableCompanyTabs({role:'field'},{timeCards:true,templates:true},'field'),[]);

// Run the real controls and original row renderer in a DOM fixture. No browser claim.
const app=fs.readFileSync('app.js','utf8'),nodes=new Map(),listeners={},calls=[],period={id:'period-a',label:'Synthetic custom',from:'2026-10-04',to:'2026-10-09',timeZone:'America/Los_Angeles',exportCount:0};let boxes=[],approveButtons=[],pendingSummary=null,pendingDownload=null,pendingCapture=null;const testPeriods=[period];
function node(id){if(!nodes.has(id))nodes.set(id,{id:id.slice(1),value:'',hidden:false,disabled:false,dataset:{},textContent:'',options:[],open:false,tabIndex:0,attributes:{},classList:{toggle(){},contains(){return false}},setAttribute(k,v){this.attributes[k]=v},focus(options){this.focused=true;this.focusOptions=options},showModal(){this.open=true},close(){this.open=false},addEventListener(type,fn){this[type]=fn},querySelector(selector){return node(id+' '+selector)}});return nodes.get(id)}
for(const id of ['timecard-job','timecard-person','timecard-status'])node('#'+id).value='all';
Object.defineProperty(node('#timecard-rows'),'innerHTML',{get(){return this.html||''},set(html){this.html=html;boxes=[...html.matchAll(/<input type="checkbox" data-timecard-pick="(\d+)"([^>]*)>/g)].map(m=>({dataset:{timecardPick:m[1]},disabled:m[2].includes('disabled'),checked:false}));approveButtons=[...html.matchAll(/<button[^>]*data-timecard-approve="(\d+)"[^>]*>/g)].map(m=>({dataset:{timecardApprove:m[1]},disabled:false}))}});
function query(selector){if(selector==='[data-timecard-pick]')return boxes;if(selector==='[data-timecard-pick], [data-timecard-approve]')return [...boxes,...approveButtons];if(selector==='[data-timecard-pick]:not(:disabled)')return boxes.filter(b=>!b.disabled);if(selector==='[data-timecard-pick]:checked')return boxes.filter(b=>b.checked);if(selector==='[data-settings-tab]')return ['company','periods','forms','activity'].map(key=>{const n=node('#settings-tab-'+key);n.dataset.settingsTab=key;return n});return []}
const context={console,Intl,Date,Number,JSON,Map,URL:{createObjectURL(){context.downloads++;return 'blob:synthetic'},revokeObjectURL(){}},setTimeout,downloads:0,company:{features:{timeCards:true,templates:true},timezone:'America/Los_Angeles'},currentUser:{id:1,role:'owner',permissions:{}},currentRole:'office',tenant:'a',team,projects:[{id:1,name:'Synthetic job',code:'QA'}],timeCards:structuredClone(cards),$:node,$$:query,signedInCompanyId(){return context.tenant},escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c])},timeCardsOn(){return context.company.features.timeCards===true},fillTimeCardFilters(){},timeCardClock(value){return value||'-'},renderEverything(){context.renderTimeCards()},showPage(page){context.page=page},document:{body:{classList:{toggle(){}}},addEventListener(type,fn){(listeners[type]||=[]).push(fn)},createElement(){return{click(){context.downloadClicks=(context.downloadClicks||0)+1}}}},prompt(){return 'Synthetic correction reason'},api:async(route,options)=>{calls.push({route,options});if(options?.method==='POST'&&route==='/api/pay-periods'){const created={...period,...JSON.parse(options.body),id:'new-period'};testPeriods.push(created);return created}if(options?.method==='POST'&&route.endsWith('/exports'))return pendingCapture||{id:'captured-fixture'};if(route.endsWith('/summary')){if(pendingSummary)return pendingSummary;return{period:testPeriods.find(p=>route.includes(p.id))||period,approvedHours:3,ready:context.captureReady===true,review:{draft:1,submitted:1,running:1,invalid:0,undated:0,missingScheduledEntries:0},people:[],missingEntries:[],latestExport:{id:'fixed-a',version:1,changed:false}}}if(route.endsWith('/exports'))return[];return{periods:testPeriods,canConfigure:context.currentUser.role==='owner'}},fetch:async(route,options)=>{context.downloadRequest={route,options};return pendingDownload||{ok:true,blob:async()=>({})}}};
context.window=context;vm.createContext(context);
function sourceFunction(name){const start=app.indexOf('function '+name+'('),line=app.slice(start).split('\n')[0];return line.trimEnd().endsWith('}')?line:app.slice(start,app.indexOf('\n}',start)+2)}
for(const name of ['canManageTime','canViewTime','timeCardOffice','timeCardFilters','timeCardApproved','filteredTimeCards','timeCardRowMarkup','updateTimeCardSelection','renderTimeCards'])vm.runInContext(sourceFunction(name),context);
vm.runInContext(fs.readFileSync('time-approval-controls.js','utf8'),context);vm.runInContext(fs.readFileSync('company-settings-tabs.js','utf8'),context);
async function flush(){await new Promise(resolve=>setImmediate(resolve));await new Promise(resolve=>setImmediate(resolve))}
async function click(selector,dataset={}){const target={dataset,closest(s){return s===selector?this:null}};for(const fn of listeners.click||[])await fn({target});await flush()}
async function change(id,value){node('#'+id).value=value;for(const fn of listeners.change||[])await fn({target:node('#'+id)});await flush()}
(async()=>{
  context.renderTimeCards();await flush();assert.match(node('#time-person-list').innerHTML,/&lt;Synthetic Alice&gt;/);assert.ok(!node('#time-person-list').innerHTML.includes('<Synthetic Alice>'));assert.equal(boxes.length,0,'person summary leaves no hidden bulk selections');assert.equal(node('#timecard-office-actions').hidden,true);
  await click('[data-time-person]',{timePerson:'1'});assert.equal(node('#time-person-list').hidden,true);assert.match(node('#timecard-rows').innerHTML,/Correction history/);assert.equal(boxes.length,3);assert.equal(boxes.filter(b=>!b.disabled).length,1,'only complete submitted cards selectable');boxes[0].checked=true;context.updateTimeCardSelection();assert.equal(node('#timecard-bulk-approve').disabled,false);node('#time-person-back').onclick();await flush();assert.equal(boxes.length,0);assert.equal(node('#timecard-bulk-approve').disabled,true);
  await click('[data-time-person]',{timePerson:'1'});node('#time-person-search').value='Bob';node('#time-person-search').oninput();await flush();assert.equal(boxes.length,0);assert.match(node('#time-person-list').innerHTML,/Synthetic Bob/);assert.ok(!node('#time-person-list').innerHTML.includes('Alice'));node('#time-filter-reset').onclick();await flush();assert.equal(node('#time-person-search').value,'');assert.equal(node('#time-more-filters').open,false);
  await change('pay-period-select','period-a');assert.equal(node('#timecard-from').value,'2026-10-04');assert.equal(node('#timecard-to').value,'2026-10-09');assert.match(node('#pay-period-panel').innerHTML,/Manage pay periods/);assert.match(node('#pay-period-panel').innerHTML,/Needs review/);assert.match(node('#pay-period-panel').innerHTML,/data-pay-capture disabled/);
  await click('[data-pay-settings]');assert.equal(context.page,'settings');assert.equal(node('#company-pay-periods').hidden,false);assert.equal(node('#settings-tab-periods').attributes['aria-selected'],'true');assert.match(node('#company-pay-period-list').innerHTML,/New custom period/);
  const tab=node('#settings-tab-periods');await node('#company-settings-tabs').keydown({target:{closest(){return tab}},key:'ArrowRight',preventDefault(){}});assert.equal(node('#daily-templates-panel').hidden,false);assert.equal(node('#settings-tab-forms').focused,true);
  await click('[data-pay-new]');assert.equal(node('#pay-period-dialog').open,true);assert.equal(node('#pay-period-label').focusOptions.preventScroll,true);node('#pay-period-close').onclick();assert.equal(node('#pay-period-dialog').open,false);
  await click('[data-pay-new]');node('#pay-period-from').value='2026-10-10';node('#pay-period-to').value='2026-10-09';await node('#pay-period-form').onsubmit({preventDefault(){}});assert.match(node('#pay-period-form-error').textContent,/End date/);assert.equal(calls.filter(c=>c.options?.method==='POST').length,0);
  node('#pay-period-label').value='Custom company dates';node('#pay-period-from').value='2026-10-10';node('#pay-period-to').value='2026-10-22';await node('#pay-period-form').onsubmit({preventDefault(){}});await flush();assert.equal(node('#pay-period-dialog').open,false);const createdCall=calls.find(c=>c.options?.method==='POST'&&c.route==='/api/pay-periods');assert.equal(JSON.parse(createdCall.options.body).to,'2026-10-22');assert.equal(node('#timecard-from').value,'2026-10-10');assert.equal(node('#timecard-to').value,'2026-10-22');
  context.captureReady=true;await change('pay-period-select','period-a');let resolveCapture;pendingCapture=new Promise(resolve=>resolveCapture=resolve);const capturing=click('[data-pay-capture]');await flush();await click('[data-pay-capture]');assert.equal(calls.filter(c=>c.options?.method==='POST'&&c.route.endsWith('/exports')).length,1,'duplicate clicks cannot create two exports');const capturedCall=calls.find(c=>c.options?.method==='POST'&&c.route.endsWith('/exports'));assert.equal(JSON.parse(capturedCall.options.body).supersedesId,'fixed-a');assert.equal(JSON.parse(capturedCall.options.body).reason,'Synthetic correction reason');resolveCapture({id:'captured-fixture'});await capturing;pendingCapture=null;assert.equal(context.downloads,1);assert.equal(context.downloadClicks,1);context.captureReady=false;
  await click('[data-pay-new]');
  context.currentUser={id:2,role:'project_manager',permissions:{viewTime:true}};context.renderEverything();await flush();assert.equal(node('#pay-period-dialog').open,false);assert.equal(node('#pay-period-label').value,'');assert.equal(node('#settings-tab-periods').hidden,true);assert.equal(node('#company-pay-period-list').innerHTML,'');assert.equal(node('#settings-tab-company').hidden,true);await click('[data-time-person]',{timePerson:'1'});assert.equal(node('#timecard-office-actions').hidden,true);assert.ok(!node('#timecard-rows').innerHTML.includes('data-timecard-approve='));assert.equal(boxes.filter(b=>!b.disabled).length,0);
  context.currentUser={id:1,role:'owner',permissions:{}};context.renderEverything();await flush();let resolveSummary;pendingSummary=new Promise(resolve=>resolveSummary=resolve);await change('pay-period-select','period-a');context.tenant='b';context.currentUser={id:3,role:'admin',permissions:{}};context.renderEverything();resolveSummary({period,approvedHours:999,ready:true,review:{},people:[{name:'Stale private name',hours:999}]});pendingSummary=null;await flush();assert.equal(node('#pay-period-panel').hidden,true);assert.ok(!node('#pay-period-panel').innerHTML.includes('Stale private'));assert.equal(node('#time-person-list').innerHTML,'');assert.equal(node('#timecard-rows').innerHTML,'');assert.equal(boxes.length,0);
  context.currentUser={id:1,role:'owner',permissions:{}};context.renderEverything();await flush();await change('pay-period-select','period-a');let resolveDownload;pendingDownload=new Promise(resolve=>resolveDownload=resolve);const downloading=click('[data-pay-download]',{payDownload:'fixed-a'});await flush();assert.equal(context.downloadRequest.options.headers['X-PDL-Company'],'b');context.tenant='c';context.renderEverything();resolveDownload({ok:true,blob:async()=>({})});await downloading;assert.equal(context.downloads,1,'no additional stale tenant download created');assert.equal(context.downloadClicks,1);
  const html=fs.readFileSync('index.html','utf8');assert.ok(html.indexOf('id="pay-period-dialog"')<html.indexOf('<script src="time-approval-controls.js'));assert.ok(html.indexOf('<script src="app.js')<html.indexOf('<script src="time-approval-controls.js'));assert.match(html,/role="tablist" aria-label="Company settings"/);assert.match(html,/id="time-more-filters"/);
  const styles=fs.readFileSync('styles.css','utf8'),mobileControls=styles.slice(styles.indexOf('/* Readable mobile controls'));
  assert.match(mobileControls,/@media\(max-width:760px\)/);for(const selector of ['#pay-period-form input','#pay-period-form select','#pay-period-form textarea','#timecards-page .time-date-filters input','#timecards-page .time-date-filters select','#timecards-page #pay-period-select'])assert.ok(mobileControls.includes(selector));assert.match(mobileControls,/font-size:max\(16px,1rem\);min-width:0;max-width:100%/);assert.match(mobileControls,/@media\(max-width:400px\).*grid-template-columns:1fr/);assert.match(html,/<meta name="viewport" content="width=device-width, initial-scale=1.0"/);assert.ok(!/user-scalable\s*=\s*no|maximum-scale\s*=\s*1/.test(html));assert.match(html,/styles\.css\?v=20261005-leave/);assert.match(html,/time-approval-controls\.js\?v=20261004-pay-period-zoom/);
  console.log('Person-first approval/settings fixtures passed: totals/status/search, escaped names, drill-down/history/Back, complete-only selection, filter reset, custom dates/discovery, keyboard tabs, roles and stale summary/download rejection. Real browser/device QA remains unverified.');
})().catch(error=>{console.error(error);process.exitCode=1});
