'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{execFileSync}=require('node:child_process');
if(!process.argv.includes('--zone')){for(const zone of ['America/Los_Angeles','Pacific/Kiritimati','Etc/UTC'])execFileSync(process.execPath,[__filename,'--zone'],{env:{...process.env,TZ:zone},stdio:'inherit'});process.exit(0)}
const source=fs.readFileSync('app.js','utf8'),index=fs.readFileSync('index.html','utf8'),styles=fs.readFileSync('styles.css','utf8'),nodes=new Map(),messages=[];
function node(id){if(!nodes.has(id))nodes.set(id,{value:'',disabled:false,hidden:false,textContent:'',innerHTML:'',handlers:{},addEventListener(name,fn){this.handlers[name]=fn},showModal(){this.open=true},close(){this.open=false;this.handlers.close?.()}});return nodes.get(id)}
function fn(name){const lines=source.split('\n'),start=lines.findIndex(line=>new RegExp(`^(?:async )?function ${name}\\(`).test(line));assert.ok(start>=0,name);if(lines[start].trimEnd().endsWith('}'))return lines[start];return lines.slice(start,lines.findIndex((line,i)=>i>start&&line.trimEnd()==='}')+1).join('\n')}
const context={$:node,window:{PDLScheduleAvailability:require('./schedule-availability'),crypto:{randomUUID:()=>`synthetic-request-${++context.uuid}`}},uuid:0,company:{timezone:'America/Los_Angeles'},currentUser:{id:1,role:'field'},currentRole:'field',signedInCompanyId:()=>context.companyId,companyId:'tenant-a',companyTodayIso:()=> '2026-11-01',team:[{id:1,name:'Synthetic Worker'}],timeOffRequests:[],renderTimeOverview(){},canManageTime:()=>context.manager,manager:false,notify:message=>messages.push(message)};
vm.createContext(context);vm.runInContext(source.match(/^let timeOffFormSequence=.*$/m)[0],context);
for(const name of ['escapeHtml','displayTime','timeOffHoursLabel','scheduleAvailabilityKey','timeOffIdentityKey','newTimeOffRequestId','timeOffFormMessage','syncTimeOffDuration','openTimeOffRequest','submitTimeOffRequest','renderTimeOff'])vm.runInContext(fn(name),context);
for(const line of source.split('\n').filter(line=>/^\$\('#(?:new-time-off|time-off-close|time-off-cancel|time-off-duration|time-off-start|time-off-modal|time-off-form|submit-time-off)'\)\?\.addEventListener/.test(line)))vm.runInContext(line,context);
function open(){node('#new-time-off').handlers.click()}
function timed(start='09:15',end='10:45'){node('#time-off-duration').value='hours';node('#time-off-duration').handlers.change();node('#time-off-start-time').value=start;node('#time-off-end-time').value=end}
function submit(){return node('#submit-time-off').handlers.click()}
let calls=[],respond;
context.api=async(path,options)=>{calls.push(JSON.parse(options.body));return new Promise(resolve=>respond=resolve)};
(async()=>{
 open();assert.equal(node('#time-off-duration').value,'all-day');assert.equal(node('#time-off-start').value,'2026-11-01');assert.equal(node('#time-off-end').value,'2026-11-01');assert.equal(node('#time-off-hours').hidden,true);assert.equal(node('#time-off-start-time').disabled,true);assert.equal(node('#time-off-end-wrap').hidden,false);assert.match(node('#time-off-zone').textContent,/America\/Los_Angeles/);
 timed();assert.equal(node('#time-off-start-label').textContent,'Day');assert.equal(node('#time-off-hours').hidden,false);assert.equal(node('#time-off-start-time').required,true);assert.equal(node('#time-off-end-wrap').hidden,true);assert.equal(node('#time-off-end').disabled,true);
 node('#time-off-start').value='2026-11-02';node('#time-off-start').handlers.change();assert.equal(node('#time-off-end').value,'2026-11-02');
 for(const [start,end] of [['','10:00'],['09:00',''],['09:00','09:00'],['10:00','09:00'],['24:00','25:00'],['23:30','00:15']]){timed(start,end);await submit();assert.match(node('#time-off-error').textContent,/later on the same day/);assert.equal(calls.length,0)}
 timed();node('#time-off-start').value='2026-02-30';await submit();assert.match(node('#time-off-error').textContent,/valid first and last day/);assert.equal(calls.length,0);
 node('#time-off-start').value='2026-11-01';node('#time-off-end').value='2027-01-01';node('#time-off-note').value=' appointment ';const pending=submit();await submit();assert.equal(calls.length,1,'double click submits once');assert.equal(node('#submit-time-off').disabled,true);assert.deepEqual(calls[0],{startDate:'2026-11-01',endDate:'2026-11-01',allDay:false,startTime:'09:15',endTime:'10:45',type:'vacation',note:'appointment',requestId:'synthetic-request-1'});respond({id:'timed-1',memberId:1,status:'pending',...calls[0]});await pending;assert.equal(node('#time-off-modal').open,false);assert.equal(node('#submit-time-off').disabled,false);assert.match(node('#time-off-list').innerHTML,/9:15 AM–10:45 AM/);assert.doesNotMatch(node('#time-off-list').innerHTML,/Approve/);
 context.currentRole='office';context.manager=true;context.renderTimeOff();assert.match(node('#time-office-timeoff-list').innerHTML,/9:15 AM–10:45 AM/);assert.match(node('#time-office-timeoff-list').innerHTML,/data-time-off-approve/);context.manager=false;context.renderTimeOff();assert.doesNotMatch(node('#time-office-timeoff-list').innerHTML,/data-time-off-approve/);context.currentRole='field';
 open();node('#time-off-end').value='2026-11-04';timed();node('#time-off-duration').value='all-day';node('#time-off-duration').handlers.change();node('#time-off-end').value='2026-11-04';let allDay=submit();assert.equal(calls.at(-1).allDay,true);assert.equal(calls.at(-1).endDate,'2026-11-04');assert.ok(!Object.hasOwn(calls.at(-1),'startTime'));respond({id:'full-1',memberId:1,status:'pending',...calls.at(-1)});await allDay;assert.match(node('#time-off-list').innerHTML,/2026-11-01 – 2026-11-04 · All day/);
 open();timed();let failures=[];context.api=async(path,options)=>{failures.push(JSON.parse(options.body));throw new Error('Network interrupted')};await submit();assert.equal(node('#time-off-modal').open,true);assert.equal(node('#time-off-start-time').value,'09:15');assert.match(node('#time-off-error').textContent,/Network interrupted/);assert.equal(node('#submit-time-off').disabled,false);await submit();assert.equal(failures[0].requestId,failures[1].requestId,'same request id survives retry');node('#time-off-start-time').value='09:30';await submit();assert.notEqual(failures[1].requestId,failures[2].requestId,'changed request uses a new id');
 node('#time-off-cancel').handlers.click();assert.equal(node('#time-off-modal').open,false);open();assert.equal(node('#time-off-start-time').value,'');assert.equal(node('#time-off-note').value,'');assert.equal(node('#time-off-duration').value,'all-day');assert.equal(node('#time-off-error').hidden,true);node('#time-off-close').handlers.click();assert.equal(node('#time-off-modal').open,false);
 context.api=async(path,options)=>{calls.push(JSON.parse(options.body));return new Promise(resolve=>respond=resolve)};
 open();timed();const cancelled=submit();node('#time-off-cancel').handlers.click();open();respond({id:'after-cancel',memberId:1,status:'pending',...calls.at(-1)});await cancelled;assert.equal(node('#time-off-modal').open,true,'late success cannot close reopened form');assert.equal(node('#time-off-duration').value,'all-day');
 const before=context.timeOffRequests.length;timed();const late=submit();context.companyId='tenant-b';context.timeOffRequests=[];respond({id:'old-tenant',memberId:1,status:'pending',...calls.at(-1)});await late;assert.equal(context.timeOffRequests.length,0,'late result from old tenant cannot leak');assert.equal(node('#time-off-modal').open,true);assert.equal(node('#submit-time-off').disabled,false);
 context.companyId='tenant-a';open();timed();const lateRole=submit();context.currentRole='office';respond({id:'old-role',memberId:1,status:'pending',...calls.at(-1)});await lateRole;assert.equal(context.timeOffRequests.length,0,'late result after role switch ignored');const count=calls.length;await submit();assert.equal(calls.length,count,'office cannot submit field request');context.currentRole='field';
 open();node('#time-off-note').value='Old account private note';context.currentUser={id:2,role:'field',memberId:2};const beforeSwitch=calls.length;await submit();assert.equal(calls.length,beforeSwitch,'old draft is never sent as a new account');assert.equal(node('#time-off-modal').open,false);assert.equal(node('#time-off-note').value,'');assert.match(messages.at(-1),/account changed/);
 open();context.currentUser.memberId=3;await submit();assert.equal(calls.length,beforeSwitch,'linked-member changes also invalidate draft');
 context.timeOffRequests=[{id:'legacy',memberId:1,status:'approved',startDate:'2026-11-01',endDate:'2026-11-01',type:'other',note:'<img src=x>'}];context.renderTimeOff();assert.match(node('#time-off-list').innerHTML,/All day/);assert.doesNotMatch(node('#time-off-list').innerHTML,/<img/);
 assert.match(index,/id="time-off-error" role="alert" hidden/);assert.match(index,/id="time-off-modal" aria-labelledby="time-off-title"/);assert.match(index,/id="time-off-duration"><option value="all-day">All day<\/option><option value="hours">Specific hours/);assert.match(styles,/#time-off-modal \[hidden\]\{display:none!important\}/);assert.match(styles,/min-height:44px/);
 console.log(`Partial-day time-off UI passed in ${process.env.TZ}: duration/date/time validation, precise field/office labels, legacy all-day, duplicate/retry protection, cancel/reopen, late tenant/role responses, accessible error and mobile controls.`);
})().catch(error=>{console.error(error);process.exitCode=1});
