'use strict';
const assert = require('node:assert/strict');
const { fixture } = require('./fixtures/project-assistant');
const access = require('./time-off-access');
const { createHandler, parse } = require('./time-off-admission');
const scheduling = require('./scheduling-access');
const db = fixture(), owner = db.users[0], field = db.users[3], pm = db.users[1], admin = db.users[6];
const policy = () => ({ version: 1, revision: 1, roles: Object.fromEntries(access.roles.map(role => [role, access.ceiling(role)])) });
assert.equal(access.access(db, admin).viewRequests, false); admin.permissions = { viewTime: true }; assert.equal(access.access(db, admin).viewRequests, false);
admin.permissions.manageTime = true; assert.equal(access.access(db, admin).viewRequests, true);
assert.equal(access.access(db, pm).viewRequests, false); pm.permissions.viewTime = true; assert.equal(access.access(db, pm).viewRequests, true);
assert.equal(access.inScope(db, pm, { memberId: 13 }), false); assert.equal(access.inScope(db, field, { memberId: 12 }), false);
for (const user of [owner, admin, pm, { ...field, role: 'crew' }, { ...field, role: 'platform_owner', permissions: { manageTime: true } }]) assert.equal(access.access(db, user).createRequest, false);
for (const key of ['owner', 'crew', 'payroll', '__proto__']) { const value = policy(); Object.defineProperty(value.roles, key, { enumerable: true, value: {} }); assert.throws(() => access.validatePolicy(value)); }
const broaden = policy(); broaden.roles.project_manager.createRequest = true; assert.throws(() => access.validatePolicy(broaden));
const approve = policy(); approve.roles.field.approve = true; assert.throws(() => access.validatePolicy(approve));
db.company.timeOffPolicyRequired = true; assert.equal(access.access(db, field).viewRequests, false); assert.equal(access.access(db, owner).viewRequests, true); assert.equal(access.actor(db, field, false), null);
db.company.timeOffRolePolicy = policy(); db.company.timeOffRolePolicy.roles.field.createRequest = false; assert.equal(access.access(db, field).createRequest, false);
delete db.company.timeOffPolicyRequired; delete db.company.timeOffRolePolicy;
const input = { startDate: '2098-10-12', endDate: '2098-10-12', allDay: false, startTime: '09:00', endTime: '10:00', type: 'other', note: '  Synthetic private note  ', requestId: 'synthetic-request' };
assert.equal(parse(input).note, 'Synthetic private note');
for (const extra of [{ id: 1 }, { memberId: 13 }, { status: 'approved' }, { permissions: {} }, { requestId: '' }, { allDay: 'false' }, { type: {} }, { note: {} }, { endDate: '2098-10-13' }, { startTime: '9:00' }]) assert.equal(parse({ ...input, ...extra }), null);
(async () => {
  let writes = 0; const handle = createHandler({ readDb: () => db, writeDb: () => writes++, body: async req => req.input, json: (res, status, data) => Object.assign(res, { status, data }) });
  const call = async (method, route, actor, value) => { const res = {}; await handle({ method, input: value, auth: { user: actor, session: db.sessions.find(row => row.userId === actor.id) } }, res, new URL('http://test' + route)); return res; };
  const created = await call('POST', '/api/time-off-requests', field, input); assert.equal(created.status, 201); assert.equal(writes, 1); assert.equal(db.timeOffActionReceipts.length, 1); assert.equal(db.assignmentEmailOutbox, undefined);
  assert.equal((await call('POST', '/api/time-off-requests', field, input)).status, 200); assert.equal(writes, 1);
  assert.equal((await call('POST', '/api/time-off-requests', field, { ...input, note: 'Changed' })).status, 409);
  const row = db.timeOffRequests[0]; row.status = 'approved'; row.unknownPrivate = 'server-only';
  row.history.push(null, 'corrupt entry', { action: 'Reviewed', by: 'Office', at: '2098-10-01', unknownPrivate: 'nested-server-only' });
  const read = await call('GET', '/api/time-off-requests', field); assert.equal(read.data[0].status, 'approved'); assert.equal(read.data[0].unknownPrivate, undefined); assert.equal(read.data[0].requestId, undefined);
  assert.doesNotMatch(JSON.stringify(read.data), /nested-server-only|corrupt entry/);
  db.timeOffRequests.push({ ...row, id: 'legacy-own', requestId: 'legacy-request-123' });
  assert.equal((await call('POST', '/api/time-off-requests', field, { ...input, requestId: 'legacy-request-123' })).status, 409); assert.equal(writes, 1);
  const available = await call('GET', '/api/schedule-availability', field); assert.equal(available.data[0].memberId, 11); assert.doesNotMatch(JSON.stringify(available.data), /Synthetic private|type|note|history|sessionHash/);
  assert.equal((await call('GET', '/api/schedule-availability', { ...field, role: 'crew' })).status, 403);
  db.company.timeOffPolicyRequired = true; db.company.timeOffRolePolicy = policy(); db.company.timeOffRolePolicy.roles.field.createRequest = false;
  assert.equal((await call('POST', '/api/time-off-requests', field, input)).status, 403); assert.equal(writes, 1);
  db.company.schedulingRolePolicy = { version: 1, revision: 1, roles: Object.fromEntries(scheduling.roles.map(role => [role, scheduling.ceiling(role)])) }; db.company.schedulingRolePolicy.roles.field = Object.fromEntries(scheduling.actions.map(action => [action, false]));
  assert.equal((await call('GET', '/api/schedule-availability', field)).status, 403);
  console.log('Typed private time-off reads/own create, immutable grants/scopes, finite inputs, fresh replay, redacted availability and no effects passed.');
})().catch(error => { console.error(error); process.exitCode = 1; });
