const assert = require('assert');
const fs = require('fs');

const read = (file) => fs.readFileSync(file, 'utf8');
const manifest = JSON.parse(read('manifest.webmanifest'));
const index = read('index.html');
const login = read('login.html');
const app = read('app.js');
const styles = read('styles.css');
const server = read('server.js');

assert.equal(manifest.start_url, '/app');
assert.equal(manifest.display, 'standalone');
assert.equal(manifest.scope, '/');
assert.ok(manifest.icons.some((icon) => icon.src === '/assets/pro-daily-link-logo.png'));
assert.match(index, /id="network-activity"[^>]*role="status"[^>]*aria-live="polite"/);
assert.match(index, /rel="manifest" href="manifest\.webmanifest"/);
assert.match(login, /rel="manifest" href="manifest\.webmanifest"/);
assert.match(app, /Create your first project/);
assert.match(app, /Create daily report/);
assert.match(app, /function projectHealthDetails/);
assert.match(app, /Why at risk\?/);
assert.match(app, /Changes & extra work/);
assert.match(app, /Create potential change/);
assert.match(index, /id="project-results-summary"[^>]*aria-live="polite"/);
assert.match(app, /Showing.*project/);
assert.match(app, /Approved completion/);
assert.match(app, /await openProjectForPricing/);
assert.match(app, /await openProjectBeforeContractValues/);
assert.match(app, /await openProjectEstimateView/);
assert.match(app, /Change workflow/);
assert.match(styles, /prefers-reduced-motion/);
assert.match(styles, /\.network-activity/);
assert.match(styles, /\.project-health-banner/);
assert.match(styles, /\.change-card/);
assert.match(styles, /\.project-results-summary/);
assert.match(styles, /\.change-workflow/);
assert.match(app, /Changes could not be loaded/);
assert.match(index, /id="report-review-summary"[^>]*aria-live="polite"/);
assert.match(app, /function openDailyForAssignment/);
assert.match(app, /Create daily/);
assert.match(app, /updateFieldReportReview/);
assert.match(styles, /\.myday-status-strip/);
assert.match(styles, /\.field-assignment-daily/);
assert.match(styles, /\.report-review-summary/);
assert.match(app, /Describe the form you need/);
assert.match(app, /function generateTemplateDraft/);
assert.match(app, /function projectTemplateIds/);
assert.match(app, /requires at least one photo/);
assert.match(app, /does not certify OSHA or legal compliance/);
assert.match(styles, /AI-first form and safety-template studio/);
assert.match(server, /function aiTemplateDraft/);
assert.match(server, /field_template_draft/);

console.log('UX shell and installability tests passed.');
