const assert = require('assert');
const fs = require('fs');

const read = (file) => fs.readFileSync(file, 'utf8');
const manifest = JSON.parse(read('manifest.webmanifest'));
const index = read('index.html');
const login = read('login.html');
const app = read('app.js');
const styles = read('styles.css');
const server = read('server.js');
const landing = read('landing.html');
const about = read('about.html');
const blog = read('blog.html');
const blogJs = read('blog.js');
const platform = read('platform.html');
const landingDemoStyles = read('landing-demo.css');

assert.equal(manifest.start_url, '/app');
assert.equal(manifest.display, 'standalone');
assert.equal(manifest.scope, '/');
assert.ok(manifest.icons.some((icon) => icon.src === '/assets/pro-daily-link-logo.png'));
assert.match(index, /id="network-activity"[^>]*role="status"[^>]*aria-live="polite"/);
assert.match(index, /rel="manifest" href="manifest\.webmanifest"/);
assert.match(login, /rel="manifest" href="manifest\.webmanifest"/);
assert.match(app, /Create your first project/);
assert.match(app, /Create daily report/);
assert.match(app, /function projectHealthDetails/);
assert.match(app, /Why at risk\?/);
assert.match(app, /Changes & extra work/);
assert.match(app, /Create potential change/);
assert.match(index, /id="project-results-summary"[^>]*aria-live="polite"/);
assert.match(app, /Showing.*project/);
assert.match(app, /Approved completion/);
assert.match(app, /await openProjectForPricing/);
assert.match(app, /await openProjectBeforeContractValues/);
assert.match(app, /await openProjectEstimateView/);
assert.match(app, /Change workflow/);
assert.match(styles, /prefers-reduced-motion/);
assert.match(styles, /\.network-activity/);
assert.match(styles, /\.project-health-banner/);
assert.match(styles, /\.change-card/);
assert.match(styles, /\.project-results-summary/);
assert.match(styles, /\.change-workflow/);
assert.match(app, /Changes could not be loaded/);
assert.match(index, /id="report-review-summary"[^>]*aria-live="polite"/);
assert.match(app, /function openDailyForAssignment/);
assert.match(app, /Create daily/);
assert.match(app, /updateFieldReportReview/);
assert.match(styles, /\.myday-status-strip/);
assert.match(styles, /\.field-assignment-daily/);
assert.match(styles, /\.report-review-summary/);
assert.match(app, /Describe the form you need/);
assert.match(app, /function generateTemplateDraft/);
assert.match(app, /function projectTemplateIds/);
assert.match(app, /requires at least one photo/);
assert.match(app, /pendingTemplatePhotoSubmission/);
assert.match(app, /upload the linked photo, then submit/);
assert.match(app, /does not certify OSHA or legal compliance/);
assert.match(styles, /AI-first form and safety-template studio/);
assert.match(server, /function aiTemplateDraft/);
assert.match(server, /field_template_draft/);
assert.match(server, /function scopedTemplateList/);
assert.match(server, /TEMPLATE_PHOTO_REQUIRED/);
assert.match(server, /This form is not assigned to the selected project/);
assert.match(landing, /I spent 25 years living this problem/);
assert.match(landing, /\/about\.html/);
assert.match(landing, /\/blog\.html/);
assert.match(about, /Why I built Pro Daily Link/);
assert.match(about, /Once approved, labor and installed quantities update production/);
assert.match(blog, /id="blog-list"/);
assert.match(blogJs, /safeBody/);
assert.match(platform, /id="blog-editor"/);
assert.match(server, /\/api\/platform\/blog/);
assert.match(landingDemoStyles, /#workflow-example-next\{color:var\(--ink\)/);
assert.match(landingDemoStyles, /\.dark \.features article p\{color:#c7cfcb\}/);
assert.match(styles, /--dark-control:#292f2c/);
assert.match(styles, /\[data-theme="dark"\] \.schedule-summary article/);
assert.match(styles, /\[data-theme="dark"\] \.schedule-cell\.person/);
assert.match(styles, /\[data-theme="dark"\] \.schedule-view-switcher button\.active/);
assert.match(styles, /\[data-theme="dark"\] table th/);
assert.match(index, /styles\.css\?v=20261005-office-recovery/);
assert.match(index, /app\.js\?v=20261007-work-review/);
assert.ok(index.indexOf('csv-cell.js?') < index.indexOf('app.js?'), 'shared CSV encoder must load before application exporters');
assert.match(app, /Launch polish for the subcontractor directory/);
assert.match(app, /function goToOverview\(\)\{showPage\(defaultPage\(\)\)/);
assert.match(app, /subcontractor-secondary subcontractor-history-details/);
assert.match(app, /data-copy-guest-link/);
assert.match(app, /No active assigned project is available/);
assert.match(styles, /Subcontractor launch polish/);
assert.match(styles, /\.brand-home:focus-visible/);
assert.match(styles, /\.subcontractor-secondary>summary/);
assert.match(styles, /\[data-theme="dark"\] \.compliance-status\.blocked/);
assert.match(styles, /\.team-tabs\{overflow-x:auto/);
assert.match(server, /subcontractorProfile/);
assert.match(server, /Choose a future expiration date/);
assert.match(server, /You can only create access for an assigned project/);
assert.match(index, /id="sidebar-home" aria-label="Go to Overview"/);
assert.match(index, /id="header-company-mark" aria-label="Go to Overview"/);

console.log('UX shell and installability tests passed.');
