'use strict';
// Synthetic, loopback-only preview; never load production data or provider credentials.
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'pdl-core-ux-preview-'));
Object.assign(process.env,{NODE_ENV:'development',PDL_DB_FILE:path.join(temp,'db.json'),PDL_PLATFORM_FILE:path.join(temp,'platform.json'),PDL_SUPABASE_ENABLED:'0',PDL_TRANSACTIONAL_DB:'off',PDL_REQUIRE_AUTH:'1',PDL_EMAIL_DEV_MODE:'1',PDL_FOUNDER_ENABLED:'0'});
for(const key of Object.keys(process.env))if(/^(STRIPE_|RESEND_|SUPABASE_|SENTRY_|OPENAI_)/.test(key))delete process.env[key];
const db=JSON.parse(fs.readFileSync(path.join(root,'data/db.json'),'utf8'));db.company={...db.company,id:'33333333-3333-4333-8333-333333333333',name:'Synthetic workflow preview',demo:true,timezone:'America/Los_Angeles',features:{timeCards:true,templates:false}};
db.team=Array.from({length:4},(_,i)=>({id:i+1,name:'Preview worker '+(i+1),initials:'W'+(i+1),role:'Field worker',crew:i<2?'Concrete':'Framing',hours:0,site:'Not assigned'}));
db.projects=db.projects.slice(0,2).map((p,i)=>({...p,id:i+1,name:'Preview project '+(i+1),code:'QA'+(i+1),archived:false,site:'Synthetic site '+(i+1)}));
const password='SyntheticPreview!42';db.users=[{id:1,role:'owner',name:'Preview Owner'},{id:2,role:'project_manager',name:'Preview Manager',projectIds:[1],assignedCrews:['Concrete'],permissions:{viewTime:true,manageTime:true,scheduleCrews:true,viewDailies:true}},{id:3,role:'project_manager',name:'Preview Viewer',projectIds:[1],assignedCrews:['Concrete'],permissions:{viewTime:true,manageTime:false,scheduleCrews:false,viewDailies:true}},{id:4,role:'field',name:'Preview Worker',memberId:1}].map(u=>{const salt=crypto.randomBytes(16).toString('hex');return{...u,email:'preview-'+({1:'owner',2:'manager',3:'viewer',4:'worker'}[u.id])+'@example.invalid',companyId:db.company.id,status:'Active',emailVerifiedAt:new Date().toISOString(),passwordSalt:salt,passwordHash:crypto.scryptSync(password,salt,64).toString('hex')}});
const date=new Date();date.setDate(date.getDate()+((8-date.getDay())%7||7));const day=date.toISOString().slice(0,10);
db.assignments=[{id:1,projectId:1,memberIds:[1,2],crew:'Concrete',date:day,start:'07:00',end:'15:00',activity:'Synthetic concrete work'},{id:2,projectId:2,memberIds:[3,4],crew:'Framing',date:day,start:'07:00',end:'15:00',activity:'Synthetic framing work'}];
db.timeCards=['draft','submitted','approved'].map((status,i)=>({id:i+1,projectId:1,memberId:i===2?2:1,date:day,inAt:day+'T'+String(7+i*2).padStart(2,'0')+':00:00-07:00',outAt:day+'T'+String(9+i*2).padStart(2,'0')+':00:00-07:00',hours:2,status,history:[{action:'Created',by:'Preview Owner',at:new Date().toISOString()}],...(status==='approved'?{approvedBy:'Preview Owner',approvedAt:new Date().toISOString()}:{})}));
db.sessions=[];db.reports=[];db.workdays=[];db.timeOffRequests=[];db.auditLog=[];db.reportingExports=[];
fs.writeFileSync(process.env.PDL_DB_FILE,JSON.stringify(db));fs.copyFileSync(path.join(root,'data/platform.json'),process.env.PDL_PLATFORM_FILE);
const originalFetch=global.fetch;global.fetch=(url,...args)=>{const parsed=new URL(String(url));if(!['127.0.0.1','localhost'].includes(parsed.hostname))throw new Error('External providers disabled in synthetic preview');return originalFetch(url,...args)};
const {server}=require(path.join(root,'server'));function cleanup(){fs.rmSync(temp,{recursive:true,force:true})}
process.on('exit',cleanup);for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>server.close(()=>process.exit(0)));
server.listen(0,'127.0.0.1',()=>{console.log('Synthetic preview: http://127.0.0.1:'+server.address().port+'/login.html');console.log('Accounts: preview-owner / preview-manager / preview-viewer / preview-worker @example.invalid');console.log('Synthetic password: '+password);console.log('Schedule fixture date: '+day+'; use that date in the schedule. Stop with Ctrl+C; temporary data is removed. No provider access.');});
